-- 系统菜单
CREATE TABLE sys_menu (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT,
    title       VARCHAR(50) NOT NULL,
    path        VARCHAR(200),
    icon        VARCHAR(50),
    sort_order  INTEGER NOT NULL DEFAULT 0,
    visible     BOOLEAN NOT NULL DEFAULT TRUE,
    menu_type   VARCHAR(20) NOT NULL DEFAULT 'MENU',
    permission  VARCHAR(100),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sys_menu IS '系统菜单';
CREATE INDEX idx_menu_parent ON sys_menu (parent_id);

-- 角色-菜单关联
CREATE TABLE sys_role_menu (
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);

-- 初始化菜单数据
INSERT INTO sys_menu (parent_id, title, path, icon, sort_order, menu_type) VALUES
(NULL, '概览', NULL, NULL, 0, 'GROUP'),
(1, '工作台', '/dashboard', 'layout-dashboard', 0, 'MENU'),
(NULL, 'AI 创作', NULL, NULL, 10, 'GROUP'),
(3, '图像生成', '/aigc', 'sparkles', 0, 'MENU'),
(3, '视频生成', '/aigc/video', 'video', 1, 'MENU'),
(3, '3D 展示', '/aigc/3d', 'box', 2, 'MENU'),
(3, '素材库', '/aigc/assets', 'image', 3, 'MENU'),
(NULL, '开发工具', NULL, NULL, 20, 'GROUP'),
(8, '文档管理', '/dev/docs', 'file-text', 0, 'MENU'),
(8, '开发日志', '/dev/log', 'scroll-text', 1, 'MENU'),
(8, '代码审查', '/dev/review', 'git-pull-request', 2, 'MENU'),
(8, '迭代统计', '/dev/stats', 'bar-chart-3', 3, 'MENU'),
(NULL, '系统', NULL, NULL, 99, 'GROUP'),
(13, '回收站', '/trash', 'trash-2', 0, 'MENU'),
(13, '设置', '/settings', 'settings', 1, 'MENU');
