-- 仪表盘
CREATE TABLE sys_dashboard (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(500),
    is_default      BOOLEAN NOT NULL DEFAULT FALSE,
    owner_id        BIGINT NOT NULL,
    create_by       BIGINT,
    create_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    remark          VARCHAR(500)
);

COMMENT ON TABLE sys_dashboard IS '仪表盘';
COMMENT ON COLUMN sys_dashboard.name IS '仪表盘名称';
COMMENT ON COLUMN sys_dashboard.is_default IS '是否默认仪表盘';
COMMENT ON COLUMN sys_dashboard.owner_id IS '所有者用户 ID';

-- 仪表盘组件
CREATE TABLE sys_dashboard_widget (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    dashboard_id    BIGINT NOT NULL REFERENCES sys_dashboard(id),
    type            VARCHAR(20) NOT NULL,
    title           VARCHAR(100) NOT NULL,
    position        JSONB NOT NULL DEFAULT '{}',
    config          JSONB NOT NULL DEFAULT '{}',
    sort_order      INTEGER NOT NULL DEFAULT 0,
    create_by       BIGINT,
    create_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    remark          VARCHAR(500)
);

COMMENT ON TABLE sys_dashboard_widget IS '仪表盘组件';
COMMENT ON COLUMN sys_dashboard_widget.dashboard_id IS '所属仪表盘 ID';
COMMENT ON COLUMN sys_dashboard_widget.type IS '组件类型：counter/chart/list/progress/shortcut/custom';
COMMENT ON COLUMN sys_dashboard_widget.title IS '组件标题';
COMMENT ON COLUMN sys_dashboard_widget.position IS '位置信息（x/y/w/h）';
COMMENT ON COLUMN sys_dashboard_widget.config IS '组件配置（JSON）';
COMMENT ON COLUMN sys_dashboard_widget.sort_order IS '排序序号';

CREATE INDEX idx_sys_dashboard_owner ON sys_dashboard(owner_id) WHERE deleted = FALSE;
CREATE INDEX idx_sys_dashboard_widget_dashboard ON sys_dashboard_widget(dashboard_id) WHERE deleted = FALSE;
