-- 实体定义
CREATE TABLE sys_entity_def (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    slug            VARCHAR(100) NOT NULL,
    config          JSONB NOT NULL DEFAULT '{}',
    builtin         BOOLEAN NOT NULL DEFAULT FALSE,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    create_by       BIGINT,
    create_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    remark          VARCHAR(500)
);

COMMENT ON TABLE sys_entity_def IS '实体定义';
COMMENT ON COLUMN sys_entity_def.slug IS '实体标识（唯一）';
COMMENT ON COLUMN sys_entity_def.config IS '实体配置（JSONB，含 fields 数组）';
COMMENT ON COLUMN sys_entity_def.builtin IS '是否内置（内置配置不可被数据库覆盖）';
COMMENT ON COLUMN sys_entity_def.enabled IS '是否启用';

CREATE UNIQUE INDEX uk_sys_entity_def_slug ON sys_entity_def(slug) WHERE deleted = FALSE;
