-- 记录模板
CREATE TABLE sys_record_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    entity_slug     VARCHAR(100) NOT NULL,
    name            VARCHAR(200) NOT NULL,
    field_values    JSONB NOT NULL DEFAULT '{}',
    is_shared       BOOLEAN NOT NULL DEFAULT FALSE,
    is_default      BOOLEAN NOT NULL DEFAULT FALSE,
    create_by       BIGINT,
    create_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    remark          VARCHAR(500)
);

COMMENT ON TABLE sys_record_template IS '记录模板';
COMMENT ON COLUMN sys_record_template.entity_slug IS '关联实体标识';
COMMENT ON COLUMN sys_record_template.name IS '模板名称';
COMMENT ON COLUMN sys_record_template.field_values IS '模板字段值（JSONB）';
COMMENT ON COLUMN sys_record_template.is_shared IS '是否共享（团队可见）';
COMMENT ON COLUMN sys_record_template.is_default IS '是否默认模板';

CREATE INDEX idx_sys_record_template_slug ON sys_record_template(entity_slug) WHERE deleted = FALSE;
CREATE INDEX idx_sys_record_template_creator ON sys_record_template(create_by) WHERE deleted = FALSE;
