-- ============================================================
-- 工作区（Workspace）：组织内部的协作空间划分
--
-- 用户在所属组织下可自建多个工作区；权限模型不设独立角色层级，
-- create_by 即该工作区的管理者，拥有邀请/移除成员、改名、删除工作区等全部管理权限。
-- 组织成员不自动加入工作区，需显式邀请/加入（sys_workspace_member 记录归属关系）。
--
-- 详见设计文档 docs/design/apps/service/workspace-isolation.md。
-- ============================================================

CREATE TABLE sys_workspace (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT       NOT NULL,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    slug         VARCHAR(100) NOT NULL,
    owner_id     BIGINT,
    create_by      BIGINT,
    create_by_type VARCHAR(16),
    create_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by      BIGINT,
    update_by_type VARCHAR(16),
    update_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_workspace IS '工作区：组织内部的协作空间划分';
COMMENT ON COLUMN sys_workspace.slug IS 'URL 友好标识，组织内唯一';

CREATE UNIQUE INDEX uk_workspace_org_slug ON sys_workspace (org_id, slug) WHERE deleted = FALSE;

CREATE TABLE sys_workspace_member (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT       NOT NULL,
    user_id      BIGINT       NOT NULL,
    owner_id     BIGINT,
    create_by      BIGINT,
    create_by_type VARCHAR(16),
    create_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by      BIGINT,
    update_by_type VARCHAR(16),
    update_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_workspace_member IS '工作区成员：记录用户与工作区的归属关系，无角色字段（管理权限看工作区 create_by）';

CREATE UNIQUE INDEX uk_workspace_member_workspace_user ON sys_workspace_member (workspace_id, user_id) WHERE deleted = FALSE;

-- ============================================================
-- 存量无组织用户数据修复
--
-- 背景：B1 多组织 orgId fail-open 安全修复的前置条件——OrgFilterAspect 即将改为
-- fail-closed（orgId 缺失时拒绝而非静默放行），此前注册流程未接入
-- OrganizationService.createPersonalOrg，导致历史注册用户在 sys_org_member 中无任何记录。
-- 本脚本一次性为这些用户补建 personal 类型组织，保证 fail-closed 生效后不会把存量用户锁死。
--
-- 幂等：仅处理没有活动组织归属的用户，可安全重复执行。
-- ============================================================

-- 1) 优先恢复用户原有但已软删除的 personal 组织，避免旧全表唯一约束阻止重建
UPDATE sys_organization o
SET type = 'personal',
    owner_id = u.id,
    deleted = FALSE,
    delete_time = NULL,
    update_time = CURRENT_TIMESTAMP
FROM sys_user u
WHERE u.deleted = FALSE
  AND o.slug = 'personal-' || u.id
  AND o.deleted = TRUE
  AND NOT EXISTS (
      SELECT 1
      FROM sys_org_member m
      JOIN sys_organization active_org ON active_org.id = m.org_id AND active_org.deleted = FALSE
      WHERE m.user_id = u.id AND m.deleted = FALSE
  );

-- 2) 为仍无活动组织归属的用户补建 personal 组织
INSERT INTO sys_organization (name, slug, type, owner_id, create_by)
SELECT u.username, 'personal-' || u.id, 'personal', u.id, u.id
FROM sys_user u
WHERE u.deleted = FALSE
  AND NOT EXISTS (
      SELECT 1
      FROM sys_org_member m
      JOIN sys_organization o ON o.id = m.org_id AND o.deleted = FALSE
      WHERE m.user_id = u.id AND m.deleted = FALSE
  )
  AND NOT EXISTS (
      SELECT 1 FROM sys_organization o WHERE o.slug = 'personal-' || u.id AND o.deleted = FALSE
  );

-- 3) 补建活动 personal 组织的成员关联（owner）
INSERT INTO sys_org_member (org_id, user_id, role, create_by)
SELECT o.id, o.owner_id, 'owner', o.owner_id
FROM sys_organization o
WHERE o.type = 'personal'
  AND o.deleted = FALSE
  AND NOT EXISTS (
      SELECT 1 FROM sys_org_member m WHERE m.org_id = o.id AND m.user_id = o.owner_id AND m.deleted = FALSE
  );

CREATE TABLE sys_todo_participant (
    todo_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (todo_id, user_id)
);

COMMENT ON TABLE sys_todo_participant IS '待办-参与人关联';

CREATE INDEX idx_todo_participant_user ON sys_todo_participant (user_id, todo_id);

-- 统一 L1-L4 授权运行时：策略生命周期/快照、授权审计和一次性 challenge。
-- Flyway locations 跨 db/migration 与 db/seed 全局排序；本脚本承接 v14，视图种子 v100-v103 后续执行。

ALTER TABLE sys_access_policy
    ADD COLUMN lifecycle VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN published_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN fact_schema_json TEXT NOT NULL DEFAULT '{}';

UPDATE sys_access_policy
SET condition_json = COALESCE(NULLIF(BTRIM(condition_json), ''), '{}'),
    fact_schema_json = '{}',
    target_resource = COALESCE(NULLIF(BTRIM(target_resource), ''), '*'),
    target_action = COALESCE(NULLIF(BTRIM(target_action), ''), '*'),
    lifecycle = CASE WHEN status = 1 THEN 'SHADOW' ELSE 'DRAFT' END,
    published_version = CASE WHEN status = 1 THEN 1 ELSE 0 END;

DROP INDEX IF EXISTS idx_sys_access_policy_target;

ALTER TABLE sys_access_policy
    ALTER COLUMN condition_json SET NOT NULL,
    ALTER COLUMN target_resource SET NOT NULL,
    ALTER COLUMN target_action SET NOT NULL,
    DROP COLUMN status,
    ADD CONSTRAINT ck_access_policy_lifecycle
        CHECK (lifecycle IN ('DRAFT', 'SHADOW', 'ENFORCE', 'DISABLED')),
    ADD CONSTRAINT ck_access_policy_effect
        CHECK (effect IN ('ALLOW', 'DENY', 'CHALLENGE'));

CREATE INDEX idx_sys_access_policy_runtime
    ON sys_access_policy (lifecycle, target_resource, target_action, priority)
    WHERE deleted = FALSE AND lifecycle IN ('SHADOW', 'ENFORCE');

CREATE TABLE sys_access_policy_snapshot (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    policy_id         BIGINT       NOT NULL,
    policy_version    BIGINT       NOT NULL,
    name              VARCHAR(128) NOT NULL,
    description       VARCHAR(512),
    condition_json    TEXT         NOT NULL,
    fact_schema_json  TEXT         NOT NULL,
    effect            VARCHAR(16)  NOT NULL,
    priority          INTEGER      NOT NULL,
    target_resource   VARCHAR(64)  NOT NULL,
    target_action     VARCHAR(64)  NOT NULL,
    lifecycle         VARCHAR(16)  NOT NULL,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id          BIGINT,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255),
    CONSTRAINT uk_access_policy_snapshot UNIQUE (policy_id, policy_version),
    CONSTRAINT ck_access_policy_snapshot_lifecycle
        CHECK (lifecycle IN ('SHADOW', 'ENFORCE')),
    CONSTRAINT ck_access_policy_snapshot_effect
        CHECK (effect IN ('ALLOW', 'DENY', 'CHALLENGE'))
);

-- 旧启用策略只进入 SHADOW，避免未经重新编译和人工发布直接参与正式裁决。
INSERT INTO sys_access_policy_snapshot (
    policy_id,
    policy_version,
    name,
    description,
    condition_json,
    fact_schema_json,
    effect,
    priority,
    target_resource,
    target_action,
    lifecycle,
    org_id,
    workspace_id,
    create_by,
    create_by_type,
    owner_id
)
SELECT id,
       1,
       name,
       description,
       condition_json,
       fact_schema_json,
       effect,
       priority,
       target_resource,
       target_action,
       'SHADOW',
       org_id,
       workspace_id,
       create_by,
       create_by_type,
       owner_id
FROM sys_access_policy
WHERE lifecycle = 'SHADOW'
  AND deleted = FALSE;

-- 既有会话物化 OWNER 关系；新会话由 RelationPermissionWriter 在创建事务中同步写入。
INSERT INTO sys_permission_tuple (
    org_id,
    workspace_id,
    object_type,
    object_id,
    relation,
    subject_type,
    subject_id,
    subject_relation,
    granted_by,
    owner_id
)
SELECT conversation.org_id,
       conversation.workspace_id,
       'session',
       conversation.id::VARCHAR,
       'OWNER',
       'USER',
       conversation.creator_id::VARCHAR,
       '',
       'migration:v15',
       conversation.creator_id
FROM conversation
WHERE conversation.deleted = FALSE
ON CONFLICT (object_type, object_id, relation, subject_type, subject_id, subject_relation)
DO UPDATE SET org_id = EXCLUDED.org_id,
              workspace_id = EXCLUDED.workspace_id,
              granted_by = EXCLUDED.granted_by,
              owner_id = EXCLUDED.owner_id,
              deleted = FALSE,
              delete_time = NULL,
              update_time = CURRENT_TIMESTAMP
WHERE sys_permission_tuple.deleted = TRUE;

CREATE INDEX idx_access_policy_snapshot_target
    ON sys_access_policy_snapshot (target_resource, target_action, priority)
    WHERE deleted = FALSE;

CREATE TABLE sys_authorization_challenge (
    id                UUID         PRIMARY KEY,
    operator_id       BIGINT,
    subject_id        BIGINT       NOT NULL,
    tenant_id         BIGINT,
    workspace_id      BIGINT,
    resource          VARCHAR(128) NOT NULL,
    action            VARCHAR(64)  NOT NULL,
    object_id         VARCHAR(128),
    request_digest    VARCHAR(64)  NOT NULL,
    policy_id         BIGINT       NOT NULL,
    policy_version    BIGINT       NOT NULL,
    snapshot_version  VARCHAR(64)  NOT NULL,
    status            VARCHAR(16)  NOT NULL,
    expires_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    approved_at       TIMESTAMP(6) WITH TIME ZONE,
    consumed_at       TIMESTAMP(6) WITH TIME ZONE,
    create_time       TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_authorization_challenge_status
        CHECK (status IN ('PENDING', 'APPROVED', 'CONSUMED'))
);

CREATE INDEX idx_authorization_challenge_subject_status
    ON sys_authorization_challenge (subject_id, status, expires_at);

CREATE TABLE sys_authorization_audit (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    event_type        VARCHAR(40)  NOT NULL,
    operator_id       BIGINT,
    subject_id        BIGINT,
    tenant_id         BIGINT,
    resource          VARCHAR(128),
    action            VARCHAR(64),
    object_id         VARCHAR(128),
    layer             VARCHAR(32),
    effect            VARCHAR(32)  NOT NULL,
    policy_id         BIGINT,
    policy_version    BIGINT,
    snapshot_version  VARCHAR(64),
    shadow            BOOLEAN      NOT NULL DEFAULT FALSE,
    challenge_id      UUID,
    reason            VARCHAR(512),
    occurred_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id          BIGINT,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

CREATE INDEX idx_authorization_audit_subject_time
    ON sys_authorization_audit (subject_id, occurred_at DESC)
    WHERE deleted = FALSE;
CREATE INDEX idx_authorization_audit_policy
    ON sys_authorization_audit (policy_id, policy_version)
    WHERE deleted = FALSE;

COMMENT ON TABLE sys_access_policy_snapshot IS '不可变授权策略发布快照';
COMMENT ON TABLE sys_authorization_challenge IS '一次性授权确认，绑定请求和策略版本';
COMMENT ON TABLE sys_authorization_audit IS '统一授权、策略影子评估和生命周期审计';
