-- ============================================================
-- 命名说明：本文件所有 tenant_id 列（VARCHAR）承载业务系统 sys_organization.id（org_id）的字符串投影，
-- 与 org_id 是同一个隔离维度，不是并行的第二套多租户机制。领域层用 tenant_id 而非直接依赖 org_id: BIGINT，
-- 是为了不让 intelligent.* 五层架构领域模型依赖具体业务模块的持久化类型；取值处见各 Controller 的
-- new TenantId(orgId.toString())。详见 intelligent.shared.id.StableId.TenantId 的类型注释。
-- ============================================================

-- 助理运行时基础表：每次执行冻结画像 + 任务控制状态机。
CREATE TABLE ai_execution_profile_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    execution_id VARCHAR(128) NOT NULL,
    assistant_id VARCHAR(128) NOT NULL,
    assistant_revision BIGINT NOT NULL,
    snapshot_payload JSONB NOT NULL,
    frozen_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_execution_profile_assistant_revision CHECK (assistant_revision >= 0)
);

COMMENT ON TABLE ai_execution_profile_snapshot IS '单次执行画像：追加式记录，恢复取同一 execution_id 下 frozen_at 最新一条，供审计与任务恢复';
COMMENT ON COLUMN ai_execution_profile_snapshot.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_execution_profile_snapshot.task_id IS '任务稳定标识';
COMMENT ON COLUMN ai_execution_profile_snapshot.execution_id IS '执行稳定标识；同一执行可多次追加，画像随物理调用推进';
COMMENT ON COLUMN ai_execution_profile_snapshot.assistant_id IS '本次执行采用的 Assistant 稳定标识';
COMMENT ON COLUMN ai_execution_profile_snapshot.assistant_revision IS '冻结时 ai_assistant 当前行修订号，仅供审计，不支持请求选择';
COMMENT ON COLUMN ai_execution_profile_snapshot.snapshot_payload IS '完整 ExecutionProfileSnapshot JSON';
COMMENT ON COLUMN ai_execution_profile_snapshot.frozen_at IS '本条画像冻结时间，同一 execution_id 下取最大值为最新画像';
CREATE INDEX idx_execution_profile_execution_frozen
    ON ai_execution_profile_snapshot (tenant_id, execution_id, frozen_at DESC);
CREATE INDEX idx_execution_profile_task
    ON ai_execution_profile_snapshot (tenant_id, task_id, frozen_at DESC);

-- 逐次物理模型请求信封：一次 provider 发送一份，append-only，不回写执行画像。
CREATE TABLE ai_prompt_envelope (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    execution_id VARCHAR(128) NOT NULL,
    envelope_seq INTEGER NOT NULL,
    attempt_no INTEGER NOT NULL DEFAULT 1,
    prompt_sha256 VARCHAR(64) NOT NULL,
    trigger_kind VARCHAR(32) NOT NULL,
    envelope_payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_prompt_envelope UNIQUE (tenant_id, execution_id, envelope_seq),
    CONSTRAINT ck_prompt_envelope_seq CHECK (envelope_seq >= 1),
    CONSTRAINT ck_prompt_envelope_attempt CHECK (attempt_no >= 1)
);

COMMENT ON TABLE ai_prompt_envelope IS '逐次物理模型请求信封：provider 发送前冻结，只存 hash 与长度投影，不存消息正文';
COMMENT ON COLUMN ai_prompt_envelope.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_prompt_envelope.task_id IS '任务稳定标识';
COMMENT ON COLUMN ai_prompt_envelope.execution_id IS '执行稳定标识；恢复取该执行的最大 envelope_seq 继续';
COMMENT ON COLUMN ai_prompt_envelope.envelope_seq IS '同一执行内严格递增；一次 provider 发送一份，重试不复用';
COMMENT ON COLUMN ai_prompt_envelope.attempt_no IS '同一逻辑调用的传输层重试次数，与 envelope_seq 正交';
COMMENT ON COLUMN ai_prompt_envelope.prompt_sha256 IS '模型/参数/消息/工具的规范化联合 hash，从 payload 提列供查询与去重';
COMMENT ON COLUMN ai_prompt_envelope.trigger_kind IS '信封产生原因：INITIAL/RETRY/COMPACTED/SKILL_LOADED/REFERENCE_LOADED';
COMMENT ON COLUMN ai_prompt_envelope.envelope_payload IS '完整 PromptEnvelope JSON；按披露约束只含 hash、长度与引用';
COMMENT ON COLUMN ai_prompt_envelope.created_at IS '信封冻结时间';
CREATE INDEX idx_prompt_envelope_task
    ON ai_prompt_envelope (tenant_id, task_id, created_at DESC);

CREATE TABLE ai_assistant_task_control (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    task_status VARCHAR(32) NOT NULL,
    control_mode VARCHAR(32) NOT NULL,
    task_payload JSONB NOT NULL,
    fencing_token BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_assistant_task_tenant_task UNIQUE (tenant_id, task_id),
    CONSTRAINT ck_assistant_task_fencing_token CHECK (fencing_token >= 0),
    CONSTRAINT ck_assistant_task_delegated_fencing
        CHECK (control_mode <> 'DELEGATED' OR fencing_token > 0)
);

COMMENT ON TABLE ai_assistant_task_control IS '助理任务控制状态：记录任务运行状态、控制模式与 fencing 信息';
COMMENT ON COLUMN ai_assistant_task_control.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_assistant_task_control.task_id IS '助理任务稳定标识';
COMMENT ON COLUMN ai_assistant_task_control.task_status IS '任务当前状态';
COMMENT ON COLUMN ai_assistant_task_control.control_mode IS '任务控制模式，如 DELEGATED';
COMMENT ON COLUMN ai_assistant_task_control.task_payload IS '任务控制所需的完整 JSON 数据';
COMMENT ON COLUMN ai_assistant_task_control.fencing_token IS '租约 fencing 令牌，防止过期执行者写入';
COMMENT ON COLUMN ai_assistant_task_control.version IS '乐观锁版本号';

CREATE INDEX idx_assistant_task_status
    ON ai_assistant_task_control (tenant_id, task_status);

-- ============================================================
-- P3 治理：认知记忆、有效上下文、凭证/授权/HITL、任务事件重建。
-- ============================================================

CREATE TABLE ai_cognition_memory (
    memory_id VARCHAR(64) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    subject_kind VARCHAR(16) NOT NULL,
    subject_id VARCHAR(128) NOT NULL,
    content TEXT NOT NULL,
    redacted_summary VARCHAR(256) NOT NULL,
    importance DOUBLE PRECISION NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    privacy VARCHAR(16) NOT NULL,
    tags TEXT[],
    embedding vector(1536),
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    forgotten_at TIMESTAMPTZ,
    CONSTRAINT ck_cognition_subject_kind CHECK (subject_kind IN ('USER', 'VISITOR')),
    CONSTRAINT ck_cognition_privacy CHECK (privacy IN ('PUBLIC', 'PERSONAL', 'SENSITIVE', 'SECRET')),
    CONSTRAINT ck_cognition_scores CHECK (
        importance BETWEEN 0 AND 1 AND confidence BETWEEN 0 AND 1),
    CONSTRAINT ck_cognition_visitor_ttl CHECK (
        subject_kind <> 'VISITOR' OR expires_at IS NOT NULL)
);

COMMENT ON TABLE ai_cognition_memory IS '认知记忆：保存用户或访客的结构化长期记忆及语义向量';
COMMENT ON COLUMN ai_cognition_memory.memory_id IS '记忆稳定标识';
COMMENT ON COLUMN ai_cognition_memory.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_cognition_memory.subject_kind IS '记忆主体类型：USER 或 VISITOR';
COMMENT ON COLUMN ai_cognition_memory.subject_id IS '记忆主体标识';
COMMENT ON COLUMN ai_cognition_memory.content IS '记忆原始内容';
COMMENT ON COLUMN ai_cognition_memory.redacted_summary IS '脱敏后的记忆摘要';
COMMENT ON COLUMN ai_cognition_memory.importance IS '记忆重要度，取值范围 0 至 1';
COMMENT ON COLUMN ai_cognition_memory.confidence IS '记忆置信度，取值范围 0 至 1';
COMMENT ON COLUMN ai_cognition_memory.privacy IS '隐私级别：PUBLIC、PERSONAL、SENSITIVE 或 SECRET';
COMMENT ON COLUMN ai_cognition_memory.tags IS '记忆标签集合';
COMMENT ON COLUMN ai_cognition_memory.embedding IS '固定 1536 维的记忆语义向量';
COMMENT ON COLUMN ai_cognition_memory.expires_at IS '记忆过期时间，访客记忆必须设置';
COMMENT ON COLUMN ai_cognition_memory.forgotten_at IS '逻辑遗忘时间，非空表示记忆已遗忘';
CREATE INDEX idx_cognition_memory_subject
    ON ai_cognition_memory (tenant_id, subject_kind, subject_id, importance DESC)
    WHERE forgotten_at IS NULL;
CREATE INDEX idx_cognition_memory_expiry
    ON ai_cognition_memory (expires_at)
    WHERE subject_kind = 'VISITOR' AND forgotten_at IS NULL;
CREATE INDEX idx_cognition_memory_embedding
    ON ai_cognition_memory USING hnsw (embedding vector_cosine_ops);

CREATE TABLE ai_context_source_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    assistant_id VARCHAR(128) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_key VARCHAR(256) NOT NULL,
    disposition VARCHAR(16) NOT NULL,
    reason VARCHAR(512) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_context_source_preference
        UNIQUE (tenant_id, user_id, assistant_id, source_type, source_key),
    CONSTRAINT ck_context_source_disposition
        CHECK (disposition IN ('DEFAULT', 'PREFERRED', 'DISABLED', 'REMOVED'))
);

COMMENT ON TABLE ai_context_source_preference IS '上下文来源偏好：记录用户对助理上下文来源的启用、偏好或移除设置';
COMMENT ON COLUMN ai_context_source_preference.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_context_source_preference.user_id IS '用户稳定标识';
COMMENT ON COLUMN ai_context_source_preference.assistant_id IS '助理稳定标识';
COMMENT ON COLUMN ai_context_source_preference.source_type IS '上下文来源类型';
COMMENT ON COLUMN ai_context_source_preference.source_key IS '上下文来源唯一键';
COMMENT ON COLUMN ai_context_source_preference.disposition IS '来源处置方式：DEFAULT、PREFERRED、DISABLED 或 REMOVED';
COMMENT ON COLUMN ai_context_source_preference.reason IS '设置该来源偏好的原因';

CREATE TABLE ai_effective_context_manifest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    manifest_payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_effective_context_task UNIQUE (tenant_id, task_id)
);

COMMENT ON TABLE ai_effective_context_manifest IS '有效上下文清单：存证任务实际采用的上下文来源与组装结果';
COMMENT ON COLUMN ai_effective_context_manifest.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_effective_context_manifest.task_id IS '任务稳定标识';
COMMENT ON COLUMN ai_effective_context_manifest.manifest_payload IS '有效上下文清单的完整 JSON 数据';

CREATE TABLE ai_credential_handle (
    handle_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    connector_id VARCHAR(256) NOT NULL,
    scopes TEXT[] NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    vault_ref VARCHAR(512) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_credential_handle_expiry CHECK (expires_at > created_at)
);

COMMENT ON TABLE ai_credential_handle IS '连接器凭证句柄：保存外部凭证的授权范围、有效期与密钥库引用';
COMMENT ON COLUMN ai_credential_handle.handle_id IS '凭证句柄稳定标识';
COMMENT ON COLUMN ai_credential_handle.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_credential_handle.user_id IS '凭证所属用户标识';
COMMENT ON COLUMN ai_credential_handle.connector_id IS '连接器稳定标识';
COMMENT ON COLUMN ai_credential_handle.scopes IS '凭证授权范围集合';
COMMENT ON COLUMN ai_credential_handle.expires_at IS '凭证句柄过期时间';
COMMENT ON COLUMN ai_credential_handle.revoked_at IS '凭证撤销时间，非空表示已撤销';
COMMENT ON COLUMN ai_credential_handle.vault_ref IS '外部密钥库中的凭证引用，不保存明文凭证';
CREATE INDEX idx_credential_handle_active
    ON ai_credential_handle (tenant_id, user_id, connector_id, expires_at DESC)
    WHERE revoked_at IS NULL;

CREATE TABLE ai_authorization_grant (
    grant_id VARCHAR(64) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    action VARCHAR(256) NOT NULL,
    resource VARCHAR(256) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    grant_payload JSONB NOT NULL,
    CONSTRAINT ck_authorization_grant_resource CHECK (resource <> '*')
);

COMMENT ON TABLE ai_authorization_grant IS '任务授权许可：记录任务对指定动作和资源的限时授权';
COMMENT ON COLUMN ai_authorization_grant.grant_id IS '授权许可稳定标识';
COMMENT ON COLUMN ai_authorization_grant.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_authorization_grant.task_id IS '获授权的任务标识';
COMMENT ON COLUMN ai_authorization_grant.action IS '获授权执行的动作';
COMMENT ON COLUMN ai_authorization_grant.resource IS '获授权访问的具体资源，不允许使用通配符';
COMMENT ON COLUMN ai_authorization_grant.expires_at IS '授权许可过期时间';
COMMENT ON COLUMN ai_authorization_grant.revoked_at IS '授权撤销时间，非空表示已撤销';
COMMENT ON COLUMN ai_authorization_grant.grant_payload IS '授权许可的完整 JSON 数据';
CREATE INDEX idx_authorization_grant_lookup
    ON ai_authorization_grant (tenant_id, task_id, action, resource, expires_at)
    WHERE revoked_at IS NULL;

CREATE TABLE ai_hitl_approval (
    approval_id VARCHAR(64) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    decided_at TIMESTAMPTZ,
    approval_payload JSONB NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_hitl_approval_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

COMMENT ON TABLE ai_hitl_approval IS '人机协同审批：记录任务人工确认请求及审批结果';
COMMENT ON COLUMN ai_hitl_approval.approval_id IS '审批稳定标识';
COMMENT ON COLUMN ai_hitl_approval.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_hitl_approval.task_id IS '待审批任务标识';
COMMENT ON COLUMN ai_hitl_approval.status IS '审批状态：PENDING、APPROVED 或 REJECTED';
COMMENT ON COLUMN ai_hitl_approval.decided_at IS '审批作出决定的时间';
COMMENT ON COLUMN ai_hitl_approval.approval_payload IS '审批请求与上下文的完整 JSON 数据';
COMMENT ON COLUMN ai_hitl_approval.version IS '乐观锁版本号';
CREATE INDEX idx_hitl_approval_pending
    ON ai_hitl_approval (tenant_id, task_id, created_at)
    WHERE status = 'PENDING';

-- ==================== 工具层人工确认（M36） ====================
-- 与上面的 ai_hitl_approval 分工：
--   ai_hitl_approval —— 任务级审批，需 AssistantTask/InvocationContext，决定后驱动任务状态迁移与恢复
--   ai_tool_approval —— 会话/工作流级工具确认（ToolService REST 调用、Flowable ToolNode 等无任务上下文的入口），
--                       决定后由 ToolApprovalGrantListener 回写会话级工具授权
-- 此表取代原内存版 HumanApprovalService：内存态在重启/多实例下丢失，且旧链无任何消费方，
-- 审批建出来永远无人可处理，而卡片已推给用户。

CREATE TABLE ai_tool_approval (
    approval_id      VARCHAR(64)  PRIMARY KEY,
    scope_key        VARCHAR(128) NOT NULL,
    user_id          BIGINT       NOT NULL,
    approval_type    VARCHAR(32)  NOT NULL,
    title            VARCHAR(200) NOT NULL,
    description      VARCHAR(1000),
    subject_type     VARCHAR(32),
    subject_key      VARCHAR(200),
    risk_level       VARCHAR(16),
    confidence       DOUBLE PRECISION,
    grant_scope      VARCHAR(16)  NOT NULL DEFAULT 'NONE',
    context_json     TEXT,
    status           VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    decision_reason  VARCHAR(500),
    created_at       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at       TIMESTAMP(6) NOT NULL,
    decided_at       TIMESTAMP(6),
    decided_by       BIGINT,
    version          INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT ck_tool_approval_status CHECK (status IN ('PENDING','APPROVED','REJECTED','TIMEOUT'))
);

COMMENT ON TABLE ai_tool_approval IS '工具层人工确认：会话/工作流级工具调用、内容审查、低置信度确认';
COMMENT ON COLUMN ai_tool_approval.scope_key IS '授权作用域键：会话 sessionId 或 workflow:<processInstanceId>；无会话时为 "-"';
COMMENT ON COLUMN ai_tool_approval.grant_scope IS '批准后授予范围：NONE/ONCE/SESSION/PATTERN，由监听器回写工具授权';
COMMENT ON COLUMN ai_tool_approval.status IS 'PENDING/APPROVED/REJECTED/TIMEOUT；TIMEOUT 由读取时按 expires_at 判定并落库';

CREATE INDEX idx_tool_approval_user_status ON ai_tool_approval (user_id, status);
CREATE INDEX idx_tool_approval_scope ON ai_tool_approval (scope_key, status);

CREATE TABLE ai_task_recovery_command (
    command_key VARCHAR(300) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    command_payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_task_recovery_command UNIQUE (tenant_id, task_id)
);

COMMENT ON TABLE ai_task_recovery_command IS '任务恢复命令：保存任务恢复执行所需的最新幂等命令';
COMMENT ON COLUMN ai_task_recovery_command.command_key IS '恢复命令幂等键';
COMMENT ON COLUMN ai_task_recovery_command.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_task_recovery_command.task_id IS '待恢复任务标识';
COMMENT ON COLUMN ai_task_recovery_command.command_payload IS '恢复命令的完整 JSON 数据';

CREATE TABLE ai_hitl_recovery (
    approval_id VARCHAR(64) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    lease_until TIMESTAMPTZ,
    last_error VARCHAR(1000),
    command_payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_hitl_recovery_approval
        FOREIGN KEY (approval_id) REFERENCES ai_hitl_approval(approval_id),
    CONSTRAINT ck_hitl_recovery_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED'))
);

COMMENT ON TABLE ai_hitl_recovery IS '人机协同恢复任务：跟踪审批后恢复执行的状态、租约与重试信息';
COMMENT ON COLUMN ai_hitl_recovery.approval_id IS '关联的人机协同审批标识';
COMMENT ON COLUMN ai_hitl_recovery.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_hitl_recovery.task_id IS '待恢复任务标识';
COMMENT ON COLUMN ai_hitl_recovery.status IS '恢复状态：PENDING、PROCESSING 或 COMPLETED';
COMMENT ON COLUMN ai_hitl_recovery.attempts IS '恢复执行尝试次数';
COMMENT ON COLUMN ai_hitl_recovery.lease_until IS '当前恢复执行租约的截止时间';
COMMENT ON COLUMN ai_hitl_recovery.last_error IS '最近一次恢复失败信息';
COMMENT ON COLUMN ai_hitl_recovery.command_payload IS '恢复命令的完整 JSON 数据';
COMMENT ON COLUMN ai_hitl_recovery.version IS '乐观锁版本号';
CREATE INDEX idx_hitl_recovery_task
    ON ai_hitl_recovery (tenant_id, task_id, status);

CREATE TABLE ai_execution_sequence (
    tenant_id VARCHAR(128) NOT NULL,
    execution_id VARCHAR(128) NOT NULL,
    next_sequence BIGINT NOT NULL,
    PRIMARY KEY (tenant_id, execution_id),
    CONSTRAINT ck_execution_next_sequence CHECK (next_sequence > 0)
);

COMMENT ON TABLE ai_execution_sequence IS '执行事件序列：为租户内单次执行分配严格递增的事件序号';
COMMENT ON COLUMN ai_execution_sequence.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_execution_sequence.execution_id IS '执行实例稳定标识';
COMMENT ON COLUMN ai_execution_sequence.next_sequence IS '下一次可分配的事件序号';

CREATE TABLE ai_connector_action_execution (
    idempotency_key VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    execution_id VARCHAR(128) NOT NULL,
    connector_id VARCHAR(256) NOT NULL,
    action_name VARCHAR(120) NOT NULL,
    request_digest VARCHAR(64) NOT NULL,
    provider_idempotency_key VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    result TEXT,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_connector_action_status CHECK (status IN ('PENDING', 'SUCCEEDED'))
);

COMMENT ON TABLE ai_connector_action_execution IS '连接器动作执行记录：保障外部连接器调用幂等并保存执行结果';
COMMENT ON COLUMN ai_connector_action_execution.idempotency_key IS '连接器动作执行幂等键';
COMMENT ON COLUMN ai_connector_action_execution.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_connector_action_execution.user_id IS '发起连接器动作的用户标识';
COMMENT ON COLUMN ai_connector_action_execution.task_id IS '所属任务标识';
COMMENT ON COLUMN ai_connector_action_execution.execution_id IS '所属执行实例标识';
COMMENT ON COLUMN ai_connector_action_execution.connector_id IS '连接器稳定标识';
COMMENT ON COLUMN ai_connector_action_execution.action_name IS '连接器动作名称';
COMMENT ON COLUMN ai_connector_action_execution.request_digest IS '规范化请求内容摘要，用于检测幂等键冲突';
COMMENT ON COLUMN ai_connector_action_execution.provider_idempotency_key IS '传递给外部服务商的幂等键';
COMMENT ON COLUMN ai_connector_action_execution.status IS '执行状态：PENDING 或 SUCCEEDED';
COMMENT ON COLUMN ai_connector_action_execution.result IS '连接器动作执行结果';
COMMENT ON COLUMN ai_connector_action_execution.attempts IS '动作执行尝试次数';
COMMENT ON COLUMN ai_connector_action_execution.last_error IS '最近一次执行失败信息';
CREATE INDEX idx_connector_action_execution
    ON ai_connector_action_execution (tenant_id, execution_id, created_at);

INSERT INTO sys_permission_code (name, code, module, resource, action, status)
VALUES (
    'Connector 凭证管理',
    'ai:connector-credential:manage',
    'ai',
    'connector-credential',
    'manage',
    0
)
ON CONFLICT (code) WHERE deleted = FALSE DO NOTHING;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
JOIN sys_permission_code p ON p.code = 'ai:connector-credential:manage'
WHERE r.code IN ('member', 'org_admin', 'admin', 'super_admin')
ON CONFLICT DO NOTHING;

-- ============================================================
-- P4 DELEGATED 生产闭环：持久任务、DAG、统一 receipt、通知 outbox 与 fencing 诊断。
-- ============================================================

-- v202 connector 专用幂等表不再由生产代码读写；统一 receipt 是唯一事实。

CREATE TABLE ai_delegated_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    conversation_id VARCHAR(128) NOT NULL,
    execution_id VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    owner_kind VARCHAR(16) NOT NULL,
    owner_id VARCHAR(128) NOT NULL,
    source VARCHAR(32) NOT NULL DEFAULT 'AUTOMATION',
    priority INTEGER NOT NULL DEFAULT 0,
    next_run_at TIMESTAMPTZ NOT NULL,
    lease_owner VARCHAR(128),
    lease_until TIMESTAMPTZ,
    fencing_token BIGINT NOT NULL DEFAULT 0,
    task_payload JSONB NOT NULL,
    command_payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_delegated_task_tenant_task UNIQUE (tenant_id, task_id),
    CONSTRAINT ck_delegated_task_status CHECK (status IN (
        'PENDING', 'RUNNING', 'PAUSED', 'AWAITING_AUTHORIZATION',
        'AWAITING_CLARIFICATION', 'COMPLETED', 'CANCELED', 'FAILED')),
    CONSTRAINT ck_delegated_task_owner CHECK (owner_kind IN ('ASSISTANT', 'AGENT', 'HUMAN')),
    CONSTRAINT ck_delegated_task_source CHECK (source IN ('CONVERSATION', 'MANUAL', 'AUTOMATION')),
    CONSTRAINT ck_delegated_task_fencing CHECK (fencing_token >= 0),
    CONSTRAINT ck_delegated_task_running_lease CHECK (
        status <> 'RUNNING'
        OR (lease_owner IS NOT NULL AND lease_until IS NOT NULL AND fencing_token > 0)),
    CONSTRAINT ck_delegated_task_human_not_running CHECK (
        owner_kind <> 'HUMAN' OR status <> 'RUNNING')
);

COMMENT ON TABLE ai_delegated_task IS '委托任务：持久化非阻塞任务的所有权、调度状态、租约与执行命令';
COMMENT ON COLUMN ai_delegated_task.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_delegated_task.user_id IS '委托任务所属用户标识';
COMMENT ON COLUMN ai_delegated_task.task_id IS '委托任务稳定标识';
COMMENT ON COLUMN ai_delegated_task.conversation_id IS '关联会话稳定标识';
COMMENT ON COLUMN ai_delegated_task.execution_id IS '关联执行实例稳定标识';
COMMENT ON COLUMN ai_delegated_task.status IS '任务状态：PENDING、RUNNING、PAUSED、AWAITING_AUTHORIZATION、AWAITING_CLARIFICATION、完成、取消或失败';
COMMENT ON COLUMN ai_delegated_task.owner_kind IS '任务所有者类型：ASSISTANT、AGENT 或 HUMAN';
COMMENT ON COLUMN ai_delegated_task.owner_id IS '任务所有者稳定标识';
COMMENT ON COLUMN ai_delegated_task.source IS '任务来源：CONVERSATION、MANUAL 或 AUTOMATION';
COMMENT ON COLUMN ai_delegated_task.priority IS '调度优先级';
COMMENT ON COLUMN ai_delegated_task.next_run_at IS '下次允许调度执行的时间';
COMMENT ON COLUMN ai_delegated_task.lease_owner IS '当前运行租约持有者';
COMMENT ON COLUMN ai_delegated_task.lease_until IS '当前运行租约截止时间';
COMMENT ON COLUMN ai_delegated_task.fencing_token IS '租约 fencing 令牌，防止过期执行者写入';
COMMENT ON COLUMN ai_delegated_task.task_payload IS '委托任务的完整 JSON 数据';
COMMENT ON COLUMN ai_delegated_task.command_payload IS '任务执行命令的完整 JSON 数据';
COMMENT ON COLUMN ai_delegated_task.version IS '乐观锁版本号';
CREATE INDEX idx_delegated_task_dispatch
    ON ai_delegated_task (status, next_run_at)
    WHERE status IN ('PENDING', 'RUNNING');
CREATE INDEX idx_delegated_task_conversation
    ON ai_delegated_task (tenant_id, conversation_id, status);
CREATE INDEX idx_delegated_task_user
    ON ai_delegated_task (tenant_id, user_id, updated_at DESC);

CREATE TABLE ai_task_board (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    board_payload JSONB NOT NULL,
    fencing_token BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_task_board_tenant_task UNIQUE (tenant_id, task_id),
    CONSTRAINT ck_task_board_fencing CHECK (fencing_token >= 0)
);

COMMENT ON TABLE ai_task_board IS '任务看板：保存委托任务的分解步骤、进度与 fencing 状态';
COMMENT ON COLUMN ai_task_board.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_task_board.task_id IS '任务稳定标识';
COMMENT ON COLUMN ai_task_board.board_payload IS '任务看板的完整 JSON 数据';
COMMENT ON COLUMN ai_task_board.fencing_token IS '租约 fencing 令牌，防止过期执行者写入';
COMMENT ON COLUMN ai_task_board.version IS '乐观锁版本号';

CREATE TABLE ai_clarification_request (
    request_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    execution_id VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    deadline TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    resolved_at TIMESTAMPTZ,
    request_payload JSONB NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_clarification_status
        CHECK (status IN ('PENDING', 'RESOLVED', 'CANCELED', 'EXPIRED')),
    CONSTRAINT ck_clarification_deadline CHECK (deadline > created_at),
    CONSTRAINT ck_clarification_resolution CHECK (
        (status = 'PENDING' AND resolved_at IS NULL)
        OR (status <> 'PENDING' AND resolved_at IS NOT NULL))
);

COMMENT ON TABLE ai_clarification_request IS '结构化澄清请求：与动作授权独立，按字段收集任务缺失参数';
COMMENT ON COLUMN ai_clarification_request.request_id IS '澄清请求稳定标识';
COMMENT ON COLUMN ai_clarification_request.execution_id IS '等待澄清的同一子 execution 标识';
COMMENT ON COLUMN ai_clarification_request.request_payload IS '字段、问题、选项、deadline、状态和值的完整 JSON';
CREATE UNIQUE INDEX uk_clarification_pending_task
    ON ai_clarification_request (tenant_id, task_id)
    WHERE status = 'PENDING';
CREATE INDEX idx_clarification_deadline
    ON ai_clarification_request (status, deadline)
    WHERE status = 'PENDING';

CREATE TABLE ai_task_input_buffer (
    input_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    input_payload JSONB NOT NULL
);

COMMENT ON TABLE ai_task_input_buffer IS '任务输入缓冲：非阻塞接受输入事实，由持有 conversation lease 的调度者确定性消费';
COMMENT ON COLUMN ai_task_input_buffer.input_id IS '调用方提供的输入幂等标识';
COMMENT ON COLUMN ai_task_input_buffer.consumed_at IS '输入已合并到任务命令的时间，空值表示待消费';
CREATE INDEX idx_task_input_pending
    ON ai_task_input_buffer (tenant_id, task_id, received_at, input_id)
    WHERE consumed_at IS NULL;

CREATE TABLE ai_task_transition_outbox (
    outbox_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    event_payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,
    CONSTRAINT uk_task_transition_event UNIQUE (event_id),
    CONSTRAINT ck_task_transition_outbox_status CHECK (status IN ('PENDING', 'PUBLISHED'))
);

COMMENT ON TABLE ai_task_transition_outbox IS '任务迁移发件箱：与 task、board、ai_task_event 同事务提交后可靠发布';
CREATE INDEX idx_task_transition_outbox_pending
    ON ai_task_transition_outbox (status, created_at)
    WHERE status = 'PENDING';

CREATE TABLE ai_tool_invocation_receipt (
    receipt_key VARCHAR(128) PRIMARY KEY,
    request_digest VARCHAR(64) NOT NULL,
    tenant_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    execution_id VARCHAR(128) NOT NULL,
    fencing_token BIGINT NOT NULL DEFAULT 0,
    tool_id VARCHAR(256) NOT NULL,
    action_key VARCHAR(256) NOT NULL,
    status VARCHAR(16) NOT NULL,
    result_payload JSONB,
    last_error VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_tool_receipt_status CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_tool_receipt_fencing CHECK (fencing_token >= 0)
);

COMMENT ON TABLE ai_tool_invocation_receipt IS '工具调用回执：统一记录工具调用幂等状态、结果与 fencing 信息';
COMMENT ON COLUMN ai_tool_invocation_receipt.receipt_key IS '工具调用回执幂等键';
COMMENT ON COLUMN ai_tool_invocation_receipt.request_digest IS '规范化调用请求摘要，用于检测幂等键冲突';
COMMENT ON COLUMN ai_tool_invocation_receipt.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_tool_invocation_receipt.user_id IS '发起工具调用的用户标识';
COMMENT ON COLUMN ai_tool_invocation_receipt.task_id IS '所属任务标识';
COMMENT ON COLUMN ai_tool_invocation_receipt.execution_id IS '所属执行实例标识';
COMMENT ON COLUMN ai_tool_invocation_receipt.fencing_token IS '租约 fencing 令牌，防止过期执行者写入';
COMMENT ON COLUMN ai_tool_invocation_receipt.tool_id IS '工具稳定标识';
COMMENT ON COLUMN ai_tool_invocation_receipt.action_key IS '工具动作键';
COMMENT ON COLUMN ai_tool_invocation_receipt.status IS '调用状态：PENDING、SUCCEEDED 或 FAILED';
COMMENT ON COLUMN ai_tool_invocation_receipt.result_payload IS '工具调用结果的 JSON 数据';
COMMENT ON COLUMN ai_tool_invocation_receipt.last_error IS '最近一次调用失败信息';
COMMENT ON COLUMN ai_tool_invocation_receipt.version IS '乐观锁版本号';
CREATE INDEX idx_tool_receipt_task
    ON ai_tool_invocation_receipt (tenant_id, task_id, updated_at DESC);
CREATE INDEX idx_tool_receipt_action
    ON ai_tool_invocation_receipt (tenant_id, tool_id, action_key);

CREATE TABLE ai_task_notification_outbox (
    notification_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    notification_payload JSONB NOT NULL,
    last_error VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_task_notification_status CHECK (status IN ('PENDING', 'DISPATCHED', 'FAILED'))
);

COMMENT ON TABLE ai_task_notification_outbox IS '任务通知发件箱：可靠投递任务状态通知并记录失败原因';
COMMENT ON COLUMN ai_task_notification_outbox.notification_id IS '通知稳定标识';
COMMENT ON COLUMN ai_task_notification_outbox.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_task_notification_outbox.user_id IS '通知接收用户标识';
COMMENT ON COLUMN ai_task_notification_outbox.task_id IS '通知关联任务标识';
COMMENT ON COLUMN ai_task_notification_outbox.status IS '投递状态：PENDING、DISPATCHED 或 FAILED';
COMMENT ON COLUMN ai_task_notification_outbox.notification_payload IS '任务通知的完整 JSON 数据';
COMMENT ON COLUMN ai_task_notification_outbox.last_error IS '最近一次通知投递失败信息';
CREATE INDEX idx_task_notification_pending
    ON ai_task_notification_outbox (status, updated_at)
    WHERE status IN ('PENDING', 'FAILED');
CREATE INDEX idx_task_notification_task
    ON ai_task_notification_outbox (tenant_id, task_id, created_at DESC);

-- ============================================================
-- P5 非 Team 自动化：版本定义、幂等运行、组织策略、生命周期与审计。
-- ============================================================

CREATE TABLE ai_automation_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    automation_id VARCHAR(128) NOT NULL,
    definition_version BIGINT NOT NULL,
    lifecycle VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    definition_payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_automation_definition UNIQUE (tenant_id, automation_id, definition_version),
    CONSTRAINT ck_automation_definition_version CHECK (definition_version > 0),
    CONSTRAINT ck_automation_lifecycle CHECK (lifecycle IN ('DRAFT','PUBLISHED','DEPRECATED','DISABLED')),
    CONSTRAINT ck_automation_enable CHECK (enabled = FALSE OR lifecycle = 'PUBLISHED')
);

COMMENT ON TABLE ai_automation_definition IS '自动化定义版本：保存非 Team 自动化的生命周期、启用状态与定义快照';
COMMENT ON COLUMN ai_automation_definition.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_automation_definition.automation_id IS '自动化稳定标识';
COMMENT ON COLUMN ai_automation_definition.definition_version IS '自动化定义版本号';
COMMENT ON COLUMN ai_automation_definition.lifecycle IS '定义生命周期：DRAFT、PUBLISHED、DEPRECATED 或 DISABLED';
COMMENT ON COLUMN ai_automation_definition.enabled IS '是否允许触发该自动化，仅已发布版本可启用';
COMMENT ON COLUMN ai_automation_definition.definition_payload IS '自动化定义的完整 JSON 快照';
COMMENT ON COLUMN ai_automation_definition.version IS '乐观锁版本号';
CREATE INDEX idx_automation_definition_tenant ON ai_automation_definition (tenant_id, automation_id, definition_version DESC);
CREATE INDEX idx_automation_definition_enabled ON ai_automation_definition (enabled, updated_at) WHERE enabled = TRUE;

CREATE TABLE ai_automation_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    run_id VARCHAR(128) NOT NULL,
    automation_id VARCHAR(128) NOT NULL,
    definition_version BIGINT NOT NULL,
    trigger_key VARCHAR(256) NOT NULL,
    delegated_task_id VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    run_payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_automation_run UNIQUE (tenant_id, run_id),
    CONSTRAINT uk_automation_trigger UNIQUE (tenant_id, automation_id, trigger_key),
    CONSTRAINT ck_automation_run_status CHECK (status IN ('PENDING','DISPATCHED','COMPLETED','FAILED','CANCELED'))
);

COMMENT ON TABLE ai_automation_run IS '自动化运行实例：按触发键幂等创建并关联委托任务';
COMMENT ON COLUMN ai_automation_run.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_automation_run.run_id IS '自动化运行稳定标识';
COMMENT ON COLUMN ai_automation_run.automation_id IS '自动化稳定标识';
COMMENT ON COLUMN ai_automation_run.definition_version IS '本次运行采用的自动化定义版本';
COMMENT ON COLUMN ai_automation_run.trigger_key IS '自动化触发幂等键';
COMMENT ON COLUMN ai_automation_run.delegated_task_id IS '本次运行创建的委托任务标识';
COMMENT ON COLUMN ai_automation_run.status IS '运行状态：PENDING、DISPATCHED、COMPLETED、FAILED 或 CANCELED';
COMMENT ON COLUMN ai_automation_run.run_payload IS '自动化运行上下文的完整 JSON 数据';
COMMENT ON COLUMN ai_automation_run.version IS '乐观锁版本号';
CREATE INDEX idx_automation_run_pending ON ai_automation_run (status, created_at) WHERE status = 'PENDING';
CREATE INDEX idx_automation_run_history ON ai_automation_run (tenant_id, automation_id, created_at DESC);

CREATE TABLE ai_automation_policy (
    tenant_id VARCHAR(128) PRIMARY KEY,
    global_stop BOOLEAN NOT NULL DEFAULT FALSE,
    policy_payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

COMMENT ON TABLE ai_automation_policy IS '租户自动化策略：保存全局停止开关与组织级自动化约束';
COMMENT ON COLUMN ai_automation_policy.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_automation_policy.global_stop IS '租户自动化全局停止开关';
COMMENT ON COLUMN ai_automation_policy.policy_payload IS '租户自动化策略的完整 JSON 数据';
COMMENT ON COLUMN ai_automation_policy.version IS '乐观锁版本号';

-- 最小 L4 Team 复用统一定义生命周期；JSON schema 在数据库层 fail-closed。
CREATE FUNCTION aaf_team_member_payload_valid(member_payload JSONB, expected_role TEXT)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
RETURNS NULL ON NULL INPUT
AS $$
    SELECT CASE
        WHEN jsonb_typeof(member_payload) IS DISTINCT FROM 'object' THEN FALSE
        WHEN member_payload - ARRAY[
                'memberKey', 'role', 'assistantId', 'assistantRevision',
                'roleKey', 'skillKey', 'allowedToolKeys'
            ] <> '{}'::JSONB THEN FALSE
        WHEN jsonb_typeof(member_payload -> 'memberKey') IS DISTINCT FROM 'string' THEN FALSE
        WHEN btrim(member_payload ->> 'memberKey') = '' THEN FALSE
        WHEN member_payload ->> 'role' IS DISTINCT FROM expected_role THEN FALSE
        WHEN jsonb_typeof(member_payload -> 'assistantId') IS DISTINCT FROM 'string' THEN FALSE
        WHEN btrim(member_payload ->> 'assistantId') = '' THEN FALSE
        WHEN jsonb_typeof(member_payload -> 'assistantRevision') IS DISTINCT FROM 'number' THEN FALSE
        WHEN member_payload ->> 'assistantRevision' !~ '^(0|[1-9][0-9]*)$' THEN FALSE
        WHEN jsonb_typeof(member_payload -> 'roleKey') IS DISTINCT FROM 'string' THEN FALSE
        WHEN btrim(member_payload ->> 'roleKey') = '' THEN FALSE
        WHEN jsonb_typeof(member_payload -> 'skillKey') IS DISTINCT FROM 'string' THEN FALSE
        WHEN btrim(member_payload ->> 'skillKey') = '' THEN FALSE
        WHEN jsonb_typeof(member_payload -> 'allowedToolKeys') IS DISTINCT FROM 'array' THEN FALSE
        WHEN EXISTS (
            SELECT 1
            FROM jsonb_array_elements(member_payload -> 'allowedToolKeys') tool(value)
            WHERE jsonb_typeof(tool.value) IS DISTINCT FROM 'string'
               OR btrim(tool.value #>> '{}') = ''
        ) THEN FALSE
        WHEN (
            SELECT count(*) <> count(DISTINCT tool.value #>> '{}')
            FROM jsonb_array_elements(member_payload -> 'allowedToolKeys') tool(value)
        ) THEN FALSE
        ELSE TRUE
    END;
$$;

CREATE FUNCTION aaf_team_definition_payload_valid(
    payload JSONB,
    expected_team_id TEXT,
    expected_version BIGINT
)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
RETURNS NULL ON NULL INPUT
AS $$
    WITH team AS (
        SELECT payload -> 'teamDefinition' AS value
    )
    SELECT CASE
        WHEN jsonb_typeof(value) IS DISTINCT FROM 'object' THEN FALSE
        WHEN value - ARRAY['teamId', 'version', 'strategy', 'leader', 'workers'] <> '{}'::JSONB THEN FALSE
        WHEN jsonb_typeof(value -> 'teamId') IS DISTINCT FROM 'string' THEN FALSE
        WHEN value ->> 'teamId' IS DISTINCT FROM expected_team_id THEN FALSE
        WHEN jsonb_typeof(value -> 'version') IS DISTINCT FROM 'number' THEN FALSE
        WHEN value ->> 'version' !~ '^[1-9][0-9]*$' THEN FALSE
        WHEN value ->> 'version' IS DISTINCT FROM expected_version::TEXT THEN FALSE
        WHEN value ->> 'strategy' IS DISTINCT FROM 'LEADER_COORDINATED' THEN FALSE
        WHEN aaf_team_member_payload_valid(value -> 'leader', 'LEADER') IS NOT TRUE THEN FALSE
        WHEN jsonb_typeof(value -> 'workers') IS DISTINCT FROM 'array' THEN FALSE
        WHEN jsonb_array_length(value -> 'workers') NOT BETWEEN 1 AND 8 THEN FALSE
        WHEN EXISTS (
            SELECT 1
            FROM jsonb_array_elements(value -> 'workers') worker(member)
            WHERE aaf_team_member_payload_valid(worker.member, 'WORKER') IS NOT TRUE
        ) THEN FALSE
        WHEN (
            SELECT count(*) <> count(DISTINCT worker.member ->> 'memberKey')
            FROM jsonb_array_elements(value -> 'workers') worker(member)
        ) THEN FALSE
        WHEN value #>> '{leader,memberKey}' IN (
            SELECT worker.member ->> 'memberKey'
            FROM jsonb_array_elements(value -> 'workers') worker(member)
        ) THEN FALSE
        ELSE TRUE
    END
    FROM team;
$$;

CREATE TABLE ai_definition_lifecycle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    definition_kind VARCHAR(32) NOT NULL,
    definition_id VARCHAR(128) NOT NULL,
    definition_version BIGINT NOT NULL,
    state VARCHAR(32) NOT NULL,
    lifecycle_payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_definition_lifecycle UNIQUE (tenant_id, definition_kind, definition_id, definition_version),
    CONSTRAINT ck_definition_kind CHECK (definition_kind IN ('ASSISTANT','SKILL','AUTOMATION','CONNECTOR','TEAM')),
    CONSTRAINT ck_definition_state CHECK (state IN ('DRAFT','PUBLISHED','DEPRECATED','DISABLED')),
    CONSTRAINT ck_definition_team_payload CHECK ((
        (
            definition_kind <> 'TEAM'
            AND (
                NOT (lifecycle_payload ? 'teamDefinition')
                OR lifecycle_payload -> 'teamDefinition' = 'null'::JSONB
            )
        )
        OR (
            definition_kind = 'TEAM'
            AND aaf_team_definition_payload_valid(
                lifecycle_payload,
                definition_id,
                definition_version
            )
        )
    ) IS TRUE
));

COMMENT ON FUNCTION aaf_team_member_payload_valid(JSONB, TEXT) IS '校验 Team leader 或 worker 的闭世界冻结成员 JSON 载荷';
COMMENT ON FUNCTION aaf_team_definition_payload_valid(JSONB, TEXT, BIGINT) IS '校验闭世界 TeamDefinition JSON 载荷与生命周期主键一致';
COMMENT ON TABLE ai_definition_lifecycle IS '统一定义生命周期：管理助理、技能、自动化、连接器和 Team 的发布状态';
COMMENT ON COLUMN ai_definition_lifecycle.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_definition_lifecycle.definition_kind IS '定义类型：ASSISTANT、SKILL、AUTOMATION、CONNECTOR 或 TEAM';
COMMENT ON COLUMN ai_definition_lifecycle.definition_id IS '定义稳定标识';
COMMENT ON COLUMN ai_definition_lifecycle.definition_version IS '定义版本号';
COMMENT ON COLUMN ai_definition_lifecycle.state IS '生命周期状态：DRAFT、PUBLISHED、DEPRECATED 或 DISABLED';
COMMENT ON COLUMN ai_definition_lifecycle.lifecycle_payload IS '完整生命周期 JSON；TEAM 类型内嵌已版本化 TeamDefinition';

CREATE INDEX idx_definition_team_state
    ON ai_definition_lifecycle (tenant_id, definition_id, definition_version, state)
    WHERE definition_kind = 'TEAM';
CREATE INDEX idx_definition_team_payload
    ON ai_definition_lifecycle
    USING GIN ((lifecycle_payload -> 'teamDefinition') jsonb_path_ops)
    WHERE definition_kind = 'TEAM';

CREATE TABLE ai_automation_audit (
    audit_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    automation_id VARCHAR(128) NOT NULL,
    action VARCHAR(64) NOT NULL,
    actor_id VARCHAR(128) NOT NULL,
    details JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE ai_automation_audit IS '自动化审计日志：记录自动化管理动作、操作者与发生时间';
COMMENT ON COLUMN ai_automation_audit.audit_id IS '审计记录稳定标识';
COMMENT ON COLUMN ai_automation_audit.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_automation_audit.automation_id IS '被操作的自动化标识';
COMMENT ON COLUMN ai_automation_audit.action IS '自动化管理动作';
COMMENT ON COLUMN ai_automation_audit.actor_id IS '执行管理动作的 Actor 标识';
COMMENT ON COLUMN ai_automation_audit.details IS '审计动作详情的 JSON 数据';
COMMENT ON COLUMN ai_automation_audit.occurred_at IS '审计动作发生时间';
CREATE INDEX idx_automation_audit_search ON ai_automation_audit (tenant_id, automation_id, occurred_at DESC);



-- ============================================================
-- LearningCandidate MVP：只记录可审查候选，不自动应用到任何运行时定义。
-- ============================================================

CREATE TABLE ai_learning_candidate (
    candidate_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    execution_id VARCHAR(128) NOT NULL,
    run_id VARCHAR(128) NOT NULL,
    session_id VARCHAR(128) NOT NULL,
    source_event_id VARCHAR(128) NOT NULL REFERENCES ai_task_event(event_id),
    source_event_offset BIGINT NOT NULL REFERENCES ai_task_event(event_offset),
    status VARCHAR(16) NOT NULL,
    schema_version INTEGER NOT NULL,
    candidate_payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_learning_candidate_source UNIQUE (tenant_id, source_event_id),
    CONSTRAINT ck_learning_candidate_status
        CHECK (status IN ('DRAFT', 'REVIEWED', 'PUBLISHED', 'REJECTED')),
    CONSTRAINT ck_learning_candidate_schema_version CHECK (schema_version > 0),
    CONSTRAINT ck_learning_candidate_version CHECK (version >= 0)
);

COMMENT ON TABLE ai_learning_candidate IS '学习候选：基于持久化执行事实显式创建，仅供人工审核与发布，不自动修改系统定义';
COMMENT ON COLUMN ai_learning_candidate.run_id IS '来源任务运行标识，仅用于安全追溯';
COMMENT ON COLUMN ai_learning_candidate.session_id IS '来源执行会话标识，仅用于安全追溯';
COMMENT ON COLUMN ai_learning_candidate.source_event_id IS '独立行为依据，必须引用 ai_task_event 持久化事实';
COMMENT ON COLUMN ai_learning_candidate.source_event_offset IS '来源事实的全局 cursor，用于校验与追溯';
COMMENT ON COLUMN ai_learning_candidate.status IS '候选治理状态：DRAFT、REVIEWED、PUBLISHED 或 REJECTED';
COMMENT ON COLUMN ai_learning_candidate.schema_version IS '候选载荷契约版本';
COMMENT ON COLUMN ai_learning_candidate.candidate_payload IS '仅含安全摘要和稳定证据引用的 LearningCandidate JSON';
COMMENT ON COLUMN ai_learning_candidate.version IS '乐观锁版本号';
CREATE INDEX idx_learning_candidate_review
    ON ai_learning_candidate (tenant_id, status, updated_at DESC);
CREATE INDEX idx_learning_candidate_task
    ON ai_learning_candidate (tenant_id, task_id, created_at DESC);

-- ============================================================
-- AAF-107：EXECUTOR 先规划再执行（ADR-006）。按当前阶段约束直接追加进本文件，不新分配 vN、不写回滚脚本。
-- 两表关系：ai_executor_plan 是计划头（含状态机、审批留痕），ai_executor_plan_step 是步骤明细；
-- 审批不新建表，复用上面的 ai_hitl_approval + ai_hitl_recovery。
-- ============================================================

CREATE TABLE ai_executor_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    board_id VARCHAR(128) NOT NULL,
    executor_agent_id VARCHAR(128) NOT NULL,
    revision INTEGER NOT NULL,
    status VARCHAR(24) NOT NULL,
    goal VARCHAR(4000) NOT NULL,
    policy_snapshot JSONB NOT NULL,
    risks JSONB NOT NULL DEFAULT '[]'::JSONB,
    verification JSONB NOT NULL DEFAULT '{}'::JSONB,
    submitted_by_type VARCHAR(16),
    submitted_by_id VARCHAR(128),
    reviewed_by_type VARCHAR(16),
    reviewed_by_id VARCHAR(128),
    review_comment VARCHAR(2000),
    approved_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    lock_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_executor_plan_id UNIQUE (plan_id),
    CONSTRAINT uk_executor_plan_revision UNIQUE (tenant_id, task_id, board_id, revision),
    CONSTRAINT ck_executor_plan_revision CHECK (revision >= 1),
    CONSTRAINT ck_executor_plan_status CHECK (status IN (
        'DRAFT', 'PLANNING', 'SUBMITTED', 'REVIEW_REQUIRED',
        'APPROVED', 'EXECUTING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REJECTED')),
    CONSTRAINT ck_executor_plan_submitted_actor CHECK (
        (submitted_by_type IS NULL) = (submitted_by_id IS NULL)),
    CONSTRAINT ck_executor_plan_reviewed_actor CHECK (
        (reviewed_by_type IS NULL) = (reviewed_by_id IS NULL))
);

COMMENT ON TABLE ai_executor_plan IS 'EXECUTOR 局部执行计划头：ADR-006 状态机 + 审批留痕；revision 一旦 SUBMITTED 正文不可变';
COMMENT ON COLUMN ai_executor_plan.plan_id IS '计划稳定标识，全局唯一';
COMMENT ON COLUMN ai_executor_plan.tenant_id IS '租户标识，对应系统组织 ID 的字符串投影';
COMMENT ON COLUMN ai_executor_plan.task_id IS '所属委托任务标识';
COMMENT ON COLUMN ai_executor_plan.board_id IS '所属 TaskBoard 内的节点标识（对应 TaskBoard.SubTask.subTaskId）';
COMMENT ON COLUMN ai_executor_plan.executor_agent_id IS '产出并执行本计划的 Agent 定义标识';
COMMENT ON COLUMN ai_executor_plan.revision IS '同一 task_id 下的修订号，从 1 开始递增，同一 revision 内容不可变';
COMMENT ON COLUMN ai_executor_plan.status IS 'ADR-006 状态机当前状态';
COMMENT ON COLUMN ai_executor_plan.goal IS '本计划要达成的目标，来自 executor 自己的 planning execution 输出';
COMMENT ON COLUMN ai_executor_plan.policy_snapshot IS '规划时冻结的策略快照（含 requiresPlan 判定依据），供审计比对';
COMMENT ON COLUMN ai_executor_plan.risks IS '模型自评风险列表；仅供展示与审计，不作为审批门控输入（ADR-006 议题四）';
COMMENT ON COLUMN ai_executor_plan.verification IS '计划整体的验证方式描述';
COMMENT ON COLUMN ai_executor_plan.submitted_by_type IS '提交者 Actor 类型：HUMAN 或 AI（对应产出本计划的 executor）';
COMMENT ON COLUMN ai_executor_plan.submitted_by_id IS '提交者 Actor 标识';
COMMENT ON COLUMN ai_executor_plan.reviewed_by_type IS '审批者 Actor 类型：HUMAN 或 SYSTEM（白名单自动批准）';
COMMENT ON COLUMN ai_executor_plan.reviewed_by_id IS '审批者 Actor 标识；白名单自动批准时为规则标识';
COMMENT ON COLUMN ai_executor_plan.review_comment IS '审批意见，人工拒绝时应说明原因';
COMMENT ON COLUMN ai_executor_plan.approved_at IS '进入 APPROVED 的时间';
COMMENT ON COLUMN ai_executor_plan.started_at IS '进入 EXECUTING 的时间';
COMMENT ON COLUMN ai_executor_plan.finished_at IS '进入终态（COMPLETED/FAILED/CANCELLED）的时间';
COMMENT ON COLUMN ai_executor_plan.lock_version IS '乐观锁版本号，所有状态转换必须 CAS';
CREATE INDEX idx_executor_plan_active
    ON ai_executor_plan (tenant_id, task_id, board_id, revision DESC)
    WHERE status NOT IN ('CANCELLED', 'REJECTED');
CREATE INDEX idx_executor_plan_review_queue
    ON ai_executor_plan (tenant_id, status, created_at)
    WHERE status = 'REVIEW_REQUIRED';

CREATE TABLE ai_executor_plan_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id VARCHAR(128) NOT NULL REFERENCES ai_executor_plan(plan_id),
    step_key VARCHAR(128) NOT NULL,
    ordinal INTEGER NOT NULL,
    title VARCHAR(256) NOT NULL,
    instruction VARCHAR(4000) NOT NULL,
    dependencies JSONB NOT NULL DEFAULT '[]'::JSONB,
    required_tools JSONB NOT NULL DEFAULT '[]'::JSONB,
    completion_criteria JSONB NOT NULL DEFAULT '[]'::JSONB,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    result_ref VARCHAR(256),
    failure_code VARCHAR(64),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    lock_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_executor_plan_step_key UNIQUE (plan_id, step_key),
    CONSTRAINT uk_executor_plan_step_ordinal UNIQUE (plan_id, ordinal),
    CONSTRAINT ck_executor_plan_step_ordinal CHECK (ordinal >= 1),
    CONSTRAINT ck_executor_plan_step_status CHECK (
        status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED'))
);

COMMENT ON TABLE ai_executor_plan_step IS 'ExecutorPlan 步骤明细：同一 plan 最多一个 RUNNING，依赖未完成不得启动';
COMMENT ON COLUMN ai_executor_plan_step.plan_id IS '所属计划标识';
COMMENT ON COLUMN ai_executor_plan_step.step_key IS '计划内步骤键，随 plan 生成';
COMMENT ON COLUMN ai_executor_plan_step.ordinal IS '展示顺序号，实际调度依据 dependencies';
COMMENT ON COLUMN ai_executor_plan_step.title IS '步骤标题';
COMMENT ON COLUMN ai_executor_plan_step.instruction IS '步骤执行指引';
COMMENT ON COLUMN ai_executor_plan_step.dependencies IS '依赖的其它 step_key 字符串数组，只能引用同 plan 内已声明步骤';
COMMENT ON COLUMN ai_executor_plan_step.required_tools IS '本步骤需要调用的工具名数组，必须是冻结工具白名单子集';
COMMENT ON COLUMN ai_executor_plan_step.completion_criteria IS '人类可读完成判据，供审计与人工审阅，不参与自动化判定';
COMMENT ON COLUMN ai_executor_plan_step.status IS '步骤状态：PENDING、RUNNING、COMPLETED、FAILED 或 CANCELLED';
COMMENT ON COLUMN ai_executor_plan_step.result_ref IS '步骤完成后的结果引用（如证据 ID），不直接持有结果正文';
COMMENT ON COLUMN ai_executor_plan_step.failure_code IS '步骤失败时的稳定失败码';
COMMENT ON COLUMN ai_executor_plan_step.lock_version IS '乐观锁版本号';
CREATE UNIQUE INDEX uk_executor_plan_step_running
    ON ai_executor_plan_step (plan_id)
    WHERE status = 'RUNNING';
CREATE INDEX idx_executor_plan_step_plan
    ON ai_executor_plan_step (plan_id, ordinal);
