-- 页面定义（PageEngine 配置驱动的营销页/落地页）
CREATE TABLE sys_page_def (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    slug            VARCHAR(200) NOT NULL,
    title           VARCHAR(200) NOT NULL,
    config          JSONB NOT NULL DEFAULT '{}',
    status          VARCHAR(20) NOT NULL DEFAULT 'draft',
    published_at    TIMESTAMP,
    create_by       BIGINT,
    create_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    remark          VARCHAR(500)
);

COMMENT ON TABLE sys_page_def IS '页面定义（PageEngine）';
COMMENT ON COLUMN sys_page_def.slug IS '页面路径标识（唯一）';
COMMENT ON COLUMN sys_page_def.title IS '页面标题';
COMMENT ON COLUMN sys_page_def.config IS '页面配置（JSONB，含 sections/theme/metadata）';
COMMENT ON COLUMN sys_page_def.status IS '状态：draft/published';
COMMENT ON COLUMN sys_page_def.published_at IS '最近发布时间';

CREATE UNIQUE INDEX uk_sys_page_def_slug ON sys_page_def(slug) WHERE deleted = FALSE;
