-- AAF-038 用户认证扩展
-- 扩展 sys_user 表增加认证相关字段，创建 OAuth 账号绑定表

-- ==================== 扩展 sys_user ====================

ALTER TABLE sys_user ADD COLUMN email VARCHAR(200);
ALTER TABLE sys_user ADD COLUMN phone VARCHAR(20);
ALTER TABLE sys_user ADD COLUMN avatar VARCHAR(500);
ALTER TABLE sys_user ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE sys_user ADD COLUMN last_login_time TIMESTAMP(6);
ALTER TABLE sys_user ADD COLUMN last_login_ip VARCHAR(50);
ALTER TABLE sys_user ADD COLUMN login_fail_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sys_user ADD COLUMN lock_time TIMESTAMP(6);

CREATE UNIQUE INDEX uk_sys_user_email ON sys_user (email) WHERE email IS NOT NULL;

COMMENT ON COLUMN sys_user.email IS '邮箱';
COMMENT ON COLUMN sys_user.phone IS '手机号';
COMMENT ON COLUMN sys_user.avatar IS '头像 URL';
COMMENT ON COLUMN sys_user.email_verified IS '邮箱是否验证';
COMMENT ON COLUMN sys_user.last_login_time IS '最后登录时间';
COMMENT ON COLUMN sys_user.last_login_ip IS '最后登录 IP';
COMMENT ON COLUMN sys_user.login_fail_count IS '登录失败次数';
COMMENT ON COLUMN sys_user.lock_time IS '锁定到期时间';

-- ==================== OAuth 账号绑定表 ====================

CREATE TABLE sys_user_oauth (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    provider          VARCHAR(50)  NOT NULL,
    provider_user_id  VARCHAR(200) NOT NULL,
    provider_username VARCHAR(200),
    access_token      VARCHAR(500),
    refresh_token     VARCHAR(500),
    token_expire_time TIMESTAMP(6),
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    create_by         BIGINT,
    create_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255),
    CONSTRAINT fk_user_oauth_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT uk_provider_user UNIQUE (provider, provider_user_id)
);

COMMENT ON TABLE sys_user_oauth IS 'OAuth 第三方账号绑定';
COMMENT ON COLUMN sys_user_oauth.user_id IS '关联用户 ID';
COMMENT ON COLUMN sys_user_oauth.provider IS 'OAuth 提供商：wechat/wecom/dingtalk';
COMMENT ON COLUMN sys_user_oauth.provider_user_id IS '第三方用户 ID';
COMMENT ON COLUMN sys_user_oauth.provider_username IS '第三方用户名';
COMMENT ON COLUMN sys_user_oauth.access_token IS '访问令牌';
COMMENT ON COLUMN sys_user_oauth.refresh_token IS '刷新令牌';
COMMENT ON COLUMN sys_user_oauth.token_expire_time IS '令牌过期时间';

CREATE INDEX idx_user_oauth_user_id ON sys_user_oauth (user_id);
