-- ============================================================
-- AAF v0.1.0 全量 Schema（按子域分段）
-- 公共字段约定：每张表均含 version / org_id / workspace_id
-- ============================================================

-- ============================================================
-- user 子域
-- ============================================================

CREATE TABLE sys_user (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    username         VARCHAR(50)  NOT NULL UNIQUE,
    password         VARCHAR(200) NOT NULL,
    nickname         VARCHAR(100),
    email            VARCHAR(200),
    phone            VARCHAR(20),
    avatar           VARCHAR(500),
    status           INTEGER      NOT NULL DEFAULT 0,
    email_verified   BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_time  TIMESTAMP(6),
    last_login_ip    VARCHAR(50),
    login_fail_count INTEGER      NOT NULL DEFAULT 0,
    lock_time        TIMESTAMP(6),
    archived_at      TIMESTAMP(6),
    create_by        BIGINT,
    create_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by        BIGINT,
    update_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    remark           VARCHAR(255),
    source_app       VARCHAR(32),
    source_channel   VARCHAR(50),
    register_ip      VARCHAR(50),
    register_location VARCHAR(100)
);

COMMENT ON TABLE sys_user IS '系统用户';
COMMENT ON COLUMN sys_user.status IS '0 正常 / 1 禁用';
COMMENT ON COLUMN sys_user.email_verified IS '邮箱是否验证';
COMMENT ON COLUMN sys_user.source_app IS '注册入口: web / uniapp / api';
COMMENT ON COLUMN sys_user.source_channel IS '注册渠道: local / wechat / wechat_mp / dingtalk / github 等';
COMMENT ON COLUMN sys_user.register_ip IS '注册时客户端 IP';
COMMENT ON COLUMN sys_user.register_location IS '注册地址（IP 解析结果，如"广东 深圳市 南山区"）';

CREATE UNIQUE INDEX uk_sys_user_email ON sys_user (email) WHERE email IS NOT NULL;

-- ============================================================
-- auth 子域
-- ============================================================

CREATE TABLE sys_user_oauth (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    user_id           BIGINT       NOT NULL REFERENCES sys_user(id),
    provider          VARCHAR(50)  NOT NULL,
    provider_user_id  VARCHAR(200) NOT NULL,
    provider_username VARCHAR(200),
    access_token      VARCHAR(500),
    refresh_token     VARCHAR(500),
    token_expire_time TIMESTAMP(6),
    create_by         BIGINT,
    create_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255),
    CONSTRAINT uk_provider_user UNIQUE (provider, provider_user_id)
);

COMMENT ON TABLE sys_user_oauth IS 'OAuth 第三方账号绑定';

CREATE INDEX idx_user_oauth_user_id ON sys_user_oauth (user_id);

-- ============================================================
-- role 子域
-- ============================================================

CREATE TABLE sys_role (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    code         VARCHAR(50)  NOT NULL UNIQUE,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(500),
    status       INTEGER      NOT NULL DEFAULT 0,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_role IS '系统角色';

CREATE TABLE sys_permission (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    action       VARCHAR(20)  NOT NULL,
    field_access JSONB,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_permission IS '实体权限';
COMMENT ON COLUMN sys_permission.action IS 'read/create/update/delete';
COMMENT ON COLUMN sys_permission.field_access IS '字段级权限 JSONB';

CREATE TABLE sys_role_permission (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER      NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    role_id       BIGINT       NOT NULL,
    permission_id BIGINT       NOT NULL,
    archived_at   TIMESTAMP(6),
    create_by     BIGINT,
    create_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by     BIGINT,
    update_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    remark        VARCHAR(255),
    UNIQUE (role_id, permission_id)
);

COMMENT ON TABLE sys_role_permission IS '角色-权限关联';
COMMENT ON COLUMN sys_role_permission.permission_id IS '关联 sys_permission_code.id';

CREATE TABLE sys_user_role (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL,
    role_id      BIGINT       NOT NULL,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255),
    UNIQUE (user_id, role_id)
);

COMMENT ON TABLE sys_user_role IS '用户-角色关联';

CREATE TABLE sys_data_access_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    roles        JSONB        NOT NULL DEFAULT '[]',
    condition    JSONB        NOT NULL DEFAULT '{}',
    effect       VARCHAR(10)  NOT NULL DEFAULT 'allow',
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_data_access_rule IS '行级数据权限规则';

CREATE INDEX idx_data_access_rule_entity ON sys_data_access_rule (entity_slug) WHERE deleted = FALSE;


-- ============================================================
-- org 子域
-- ============================================================

CREATE TABLE sys_organization (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    slug         VARCHAR(100) NOT NULL UNIQUE,
    type         VARCHAR(20)  NOT NULL DEFAULT 'team',
    owner_id     BIGINT       NOT NULL,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_organization IS '组织/租户';
COMMENT ON COLUMN sys_organization.type IS 'personal / team';

CREATE TABLE sys_org_member (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT       NOT NULL,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL,
    role         VARCHAR(20)  NOT NULL DEFAULT 'member',
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_org_member IS '组织成员';
COMMENT ON COLUMN sys_org_member.role IS 'owner / admin / member';

CREATE UNIQUE INDEX uk_org_member_org_user ON sys_org_member (org_id, user_id) WHERE deleted = FALSE;

-- ============================================================
-- notify 子域
-- ============================================================

CREATE TABLE sys_notification (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL,
    type         VARCHAR(50)  NOT NULL,
    title        VARCHAR(200) NOT NULL,
    body         TEXT,
    entity_type  VARCHAR(100),
    entity_id    BIGINT,
    related_url  VARCHAR(500),
    is_read      BOOLEAN      NOT NULL DEFAULT FALSE,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_notification IS '系统通知';

CREATE INDEX idx_notification_user ON sys_notification (user_id);
CREATE INDEX idx_notification_user_read ON sys_notification (user_id, is_read);

CREATE TABLE sys_notification_preference (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL UNIQUE,
    preferences  JSONB        NOT NULL DEFAULT '{}',
    quiet_start  TIME,
    quiet_end    TIME,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_notification_preference IS '通知偏好设置';

CREATE TABLE sys_subscription (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    fields       JSONB,
    channels     JSONB,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_subscription IS '字段变更订阅';

CREATE UNIQUE INDEX idx_subscription_unique ON sys_subscription (user_id, entity_type, entity_id) WHERE deleted = FALSE;

CREATE TABLE sys_message_template (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    code         VARCHAR(100) NOT NULL UNIQUE,
    name         VARCHAR(200) NOT NULL,
    channel      VARCHAR(20)  NOT NULL,
    subject      VARCHAR(500),
    content      TEXT         NOT NULL,
    variables    JSONB,
    status       SMALLINT     NOT NULL DEFAULT 1,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_message_template IS '消息模板';
COMMENT ON COLUMN sys_message_template.channel IS 'SMS/EMAIL/INTERNAL';

-- ============================================================
-- log 子域
-- ============================================================

CREATE TABLE sys_operation_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    username        VARCHAR(50),
    module          VARCHAR(50)  NOT NULL,
    type            VARCHAR(20)  NOT NULL,
    description     VARCHAR(500),
    biz_no          VARCHAR(100),
    request_method  VARCHAR(10),
    request_url     VARCHAR(500),
    request_params  TEXT,
    response_result TEXT,
    ip              VARCHAR(50),
    user_agent      VARCHAR(500),
    duration_ms     BIGINT,
    success         BOOLEAN      NOT NULL DEFAULT TRUE,
    error_message   TEXT,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_operation_log IS '操作日志（不可变）';

CREATE INDEX idx_operation_log_user   ON sys_operation_log(user_id);
CREATE INDEX idx_operation_log_module ON sys_operation_log(module);
CREATE INDEX idx_operation_log_time   ON sys_operation_log(create_time);

CREATE TABLE sys_audit_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id        BIGINT,
    workspace_id  BIGINT,
    entity_type   VARCHAR(50)  NOT NULL,
    entity_id     BIGINT       NOT NULL,
    action        VARCHAR(50)  NOT NULL,
    user_id       BIGINT,
    changes       JSONB,
    ip            VARCHAR(45),
    hash          VARCHAR(64),
    previous_hash VARCHAR(64),
    created_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_audit_log IS '审计日志（不可变，链式哈希）';

CREATE RULE audit_log_no_update AS ON UPDATE TO sys_audit_log DO INSTEAD NOTHING;
CREATE RULE audit_log_no_delete AS ON DELETE TO sys_audit_log DO INSTEAD NOTHING;

CREATE INDEX idx_audit_log_entity ON sys_audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_log_user   ON sys_audit_log (user_id);
CREATE INDEX idx_audit_log_time   ON sys_audit_log (created_at);

CREATE TABLE sys_activity_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    action       VARCHAR(50)  NOT NULL,
    changes      JSONB,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_activity_log IS '实体活动日志';

CREATE INDEX idx_activity_log_entity ON sys_activity_log (entity_type, entity_id, create_time DESC);

CREATE TABLE sys_comment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    content      TEXT         NOT NULL,
    mentions     JSONB,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_comment IS '实体评论';

CREATE INDEX idx_comment_entity ON sys_comment (entity_type, entity_id, create_time DESC);

CREATE TABLE sys_record_version (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    ver_number   INTEGER      NOT NULL,
    data         JSONB        NOT NULL,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_record_version IS '实体版本快照';

CREATE INDEX idx_record_version_entity ON sys_record_version (entity_type, entity_id, ver_number DESC);


-- ============================================================
-- chat 子域 → 已迁移至 v8__conversation_schema.sql
-- conversation / conversation_participant / conversation_message
-- ============================================================

-- ============================================================
-- entity 子域（元数据引擎）
-- ============================================================

CREATE TABLE sys_entity_def (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    slug         VARCHAR(100) NOT NULL,
    config       JSONB        NOT NULL DEFAULT '{}',
    builtin      BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_entity_def IS '实体定义';

CREATE UNIQUE INDEX uk_sys_entity_def_slug ON sys_entity_def(slug) WHERE deleted = FALSE;

CREATE TABLE sys_record_template (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    name         VARCHAR(200) NOT NULL,
    field_values JSONB        NOT NULL DEFAULT '{}',
    is_shared    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_record_template IS '记录模板';

CREATE INDEX idx_sys_record_template_slug ON sys_record_template(entity_slug) WHERE deleted = FALSE;

-- ============================================================
-- dashboard 子域
-- ============================================================

CREATE TABLE sys_dashboard (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(500),
    is_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    owner_id     BIGINT       NOT NULL,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_dashboard IS '仪表盘';

CREATE INDEX idx_sys_dashboard_owner ON sys_dashboard(owner_id) WHERE deleted = FALSE;

CREATE TABLE sys_dashboard_widget (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    dashboard_id BIGINT       NOT NULL REFERENCES sys_dashboard(id),
    type         VARCHAR(20)  NOT NULL,
    title        VARCHAR(100) NOT NULL,
    position     JSONB        NOT NULL DEFAULT '{}',
    config       JSONB        NOT NULL DEFAULT '{}',
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_dashboard_widget IS '仪表盘组件';

CREATE INDEX idx_sys_dashboard_widget_dashboard ON sys_dashboard_widget(dashboard_id) WHERE deleted = FALSE;

CREATE TABLE sys_page_def (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    slug         VARCHAR(200) NOT NULL,
    title        VARCHAR(200) NOT NULL,
    config       JSONB        NOT NULL DEFAULT '{}',
    status       VARCHAR(20)  NOT NULL DEFAULT 'draft',
    published_at TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_page_def IS '页面定义（PageEngine）';

CREATE UNIQUE INDEX uk_sys_page_def_slug ON sys_page_def(slug) WHERE deleted = FALSE;


-- ============================================================
-- workflow 子域
-- ============================================================

CREATE TABLE sys_delegation (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    delegator_id BIGINT       NOT NULL,
    delegate_id  BIGINT       NOT NULL,
    start_date   TIMESTAMP(6) NOT NULL,
    end_date     TIMESTAMP(6) NOT NULL,
    process_keys JSONB,
    status       VARCHAR(20)  NOT NULL DEFAULT 'active',
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_delegation IS '审批委托';

CREATE INDEX idx_delegation_delegator ON sys_delegation (delegator_id, status) WHERE deleted = FALSE;
CREATE INDEX idx_delegation_delegate ON sys_delegation (delegate_id, status) WHERE deleted = FALSE;

CREATE TABLE sys_automation_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    entity_slug  VARCHAR(100) NOT NULL,
    trigger_type VARCHAR(50)  NOT NULL,
    conditions   JSONB,
    actions      JSONB        NOT NULL,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_automation_rule IS '自动化规则';

CREATE INDEX idx_automation_rule_entity ON sys_automation_rule (entity_slug, trigger_type) WHERE deleted = FALSE AND enabled = TRUE;

CREATE TABLE sys_automation_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    rule_id      BIGINT       NOT NULL,
    trigger_type VARCHAR(50)  NOT NULL,
    entity_type  VARCHAR(100),
    entity_id    BIGINT,
    status       VARCHAR(20)  NOT NULL,
    error_message TEXT,
    executed_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_automation_log IS '自动化执行日志';

CREATE INDEX idx_automation_log_rule ON sys_automation_log (rule_id) WHERE deleted = FALSE;

CREATE TABLE sys_archive_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    condition    JSONB        NOT NULL DEFAULT '{}',
    after_days   INTEGER      NOT NULL DEFAULT 90,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_archive_rule IS '数据归档规则';

CREATE INDEX idx_archive_rule_entity ON sys_archive_rule (entity_slug) WHERE deleted = FALSE;

-- ============================================================
-- task 子域
-- ============================================================

CREATE TABLE sys_todo (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    assignee_id  BIGINT       NOT NULL,
    title        VARCHAR(200) NOT NULL,
    source_type  VARCHAR(50),
    source_entity VARCHAR(100),
    source_id    BIGINT,
    category     VARCHAR(20)  NOT NULL DEFAULT 'todo',
    status       VARCHAR(20)  NOT NULL DEFAULT 'pending',
    due_date     TIMESTAMP(6),
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_todo IS '待办事项';

CREATE INDEX idx_todo_assignee ON sys_todo (assignee_id, status);

CREATE TABLE sys_scheduled_task (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    type         VARCHAR(50)  NOT NULL,
    cron         VARCHAR(50),
    trigger_type VARCHAR(20)  NOT NULL DEFAULT 'CRON',
    interval_ms  BIGINT,
    status       VARCHAR(20)  NOT NULL DEFAULT 'active',
    last_run     TIMESTAMP(6),
    next_run     TIMESTAMP(6),
    fail_count   INTEGER      NOT NULL DEFAULT 0,
    action_type  VARCHAR(30),
    action_config TEXT,
    misfire_policy VARCHAR(20) NOT NULL DEFAULT 'IGNORE',
    calendar_code  VARCHAR(50),
    timeout_seconds INTEGER      NOT NULL DEFAULT 0,
    owner_id     BIGINT,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_scheduled_task IS '计划任务注册表';
COMMENT ON COLUMN sys_scheduled_task.owner_id IS '归属用户 ID：NULL=系统任务，非 NULL=用户任务（执行时注入用户上下文，积分等切面可正确归账）';

CREATE TABLE sys_task_execution (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER      NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    task_name     VARCHAR(100) NOT NULL,
    task_type     VARCHAR(50)  NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'running',
    start_time    TIMESTAMP(6) NOT NULL,
    end_time      TIMESTAMP(6),
    duration_ms   BIGINT,
    error_message TEXT,
    retry_count   INTEGER      DEFAULT 0,
    priority      SMALLINT     DEFAULT 5,
    trigger_type  VARCHAR(20),
    biz_id        VARCHAR(100),
    context       TEXT,
    create_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_task_execution IS '任务执行记录';
COMMENT ON COLUMN sys_task_execution.biz_id IS '关联业务 ID（如 aigc_task.id、pay_order.order_no），方便直接定位原始记录';
COMMENT ON COLUMN sys_task_execution.context IS '执行参数快照 JSON（触发时的关键上下文，如 userId/prompt/processKey），便于排查时不查原表';

CREATE INDEX idx_task_execution_name ON sys_task_execution(task_name);
CREATE INDEX idx_task_execution_status ON sys_task_execution(status);

-- ==================== 排除日历 ====================
CREATE TABLE sys_holiday_calendar
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        INTEGER      NOT NULL DEFAULT 0,
    calendar_code  VARCHAR(50)  NOT NULL,
    exclude_date   DATE         NOT NULL,
    day_type       VARCHAR(20)  NOT NULL DEFAULT 'HOLIDAY',
    org_id         BIGINT,
    workspace_id   BIGINT,
    owner_id       BIGINT,
    create_by      BIGINT,
    create_by_type VARCHAR(16),
    update_by      BIGINT,
    update_by_type VARCHAR(16),
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    delete_time    TIMESTAMP,
    create_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark         VARCHAR(255)
);

COMMENT ON TABLE sys_holiday_calendar IS '排除日历（节假日/停服日/自定义排除日期）';
COMMENT ON COLUMN sys_holiday_calendar.calendar_code IS '日历编码，如 CN_HOLIDAY / COMPANY_OFFDAY / PROJECT_FREEZE';
COMMENT ON COLUMN sys_holiday_calendar.exclude_date IS '排除日期';
COMMENT ON COLUMN sys_holiday_calendar.day_type IS 'HOLIDAY=排除跳过 / WORKDAY=调休补班不跳过（优先级更高）';

CREATE INDEX idx_holiday_calendar_code_date ON sys_holiday_calendar (calendar_code, exclude_date) WHERE deleted = FALSE;


-- ============================================================
-- config 子域
-- ============================================================

CREATE TABLE sys_config (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER      NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    category      VARCHAR(64)  NOT NULL,
    config_key    VARCHAR(128) NOT NULL UNIQUE,
    value         TEXT,
    default_value TEXT,
    value_type    VARCHAR(16)  NOT NULL DEFAULT 'string',
    name          VARCHAR(200) NOT NULL,
    description   VARCHAR(500),
    visible       BOOLEAN      NOT NULL DEFAULT TRUE,
    editable      BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by     BIGINT,
    create_by_type VARCHAR(16),
    create_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by     BIGINT,
    update_by_type VARCHAR(16),
    update_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id      BIGINT,
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    remark        VARCHAR(255)
);

COMMENT ON TABLE sys_config IS '系统配置表';
COMMENT ON COLUMN sys_config.category IS '分类（security/user/ai/sms/storage）';
COMMENT ON COLUMN sys_config.config_key IS '配置键，全局唯一（如 user.default_password）';
COMMENT ON COLUMN sys_config.value_type IS '值类型（string/integer/boolean/json）';
COMMENT ON COLUMN sys_config.visible IS '是否前端可见，false=敏感配置不返回 value';
COMMENT ON COLUMN sys_config.editable IS '是否可编辑，false=只读系统参数';
COMMENT ON COLUMN sys_config.default_value IS '默认值，value 为空时使用';

CREATE INDEX idx_sys_config_category ON sys_config (category) WHERE deleted = FALSE;

-- ============================================================
-- sms 子域
-- ============================================================

CREATE TABLE sys_sms_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    code            VARCHAR(64)  NOT NULL UNIQUE,
    name            VARCHAR(100) NOT NULL,
    sign_name       VARCHAR(64),
    api_template_id VARCHAR(64)  NOT NULL,
    params          VARCHAR(255),
    provider        VARCHAR(20),
    status          SMALLINT     NOT NULL DEFAULT 1,
    create_by       BIGINT,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE sys_sms_template IS '短信模板配置';
COMMENT ON COLUMN sys_sms_template.code IS '业务场景编码，调用方使用';
COMMENT ON COLUMN sys_sms_template.sign_name IS '签名，为空则使用系统默认签名';
COMMENT ON COLUMN sys_sms_template.api_template_id IS '厂商模板 ID（阿里云/腾讯云后台审核通过的模板 ID）';
COMMENT ON COLUMN sys_sms_template.params IS '参数名列表（JSON 数组，如 ["code","expireMinutes"]）';
COMMENT ON COLUMN sys_sms_template.provider IS '指定厂商（null=使用系统默认）';

-- ============================================================
-- sequence 子域
-- ============================================================

CREATE TABLE sys_sequence (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    name             VARCHAR(100) NOT NULL,
    code             VARCHAR(50)  NOT NULL UNIQUE,
    prefix           VARCHAR(100),
    suffix           VARCHAR(100),
    number_next      BIGINT       NOT NULL DEFAULT 1,
    number_increment INTEGER      NOT NULL DEFAULT 1,
    padding          INTEGER      NOT NULL DEFAULT 4,
    use_date_range   BOOLEAN      NOT NULL DEFAULT FALSE,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by        BIGINT,
    create_by_type   VARCHAR(16),
    create_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by        BIGINT,
    update_by_type   VARCHAR(16),
    update_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id         BIGINT,
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    remark           VARCHAR(255)
);

COMMENT ON TABLE sys_sequence IS '序列号配置表';
COMMENT ON COLUMN sys_sequence.code IS '序列编码，业务唯一标识';
COMMENT ON COLUMN sys_sequence.prefix IS '前缀模板，支持 %(year)s %(month)s %(day)s 等变量';
COMMENT ON COLUMN sys_sequence.suffix IS '后缀模板';
COMMENT ON COLUMN sys_sequence.number_next IS '下一个值（仅记录，实际由 PG SEQUENCE 驱动）';
COMMENT ON COLUMN sys_sequence.padding IS '数字补零位数，默认 4 位';
COMMENT ON COLUMN sys_sequence.use_date_range IS '是否按日期分段（每月独立计数）';

CREATE TABLE sys_sequence_date_range (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sequence_id BIGINT NOT NULL REFERENCES sys_sequence(id),
    date_from   DATE   NOT NULL,
    date_to     DATE   NOT NULL,
    number_next BIGINT NOT NULL DEFAULT 1
);

COMMENT ON TABLE sys_sequence_date_range IS '序列号日期分段表，按月自动创建';

CREATE INDEX idx_sys_sequence_date_range ON sys_sequence_date_range (sequence_id, date_from, date_to);

-- document 子域已移至 v3__doc_schema.sql
-- autodev 子域已移至 v4__autodev_schema.sql

-- ============================================================
-- knowledge 子域
-- ============================================================

CREATE EXTENSION IF NOT EXISTS vector;

-- knowledge_base / knowledge_document / knowledge_chunk / knowledge_embedding
-- memory_atom / memory_relation
-- 已迁移至 v2__ai_schema.sql，表名加 ai_ 前缀

-- ============================================================
-- memory 子域
-- ============================================================

-- （已迁移至 v2__ai_schema.sql）

-- ============================================================
-- dict 子域
-- ============================================================

CREATE TABLE sys_dict_type (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    type         VARCHAR(100) NOT NULL,
    status       INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_dict_type IS '字典类型';
COMMENT ON COLUMN sys_dict_type.name IS '字典名称';
COMMENT ON COLUMN sys_dict_type.type IS '字典类型编码';
COMMENT ON COLUMN sys_dict_type.status IS '0 正常 / 1 禁用';

CREATE UNIQUE INDEX uk_sys_dict_type_type ON sys_dict_type (type) WHERE deleted = FALSE;

CREATE TABLE sys_dict_data (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    dict_type    VARCHAR(100) NOT NULL,
    label        VARCHAR(100) NOT NULL,
    value        VARCHAR(100) NOT NULL,
    sort         INTEGER      NOT NULL DEFAULT 0,
    status       INTEGER      NOT NULL DEFAULT 0,
    color_type   VARCHAR(50),
    css_class    VARCHAR(100),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_dict_data IS '字典数据';
COMMENT ON COLUMN sys_dict_data.dict_type IS '字典类型编码（关联 sys_dict_type.type）';
COMMENT ON COLUMN sys_dict_data.label IS '字典标签';
COMMENT ON COLUMN sys_dict_data.value IS '字典键值';
COMMENT ON COLUMN sys_dict_data.sort IS '显示排序';
COMMENT ON COLUMN sys_dict_data.status IS '0 正常 / 1 禁用';
COMMENT ON COLUMN sys_dict_data.color_type IS '标签颜色（default/primary/success/info/warning/danger）';
COMMENT ON COLUMN sys_dict_data.css_class IS '自定义 CSS 样式';

CREATE INDEX idx_sys_dict_data_dict_type ON sys_dict_data (dict_type);


-- ============================================================
-- 动态数据表元数据 Schema
-- 存储用户自定义表的定义（表名、列定义），实际数据表通过 DDL 动态创建
-- ============================================================

CREATE TABLE data_table_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(64)  NOT NULL UNIQUE,
    display_name    VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    table_name      VARCHAR(80)  NOT NULL UNIQUE,  -- 实际 PG 表名（data_{slug}）
    org_id          BIGINT,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ
);

COMMENT ON TABLE data_table_definition IS '动态数据表定义';

CREATE TABLE data_column_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id        BIGINT       NOT NULL REFERENCES data_table_definition(id) ON DELETE CASCADE,
    name            VARCHAR(64)  NOT NULL,
    display_name    VARCHAR(128),
    column_type     VARCHAR(32)  NOT NULL,  -- string/text/integer/decimal/boolean/timestamp/json
    nullable        BOOLEAN      NOT NULL DEFAULT TRUE,
    unique_col      BOOLEAN      NOT NULL DEFAULT FALSE,
    default_value   VARCHAR(256),
    sort_order      INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE data_column_definition IS '动态数据表列定义';
CREATE INDEX idx_data_column_table ON data_column_definition(table_id, sort_order);


-- ============================================================
-- 数据摄入 API Key
-- ============================================================

CREATE TABLE data_api_key (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_hash        VARCHAR(64)  NOT NULL UNIQUE,
    key_prefix      VARCHAR(16)  NOT NULL,
    name            VARCHAR(128) NOT NULL,
    user_id         BIGINT       NOT NULL,
    allowed_tables  VARCHAR(1024),
    permissions     VARCHAR(64)  NOT NULL DEFAULT 'ingest',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at      TIMESTAMPTZ,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    last_used_at    TIMESTAMPTZ
);

COMMENT ON TABLE data_api_key IS '数据摄入 API Key';
CREATE INDEX idx_data_api_key_user ON data_api_key(user_id);



-- ============================================================
-- permission 子域（功能权限码）
-- ============================================================

CREATE TABLE sys_permission_code (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        INTEGER      NOT NULL DEFAULT 0,
    org_id         BIGINT,
    workspace_id   BIGINT,
    name           VARCHAR(100) NOT NULL,
    code           VARCHAR(120) NOT NULL UNIQUE,
    module         VARCHAR(50)  NOT NULL,
    resource       VARCHAR(50)  NOT NULL,
    action         VARCHAR(50)  NOT NULL,
    status         INTEGER      NOT NULL DEFAULT 0,
    archived_at    TIMESTAMP(6),
    create_by      BIGINT,
    create_by_type VARCHAR(16),
    create_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by      BIGINT,
    update_by_type VARCHAR(16),
    update_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id       BIGINT,
    delete_time    TIMESTAMP(6),
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    remark         VARCHAR(255)
);

COMMENT ON TABLE sys_permission_code IS '功能权限码';
COMMENT ON COLUMN sys_permission_code.code IS '三段式权限码：模块:资源:动作';
COMMENT ON COLUMN sys_permission_code.module IS '模块标识';
COMMENT ON COLUMN sys_permission_code.resource IS '资源标识';
COMMENT ON COLUMN sys_permission_code.action IS '动作标识';
COMMENT ON COLUMN sys_permission_code.status IS '0 正常 / 1 禁用';

CREATE INDEX idx_sys_permission_code_module_resource ON sys_permission_code (module, resource) WHERE deleted = FALSE;

-- ============================================================
-- file 子域
-- ============================================================

CREATE TABLE sys_file (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    file_key     VARCHAR(500) NOT NULL UNIQUE,
    original_name VARCHAR(500) NOT NULL,
    mime_type    VARCHAR(200),
    size         BIGINT       NOT NULL,
    storage_path VARCHAR(1000),
    uploader_id  BIGINT,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_file IS '文件记录';
COMMENT ON COLUMN sys_file.file_key IS '文件唯一标识（存储 key）';

CREATE INDEX idx_sys_file_uploader ON sys_file (uploader_id) WHERE deleted = FALSE;

CREATE TABLE sys_file_config (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    storage_type VARCHAR(20)  NOT NULL,
    config       TEXT,
    master       BOOLEAN      NOT NULL DEFAULT FALSE,
    status       INTEGER      NOT NULL DEFAULT 0,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_file_config IS '文件存储配置';
COMMENT ON COLUMN sys_file_config.storage_type IS 'LOCAL / S3 / OSS';
COMMENT ON COLUMN sys_file_config.master IS '是否主配置';
COMMENT ON COLUMN sys_file_config.status IS '0 正常 / 1 禁用';

-- ============================================================
-- log 子域（登录日志）
-- ============================================================

CREATE TABLE sys_login_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT,
    username     VARCHAR(50),
    login_type   VARCHAR(20)  NOT NULL,
    ip           VARCHAR(50),
    user_agent   VARCHAR(500),
    location     VARCHAR(200),
    success      BOOLEAN      NOT NULL DEFAULT TRUE,
    fail_reason  VARCHAR(500),
    login_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_login_log IS '登录日志（不可变）';
COMMENT ON COLUMN sys_login_log.login_type IS 'PASSWORD / EMAIL / OAUTH';

CREATE INDEX idx_sys_login_log_user ON sys_login_log (user_id, login_time DESC);
CREATE INDEX idx_sys_login_log_time ON sys_login_log (login_time DESC);

-- ============================================================
-- mail 子域
-- ============================================================

CREATE TABLE sys_mail_account (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    host         VARCHAR(200) NOT NULL,
    port         INTEGER      NOT NULL,
    username     VARCHAR(200) NOT NULL,
    password     VARCHAR(200) NOT NULL,
    ssl_enabled  BOOLEAN      NOT NULL DEFAULT FALSE,
    from_address VARCHAR(200) NOT NULL,
    status       SMALLINT     NOT NULL DEFAULT 1,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_mail_account IS '邮件账号配置';
COMMENT ON COLUMN sys_mail_account.status IS '1=启用 0=禁用';

CREATE TABLE sys_mail_template (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    code         VARCHAR(64)  NOT NULL UNIQUE,
    name         VARCHAR(100) NOT NULL,
    subject      VARCHAR(200) NOT NULL,
    content      TEXT         NOT NULL,
    account_id   BIGINT       NOT NULL,
    params       VARCHAR(500),
    status       SMALLINT     NOT NULL DEFAULT 1,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_mail_template IS '邮件模板';
COMMENT ON COLUMN sys_mail_template.code IS '模板编码，唯一标识';
COMMENT ON COLUMN sys_mail_template.params IS '参数名列表（JSON 数组）';
COMMENT ON COLUMN sys_mail_template.status IS '1=启用 0=禁用';

CREATE INDEX idx_sys_mail_template_account ON sys_mail_template (account_id) WHERE deleted = FALSE;

CREATE TABLE sys_mail_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    template_id  BIGINT,
    to_address   VARCHAR(200) NOT NULL,
    subject      VARCHAR(200) NOT NULL,
    content      TEXT,
    send_status  SMALLINT     NOT NULL DEFAULT 0,
    send_time    TIMESTAMP(6),
    error_message VARCHAR(500),
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_mail_log IS '邮件发送日志';
COMMENT ON COLUMN sys_mail_log.send_status IS '0=发送中 1=成功 2=失败';

CREATE INDEX idx_sys_mail_log_template ON sys_mail_log (template_id);
CREATE INDEX idx_sys_mail_log_time ON sys_mail_log (create_time DESC);

-- ============================================================
-- notify 子域（通知公告）
-- ============================================================

CREATE TABLE sys_notice (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    title        VARCHAR(200) NOT NULL,
    content      TEXT,
    type         VARCHAR(20)  NOT NULL,
    status       SMALLINT     NOT NULL DEFAULT 0,
    publish_time TIMESTAMP(6),
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_notice IS '通知公告';
COMMENT ON COLUMN sys_notice.type IS 'NOTICE=通知 / ANNOUNCEMENT=公告';
COMMENT ON COLUMN sys_notice.status IS '0=草稿 1=已发布';

CREATE INDEX idx_sys_notice_type_status ON sys_notice (type, status) WHERE deleted = FALSE;

-- ============================================================
-- role 子域（ReBAC 资源关系 + ABAC 访问策略）
-- ============================================================

CREATE TABLE sys_permission_tuple (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    object_type      VARCHAR(50)  NOT NULL,
    object_id        VARCHAR(100) NOT NULL,
    relation         VARCHAR(50)  NOT NULL,
    subject_type     VARCHAR(50)  NOT NULL,
    subject_id       VARCHAR(100) NOT NULL,
    subject_relation VARCHAR(50)  NOT NULL DEFAULT '',
    expires_at       TIMESTAMP,
    granted_by       VARCHAR(100),
    create_by        BIGINT,
    create_by_type   VARCHAR(16),
    create_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by        BIGINT,
    update_by_type   VARCHAR(16),
    update_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id         BIGINT,
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    remark           VARCHAR(255),
    UNIQUE (object_type, object_id, relation, subject_type, subject_id, subject_relation)
);

COMMENT ON TABLE sys_permission_tuple IS 'ReBAC Zanzibar 风格关系元组';
COMMENT ON COLUMN sys_permission_tuple.subject_relation IS '主体为对象集合时，沿该关系递归展开';

CREATE INDEX idx_permission_tuple_object ON sys_permission_tuple (object_type, object_id, relation) WHERE deleted = FALSE;
CREATE INDEX idx_permission_tuple_subject ON sys_permission_tuple (subject_type, subject_id, subject_relation) WHERE deleted = FALSE;

CREATE TABLE sys_access_policy (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    condition_json  TEXT,
    effect          VARCHAR(16)  NOT NULL DEFAULT 'ALLOW',
    priority        INTEGER      NOT NULL DEFAULT 100,
    target_resource VARCHAR(64),
    target_action   VARCHAR(64),
    status          INTEGER      NOT NULL DEFAULT 1,
    archived_at     TIMESTAMP(6),
    create_by       BIGINT,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE sys_access_policy IS 'ABAC 访问策略';
COMMENT ON COLUMN sys_access_policy.effect IS 'ALLOW / DENY';
COMMENT ON COLUMN sys_access_policy.priority IS '数值越小优先级越高';
COMMENT ON COLUMN sys_access_policy.condition_json IS '条件表达式（JSON）';
COMMENT ON COLUMN sys_access_policy.status IS '0=禁用 1=启用';

CREATE INDEX idx_sys_access_policy_target ON sys_access_policy (target_resource, target_action) WHERE deleted = FALSE AND status = 1;


-- ============================================================
-- operator 字段补充（为所有含 create_by 的表添加类型和归属字段）
-- ============================================================

DO $$
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN
        SELECT table_name
        FROM information_schema.columns
        WHERE column_name = 'create_by'
          AND table_schema = 'public'
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = tbl AND column_name = 'create_by_type' AND table_schema = 'public'
        ) THEN
            EXECUTE format('ALTER TABLE %I ADD COLUMN create_by_type VARCHAR(16) DEFAULT ''HUMAN''', tbl);
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = tbl AND column_name = 'update_by_type' AND table_schema = 'public'
        ) THEN
            EXECUTE format('ALTER TABLE %I ADD COLUMN update_by_type VARCHAR(16) DEFAULT ''HUMAN''', tbl);
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = tbl AND column_name = 'owner_id' AND table_schema = 'public'
        ) THEN
            EXECUTE format('ALTER TABLE %I ADD COLUMN owner_id BIGINT', tbl);
            EXECUTE format('UPDATE %I SET owner_id = create_by WHERE owner_id IS NULL', tbl);
        END IF;
    END LOOP;
END $$;

DO $$
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN
        SELECT table_name
        FROM information_schema.columns
        WHERE column_name = 'owner_id' AND table_schema = 'public'
    LOOP
        EXECUTE format('CREATE INDEX IF NOT EXISTS idx_%s_owner_id ON %I (owner_id)', tbl, tbl);
    END LOOP;
END $$;

-- ============================================================
-- approval 子域（审批记录 + 抄送 + 表单模板 + 评论）
-- ============================================================

CREATE TABLE sys_approval_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    process_instance_id VARCHAR(64) NOT NULL,
    task_id         VARCHAR(64),
    assignee        VARCHAR(64)  NOT NULL,
    operation_type  VARCHAR(20)  NOT NULL,
    comment         VARCHAR(500),
    operation_time  TIMESTAMP(6) NOT NULL,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE sys_approval_record IS '审批记录';
COMMENT ON COLUMN sys_approval_record.operation_type IS 'APPROVE/REJECT/DELEGATE/ADD_SIGN/TRANSFER/WITHDRAW/URGE';

CREATE INDEX idx_approval_record_process ON sys_approval_record(process_instance_id);
CREATE INDEX idx_approval_record_assignee ON sys_approval_record(assignee);
CREATE INDEX idx_approval_record_task ON sys_approval_record(task_id);

CREATE TABLE sys_approval_cc_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    process_instance_id VARCHAR(64) NOT NULL,
    task_name       VARCHAR(128),
    cc_user         VARCHAR(64)  NOT NULL,
    cc_time         TIMESTAMP(6) NOT NULL,
    entity_type     VARCHAR(64),
    entity_id       BIGINT,
    read            BOOLEAN      NOT NULL DEFAULT FALSE,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE sys_approval_cc_record IS '审批抄送记录';

CREATE INDEX idx_cc_record_user ON sys_approval_cc_record(cc_user);
CREATE INDEX idx_cc_record_process ON sys_approval_cc_record(process_instance_id);

CREATE TABLE sys_approval_form_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(500),
    process_key     VARCHAR(128) NOT NULL,
    fields_json     TEXT,
    status          INTEGER      NOT NULL DEFAULT 1,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE sys_approval_form_template IS '审批表单模板';

CREATE INDEX idx_form_template_process_key ON sys_approval_form_template(process_key);

CREATE TABLE sys_approval_comment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_instance_id VARCHAR(64) NOT NULL,
    task_id         VARCHAR(64),
    user_id         BIGINT       NOT NULL,
    content         TEXT,
    attachments     TEXT,
    mentioned_users JSONB,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_approval_comment IS '审批评论';

CREATE INDEX idx_comment_process ON sys_approval_comment(process_instance_id);
CREATE INDEX idx_comment_task ON sys_approval_comment(task_id);

-- ============================================================
-- menu 子域（系统菜单 + 角色菜单关联）
-- ============================================================

CREATE TABLE sys_menu (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        INTEGER      NOT NULL DEFAULT 0,
    org_id         BIGINT,
    workspace_id   BIGINT,
    parent_id      BIGINT,
    title          VARCHAR(50)  NOT NULL,
    path           VARCHAR(200),
    icon           VARCHAR(50),
    sort_order     INTEGER      NOT NULL DEFAULT 0,
    visible        BOOLEAN      NOT NULL DEFAULT TRUE,
    menu_type      VARCHAR(20)  NOT NULL DEFAULT 'MENU',
    permission_code VARCHAR(120),
    create_by      BIGINT,
    create_by_type VARCHAR(16),
    create_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by      BIGINT,
    update_by_type VARCHAR(16),
    update_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id       BIGINT,
    delete_time    TIMESTAMP(6),
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    remark         VARCHAR(255)
);

COMMENT ON TABLE sys_menu IS '系统菜单';
COMMENT ON COLUMN sys_menu.menu_type IS 'GROUP/MENU/BUTTON';
COMMENT ON COLUMN sys_menu.permission_code IS '可选绑定的功能权限码，仅用于前端显隐；安全边界以接口 @PreAuthorize 为准';

CREATE INDEX idx_menu_parent ON sys_menu(parent_id);
CREATE INDEX idx_sys_menu_deleted ON sys_menu (deleted);

CREATE TABLE sys_role_menu (
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);

COMMENT ON TABLE sys_role_menu IS '角色-菜单关联';


-- ============================================================
-- channel 子域（渠道集成）
-- ============================================================

CREATE TABLE IF NOT EXISTS channel_config (
    id              BIGSERIAL PRIMARY KEY,
    channel_type    VARCHAR(32) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    app_id          VARCHAR(200),
    app_secret      VARCHAR(500),
    token           VARCHAR(200),
    encoding_aes_key VARCHAR(200),
    status          INT NOT NULL DEFAULT 0,
    ext_config      JSONB,
    version         INT NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

CREATE INDEX idx_channel_config_type ON channel_config(channel_type) WHERE deleted = FALSE;
COMMENT ON TABLE channel_config IS '渠道配置';

CREATE TABLE channel_platform (
    id              BIGSERIAL PRIMARY KEY,
    type            VARCHAR(32)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    config          JSONB,
    status          INT          NOT NULL DEFAULT 0,
    version         INT          NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(500)
);

COMMENT ON TABLE channel_platform IS '渠道平台配置';
COMMENT ON COLUMN channel_platform.type IS '平台类型：dingtalk/feishu/wecom_kf/wechat_mp/wechat_mini';
COMMENT ON COLUMN channel_platform.config IS '平台凭证 JSON（按 type 结构不同）';

CREATE INDEX idx_channel_platform_type ON channel_platform (type) WHERE deleted = FALSE;

CREATE TABLE channel_bot_binding (
    id              BIGSERIAL PRIMARY KEY,
    platform_id     BIGINT       NOT NULL,
    name            VARCHAR(100) NOT NULL,
    assistant_id    BIGINT       NOT NULL,
    route_rule      JSONB,
    fallback_reply  VARCHAR(500),
    status          INT          NOT NULL DEFAULT 0,
    version         INT          NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(500)
);

COMMENT ON TABLE channel_bot_binding IS '机器人绑定 Assistant';
COMMENT ON COLUMN channel_bot_binding.platform_id IS '关联 channel_platform.id';
COMMENT ON COLUMN channel_bot_binding.assistant_id IS '绑定的 Assistant ID（BIGINT，跨 schema 引用 ai_assistant.id）';
COMMENT ON COLUMN channel_bot_binding.route_rule IS '触发规则 JSON（关键词/群 ID 等）';

CREATE INDEX idx_bot_binding_platform ON channel_bot_binding (platform_id) WHERE deleted = FALSE;
CREATE INDEX idx_bot_binding_assistant ON channel_bot_binding (assistant_id) WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS channel_message (
    id              BIGSERIAL PRIMARY KEY,
    channel_type    VARCHAR(32) NOT NULL,
    direction       VARCHAR(16) NOT NULL,
    message_type    VARCHAR(16) NOT NULL,
    external_user_id VARCHAR(200) NOT NULL,
    user_id         BIGINT,
    content         TEXT,
    media_url       VARCHAR(500),
    raw_payload     TEXT,
    message_time    TIMESTAMP,
    version         INT NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

CREATE INDEX idx_channel_message_user ON channel_message(external_user_id, channel_type) WHERE deleted = FALSE;
CREATE INDEX idx_channel_message_time ON channel_message(message_time DESC) WHERE deleted = FALSE;
COMMENT ON TABLE channel_message IS '渠道消息记录';

CREATE TABLE IF NOT EXISTS webhook_config (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    url             VARCHAR(500) NOT NULL,
    event_types     VARCHAR(500),
    secret          VARCHAR(200),
    status          VARCHAR(16) NOT NULL DEFAULT 'active',
    direction       VARCHAR(16) NOT NULL DEFAULT 'outbound',
    failure_count   INT DEFAULT 0,
    max_retries     INT DEFAULT 3,
    version         INT NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

CREATE INDEX idx_webhook_config_status ON webhook_config(status) WHERE deleted = FALSE;
COMMENT ON TABLE webhook_config IS 'Webhook 配置';

CREATE TABLE IF NOT EXISTS webhook_log (
    id              BIGSERIAL PRIMARY KEY,
    webhook_id      BIGINT NOT NULL,
    event_type      VARCHAR(64) NOT NULL,
    request_body    TEXT,
    response_status INT,
    response_body   VARCHAR(2000),
    status          VARCHAR(16) NOT NULL DEFAULT 'pending',
    failure_reason  VARCHAR(500),
    retry_count     INT DEFAULT 0,
    next_retry_time TIMESTAMP,
    push_time       TIMESTAMP,
    version         INT NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

CREATE INDEX idx_webhook_log_webhook ON webhook_log(webhook_id) WHERE deleted = FALSE;
CREATE INDEX idx_webhook_log_retry ON webhook_log(status, next_retry_time) WHERE deleted = FALSE;
COMMENT ON TABLE webhook_log IS 'Webhook 推送日志';

-- ============================================================
-- livechat 子域（客服系统）
-- ============================================================

-- ============================================================
-- stats 子域（运营统计）
-- ============================================================

CREATE TABLE IF NOT EXISTS sys_user_event (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    event_type      VARCHAR(32)  NOT NULL,
    page            VARCHAR(255),
    target          VARCHAR(255),
    extra           JSONB,
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_event_type_time ON sys_user_event (event_type, create_time);
CREATE INDEX IF NOT EXISTS idx_user_event_user ON sys_user_event (user_id, create_time);
CREATE INDEX idx_user_event_date ON sys_user_event ((create_time::date));
COMMENT ON TABLE sys_user_event IS '用户行为事件（追加写入）';

-- ============================================================
-- 用户画像模块
-- ============================================================

-- 画像维度定义
CREATE TABLE sys_profile_dimension (
    id              BIGSERIAL PRIMARY KEY,
    code            VARCHAR(64)  NOT NULL UNIQUE,
    name            VARCHAR(100) NOT NULL,
    group_code      VARCHAR(32)  NOT NULL,
    value_type      VARCHAR(32)  NOT NULL DEFAULT 'text',
    enum_options    JSONB,
    unit            VARCHAR(32),
    source          VARCHAR(32)  NOT NULL DEFAULT 'manual',
    sort_order      INT          NOT NULL DEFAULT 0,
    required        BOOLEAN      NOT NULL DEFAULT FALSE,
    searchable      BOOLEAN      NOT NULL DEFAULT FALSE,
    ai_visible      BOOLEAN      NOT NULL DEFAULT TRUE,
    status          INT          NOT NULL DEFAULT 0,
    version         INT          NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(500)
);

COMMENT ON TABLE sys_profile_dimension IS '画像维度定义';
COMMENT ON COLUMN sys_profile_dimension.code IS '维度编码（如 health.blood_pressure）';
COMMENT ON COLUMN sys_profile_dimension.group_code IS '分组：basic/preference/behavior/health/living/shopping/social/personality';
COMMENT ON COLUMN sys_profile_dimension.value_type IS '值类型：text/number/boolean/enum/tags/json';
COMMENT ON COLUMN sys_profile_dimension.ai_visible IS '是否注入 AI 上下文';

-- 用户维度值
CREATE TABLE sys_profile_dimension_value (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    dimension_id    BIGINT       NOT NULL,
    value_text      TEXT,
    value_number    DECIMAL(18,4),
    value_tags      JSONB,
    confidence      DECIMAL(3,2) DEFAULT 1.0,
    source          VARCHAR(32)  NOT NULL DEFAULT 'manual',
    expires_at      TIMESTAMP,
    version         INT          NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(500)
);

COMMENT ON TABLE sys_profile_dimension_value IS '用户画像维度值';
CREATE UNIQUE INDEX uk_profile_dim_value_user_dim ON sys_profile_dimension_value (user_id, dimension_id) WHERE deleted = FALSE;
CREATE INDEX idx_profile_dim_value_user ON sys_profile_dimension_value (user_id) WHERE deleted = FALSE;

-- 用户画像主表（聚合摘要）
CREATE TABLE sys_user_profile (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT       NOT NULL UNIQUE,
    lifecycle_stage VARCHAR(32)  NOT NULL DEFAULT 'new',
    ai_summary      TEXT,
    last_analyzed_at TIMESTAMP,
    version         INT          NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(500)
);

COMMENT ON TABLE sys_user_profile IS '用户画像主表';

-- ============================================================
-- 企微客服账号绑定
-- ============================================================

CREATE TABLE wecom_kf_account_binding (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    open_kf_id      VARCHAR(64)  NOT NULL UNIQUE,
    account_name    VARCHAR(128),
    assistant_id    BIGINT       NOT NULL,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6),
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6),
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(256)
);

COMMENT ON TABLE wecom_kf_account_binding IS '企微客服账号与 Assistant 的绑定关系';
CREATE UNIQUE INDEX idx_wecom_kf_open_kf_id ON wecom_kf_account_binding (open_kf_id);


-- ============================================================
-- 开发者商业授权与托管模型额度
-- 说明：仅管理开发者授权、订阅、额度、兑换码、子代理资格。
-- ============================================================

CREATE TABLE developer_account (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version               INTEGER      NOT NULL DEFAULT 0,
    org_id                BIGINT,
    workspace_id          BIGINT,
    developer_code        VARCHAR(64)  NOT NULL,
    user_id               BIGINT       NOT NULL,
    name                  VARCHAR(120) NOT NULL,
    status                VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    license_id            VARCHAR(120),
    license_tier          VARCHAR(32)  NOT NULL DEFAULT 'FREE',
    allow_managed_gateway BOOLEAN      NOT NULL DEFAULT FALSE,
    allow_sub_proxy       BOOLEAN      NOT NULL DEFAULT FALSE,
    max_proxy_depth       INTEGER      NOT NULL DEFAULT 0,
    owner_id              BIGINT,
    create_by             BIGINT,
    create_by_type        VARCHAR(16),
    create_time           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by             BIGINT,
    update_by_type        VARCHAR(16),
    update_time           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time           TIMESTAMP(6),
    deleted               BOOLEAN      NOT NULL DEFAULT FALSE,
    remark                VARCHAR(255)
);

COMMENT ON TABLE developer_account IS '开发者账户：承载框架开发者授权、托管网关和子代理资格';
COMMENT ON COLUMN developer_account.allow_managed_gateway IS '是否允许使用 AAF 托管模型网关';
COMMENT ON COLUMN developer_account.allow_sub_proxy IS '是否允许开通子代理';
COMMENT ON COLUMN developer_account.max_proxy_depth IS '允许的最大子代理层级';
CREATE UNIQUE INDEX uk_developer_account_code ON developer_account(developer_code) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_developer_account_user ON developer_account(user_id) WHERE deleted = FALSE;

CREATE TABLE developer_subscription_plan (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version               INTEGER      NOT NULL DEFAULT 0,
    org_id                BIGINT,
    workspace_id          BIGINT,
    code                  VARCHAR(40)  NOT NULL,
    name                  VARCHAR(100) NOT NULL,
    duration_days         INTEGER      NOT NULL,
    price                 BIGINT       NOT NULL DEFAULT 0,
    included_tokens       BIGINT       NOT NULL DEFAULT 0,
    allow_managed_gateway BOOLEAN      NOT NULL DEFAULT FALSE,
    allow_sub_proxy       BOOLEAN      NOT NULL DEFAULT FALSE,
    max_proxy_depth       INTEGER      NOT NULL DEFAULT 0,
    status                VARCHAR(20)  NOT NULL DEFAULT 'ENABLED',
    sort_order            INTEGER      NOT NULL DEFAULT 100,
    owner_id              BIGINT,
    create_by             BIGINT,
    create_by_type        VARCHAR(16),
    create_time           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by             BIGINT,
    update_by_type        VARCHAR(16),
    update_time           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time           TIMESTAMP(6),
    deleted               BOOLEAN      NOT NULL DEFAULT FALSE,
    remark                VARCHAR(255)
);

COMMENT ON TABLE developer_subscription_plan IS '开发者订阅套餐';
CREATE UNIQUE INDEX uk_developer_subscription_plan_code ON developer_subscription_plan(code) WHERE deleted = FALSE;

CREATE TABLE developer_subscription (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        INTEGER      NOT NULL DEFAULT 0,
    org_id         BIGINT,
    workspace_id   BIGINT,
    developer_id   BIGINT       NOT NULL,
    plan_id        BIGINT       NOT NULL,
    start_at       TIMESTAMP(6) NOT NULL,
    end_at         TIMESTAMP(6),
    status         VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    source_id      BIGINT,
    owner_id       BIGINT,
    create_by      BIGINT,
    create_by_type VARCHAR(16),
    create_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by      BIGINT,
    update_by_type VARCHAR(16),
    update_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time    TIMESTAMP(6),
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    remark         VARCHAR(255)
);

COMMENT ON TABLE developer_subscription IS '开发者订阅实例';
CREATE INDEX idx_developer_subscription_developer ON developer_subscription(developer_id, status) WHERE deleted = FALSE;

CREATE TABLE developer_token_account (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER      NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    developer_id        BIGINT       NOT NULL,
    balance_tokens      BIGINT       NOT NULL DEFAULT 0,
    frozen_tokens       BIGINT       NOT NULL DEFAULT 0,
    total_earned_tokens BIGINT       NOT NULL DEFAULT 0,
    total_spent_tokens  BIGINT       NOT NULL DEFAULT 0,
    owner_id            BIGINT,
    create_by           BIGINT,
    create_by_type      VARCHAR(16),
    create_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    remark              VARCHAR(255)
);

COMMENT ON TABLE developer_token_account IS '开发者托管模型总 Token 池';
CREATE UNIQUE INDEX uk_developer_token_account ON developer_token_account(developer_id) WHERE deleted = FALSE;

CREATE TABLE developer_token_transaction (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version              INTEGER      NOT NULL DEFAULT 0,
    org_id               BIGINT,
    workspace_id         BIGINT,
    account_id           BIGINT       NOT NULL,
    developer_id         BIGINT       NOT NULL,
    type                 VARCHAR(20)  NOT NULL,
    amount_tokens        BIGINT       NOT NULL,
    balance_after_tokens BIGINT       NOT NULL,
    source               VARCHAR(80),
    biz_id               VARCHAR(120),
    owner_id             BIGINT,
    create_by            BIGINT,
    create_by_type       VARCHAR(16),
    create_time          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by            BIGINT,
    update_by_type       VARCHAR(16),
    update_time          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time          TIMESTAMP(6),
    deleted              BOOLEAN      NOT NULL DEFAULT FALSE,
    remark               VARCHAR(255)
);

COMMENT ON TABLE developer_token_transaction IS '开发者 Token 池流水';
CREATE INDEX idx_developer_token_tx_developer ON developer_token_transaction(developer_id, create_time) WHERE deleted = FALSE;
CREATE INDEX idx_developer_token_tx_biz ON developer_token_transaction(biz_id) WHERE deleted = FALSE;

CREATE TABLE developer_redeem_code (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                    INTEGER      NOT NULL DEFAULT 0,
    org_id                     BIGINT,
    workspace_id               BIGINT,
    code_hash                  VARCHAR(64)  NOT NULL,
    code_prefix                VARCHAR(20)  NOT NULL,
    token_amount               BIGINT       NOT NULL,
    status                     VARCHAR(20)  NOT NULL DEFAULT 'UNUSED',
    expires_at                 TIMESTAMP(6),
    redeemed_by_developer_id   BIGINT,
    redeemed_at                TIMESTAMP(6),
    owner_id                   BIGINT,
    create_by                  BIGINT,
    create_by_type             VARCHAR(16),
    create_time                TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by                  BIGINT,
    update_by_type             VARCHAR(16),
    update_time                TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time                TIMESTAMP(6),
    deleted                    BOOLEAN      NOT NULL DEFAULT FALSE,
    remark                     VARCHAR(255),
    type                       VARCHAR(20)  NOT NULL DEFAULT 'TOKEN',
    plan_code                  VARCHAR(40),
    license_jwt                TEXT
);

COMMENT ON TABLE developer_redeem_code IS '开发者 Token 兑换码';
COMMENT ON COLUMN developer_redeem_code.type        IS '兑换码类型：TOKEN=发放token额度，LICENSE=激活套餐订阅';
COMMENT ON COLUMN developer_redeem_code.plan_code   IS 'type=LICENSE 时绑定的套餐 code';
COMMENT ON COLUMN developer_redeem_code.license_jwt IS 'type=LICENSE 时预签发的 license.jwt 内容';
CREATE UNIQUE INDEX uk_developer_redeem_code_hash ON developer_redeem_code(code_hash) WHERE deleted = FALSE;

CREATE TABLE developer_api_key (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        INTEGER      NOT NULL DEFAULT 0,
    org_id         BIGINT,
    workspace_id   BIGINT,
    developer_id   BIGINT       NOT NULL,
    name           VARCHAR(120) NOT NULL,
    key_hash       VARCHAR(64)  NOT NULL,
    key_prefix     VARCHAR(24)  NOT NULL,
    scopes         VARCHAR(255) NOT NULL DEFAULT 'gateway:chat',
    enabled        BOOLEAN      NOT NULL DEFAULT TRUE,
    expires_at     TIMESTAMPTZ,
    last_used_at   TIMESTAMPTZ,
    owner_id       BIGINT,
    create_by      BIGINT,
    create_by_type VARCHAR(16),
    create_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by      BIGINT,
    update_by_type VARCHAR(16),
    update_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time    TIMESTAMP(6),
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    remark         VARCHAR(255)
);

COMMENT ON TABLE developer_api_key IS '开发者调用 AAF Model Gateway 的 API Key，当前仅管理，不启用代理执行入口';
CREATE UNIQUE INDEX uk_developer_api_key_hash ON developer_api_key(key_hash) WHERE deleted = FALSE;
CREATE INDEX idx_developer_api_key_developer ON developer_api_key(developer_id) WHERE deleted = FALSE;

CREATE TABLE developer_proxy (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER      NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    parent_developer_id BIGINT       NOT NULL,
    child_developer_id  BIGINT       NOT NULL,
    proxy_depth         INTEGER      NOT NULL DEFAULT 1,
    status              VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    token_limit         BIGINT,
    allow_sub_proxy     BOOLEAN      NOT NULL DEFAULT FALSE,
    owner_id            BIGINT,
    create_by           BIGINT,
    create_by_type      VARCHAR(16),
    create_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    remark              VARCHAR(255)
);

COMMENT ON TABLE developer_proxy IS '开发者子代理配置，用于受控分销层级';
CREATE UNIQUE INDEX uk_developer_proxy_pair ON developer_proxy(parent_developer_id, child_developer_id) WHERE deleted = FALSE;

-- ==================== 统一消息发送日志 ====================
CREATE TABLE sys_message_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER      NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    channel       VARCHAR(20)  NOT NULL,
    template_code VARCHAR(100),
    recipients    TEXT,
    subject       VARCHAR(200),
    content       TEXT,
    status        VARCHAR(10)  NOT NULL DEFAULT 'PENDING',
    error_msg     VARCHAR(500),
    send_time     TIMESTAMP(6),
    -- 厂商响应（短信/邮件等外部渠道使用，站内信留空）
    provider       VARCHAR(20),
    api_request_id VARCHAR(128),
    api_code       VARCHAR(64),
    api_msg        VARCHAR(512),
    archived_at   TIMESTAMP(6),
    create_by     BIGINT,
    create_by_type VARCHAR(16),
    create_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by     BIGINT,
    update_by_type VARCHAR(16),
    update_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id      BIGINT,
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    remark        VARCHAR(255)
);

COMMENT ON TABLE sys_message_log IS '统一消息发送日志（EMAIL/SMS/DINGTALK 等所有渠道）';
COMMENT ON COLUMN sys_message_log.status IS 'PENDING=待发送 SUCCESS=成功 FAILED=失败';
COMMENT ON COLUMN sys_message_log.provider IS '厂商标识（aliyun/tencent 等），仅短信/邮件等外部渠道使用';
COMMENT ON COLUMN sys_message_log.api_request_id IS '厂商响应请求 ID（阿里云 BizId 等）';
COMMENT ON COLUMN sys_message_log.api_code IS '厂商响应码（OK/IS_OUT_OF_SERVICE 等）';
COMMENT ON COLUMN sys_message_log.api_msg IS '厂商响应描述';
CREATE INDEX idx_sys_message_log_channel ON sys_message_log (channel);
CREATE INDEX idx_sys_message_log_time ON sys_message_log (create_time DESC);

-- ============================================================
-- contact 子域
-- sys_contact：联系人/伙伴（个人 / 组织）
-- sys_contact_identity：渠道身份（企微userId、钉钉userId、微信openId等）
-- sys_user.contact_id：用户关联联系人（可空）
-- ============================================================

CREATE TABLE sys_contact (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER       NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(100)  NOT NULL,
    real_name       VARCHAR(100),
    phone           VARCHAR(20),
    email           VARCHAR(200),
    avatar          VARCHAR(500),
    type            VARCHAR(20)   NOT NULL DEFAULT 'PERSON',
    source          VARCHAR(20),
    status          VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    parent_id       BIGINT        REFERENCES sys_contact(id),
    ext             JSONB,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN       NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE sys_contact IS '联系人/伙伴';
COMMENT ON COLUMN sys_contact.type IS 'PERSON=个人 / ORG=组织';
COMMENT ON COLUMN sys_contact.source IS '来源：REGISTER=注册 / IMPORT=导入 / CHANNEL=渠道接入 / VISITOR=访客';
COMMENT ON COLUMN sys_contact.status IS '状态：ACTIVE=活跃 / LEAD=线索 / VISITOR=访客 / ARCHIVED=已归档';
COMMENT ON COLUMN sys_contact.parent_id IS '所属组织（自关联）';
COMMENT ON COLUMN sys_contact.ext IS '扩展字段（地区、标签、行业等）';

CREATE INDEX idx_sys_contact_type ON sys_contact (type) WHERE deleted = false;
CREATE INDEX idx_sys_contact_status ON sys_contact (status) WHERE deleted = false;
CREATE INDEX idx_sys_contact_parent_id ON sys_contact (parent_id) WHERE deleted = false;

CREATE TABLE sys_contact_identity (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER       NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    contact_id      BIGINT        NOT NULL REFERENCES sys_contact(id),
    channel         VARCHAR(50)   NOT NULL,
    external_id     VARCHAR(200)  NOT NULL,
    corp_id         VARCHAR(100),
    display_name    VARCHAR(100),
    avatar_url      VARCHAR(500),
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN       NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255),
    CONSTRAINT uk_sys_contact_identity_channel_external UNIQUE (channel, external_id, corp_id)
);

COMMENT ON TABLE sys_contact_identity IS '联系人渠道身份（身份索引，与 sys_user_oauth 互补）';
COMMENT ON COLUMN sys_contact_identity.channel IS '渠道标识：WECOM / DINGTALK / WECHAT_MP / WECHAT_MINI 等';
COMMENT ON COLUMN sys_contact_identity.external_id IS '渠道内的外部用户 ID';
COMMENT ON COLUMN sys_contact_identity.corp_id IS '企业 ID（企微/钉钉区分企业，微信类为 null）';

CREATE INDEX idx_sys_contact_identity_contact_id ON sys_contact_identity (contact_id) WHERE deleted = false;
CREATE INDEX idx_sys_contact_identity_channel ON sys_contact_identity (channel) WHERE deleted = false;

ALTER TABLE sys_user ADD COLUMN contact_id BIGINT REFERENCES sys_contact(id);

COMMENT ON COLUMN sys_user.contact_id IS '关联联系人 ID（可空）：user 是能登录的 contact，contact 是身份本体';

CREATE INDEX idx_sys_user_contact_id ON sys_user (contact_id) WHERE contact_id IS NOT NULL;


-- ==================== 演示数据标记表 ====================
CREATE TABLE sys_demo_data_record (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name  VARCHAR(100) NOT NULL,
    record_id   BIGINT       NOT NULL,
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_demo_data_record IS '演示数据标记表：记录由演示模式写入的数据，用于精确清理';
CREATE INDEX idx_demo_data_record_table ON sys_demo_data_record (table_name);

-- =====================================================
-- sys_dashboard_preset：仪表盘预设模板表
-- =====================================================

CREATE TABLE sys_dashboard_preset (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preset_key      VARCHAR(64)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(500),
    admin_only      BOOLEAN      NOT NULL DEFAULT FALSE,
    refresh_interval INTEGER     NOT NULL DEFAULT 300,
    widgets         JSONB        NOT NULL DEFAULT '[]',
    sort_order      INTEGER      NOT NULL DEFAULT 0,
    status          SMALLINT     NOT NULL DEFAULT 0,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    delete_time     TIMESTAMP(6)
);

COMMENT ON TABLE sys_dashboard_preset IS '仪表盘预设模板';
COMMENT ON COLUMN sys_dashboard_preset.preset_key      IS '预设唯一标识';
COMMENT ON COLUMN sys_dashboard_preset.admin_only      IS 'true=仅管理员可见';
COMMENT ON COLUMN sys_dashboard_preset.refresh_interval IS '刷新间隔（秒）';
COMMENT ON COLUMN sys_dashboard_preset.widgets         IS 'Widget 布局配置（JSON 数组）';
COMMENT ON COLUMN sys_dashboard_preset.sort_order      IS '展示排序，数字越小越靠前';

CREATE UNIQUE INDEX uk_dashboard_preset_key ON sys_dashboard_preset (preset_key) WHERE deleted = FALSE;
