-- ============================================================
-- AAF v0.1.0 全量 Schema（按子域分段）
-- 公共字段约定：每张表均含 version / org_id / workspace_id
-- ============================================================

-- ============================================================
-- user 子域
-- ============================================================

CREATE TABLE sys_user (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    username         VARCHAR(50)  NOT NULL UNIQUE,
    password         VARCHAR(200) NOT NULL,
    nickname         VARCHAR(100),
    email            VARCHAR(200),
    phone            VARCHAR(20),
    avatar           VARCHAR(500),
    status           INTEGER      NOT NULL DEFAULT 0,
    email_verified   BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_time  TIMESTAMP(6),
    last_login_ip    VARCHAR(50),
    login_fail_count INTEGER      NOT NULL DEFAULT 0,
    lock_time        TIMESTAMP(6),
    archived_at      TIMESTAMP(6),
    create_by        BIGINT,
    create_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by        BIGINT,
    update_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    remark           VARCHAR(255)
);

COMMENT ON TABLE sys_user IS '系统用户';
COMMENT ON COLUMN sys_user.status IS '0 正常 / 1 禁用';
COMMENT ON COLUMN sys_user.email_verified IS '邮箱是否验证';

CREATE UNIQUE INDEX uk_sys_user_email ON sys_user (email) WHERE email IS NOT NULL;

-- ============================================================
-- auth 子域
-- ============================================================

CREATE TABLE sys_user_oauth (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    user_id           BIGINT       NOT NULL REFERENCES sys_user(id),
    provider          VARCHAR(50)  NOT NULL,
    provider_user_id  VARCHAR(200) NOT NULL,
    provider_username VARCHAR(200),
    access_token      VARCHAR(500),
    refresh_token     VARCHAR(500),
    token_expire_time TIMESTAMP(6),
    create_by         BIGINT,
    create_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255),
    CONSTRAINT uk_provider_user UNIQUE (provider, provider_user_id)
);

COMMENT ON TABLE sys_user_oauth IS 'OAuth 第三方账号绑定';

CREATE INDEX idx_user_oauth_user_id ON sys_user_oauth (user_id);

-- ============================================================
-- role 子域
-- ============================================================

CREATE TABLE sys_role (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    code         VARCHAR(50)  NOT NULL UNIQUE,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(500),
    status       INTEGER      NOT NULL DEFAULT 0,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_role IS '系统角色';

CREATE TABLE sys_permission (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    action       VARCHAR(20)  NOT NULL,
    field_access JSONB,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_permission IS '实体权限';
COMMENT ON COLUMN sys_permission.action IS 'read/create/update/delete';
COMMENT ON COLUMN sys_permission.field_access IS '字段级权限 JSONB';

CREATE TABLE sys_role_permission (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER      NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    role_id       BIGINT       NOT NULL,
    permission_id BIGINT       NOT NULL,
    archived_at   TIMESTAMP(6),
    create_by     BIGINT,
    create_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by     BIGINT,
    update_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    remark        VARCHAR(255),
    UNIQUE (role_id, permission_id)
);

COMMENT ON TABLE sys_role_permission IS '角色-权限关联';

CREATE TABLE sys_user_role (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL,
    role_id      BIGINT       NOT NULL,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255),
    UNIQUE (user_id, role_id)
);

COMMENT ON TABLE sys_user_role IS '用户-角色关联';

CREATE TABLE sys_data_access_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    roles        JSONB        NOT NULL DEFAULT '[]',
    condition    JSONB        NOT NULL DEFAULT '{}',
    effect       VARCHAR(10)  NOT NULL DEFAULT 'allow',
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_data_access_rule IS '行级数据权限规则';

CREATE INDEX idx_data_access_rule_entity ON sys_data_access_rule (entity_slug) WHERE deleted = FALSE;


-- ============================================================
-- org 子域
-- ============================================================

CREATE TABLE sys_organization (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    slug         VARCHAR(100) NOT NULL UNIQUE,
    type         VARCHAR(20)  NOT NULL DEFAULT 'team',
    owner_id     BIGINT       NOT NULL,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_organization IS '组织/租户';
COMMENT ON COLUMN sys_organization.type IS 'personal / team';

CREATE TABLE sys_org_member (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT       NOT NULL,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL,
    role         VARCHAR(20)  NOT NULL DEFAULT 'member',
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_org_member IS '组织成员';
COMMENT ON COLUMN sys_org_member.role IS 'owner / admin / member';

CREATE UNIQUE INDEX uk_org_member_org_user ON sys_org_member (org_id, user_id) WHERE deleted = FALSE;

-- ============================================================
-- notify 子域
-- ============================================================

CREATE TABLE sys_notification (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL,
    type         VARCHAR(50)  NOT NULL,
    title        VARCHAR(200) NOT NULL,
    body         TEXT,
    entity_type  VARCHAR(100),
    entity_id    BIGINT,
    is_read      BOOLEAN      NOT NULL DEFAULT FALSE,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_notification IS '系统通知';

CREATE INDEX idx_notification_user ON sys_notification (user_id);
CREATE INDEX idx_notification_user_read ON sys_notification (user_id, is_read);

CREATE TABLE sys_notification_preference (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL UNIQUE,
    preferences  JSONB        NOT NULL DEFAULT '{}',
    quiet_start  TIME,
    quiet_end    TIME,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_notification_preference IS '通知偏好设置';

CREATE TABLE sys_subscription (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    fields       JSONB,
    channels     JSONB,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_subscription IS '字段变更订阅';

CREATE UNIQUE INDEX idx_subscription_unique ON sys_subscription (user_id, entity_type, entity_id) WHERE deleted = FALSE;

CREATE TABLE sys_message_template (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    code         VARCHAR(100) NOT NULL UNIQUE,
    name         VARCHAR(200) NOT NULL,
    channel      VARCHAR(20)  NOT NULL,
    subject      VARCHAR(500),
    content      TEXT         NOT NULL,
    variables    JSONB,
    status       SMALLINT     NOT NULL DEFAULT 1,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_message_template IS '消息模板';
COMMENT ON COLUMN sys_message_template.channel IS 'SMS/EMAIL/INTERNAL';

-- ============================================================
-- log 子域
-- ============================================================

CREATE TABLE sys_operation_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    username        VARCHAR(50),
    module          VARCHAR(50)  NOT NULL,
    type            VARCHAR(20)  NOT NULL,
    description     VARCHAR(500),
    biz_no          VARCHAR(100),
    request_method  VARCHAR(10),
    request_url     VARCHAR(500),
    request_params  TEXT,
    response_result TEXT,
    ip              VARCHAR(50),
    user_agent      VARCHAR(500),
    duration_ms     BIGINT,
    success         BOOLEAN      NOT NULL DEFAULT TRUE,
    error_message   TEXT,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_operation_log IS '操作日志（不可变）';

CREATE INDEX idx_operation_log_user   ON sys_operation_log(user_id);
CREATE INDEX idx_operation_log_module ON sys_operation_log(module);
CREATE INDEX idx_operation_log_time   ON sys_operation_log(create_time);

CREATE TABLE sys_audit_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id        BIGINT,
    workspace_id  BIGINT,
    entity_type   VARCHAR(50)  NOT NULL,
    entity_id     BIGINT       NOT NULL,
    action        VARCHAR(50)  NOT NULL,
    user_id       BIGINT,
    changes       JSONB,
    ip            VARCHAR(45),
    hash          VARCHAR(64),
    previous_hash VARCHAR(64),
    created_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_audit_log IS '审计日志（不可变，链式哈希）';

CREATE RULE audit_log_no_update AS ON UPDATE TO sys_audit_log DO INSTEAD NOTHING;
CREATE RULE audit_log_no_delete AS ON DELETE TO sys_audit_log DO INSTEAD NOTHING;

CREATE INDEX idx_audit_log_entity ON sys_audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_log_user   ON sys_audit_log (user_id);
CREATE INDEX idx_audit_log_time   ON sys_audit_log (created_at);

CREATE TABLE sys_activity_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    action       VARCHAR(50)  NOT NULL,
    changes      JSONB,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_activity_log IS '实体活动日志';

CREATE INDEX idx_activity_log_entity ON sys_activity_log (entity_type, entity_id, create_time DESC);

CREATE TABLE sys_comment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    content      TEXT         NOT NULL,
    mentions     JSONB,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_comment IS '实体评论';

CREATE INDEX idx_comment_entity ON sys_comment (entity_type, entity_id, create_time DESC);

CREATE TABLE sys_record_version (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    ver_number   INTEGER      NOT NULL,
    data         JSONB        NOT NULL,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_record_version IS '实体版本快照';

CREATE INDEX idx_record_version_entity ON sys_record_version (entity_type, entity_id, ver_number DESC);


-- ============================================================
-- chat 子域
-- ============================================================

CREATE TABLE sys_chat_session (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    title        VARCHAR(200),
    type         VARCHAR(30)  NOT NULL DEFAULT 'LIVECHAT',
    status       VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    creator_id   BIGINT       NOT NULL,
    agent_id     VARCHAR(100),
    model_id     VARCHAR(100),
    total_tokens BIGINT       DEFAULT 0,
    -- 会话创建时的用户感知快照（页面、操作、业务上下文）
    context_snapshot JSONB,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_chat_session IS '聊天会话';
COMMENT ON COLUMN sys_chat_session.type IS 'LIVECHAT / AI / IM';
COMMENT ON COLUMN sys_chat_session.context_snapshot IS '会话创建时的用户感知快照（pageId/operation/entityType 等）';

CREATE INDEX idx_sys_chat_session_creator ON sys_chat_session(creator_id) WHERE deleted = FALSE;

CREATE TABLE sys_chat_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    session_id      BIGINT       NOT NULL,
    sender_id       BIGINT       NOT NULL,
    sender_type     VARCHAR(16)  NOT NULL DEFAULT 'HUMAN',
    role            VARCHAR(20)  NOT NULL DEFAULT 'user',
    content         TEXT         NOT NULL,
    -- 消息类型：text / tool_call / tool_result / system_event
    message_type    VARCHAR(20)  NOT NULL DEFAULT 'text',
    -- 行动者类型：human / ai / bot / system
    actor_type      VARCHAR(20)  NOT NULL DEFAULT 'human',
    -- 消息发送时的用户感知上下文（pageId/operation/entityType/entityId 等）
    awareness_context JSONB,
    token_count     INTEGER,
    metadata        TEXT,
    create_by       BIGINT,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE sys_chat_message IS '聊天消息';
COMMENT ON COLUMN sys_chat_message.message_type IS 'text / tool_call / tool_result / system_event';
COMMENT ON COLUMN sys_chat_message.actor_type IS 'human / ai / bot / system';
COMMENT ON COLUMN sys_chat_message.awareness_context IS '消息发送时的用户感知上下文（pageId/operation/entityType 等）';

CREATE INDEX idx_sys_chat_message_session ON sys_chat_message(session_id) WHERE deleted = FALSE;
CREATE INDEX idx_sys_chat_message_type ON sys_chat_message(session_id, message_type) WHERE deleted = FALSE;

-- ============================================================
-- entity 子域（元数据引擎）
-- ============================================================

CREATE TABLE sys_entity_def (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    slug         VARCHAR(100) NOT NULL,
    config       JSONB        NOT NULL DEFAULT '{}',
    builtin      BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_entity_def IS '实体定义';

CREATE UNIQUE INDEX uk_sys_entity_def_slug ON sys_entity_def(slug) WHERE deleted = FALSE;

CREATE TABLE sys_record_template (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    name         VARCHAR(200) NOT NULL,
    field_values JSONB        NOT NULL DEFAULT '{}',
    is_shared    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_record_template IS '记录模板';

CREATE INDEX idx_sys_record_template_slug ON sys_record_template(entity_slug) WHERE deleted = FALSE;

-- ============================================================
-- dashboard 子域
-- ============================================================

CREATE TABLE sys_dashboard (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(500),
    is_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    owner_id     BIGINT       NOT NULL,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_dashboard IS '仪表盘';

CREATE INDEX idx_sys_dashboard_owner ON sys_dashboard(owner_id) WHERE deleted = FALSE;

CREATE TABLE sys_dashboard_widget (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    dashboard_id BIGINT       NOT NULL REFERENCES sys_dashboard(id),
    type         VARCHAR(20)  NOT NULL,
    title        VARCHAR(100) NOT NULL,
    position     JSONB        NOT NULL DEFAULT '{}',
    config       JSONB        NOT NULL DEFAULT '{}',
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_dashboard_widget IS '仪表盘组件';

CREATE INDEX idx_sys_dashboard_widget_dashboard ON sys_dashboard_widget(dashboard_id) WHERE deleted = FALSE;

CREATE TABLE sys_page_def (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    slug         VARCHAR(200) NOT NULL,
    title        VARCHAR(200) NOT NULL,
    config       JSONB        NOT NULL DEFAULT '{}',
    status       VARCHAR(20)  NOT NULL DEFAULT 'draft',
    published_at TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_page_def IS '页面定义（PageEngine）';

CREATE UNIQUE INDEX uk_sys_page_def_slug ON sys_page_def(slug) WHERE deleted = FALSE;


-- ============================================================
-- workflow 子域
-- ============================================================

CREATE TABLE sys_delegation (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    delegator_id BIGINT       NOT NULL,
    delegate_id  BIGINT       NOT NULL,
    start_date   TIMESTAMP(6) NOT NULL,
    end_date     TIMESTAMP(6) NOT NULL,
    process_keys JSONB,
    status       VARCHAR(20)  NOT NULL DEFAULT 'active',
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_delegation IS '审批委托';

CREATE INDEX idx_delegation_delegator ON sys_delegation (delegator_id, status) WHERE deleted = FALSE;
CREATE INDEX idx_delegation_delegate ON sys_delegation (delegate_id, status) WHERE deleted = FALSE;

CREATE TABLE sys_automation_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    entity_slug  VARCHAR(100) NOT NULL,
    trigger_type VARCHAR(50)  NOT NULL,
    conditions   JSONB,
    actions      JSONB        NOT NULL,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_automation_rule IS '自动化规则';

CREATE INDEX idx_automation_rule_entity ON sys_automation_rule (entity_slug, trigger_type) WHERE deleted = FALSE AND enabled = TRUE;

CREATE TABLE sys_automation_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    rule_id      BIGINT       NOT NULL,
    trigger_type VARCHAR(50)  NOT NULL,
    entity_type  VARCHAR(100),
    entity_id    BIGINT,
    status       VARCHAR(20)  NOT NULL,
    error_message TEXT,
    executed_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_automation_log IS '自动化执行日志';

CREATE INDEX idx_automation_log_rule ON sys_automation_log (rule_id) WHERE deleted = FALSE;

CREATE TABLE sys_archive_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    condition    JSONB        NOT NULL DEFAULT '{}',
    after_days   INTEGER      NOT NULL DEFAULT 90,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_archive_rule IS '数据归档规则';

CREATE INDEX idx_archive_rule_entity ON sys_archive_rule (entity_slug) WHERE deleted = FALSE;

-- ============================================================
-- task 子域
-- ============================================================

CREATE TABLE sys_todo (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    assignee_id  BIGINT       NOT NULL,
    title        VARCHAR(200) NOT NULL,
    source_type  VARCHAR(50),
    source_entity VARCHAR(100),
    source_id    BIGINT,
    status       VARCHAR(20)  NOT NULL DEFAULT 'pending',
    due_date     TIMESTAMP(6),
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_todo IS '待办事项';

CREATE INDEX idx_todo_assignee ON sys_todo (assignee_id, status);

CREATE TABLE sys_scheduled_task (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    type         VARCHAR(50)  NOT NULL,
    cron         VARCHAR(50)  NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'active',
    last_run     TIMESTAMP(6),
    next_run     TIMESTAMP(6),
    fail_count   INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_scheduled_task IS '计划任务注册表';

CREATE TABLE sys_task_execution (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER      NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    task_name     VARCHAR(100) NOT NULL,
    task_type     VARCHAR(50)  NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'running',
    start_time    TIMESTAMP(6) NOT NULL,
    end_time      TIMESTAMP(6),
    duration_ms   BIGINT,
    error_message TEXT,
    retry_count   INTEGER      DEFAULT 0,
    create_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_task_execution IS '任务执行记录';

CREATE INDEX idx_task_execution_name ON sys_task_execution(task_name);
CREATE INDEX idx_task_execution_status ON sys_task_execution(status);


-- ============================================================
-- config 子域
-- ============================================================

CREATE TABLE sys_config (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER      NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    category      VARCHAR(64)  NOT NULL,
    config_key    VARCHAR(128) NOT NULL UNIQUE,
    value         TEXT,
    default_value TEXT,
    value_type    VARCHAR(16)  NOT NULL DEFAULT 'string',
    name          VARCHAR(200) NOT NULL,
    description   VARCHAR(500),
    visible       BOOLEAN      NOT NULL DEFAULT TRUE,
    editable      BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by     BIGINT,
    create_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by     BIGINT,
    update_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    remark        VARCHAR(255)
);

COMMENT ON TABLE sys_config IS '系统配置表';
COMMENT ON COLUMN sys_config.category IS '分类（security/user/ai/sms/storage）';
COMMENT ON COLUMN sys_config.config_key IS '配置键，全局唯一（如 user.default_password）';
COMMENT ON COLUMN sys_config.value_type IS '值类型（string/integer/boolean/json）';
COMMENT ON COLUMN sys_config.visible IS '是否前端可见，false=敏感配置不返回 value';
COMMENT ON COLUMN sys_config.editable IS '是否可编辑，false=只读系统参数';
COMMENT ON COLUMN sys_config.default_value IS '默认值，value 为空时使用';

CREATE INDEX idx_sys_config_category ON sys_config (category) WHERE deleted = FALSE;

-- ============================================================
-- sms 子域
-- ============================================================

CREATE TABLE sys_sms_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    code            VARCHAR(64)  NOT NULL UNIQUE,
    name            VARCHAR(100) NOT NULL,
    sign_name       VARCHAR(64),
    api_template_id VARCHAR(64)  NOT NULL,
    params          VARCHAR(255),
    provider        VARCHAR(20),
    status          SMALLINT     NOT NULL DEFAULT 1,
    create_by       BIGINT,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE sys_sms_template IS '短信模板配置';
COMMENT ON COLUMN sys_sms_template.code IS '业务场景编码，调用方使用';
COMMENT ON COLUMN sys_sms_template.sign_name IS '签名，为空则使用系统默认签名';
COMMENT ON COLUMN sys_sms_template.api_template_id IS '厂商模板 ID（阿里云/腾讯云后台审核通过的模板 ID）';
COMMENT ON COLUMN sys_sms_template.params IS '参数名列表（JSON 数组，如 ["code","expireMinutes"]）';
COMMENT ON COLUMN sys_sms_template.provider IS '指定厂商（null=使用系统默认）';

CREATE TABLE sys_sms_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone           VARCHAR(20)  NOT NULL,
    template_code   VARCHAR(100) NOT NULL,
    params          TEXT,
    provider        VARCHAR(20)  NOT NULL,
    send_status     SMALLINT     NOT NULL DEFAULT 0,
    send_time       TIMESTAMP(6),
    api_request_id  VARCHAR(128),
    api_code        VARCHAR(64),
    api_msg         VARCHAR(512),
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_sms_log IS '短信发送日志';
COMMENT ON COLUMN sys_sms_log.send_status IS '0=待发送 1=发送成功 2=发送失败';

CREATE INDEX idx_sys_sms_log_phone ON sys_sms_log (phone, created_at DESC);

-- ============================================================
-- sequence 子域
-- ============================================================

CREATE TABLE sys_sequence (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    name             VARCHAR(100) NOT NULL,
    code             VARCHAR(50)  NOT NULL UNIQUE,
    prefix           VARCHAR(100),
    suffix           VARCHAR(100),
    number_next      BIGINT       NOT NULL DEFAULT 1,
    number_increment INTEGER      NOT NULL DEFAULT 1,
    padding          INTEGER      NOT NULL DEFAULT 4,
    use_date_range   BOOLEAN      NOT NULL DEFAULT FALSE,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by        BIGINT,
    create_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by        BIGINT,
    update_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    remark           VARCHAR(255)
);

COMMENT ON TABLE sys_sequence IS '序列号配置表';
COMMENT ON COLUMN sys_sequence.code IS '序列编码，业务唯一标识';
COMMENT ON COLUMN sys_sequence.prefix IS '前缀模板，支持 %(year)s %(month)s %(day)s 等变量';
COMMENT ON COLUMN sys_sequence.suffix IS '后缀模板';
COMMENT ON COLUMN sys_sequence.number_next IS '下一个值（仅记录，实际由 PG SEQUENCE 驱动）';
COMMENT ON COLUMN sys_sequence.padding IS '数字补零位数，默认 4 位';
COMMENT ON COLUMN sys_sequence.use_date_range IS '是否按日期分段（每月独立计数）';

CREATE TABLE sys_sequence_date_range (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sequence_id BIGINT NOT NULL REFERENCES sys_sequence(id),
    date_from   DATE   NOT NULL,
    date_to     DATE   NOT NULL,
    number_next BIGINT NOT NULL DEFAULT 1
);

COMMENT ON TABLE sys_sequence_date_range IS '序列号日期分段表，按月自动创建';

CREATE INDEX idx_sys_sequence_date_range ON sys_sequence_date_range (sequence_id, date_from, date_to);

-- document 子域已移至 v3__doc_schema.sql
-- autodev 子域已移至 v4__autodev_schema.sql

-- ============================================================
-- knowledge 子域
-- ============================================================

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE knowledge_base (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(200) NOT NULL,
    description     VARCHAR(1000),
    embedding_model VARCHAR(100),
    chunk_strategy  VARCHAR(50),
    chunk_size      INTEGER          DEFAULT 512,
    chunk_overlap   INTEGER          DEFAULT 64,
    status          INTEGER      NOT NULL DEFAULT 0,
    create_by       BIGINT,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE knowledge_base IS '知识库';

CREATE TABLE knowledge_document (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    knowledge_base_id BIGINT       NOT NULL REFERENCES knowledge_base(id),
    title             VARCHAR(500) NOT NULL,
    file_path         VARCHAR(1000),
    file_type         VARCHAR(50),
    file_size         BIGINT,
    content_hash      VARCHAR(64),
    status            INTEGER      NOT NULL DEFAULT 0,
    error_message     VARCHAR(2000),
    chunk_count       INTEGER          DEFAULT 0,
    create_by         BIGINT,
    create_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            TEXT
);

COMMENT ON TABLE knowledge_document IS '知识库文档';

CREATE INDEX idx_knowledge_document_base_id ON knowledge_document(knowledge_base_id);

CREATE TABLE knowledge_chunk (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id       BIGINT       NOT NULL REFERENCES knowledge_document(id),
    knowledge_base_id BIGINT       NOT NULL REFERENCES knowledge_base(id),
    content           TEXT         NOT NULL,
    chunk_index       INTEGER          NOT NULL DEFAULT 0,
    metadata          JSONB,
    token_count       INTEGER          DEFAULT 0,
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE knowledge_chunk IS '知识库文本块';

CREATE INDEX idx_knowledge_chunk_document_id ON knowledge_chunk(document_id);
CREATE INDEX idx_knowledge_chunk_base_id ON knowledge_chunk(knowledge_base_id);

CREATE TABLE knowledge_embedding (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    content           TEXT,
    metadata          JSONB,
    embedding         vector(1536),
    chunk_id          BIGINT       REFERENCES knowledge_chunk(id),
    knowledge_base_id BIGINT       REFERENCES knowledge_base(id),
    model_name        VARCHAR(50),
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE knowledge_embedding IS '知识库向量嵌入（兼容 Spring AI VectorStore）';

CREATE INDEX idx_knowledge_embedding_chunk_id ON knowledge_embedding(chunk_id);
CREATE INDEX idx_knowledge_embedding_base_id ON knowledge_embedding(knowledge_base_id);
CREATE INDEX idx_knowledge_embedding_hnsw ON knowledge_embedding
    USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- ============================================================
-- memory 子域
-- ============================================================

CREATE TABLE memory_atom (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          BIGINT                   NOT NULL,
    scope            VARCHAR(20)              NOT NULL,
    content          TEXT                     NOT NULL,
    embedding        vector(1536),
    event_time       TIMESTAMP WITH TIME ZONE NOT NULL,
    valid_from       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    valid_to         TIMESTAMP WITH TIME ZONE,
    weight           DOUBLE PRECISION         NOT NULL DEFAULT 0.5,
    access_count     INTEGER                      NOT NULL DEFAULT 0,
    last_accessed_at TIMESTAMP WITH TIME ZONE,
    tags             TEXT[],
    metadata         JSONB,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_memory_atom_user_scope ON memory_atom(user_id, scope);
CREATE INDEX idx_memory_atom_user_event ON memory_atom(user_id, event_time DESC);
CREATE INDEX idx_memory_atom_user_weight ON memory_atom(user_id, weight DESC);
CREATE INDEX idx_memory_atom_tags ON memory_atom USING GIN(tags);
CREATE INDEX idx_memory_atom_embedding ON memory_atom
    USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

CREATE TABLE memory_relation (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id     UUID             NOT NULL REFERENCES memory_atom(id) ON DELETE CASCADE,
    target_id     UUID             NOT NULL REFERENCES memory_atom(id) ON DELETE CASCADE,
    relation_type VARCHAR(50)      NOT NULL,
    weight        DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_memory_relation_source ON memory_relation(source_id);
CREATE INDEX idx_memory_relation_target ON memory_relation(target_id);


-- ============================================================
-- dict 子域
-- ============================================================

CREATE TABLE sys_dict_type (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    type         VARCHAR(100) NOT NULL,
    status       INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_dict_type IS '字典类型';
COMMENT ON COLUMN sys_dict_type.name IS '字典名称';
COMMENT ON COLUMN sys_dict_type.type IS '字典类型编码';
COMMENT ON COLUMN sys_dict_type.status IS '0 正常 / 1 禁用';

CREATE UNIQUE INDEX uk_sys_dict_type_type ON sys_dict_type (type) WHERE deleted = FALSE;

CREATE TABLE sys_dict_data (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    dict_type    VARCHAR(100) NOT NULL,
    label        VARCHAR(100) NOT NULL,
    value        VARCHAR(100) NOT NULL,
    sort         INTEGER      NOT NULL DEFAULT 0,
    status       INTEGER      NOT NULL DEFAULT 0,
    color_type   VARCHAR(50),
    css_class    VARCHAR(100),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_dict_data IS '字典数据';
COMMENT ON COLUMN sys_dict_data.dict_type IS '字典类型编码（关联 sys_dict_type.type）';
COMMENT ON COLUMN sys_dict_data.label IS '字典标签';
COMMENT ON COLUMN sys_dict_data.value IS '字典键值';
COMMENT ON COLUMN sys_dict_data.sort IS '显示排序';
COMMENT ON COLUMN sys_dict_data.status IS '0 正常 / 1 禁用';
COMMENT ON COLUMN sys_dict_data.color_type IS '标签颜色（default/primary/success/info/warning/danger）';
COMMENT ON COLUMN sys_dict_data.css_class IS '自定义 CSS 样式';

CREATE INDEX idx_sys_dict_data_dict_type ON sys_dict_data (dict_type);


-- ============================================================
-- 动态数据表元数据 Schema
-- 存储用户自定义表的定义（表名、列定义），实际数据表通过 DDL 动态创建
-- ============================================================

CREATE TABLE data_table_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(64)  NOT NULL UNIQUE,
    display_name    VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    table_name      VARCHAR(80)  NOT NULL UNIQUE,  -- 实际 PG 表名（data_{slug}）
    org_id          BIGINT,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ
);

COMMENT ON TABLE data_table_definition IS '动态数据表定义';

CREATE TABLE data_column_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id        BIGINT       NOT NULL REFERENCES data_table_definition(id) ON DELETE CASCADE,
    name            VARCHAR(64)  NOT NULL,
    display_name    VARCHAR(128),
    column_type     VARCHAR(32)  NOT NULL,  -- string/text/integer/decimal/boolean/timestamp/json
    nullable        BOOLEAN      NOT NULL DEFAULT TRUE,
    unique_col      BOOLEAN      NOT NULL DEFAULT FALSE,
    default_value   VARCHAR(256),
    sort_order      INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE data_column_definition IS '动态数据表列定义';
CREATE INDEX idx_data_column_table ON data_column_definition(table_id, sort_order);


-- ============================================================
-- 数据摄入 API Key
-- ============================================================

CREATE TABLE data_api_key (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_hash        VARCHAR(64)  NOT NULL UNIQUE,
    key_prefix      VARCHAR(16)  NOT NULL,
    name            VARCHAR(128) NOT NULL,
    user_id         BIGINT       NOT NULL,
    allowed_tables  VARCHAR(1024),
    permissions     VARCHAR(64)  NOT NULL DEFAULT 'ingest',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at      TIMESTAMPTZ,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    last_used_at    TIMESTAMPTZ
);

COMMENT ON TABLE data_api_key IS '数据摄入 API Key';
CREATE INDEX idx_data_api_key_user ON data_api_key(user_id);

