-- ============================================================
-- AAF v0.1.0 全量 Schema（按子域分段）
-- 公共字段约定：每张表均含 version / org_id / workspace_id
-- ============================================================

-- ============================================================
-- user 子域
-- ============================================================

CREATE TABLE sys_user (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    username         VARCHAR(50)  NOT NULL UNIQUE,
    password         VARCHAR(200) NOT NULL,
    nickname         VARCHAR(100),
    email            VARCHAR(200),
    phone            VARCHAR(20),
    avatar           VARCHAR(500),
    status           INTEGER      NOT NULL DEFAULT 0,
    email_verified   BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_time  TIMESTAMP(6),
    last_login_ip    VARCHAR(50),
    login_fail_count INTEGER      NOT NULL DEFAULT 0,
    lock_time        TIMESTAMP(6),
    archived_at      TIMESTAMP(6),
    create_by        BIGINT,
    create_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by        BIGINT,
    update_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    remark           VARCHAR(255)
);

COMMENT ON TABLE sys_user IS '系统用户';
COMMENT ON COLUMN sys_user.status IS '0 正常 / 1 禁用';
COMMENT ON COLUMN sys_user.email_verified IS '邮箱是否验证';

CREATE UNIQUE INDEX uk_sys_user_email ON sys_user (email) WHERE email IS NOT NULL;

-- ============================================================
-- auth 子域
-- ============================================================

CREATE TABLE sys_user_oauth (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    user_id           BIGINT       NOT NULL REFERENCES sys_user(id),
    provider          VARCHAR(50)  NOT NULL,
    provider_user_id  VARCHAR(200) NOT NULL,
    provider_username VARCHAR(200),
    access_token      VARCHAR(500),
    refresh_token     VARCHAR(500),
    token_expire_time TIMESTAMP(6),
    create_by         BIGINT,
    create_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255),
    CONSTRAINT uk_provider_user UNIQUE (provider, provider_user_id)
);

COMMENT ON TABLE sys_user_oauth IS 'OAuth 第三方账号绑定';

CREATE INDEX idx_user_oauth_user_id ON sys_user_oauth (user_id);

-- ============================================================
-- role 子域
-- ============================================================

CREATE TABLE sys_role (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    code         VARCHAR(50)  NOT NULL UNIQUE,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(500),
    status       INTEGER      NOT NULL DEFAULT 0,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_role IS '系统角色';

CREATE TABLE sys_permission (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    action       VARCHAR(20)  NOT NULL,
    field_access JSONB,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_permission IS '实体权限';
COMMENT ON COLUMN sys_permission.action IS 'read/create/update/delete';
COMMENT ON COLUMN sys_permission.field_access IS '字段级权限 JSONB';

CREATE TABLE sys_role_permission (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER      NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    role_id       BIGINT       NOT NULL,
    permission_id BIGINT       NOT NULL,
    archived_at   TIMESTAMP(6),
    create_by     BIGINT,
    create_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by     BIGINT,
    update_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    remark        VARCHAR(255),
    UNIQUE (role_id, permission_id)
);

COMMENT ON TABLE sys_role_permission IS '角色-权限关联';

CREATE TABLE sys_user_role (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL,
    role_id      BIGINT       NOT NULL,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255),
    UNIQUE (user_id, role_id)
);

COMMENT ON TABLE sys_user_role IS '用户-角色关联';

CREATE TABLE sys_data_access_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    roles        JSONB        NOT NULL DEFAULT '[]',
    condition    JSONB        NOT NULL DEFAULT '{}',
    effect       VARCHAR(10)  NOT NULL DEFAULT 'allow',
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_data_access_rule IS '行级数据权限规则';

CREATE INDEX idx_data_access_rule_entity ON sys_data_access_rule (entity_slug) WHERE deleted = FALSE;


-- ============================================================
-- org 子域
-- ============================================================

CREATE TABLE sys_organization (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    slug         VARCHAR(100) NOT NULL UNIQUE,
    type         VARCHAR(20)  NOT NULL DEFAULT 'team',
    owner_id     BIGINT       NOT NULL,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_organization IS '组织/租户';
COMMENT ON COLUMN sys_organization.type IS 'personal / team';

CREATE TABLE sys_org_member (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT       NOT NULL,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL,
    role         VARCHAR(20)  NOT NULL DEFAULT 'member',
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_org_member IS '组织成员';
COMMENT ON COLUMN sys_org_member.role IS 'owner / admin / member';

CREATE UNIQUE INDEX uk_org_member_org_user ON sys_org_member (org_id, user_id) WHERE deleted = FALSE;

-- ============================================================
-- notify 子域
-- ============================================================

CREATE TABLE sys_notification (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL,
    type         VARCHAR(50)  NOT NULL,
    title        VARCHAR(200) NOT NULL,
    body         TEXT,
    entity_type  VARCHAR(100),
    entity_id    BIGINT,
    is_read      BOOLEAN      NOT NULL DEFAULT FALSE,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_notification IS '系统通知';

CREATE INDEX idx_notification_user ON sys_notification (user_id);
CREATE INDEX idx_notification_user_read ON sys_notification (user_id, is_read);

CREATE TABLE sys_notification_preference (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL UNIQUE,
    preferences  JSONB        NOT NULL DEFAULT '{}',
    quiet_start  TIME,
    quiet_end    TIME,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_notification_preference IS '通知偏好设置';

CREATE TABLE sys_subscription (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    fields       JSONB,
    channels     JSONB,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_subscription IS '字段变更订阅';

CREATE UNIQUE INDEX idx_subscription_unique ON sys_subscription (user_id, entity_type, entity_id) WHERE deleted = FALSE;

CREATE TABLE sys_message_template (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    code         VARCHAR(100) NOT NULL UNIQUE,
    name         VARCHAR(200) NOT NULL,
    channel      VARCHAR(20)  NOT NULL,
    subject      VARCHAR(500),
    content      TEXT         NOT NULL,
    variables    JSONB,
    status       SMALLINT     NOT NULL DEFAULT 1,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_message_template IS '消息模板';
COMMENT ON COLUMN sys_message_template.channel IS 'SMS/EMAIL/INTERNAL';

-- ============================================================
-- log 子域
-- ============================================================

CREATE TABLE sys_operation_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    username        VARCHAR(50),
    module          VARCHAR(50)  NOT NULL,
    type            VARCHAR(20)  NOT NULL,
    description     VARCHAR(500),
    biz_no          VARCHAR(100),
    request_method  VARCHAR(10),
    request_url     VARCHAR(500),
    request_params  TEXT,
    response_result TEXT,
    ip              VARCHAR(50),
    user_agent      VARCHAR(500),
    duration_ms     BIGINT,
    success         BOOLEAN      NOT NULL DEFAULT TRUE,
    error_message   TEXT,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_operation_log IS '操作日志（不可变）';

CREATE INDEX idx_operation_log_user   ON sys_operation_log(user_id);
CREATE INDEX idx_operation_log_module ON sys_operation_log(module);
CREATE INDEX idx_operation_log_time   ON sys_operation_log(create_time);

CREATE TABLE sys_audit_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id        BIGINT,
    workspace_id  BIGINT,
    entity_type   VARCHAR(50)  NOT NULL,
    entity_id     BIGINT       NOT NULL,
    action        VARCHAR(50)  NOT NULL,
    user_id       BIGINT,
    changes       JSONB,
    ip            VARCHAR(45),
    hash          VARCHAR(64),
    previous_hash VARCHAR(64),
    created_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_audit_log IS '审计日志（不可变，链式哈希）';

CREATE RULE audit_log_no_update AS ON UPDATE TO sys_audit_log DO INSTEAD NOTHING;
CREATE RULE audit_log_no_delete AS ON DELETE TO sys_audit_log DO INSTEAD NOTHING;

CREATE INDEX idx_audit_log_entity ON sys_audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_log_user   ON sys_audit_log (user_id);
CREATE INDEX idx_audit_log_time   ON sys_audit_log (created_at);

CREATE TABLE sys_activity_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    action       VARCHAR(50)  NOT NULL,
    changes      JSONB,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_activity_log IS '实体活动日志';

CREATE INDEX idx_activity_log_entity ON sys_activity_log (entity_type, entity_id, create_time DESC);

CREATE TABLE sys_comment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    content      TEXT         NOT NULL,
    mentions     JSONB,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_comment IS '实体评论';

CREATE INDEX idx_comment_entity ON sys_comment (entity_type, entity_id, create_time DESC);

CREATE TABLE sys_record_version (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    ver_number   INTEGER      NOT NULL,
    data         JSONB        NOT NULL,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_record_version IS '实体版本快照';

CREATE INDEX idx_record_version_entity ON sys_record_version (entity_type, entity_id, ver_number DESC);


-- ============================================================
-- chat 子域
-- ============================================================

CREATE TABLE sys_chat_session (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    title        VARCHAR(200),
    type         VARCHAR(30)  NOT NULL DEFAULT 'LIVECHAT',
    status       VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    creator_id   BIGINT       NOT NULL,
    agent_id     VARCHAR(100),
    model_id     VARCHAR(100),
    total_tokens BIGINT       DEFAULT 0,
    -- 会话创建时的用户感知快照（页面、操作、业务上下文）
    context_snapshot JSONB,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_chat_session IS '聊天会话';
COMMENT ON COLUMN sys_chat_session.type IS 'LIVECHAT / AI / IM';
COMMENT ON COLUMN sys_chat_session.context_snapshot IS '会话创建时的用户感知快照（pageId/operation/entityType 等）';

CREATE INDEX idx_sys_chat_session_creator ON sys_chat_session(creator_id) WHERE deleted = FALSE;

CREATE TABLE sys_chat_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    session_id      BIGINT       NOT NULL,
    sender_id       BIGINT       NOT NULL,
    sender_type     VARCHAR(16)  NOT NULL DEFAULT 'HUMAN',
    role            VARCHAR(20)  NOT NULL DEFAULT 'user',
    content         TEXT         NOT NULL,
    -- 消息类型：text / tool_call / tool_result / system_event
    message_type    VARCHAR(20)  NOT NULL DEFAULT 'text',
    -- 行动者类型：human / ai / bot / system
    actor_type      VARCHAR(20)  NOT NULL DEFAULT 'human',
    -- 消息发送时的用户感知上下文（pageId/operation/entityType/entityId 等）
    awareness_context JSONB,
    token_count     INTEGER,
    metadata        TEXT,
    create_by       BIGINT,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE sys_chat_message IS '聊天消息';
COMMENT ON COLUMN sys_chat_message.message_type IS 'text / tool_call / tool_result / system_event';
COMMENT ON COLUMN sys_chat_message.actor_type IS 'human / ai / bot / system';
COMMENT ON COLUMN sys_chat_message.awareness_context IS '消息发送时的用户感知上下文（pageId/operation/entityType 等）';

CREATE INDEX idx_sys_chat_message_session ON sys_chat_message(session_id) WHERE deleted = FALSE;
CREATE INDEX idx_sys_chat_message_type ON sys_chat_message(session_id, message_type) WHERE deleted = FALSE;

-- ============================================================
-- entity 子域（元数据引擎）
-- ============================================================

CREATE TABLE sys_entity_def (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    slug         VARCHAR(100) NOT NULL,
    config       JSONB        NOT NULL DEFAULT '{}',
    builtin      BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_entity_def IS '实体定义';

CREATE UNIQUE INDEX uk_sys_entity_def_slug ON sys_entity_def(slug) WHERE deleted = FALSE;

CREATE TABLE sys_record_template (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    name         VARCHAR(200) NOT NULL,
    field_values JSONB        NOT NULL DEFAULT '{}',
    is_shared    BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_record_template IS '记录模板';

CREATE INDEX idx_sys_record_template_slug ON sys_record_template(entity_slug) WHERE deleted = FALSE;

-- ============================================================
-- dashboard 子域
-- ============================================================

CREATE TABLE sys_dashboard (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(500),
    is_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    owner_id     BIGINT       NOT NULL,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_dashboard IS '仪表盘';

CREATE INDEX idx_sys_dashboard_owner ON sys_dashboard(owner_id) WHERE deleted = FALSE;

CREATE TABLE sys_dashboard_widget (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    dashboard_id BIGINT       NOT NULL REFERENCES sys_dashboard(id),
    type         VARCHAR(20)  NOT NULL,
    title        VARCHAR(100) NOT NULL,
    position     JSONB        NOT NULL DEFAULT '{}',
    config       JSONB        NOT NULL DEFAULT '{}',
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_dashboard_widget IS '仪表盘组件';

CREATE INDEX idx_sys_dashboard_widget_dashboard ON sys_dashboard_widget(dashboard_id) WHERE deleted = FALSE;

CREATE TABLE sys_page_def (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    slug         VARCHAR(200) NOT NULL,
    title        VARCHAR(200) NOT NULL,
    config       JSONB        NOT NULL DEFAULT '{}',
    status       VARCHAR(20)  NOT NULL DEFAULT 'draft',
    published_at TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_page_def IS '页面定义（PageEngine）';

CREATE UNIQUE INDEX uk_sys_page_def_slug ON sys_page_def(slug) WHERE deleted = FALSE;


-- ============================================================
-- workflow 子域
-- ============================================================

CREATE TABLE sys_delegation (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    delegator_id BIGINT       NOT NULL,
    delegate_id  BIGINT       NOT NULL,
    start_date   TIMESTAMP(6) NOT NULL,
    end_date     TIMESTAMP(6) NOT NULL,
    process_keys JSONB,
    status       VARCHAR(20)  NOT NULL DEFAULT 'active',
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_delegation IS '审批委托';

CREATE INDEX idx_delegation_delegator ON sys_delegation (delegator_id, status) WHERE deleted = FALSE;
CREATE INDEX idx_delegation_delegate ON sys_delegation (delegate_id, status) WHERE deleted = FALSE;

CREATE TABLE sys_automation_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    entity_slug  VARCHAR(100) NOT NULL,
    trigger_type VARCHAR(50)  NOT NULL,
    conditions   JSONB,
    actions      JSONB        NOT NULL,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_automation_rule IS '自动化规则';

CREATE INDEX idx_automation_rule_entity ON sys_automation_rule (entity_slug, trigger_type) WHERE deleted = FALSE AND enabled = TRUE;

CREATE TABLE sys_automation_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    rule_id      BIGINT       NOT NULL,
    trigger_type VARCHAR(50)  NOT NULL,
    entity_type  VARCHAR(100),
    entity_id    BIGINT,
    status       VARCHAR(20)  NOT NULL,
    error_message TEXT,
    executed_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_automation_log IS '自动化执行日志';

CREATE INDEX idx_automation_log_rule ON sys_automation_log (rule_id) WHERE deleted = FALSE;

CREATE TABLE sys_archive_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    condition    JSONB        NOT NULL DEFAULT '{}',
    after_days   INTEGER      NOT NULL DEFAULT 90,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_archive_rule IS '数据归档规则';

CREATE INDEX idx_archive_rule_entity ON sys_archive_rule (entity_slug) WHERE deleted = FALSE;

-- ============================================================
-- task 子域
-- ============================================================

CREATE TABLE sys_todo (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    assignee_id  BIGINT       NOT NULL,
    title        VARCHAR(200) NOT NULL,
    source_type  VARCHAR(50),
    source_entity VARCHAR(100),
    source_id    BIGINT,
    status       VARCHAR(20)  NOT NULL DEFAULT 'pending',
    due_date     TIMESTAMP(6),
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_todo IS '待办事项';

CREATE INDEX idx_todo_assignee ON sys_todo (assignee_id, status);

CREATE TABLE sys_scheduled_task (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    type         VARCHAR(50)  NOT NULL,
    cron         VARCHAR(50)  NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'active',
    last_run     TIMESTAMP(6),
    next_run     TIMESTAMP(6),
    fail_count   INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_scheduled_task IS '计划任务注册表';

CREATE TABLE sys_task_execution (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER      NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    task_name     VARCHAR(100) NOT NULL,
    task_type     VARCHAR(50)  NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'running',
    start_time    TIMESTAMP(6) NOT NULL,
    end_time      TIMESTAMP(6),
    duration_ms   BIGINT,
    error_message TEXT,
    retry_count   INTEGER      DEFAULT 0,
    create_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_task_execution IS '任务执行记录';

CREATE INDEX idx_task_execution_name ON sys_task_execution(task_name);
CREATE INDEX idx_task_execution_status ON sys_task_execution(status);


-- ============================================================
-- config 子域
-- ============================================================

CREATE TABLE sys_config (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER      NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    category      VARCHAR(64)  NOT NULL,
    config_key    VARCHAR(128) NOT NULL UNIQUE,
    value         TEXT,
    default_value TEXT,
    value_type    VARCHAR(16)  NOT NULL DEFAULT 'string',
    name          VARCHAR(200) NOT NULL,
    description   VARCHAR(500),
    visible       BOOLEAN      NOT NULL DEFAULT TRUE,
    editable      BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by     BIGINT,
    create_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by     BIGINT,
    update_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    remark        VARCHAR(255)
);

COMMENT ON TABLE sys_config IS '系统配置表';
COMMENT ON COLUMN sys_config.category IS '分类（security/user/ai/sms/storage）';
COMMENT ON COLUMN sys_config.config_key IS '配置键，全局唯一（如 user.default_password）';
COMMENT ON COLUMN sys_config.value_type IS '值类型（string/integer/boolean/json）';
COMMENT ON COLUMN sys_config.visible IS '是否前端可见，false=敏感配置不返回 value';
COMMENT ON COLUMN sys_config.editable IS '是否可编辑，false=只读系统参数';
COMMENT ON COLUMN sys_config.default_value IS '默认值，value 为空时使用';

CREATE INDEX idx_sys_config_category ON sys_config (category) WHERE deleted = FALSE;

-- ============================================================
-- sms 子域
-- ============================================================

CREATE TABLE sys_sms_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    code            VARCHAR(64)  NOT NULL UNIQUE,
    name            VARCHAR(100) NOT NULL,
    sign_name       VARCHAR(64),
    api_template_id VARCHAR(64)  NOT NULL,
    params          VARCHAR(255),
    provider        VARCHAR(20),
    status          SMALLINT     NOT NULL DEFAULT 1,
    create_by       BIGINT,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE sys_sms_template IS '短信模板配置';
COMMENT ON COLUMN sys_sms_template.code IS '业务场景编码，调用方使用';
COMMENT ON COLUMN sys_sms_template.sign_name IS '签名，为空则使用系统默认签名';
COMMENT ON COLUMN sys_sms_template.api_template_id IS '厂商模板 ID（阿里云/腾讯云后台审核通过的模板 ID）';
COMMENT ON COLUMN sys_sms_template.params IS '参数名列表（JSON 数组，如 ["code","expireMinutes"]）';
COMMENT ON COLUMN sys_sms_template.provider IS '指定厂商（null=使用系统默认）';

CREATE TABLE sys_sms_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone           VARCHAR(20)  NOT NULL,
    template_code   VARCHAR(100) NOT NULL,
    params          TEXT,
    provider        VARCHAR(20)  NOT NULL,
    send_status     SMALLINT     NOT NULL DEFAULT 0,
    send_time       TIMESTAMP(6),
    api_request_id  VARCHAR(128),
    api_code        VARCHAR(64),
    api_msg         VARCHAR(512),
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_sms_log IS '短信发送日志';
COMMENT ON COLUMN sys_sms_log.send_status IS '0=待发送 1=发送成功 2=发送失败';

CREATE INDEX idx_sys_sms_log_phone ON sys_sms_log (phone, created_at DESC);

-- ============================================================
-- sequence 子域
-- ============================================================

CREATE TABLE sys_sequence (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    name             VARCHAR(100) NOT NULL,
    code             VARCHAR(50)  NOT NULL UNIQUE,
    prefix           VARCHAR(100),
    suffix           VARCHAR(100),
    number_next      BIGINT       NOT NULL DEFAULT 1,
    number_increment INTEGER      NOT NULL DEFAULT 1,
    padding          INTEGER      NOT NULL DEFAULT 4,
    use_date_range   BOOLEAN      NOT NULL DEFAULT FALSE,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    create_by        BIGINT,
    create_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by        BIGINT,
    update_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    remark           VARCHAR(255)
);

COMMENT ON TABLE sys_sequence IS '序列号配置表';
COMMENT ON COLUMN sys_sequence.code IS '序列编码，业务唯一标识';
COMMENT ON COLUMN sys_sequence.prefix IS '前缀模板，支持 %(year)s %(month)s %(day)s 等变量';
COMMENT ON COLUMN sys_sequence.suffix IS '后缀模板';
COMMENT ON COLUMN sys_sequence.number_next IS '下一个值（仅记录，实际由 PG SEQUENCE 驱动）';
COMMENT ON COLUMN sys_sequence.padding IS '数字补零位数，默认 4 位';
COMMENT ON COLUMN sys_sequence.use_date_range IS '是否按日期分段（每月独立计数）';

CREATE TABLE sys_sequence_date_range (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sequence_id BIGINT NOT NULL REFERENCES sys_sequence(id),
    date_from   DATE   NOT NULL,
    date_to     DATE   NOT NULL,
    number_next BIGINT NOT NULL DEFAULT 1
);

COMMENT ON TABLE sys_sequence_date_range IS '序列号日期分段表，按月自动创建';

CREATE INDEX idx_sys_sequence_date_range ON sys_sequence_date_range (sequence_id, date_from, date_to);

-- document 子域已移至 v3__doc_schema.sql
-- autodev 子域已移至 v4__autodev_schema.sql

-- ============================================================
-- knowledge 子域
-- ============================================================

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE knowledge_base (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(200) NOT NULL,
    description     VARCHAR(1000),
    embedding_model VARCHAR(100),
    chunk_strategy  VARCHAR(50),
    chunk_size      INTEGER          DEFAULT 512,
    chunk_overlap   INTEGER          DEFAULT 64,
    status          INTEGER      NOT NULL DEFAULT 0,
    create_by       BIGINT,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE knowledge_base IS '知识库';

CREATE TABLE knowledge_document (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    knowledge_base_id BIGINT       NOT NULL REFERENCES knowledge_base(id),
    title             VARCHAR(500) NOT NULL,
    file_path         VARCHAR(1000),
    file_type         VARCHAR(50),
    file_size         BIGINT,
    content_hash      VARCHAR(64),
    status            INTEGER      NOT NULL DEFAULT 0,
    error_message     VARCHAR(2000),
    chunk_count       INTEGER          DEFAULT 0,
    create_by         BIGINT,
    create_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            TEXT
);

COMMENT ON TABLE knowledge_document IS '知识库文档';

CREATE INDEX idx_knowledge_document_base_id ON knowledge_document(knowledge_base_id);

CREATE TABLE knowledge_chunk (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id       BIGINT       NOT NULL REFERENCES knowledge_document(id),
    knowledge_base_id BIGINT       NOT NULL REFERENCES knowledge_base(id),
    content           TEXT         NOT NULL,
    chunk_index       INTEGER          NOT NULL DEFAULT 0,
    metadata          JSONB,
    token_count       INTEGER          DEFAULT 0,
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE knowledge_chunk IS '知识库文本块';

CREATE INDEX idx_knowledge_chunk_document_id ON knowledge_chunk(document_id);
CREATE INDEX idx_knowledge_chunk_base_id ON knowledge_chunk(knowledge_base_id);

CREATE TABLE knowledge_embedding (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    content           TEXT,
    metadata          JSONB,
    embedding         vector(1536),
    chunk_id          BIGINT       REFERENCES knowledge_chunk(id),
    knowledge_base_id BIGINT       REFERENCES knowledge_base(id),
    model_name        VARCHAR(50),
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE knowledge_embedding IS '知识库向量嵌入（兼容 Spring AI VectorStore）';

CREATE INDEX idx_knowledge_embedding_chunk_id ON knowledge_embedding(chunk_id);
CREATE INDEX idx_knowledge_embedding_base_id ON knowledge_embedding(knowledge_base_id);
CREATE INDEX idx_knowledge_embedding_hnsw ON knowledge_embedding
    USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- ============================================================
-- memory 子域
-- ============================================================

CREATE TABLE memory_atom (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          BIGINT                   NOT NULL,
    scope            VARCHAR(20)              NOT NULL,
    content          TEXT                     NOT NULL,
    embedding        vector(1536),
    event_time       TIMESTAMP WITH TIME ZONE NOT NULL,
    valid_from       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    valid_to         TIMESTAMP WITH TIME ZONE,
    weight           DOUBLE PRECISION         NOT NULL DEFAULT 0.5,
    access_count     INTEGER                      NOT NULL DEFAULT 0,
    last_accessed_at TIMESTAMP WITH TIME ZONE,
    tags             TEXT[],
    metadata         JSONB,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_memory_atom_user_scope ON memory_atom(user_id, scope);
CREATE INDEX idx_memory_atom_user_event ON memory_atom(user_id, event_time DESC);
CREATE INDEX idx_memory_atom_user_weight ON memory_atom(user_id, weight DESC);
CREATE INDEX idx_memory_atom_tags ON memory_atom USING GIN(tags);
CREATE INDEX idx_memory_atom_embedding ON memory_atom
    USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

CREATE TABLE memory_relation (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id     UUID             NOT NULL REFERENCES memory_atom(id) ON DELETE CASCADE,
    target_id     UUID             NOT NULL REFERENCES memory_atom(id) ON DELETE CASCADE,
    relation_type VARCHAR(50)      NOT NULL,
    weight        DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_memory_relation_source ON memory_relation(source_id);
CREATE INDEX idx_memory_relation_target ON memory_relation(target_id);


-- ============================================================
-- dict 子域
-- ============================================================

CREATE TABLE sys_dict_type (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    type         VARCHAR(100) NOT NULL,
    status       INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_dict_type IS '字典类型';
COMMENT ON COLUMN sys_dict_type.name IS '字典名称';
COMMENT ON COLUMN sys_dict_type.type IS '字典类型编码';
COMMENT ON COLUMN sys_dict_type.status IS '0 正常 / 1 禁用';

CREATE UNIQUE INDEX uk_sys_dict_type_type ON sys_dict_type (type) WHERE deleted = FALSE;

CREATE TABLE sys_dict_data (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    dict_type    VARCHAR(100) NOT NULL,
    label        VARCHAR(100) NOT NULL,
    value        VARCHAR(100) NOT NULL,
    sort         INTEGER      NOT NULL DEFAULT 0,
    status       INTEGER      NOT NULL DEFAULT 0,
    color_type   VARCHAR(50),
    css_class    VARCHAR(100),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_dict_data IS '字典数据';
COMMENT ON COLUMN sys_dict_data.dict_type IS '字典类型编码（关联 sys_dict_type.type）';
COMMENT ON COLUMN sys_dict_data.label IS '字典标签';
COMMENT ON COLUMN sys_dict_data.value IS '字典键值';
COMMENT ON COLUMN sys_dict_data.sort IS '显示排序';
COMMENT ON COLUMN sys_dict_data.status IS '0 正常 / 1 禁用';
COMMENT ON COLUMN sys_dict_data.color_type IS '标签颜色（default/primary/success/info/warning/danger）';
COMMENT ON COLUMN sys_dict_data.css_class IS '自定义 CSS 样式';

CREATE INDEX idx_sys_dict_data_dict_type ON sys_dict_data (dict_type);


-- ============================================================
-- 动态数据表元数据 Schema
-- 存储用户自定义表的定义（表名、列定义），实际数据表通过 DDL 动态创建
-- ============================================================

CREATE TABLE data_table_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(64)  NOT NULL UNIQUE,
    display_name    VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    table_name      VARCHAR(80)  NOT NULL UNIQUE,  -- 实际 PG 表名（data_{slug}）
    org_id          BIGINT,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ
);

COMMENT ON TABLE data_table_definition IS '动态数据表定义';

CREATE TABLE data_column_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id        BIGINT       NOT NULL REFERENCES data_table_definition(id) ON DELETE CASCADE,
    name            VARCHAR(64)  NOT NULL,
    display_name    VARCHAR(128),
    column_type     VARCHAR(32)  NOT NULL,  -- string/text/integer/decimal/boolean/timestamp/json
    nullable        BOOLEAN      NOT NULL DEFAULT TRUE,
    unique_col      BOOLEAN      NOT NULL DEFAULT FALSE,
    default_value   VARCHAR(256),
    sort_order      INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE data_column_definition IS '动态数据表列定义';
CREATE INDEX idx_data_column_table ON data_column_definition(table_id, sort_order);


-- ============================================================
-- 数据摄入 API Key
-- ============================================================

CREATE TABLE data_api_key (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_hash        VARCHAR(64)  NOT NULL UNIQUE,
    key_prefix      VARCHAR(16)  NOT NULL,
    name            VARCHAR(128) NOT NULL,
    user_id         BIGINT       NOT NULL,
    allowed_tables  VARCHAR(1024),
    permissions     VARCHAR(64)  NOT NULL DEFAULT 'ingest',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at      TIMESTAMPTZ,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    last_used_at    TIMESTAMPTZ
);

COMMENT ON TABLE data_api_key IS '数据摄入 API Key';
CREATE INDEX idx_data_api_key_user ON data_api_key(user_id);



-- ============================================================
-- permission 子域（菜单/按钮/接口权限点）
-- ============================================================

CREATE TABLE sys_menu_permission (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    code         VARCHAR(100) NOT NULL UNIQUE,
    type         VARCHAR(20)  NOT NULL,
    parent_id    BIGINT       NOT NULL DEFAULT 0,
    path         VARCHAR(255),
    icon         VARCHAR(100),
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    status       INTEGER      NOT NULL DEFAULT 0,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_menu_permission IS '菜单/按钮/接口权限点';
COMMENT ON COLUMN sys_menu_permission.type IS 'MENU / BUTTON / API';
COMMENT ON COLUMN sys_menu_permission.parent_id IS '父级 ID，顶级为 0';
COMMENT ON COLUMN sys_menu_permission.status IS '0 正常 / 1 禁用';

CREATE INDEX idx_sys_menu_permission_parent ON sys_menu_permission (parent_id) WHERE deleted = FALSE;

-- ============================================================
-- file 子域
-- ============================================================

CREATE TABLE sys_file (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    file_key     VARCHAR(500) NOT NULL UNIQUE,
    original_name VARCHAR(500) NOT NULL,
    mime_type    VARCHAR(200),
    size         BIGINT       NOT NULL,
    storage_path VARCHAR(1000),
    uploader_id  BIGINT,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_file IS '文件记录';
COMMENT ON COLUMN sys_file.file_key IS '文件唯一标识（存储 key）';

CREATE INDEX idx_sys_file_uploader ON sys_file (uploader_id) WHERE deleted = FALSE;

CREATE TABLE sys_file_config (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    storage_type VARCHAR(20)  NOT NULL,
    config       TEXT,
    master       BOOLEAN      NOT NULL DEFAULT FALSE,
    status       INTEGER      NOT NULL DEFAULT 0,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_file_config IS '文件存储配置';
COMMENT ON COLUMN sys_file_config.storage_type IS 'LOCAL / S3 / OSS';
COMMENT ON COLUMN sys_file_config.master IS '是否主配置';
COMMENT ON COLUMN sys_file_config.status IS '0 正常 / 1 禁用';

-- ============================================================
-- log 子域（登录日志）
-- ============================================================

CREATE TABLE sys_login_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT,
    username     VARCHAR(50),
    login_type   VARCHAR(20)  NOT NULL,
    ip           VARCHAR(50),
    user_agent   VARCHAR(500),
    location     VARCHAR(200),
    success      BOOLEAN      NOT NULL DEFAULT TRUE,
    fail_reason  VARCHAR(500),
    login_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_login_log IS '登录日志（不可变）';
COMMENT ON COLUMN sys_login_log.login_type IS 'PASSWORD / EMAIL / OAUTH';

CREATE INDEX idx_sys_login_log_user ON sys_login_log (user_id, login_time DESC);
CREATE INDEX idx_sys_login_log_time ON sys_login_log (login_time DESC);

-- ============================================================
-- mail 子域
-- ============================================================

CREATE TABLE sys_mail_account (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    host         VARCHAR(200) NOT NULL,
    port         INTEGER      NOT NULL,
    username     VARCHAR(200) NOT NULL,
    password     VARCHAR(200) NOT NULL,
    ssl_enabled  BOOLEAN      NOT NULL DEFAULT FALSE,
    from_address VARCHAR(200) NOT NULL,
    status       SMALLINT     NOT NULL DEFAULT 1,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_mail_account IS '邮件账号配置';
COMMENT ON COLUMN sys_mail_account.status IS '1=启用 0=禁用';

CREATE TABLE sys_mail_template (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    code         VARCHAR(64)  NOT NULL UNIQUE,
    name         VARCHAR(100) NOT NULL,
    subject      VARCHAR(200) NOT NULL,
    content      TEXT         NOT NULL,
    account_id   BIGINT       NOT NULL,
    params       VARCHAR(500),
    status       SMALLINT     NOT NULL DEFAULT 1,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_mail_template IS '邮件模板';
COMMENT ON COLUMN sys_mail_template.code IS '模板编码，唯一标识';
COMMENT ON COLUMN sys_mail_template.params IS '参数名列表（JSON 数组）';
COMMENT ON COLUMN sys_mail_template.status IS '1=启用 0=禁用';

CREATE INDEX idx_sys_mail_template_account ON sys_mail_template (account_id) WHERE deleted = FALSE;

CREATE TABLE sys_mail_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    template_id  BIGINT       NOT NULL,
    to_address   VARCHAR(200) NOT NULL,
    subject      VARCHAR(200) NOT NULL,
    content      TEXT,
    send_status  SMALLINT     NOT NULL DEFAULT 0,
    send_time    TIMESTAMP(6),
    error_message VARCHAR(500),
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_mail_log IS '邮件发送日志';
COMMENT ON COLUMN sys_mail_log.send_status IS '0=发送中 1=成功 2=失败';

CREATE INDEX idx_sys_mail_log_template ON sys_mail_log (template_id);
CREATE INDEX idx_sys_mail_log_time ON sys_mail_log (create_time DESC);

-- ============================================================
-- notify 子域（通知公告）
-- ============================================================

CREATE TABLE sys_notice (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    title        VARCHAR(200) NOT NULL,
    content      TEXT,
    type         VARCHAR(20)  NOT NULL,
    status       SMALLINT     NOT NULL DEFAULT 0,
    publish_time TIMESTAMP(6),
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_notice IS '通知公告';
COMMENT ON COLUMN sys_notice.type IS 'NOTICE=通知 / ANNOUNCEMENT=公告';
COMMENT ON COLUMN sys_notice.status IS '0=草稿 1=已发布';

CREATE INDEX idx_sys_notice_type_status ON sys_notice (type, status) WHERE deleted = FALSE;

-- ============================================================
-- role 子域（ReBAC 资源关系 + ABAC 访问策略）
-- ============================================================

CREATE TABLE sys_resource_relation (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    resource_type VARCHAR(50) NOT NULL,
    resource_id  BIGINT       NOT NULL,
    relation     VARCHAR(20)  NOT NULL,
    subject_type VARCHAR(20)  NOT NULL,
    subject_id   BIGINT       NOT NULL,
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255),
    CONSTRAINT uk_resource_relation UNIQUE (resource_type, resource_id, relation, subject_type, subject_id)
);

COMMENT ON TABLE sys_resource_relation IS 'ReBAC 资源关系元组';
COMMENT ON COLUMN sys_resource_relation.relation IS 'OWNER / EDITOR / VIEWER';
COMMENT ON COLUMN sys_resource_relation.subject_type IS 'USER / ROLE / AGENT';

CREATE INDEX idx_sys_resource_relation_resource ON sys_resource_relation (resource_type, resource_id) WHERE deleted = FALSE;
CREATE INDEX idx_sys_resource_relation_subject ON sys_resource_relation (subject_type, subject_id) WHERE deleted = FALSE;

CREATE TABLE sys_access_policy (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    condition_json  TEXT,
    effect          VARCHAR(16)  NOT NULL DEFAULT 'ALLOW',
    priority        INTEGER      NOT NULL DEFAULT 100,
    target_resource VARCHAR(64),
    target_action   VARCHAR(64),
    status          INTEGER      NOT NULL DEFAULT 1,
    archived_at     TIMESTAMP(6),
    create_by       BIGINT,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE sys_access_policy IS 'ABAC 访问策略';
COMMENT ON COLUMN sys_access_policy.effect IS 'ALLOW / DENY';
COMMENT ON COLUMN sys_access_policy.priority IS '数值越小优先级越高';
COMMENT ON COLUMN sys_access_policy.condition_json IS '条件表达式（JSON）';
COMMENT ON COLUMN sys_access_policy.status IS '0=禁用 1=启用';

CREATE INDEX idx_sys_access_policy_target ON sys_access_policy (target_resource, target_action) WHERE deleted = FALSE AND status = 1;


-- ============================================================
-- Seed Data
-- ============================================================

-- 内置角色
INSERT INTO sys_role (code, name, description, status) VALUES
    ('super_admin', '超级管理员', '系统最高权限，不可删除', 0),
    ('org_admin', '组织管理员', '组织级管理权限', 0),
    ('member', '普通成员', '默认角色，基础读写权限', 0),
    ('guest', '访客', '只读权限', 0),
    ('agent', 'AI 智能体', 'AI Agent 专用角色', 0);

-- 字典类型
INSERT INTO sys_dict_type (name, type, status) VALUES
    ('文件存储类型', 'file_storage_type', 0),
    ('通知类型', 'notice_type', 0),
    ('登录类型', 'login_type', 0),
    ('邮件发送状态', 'mail_send_status', 0);

-- 字典数据：文件存储类型
INSERT INTO sys_dict_data (dict_type, label, value, sort, status) VALUES
    ('file_storage_type', '本地存储', 'LOCAL', 1, 0),
    ('file_storage_type', 'AWS S3', 'S3', 2, 0),
    ('file_storage_type', '阿里云 OSS', 'OSS', 3, 0);

-- 字典数据：通知类型
INSERT INTO sys_dict_data (dict_type, label, value, sort, status) VALUES
    ('notice_type', '通知', 'NOTICE', 1, 0),
    ('notice_type', '公告', 'ANNOUNCEMENT', 2, 0);

-- 字典数据：登录类型
INSERT INTO sys_dict_data (dict_type, label, value, sort, status) VALUES
    ('login_type', '密码登录', 'PASSWORD', 1, 0),
    ('login_type', '邮箱验证码', 'EMAIL', 2, 0),
    ('login_type', '第三方 OAuth', 'OAUTH', 3, 0);

-- 字典数据：邮件发送状态
INSERT INTO sys_dict_data (dict_type, label, value, sort, status) VALUES
    ('mail_send_status', '发送中', 'PENDING', 1, 0),
    ('mail_send_status', '发送成功', 'SUCCESS', 2, 0),
    ('mail_send_status', '发送失败', 'FAIL', 3, 0);

-- 默认文件存储配置（本地存储）
INSERT INTO sys_file_config (name, storage_type, config, master, status) VALUES
    ('本地存储', 'LOCAL', '{"basePath":"/data/aaf/files"}', TRUE, 0);

-- 默认系统配置项
INSERT INTO sys_config (category, config_key, value, default_value, value_type, name, description, visible, editable) VALUES
    ('site', 'site.name', 'AAF', 'AAF', 'string', '站点名称', '系统显示名称', TRUE, TRUE),
    ('site', 'site.logo', NULL, NULL, 'string', '站点 Logo', 'Logo 图片 URL', TRUE, TRUE),
    ('user', 'user.register_enabled', 'true', 'true', 'boolean', '开放注册', '是否允许用户自助注册', TRUE, TRUE),
    ('user', 'user.default_password', '123456', '123456', 'string', '默认密码', '管理员创建用户时的默认密码', FALSE, TRUE),
    ('security', 'security.login_fail_lock_count', '5', '5', 'integer', '登录失败锁定次数', '连续失败 N 次后锁定账号', TRUE, TRUE),
    ('security', 'security.login_fail_lock_minutes', '30', '30', 'integer', '锁定时长（分钟）', '账号锁定持续时间', TRUE, TRUE),
    ('security', 'security.captcha_enabled', 'true', 'true', 'boolean', '验证码开关', '登录是否需要验证码', TRUE, TRUE);




-- ============================================================
-- operator 字段补充（为所有含 create_by 的表添加类型和归属字段）
-- ============================================================

DO $$
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN
        SELECT table_name
        FROM information_schema.columns
        WHERE column_name = 'create_by'
          AND table_schema = 'public'
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = tbl AND column_name = 'create_by_type' AND table_schema = 'public'
        ) THEN
            EXECUTE format('ALTER TABLE %I ADD COLUMN create_by_type VARCHAR(16) DEFAULT ''HUMAN''', tbl);
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = tbl AND column_name = 'update_by_type' AND table_schema = 'public'
        ) THEN
            EXECUTE format('ALTER TABLE %I ADD COLUMN update_by_type VARCHAR(16) DEFAULT ''HUMAN''', tbl);
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = tbl AND column_name = 'owner_id' AND table_schema = 'public'
        ) THEN
            EXECUTE format('ALTER TABLE %I ADD COLUMN owner_id BIGINT', tbl);
            EXECUTE format('UPDATE %I SET owner_id = create_by WHERE owner_id IS NULL', tbl);
        END IF;
    END LOOP;
END $$;

DO $$
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN
        SELECT table_name
        FROM information_schema.columns
        WHERE column_name = 'owner_id' AND table_schema = 'public'
    LOOP
        EXECUTE format('CREATE INDEX IF NOT EXISTS idx_%s_owner_id ON %I (owner_id)', tbl, tbl);
    END LOOP;
END $$;

-- ============================================================
-- approval 子域（审批记录 + 抄送 + 表单模板 + 评论）
-- ============================================================

CREATE TABLE sys_approval_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    process_instance_id VARCHAR(64) NOT NULL,
    task_id         VARCHAR(64),
    assignee        VARCHAR(64)  NOT NULL,
    operation_type  VARCHAR(20)  NOT NULL,
    comment         VARCHAR(500),
    operation_time  TIMESTAMP(6) NOT NULL,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE sys_approval_record IS '审批记录';
COMMENT ON COLUMN sys_approval_record.operation_type IS 'APPROVE/REJECT/DELEGATE/ADD_SIGN/TRANSFER/WITHDRAW/URGE';

CREATE INDEX idx_approval_record_process ON sys_approval_record(process_instance_id);
CREATE INDEX idx_approval_record_assignee ON sys_approval_record(assignee);
CREATE INDEX idx_approval_record_task ON sys_approval_record(task_id);

CREATE TABLE approval_cc_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    process_instance_id VARCHAR(64) NOT NULL,
    task_name       VARCHAR(128),
    cc_user         VARCHAR(64)  NOT NULL,
    cc_time         TIMESTAMP(6) NOT NULL,
    entity_type     VARCHAR(64),
    entity_id       VARCHAR(64),
    read            BOOLEAN      NOT NULL DEFAULT FALSE,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE approval_cc_record IS '审批抄送记录';

CREATE INDEX idx_cc_record_user ON approval_cc_record(cc_user);
CREATE INDEX idx_cc_record_process ON approval_cc_record(process_instance_id);

CREATE TABLE approval_form_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(500),
    process_key     VARCHAR(128) NOT NULL,
    fields_json     TEXT,
    status          INTEGER      NOT NULL DEFAULT 1,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE approval_form_template IS '审批表单模板';

CREATE INDEX idx_form_template_process_key ON approval_form_template(process_key);

CREATE TABLE approval_comment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_instance_id VARCHAR(64) NOT NULL,
    task_id         VARCHAR(64),
    user_id         VARCHAR(64)  NOT NULL,
    content         TEXT,
    attachments     TEXT,
    mentioned_users TEXT,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE approval_comment IS '审批评论';

CREATE INDEX idx_comment_process ON approval_comment(process_instance_id);
CREATE INDEX idx_comment_task ON approval_comment(task_id);

-- ============================================================
-- menu 子域（系统菜单 + 角色菜单关联）
-- ============================================================

CREATE TABLE sys_menu (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT,
    title       VARCHAR(50)  NOT NULL,
    path        VARCHAR(200),
    icon        VARCHAR(50),
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    visible     BOOLEAN      NOT NULL DEFAULT TRUE,
    menu_type   VARCHAR(20)  NOT NULL DEFAULT 'MENU',
    permission  VARCHAR(100),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sys_menu IS '系统菜单';
COMMENT ON COLUMN sys_menu.menu_type IS 'GROUP/MENU/BUTTON';

CREATE INDEX idx_menu_parent ON sys_menu(parent_id);

CREATE TABLE sys_role_menu (
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);

COMMENT ON TABLE sys_role_menu IS '角色-菜单关联';


-- ============================================================
-- channel 子域（渠道集成）
-- ============================================================

CREATE TABLE IF NOT EXISTS channel_config (
    id              BIGSERIAL PRIMARY KEY,
    channel_type    VARCHAR(32) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    app_id          VARCHAR(200),
    app_secret      VARCHAR(500),
    token           VARCHAR(200),
    encoding_aes_key VARCHAR(200),
    status          INT NOT NULL DEFAULT 0,
    ext_config      JSONB,
    version         INT NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

CREATE INDEX idx_channel_config_type ON channel_config(channel_type) WHERE deleted = FALSE;
COMMENT ON TABLE channel_config IS '渠道配置';

CREATE TABLE IF NOT EXISTS channel_message (
    id              BIGSERIAL PRIMARY KEY,
    channel_type    VARCHAR(32) NOT NULL,
    direction       VARCHAR(16) NOT NULL,
    message_type    VARCHAR(16) NOT NULL,
    external_user_id VARCHAR(200) NOT NULL,
    user_id         BIGINT,
    content         TEXT,
    media_url       VARCHAR(500),
    raw_payload     TEXT,
    message_time    TIMESTAMP,
    version         INT NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

CREATE INDEX idx_channel_message_user ON channel_message(external_user_id, channel_type) WHERE deleted = FALSE;
CREATE INDEX idx_channel_message_time ON channel_message(message_time DESC) WHERE deleted = FALSE;
COMMENT ON TABLE channel_message IS '渠道消息记录';

CREATE TABLE IF NOT EXISTS webhook_config (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    url             VARCHAR(500) NOT NULL,
    event_types     VARCHAR(500),
    secret          VARCHAR(200),
    status          VARCHAR(16) NOT NULL DEFAULT 'active',
    direction       VARCHAR(16) NOT NULL DEFAULT 'outbound',
    failure_count   INT DEFAULT 0,
    max_retries     INT DEFAULT 3,
    version         INT NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

CREATE INDEX idx_webhook_config_status ON webhook_config(status) WHERE deleted = FALSE;
COMMENT ON TABLE webhook_config IS 'Webhook 配置';

CREATE TABLE IF NOT EXISTS webhook_log (
    id              BIGSERIAL PRIMARY KEY,
    webhook_id      BIGINT NOT NULL,
    event_type      VARCHAR(64) NOT NULL,
    request_body    TEXT,
    response_status INT,
    response_body   VARCHAR(2000),
    status          VARCHAR(16) NOT NULL DEFAULT 'pending',
    failure_reason  VARCHAR(500),
    retry_count     INT DEFAULT 0,
    next_retry_time TIMESTAMP,
    push_time       TIMESTAMP,
    version         INT NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

CREATE INDEX idx_webhook_log_webhook ON webhook_log(webhook_id) WHERE deleted = FALSE;
CREATE INDEX idx_webhook_log_retry ON webhook_log(status, next_retry_time) WHERE deleted = FALSE;
COMMENT ON TABLE webhook_log IS 'Webhook 推送日志';

-- ============================================================
-- livechat 子域（客服系统）
-- ============================================================

CREATE TABLE chat_session (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT,
    external_user_id VARCHAR(128) NOT NULL,
    channel_type    VARCHAR(32)  NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'bot',
    agent_id        BIGINT,
    staff_id        BIGINT,
    skill_group     VARCHAR(64),
    tags            VARCHAR(256),
    priority        INTEGER      DEFAULT 3,
    last_active_time TIMESTAMP,
    closed_time     TIMESTAMP,
    org_id          BIGINT,
    workspace_id    BIGINT,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255),
    version         INTEGER      NOT NULL DEFAULT 0
);

CREATE INDEX idx_chat_session_external_user ON chat_session(external_user_id, channel_type);
CREATE INDEX idx_chat_session_status ON chat_session(status);
COMMENT ON TABLE chat_session IS '客服会话';

CREATE TABLE chat_message (
    id              BIGSERIAL PRIMARY KEY,
    session_id      BIGINT       NOT NULL,
    sender_type     VARCHAR(16)  NOT NULL,
    sender_id       BIGINT,
    message_type    VARCHAR(16)  NOT NULL DEFAULT 'TEXT',
    content         TEXT,
    internal        BOOLEAN      NOT NULL DEFAULT FALSE,
    org_id          BIGINT,
    workspace_id    BIGINT,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255),
    version         INTEGER      NOT NULL DEFAULT 0
);

CREATE INDEX idx_chat_message_session ON chat_message(session_id, create_time);
COMMENT ON TABLE chat_message IS '客服会话消息';

CREATE TABLE livechat_seat (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT       NOT NULL UNIQUE,
    nickname        VARCHAR(64),
    skill_group     VARCHAR(128),
    status          VARCHAR(16)  NOT NULL DEFAULT 'offline',
    current_sessions INTEGER     NOT NULL DEFAULT 0,
    max_sessions    INTEGER      NOT NULL DEFAULT 5,
    org_id          BIGINT,
    workspace_id    BIGINT,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255),
    version         INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE livechat_seat IS '客服坐席';

CREATE TABLE session_transfer (
    id              BIGSERIAL PRIMARY KEY,
    session_id      BIGINT       NOT NULL,
    from_staff_id   BIGINT       NOT NULL,
    to_staff_id     BIGINT,
    to_skill_group  VARCHAR(64),
    reason          VARCHAR(32)  NOT NULL,
    note            VARCHAR(512),
    org_id          BIGINT,
    workspace_id    BIGINT,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255),
    version         INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE session_transfer IS '会话转接记录';

CREATE TABLE session_rating (
    id              BIGSERIAL PRIMARY KEY,
    session_id      BIGINT       NOT NULL,
    user_id         BIGINT,
    staff_id        BIGINT,
    score           INTEGER      NOT NULL,
    comment         VARCHAR(512),
    org_id          BIGINT,
    workspace_id    BIGINT,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255),
    version         INTEGER      NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX idx_session_rating_session ON session_rating(session_id) WHERE deleted = false;
COMMENT ON TABLE session_rating IS '会话满意度评价';

CREATE TABLE ticket (
    id              BIGSERIAL PRIMARY KEY,
    ticket_no       VARCHAR(32)  NOT NULL UNIQUE,
    title           VARCHAR(128) NOT NULL,
    description     TEXT,
    user_id         BIGINT,
    session_id      BIGINT,
    type            VARCHAR(32)  NOT NULL,
    priority        VARCHAR(16)  NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    assignee_id     BIGINT,
    sla_due_time    TIMESTAMP,
    closed_time     TIMESTAMP,
    org_id          BIGINT,
    workspace_id    BIGINT,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255),
    version         INTEGER      NOT NULL DEFAULT 0
);

CREATE INDEX idx_ticket_status ON ticket(status);
COMMENT ON TABLE ticket IS '客服工单';

CREATE TABLE ticket_record (
    id              BIGSERIAL PRIMARY KEY,
    ticket_id       BIGINT       NOT NULL,
    operation       VARCHAR(16)  NOT NULL,
    operator_id     BIGINT,
    from_status     VARCHAR(16),
    to_status       VARCHAR(16),
    record_remark   VARCHAR(512),
    org_id          BIGINT,
    workspace_id    BIGINT,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255),
    version         INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE ticket_record IS '工单流转记录';

-- ============================================================
-- stats 子域（运营统计）
-- ============================================================

CREATE TABLE IF NOT EXISTS user_event (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    event_type      VARCHAR(32)  NOT NULL,
    page            VARCHAR(255),
    target          VARCHAR(255),
    extra           JSONB,
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_event_type_time ON user_event (event_type, create_time);
CREATE INDEX idx_user_event_user ON user_event (user_id, create_time);
CREATE INDEX idx_user_event_date ON user_event ((create_time::date));
COMMENT ON TABLE user_event IS '用户行为事件（追加写入）';

-- ============================================================
-- 字典 seed：渠道/客服/统计
-- ============================================================

INSERT INTO sys_dict_type (name, type, status, version, deleted, create_time, update_time) VALUES
    ('渠道类型', 'channel_type', 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('渠道消息类型', 'channel_message_type', 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Webhook状态', 'webhook_status', 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('客服会话状态', 'livechat_session_status', 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('坐席状态', 'livechat_seat_status', 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('转接原因', 'livechat_transfer_reason', 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('工单状态', 'livechat_ticket_status', 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('工单优先级', 'livechat_ticket_priority', 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('工单类型', 'livechat_ticket_type', 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('用户事件类型', 'stats_event_type', 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_dict_data (dict_type, label, value, sort, status, version, deleted, create_time, update_time) VALUES
    ('channel_type', '微信公众号', 'wechat_mp', 1, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('channel_type', '微信小程序', 'wechat_mini', 2, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('channel_type', '钉钉', 'dingtalk', 3, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('channel_type', '飞书', 'feishu', 4, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('channel_type', '网页', 'web', 5, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('channel_type', 'Webhook', 'webhook', 6, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('channel_message_type', '文本', 'text', 1, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('channel_message_type', '图片', 'image', 2, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('channel_message_type', '语音', 'voice', 3, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('channel_message_type', '事件', 'event', 4, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('channel_message_type', '模板消息', 'template', 5, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('channel_message_type', 'Markdown', 'markdown', 6, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('channel_message_type', '卡片消息', 'card', 7, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('webhook_status', '启用', 'active', 1, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('webhook_status', '停用', 'inactive', 2, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('webhook_status', '失败', 'failed', 3, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_session_status', '机器人服务中', 'bot', 1, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_session_status', '等待人工接入', 'waiting', 2, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_session_status', '人工服务中', 'active', 3, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_session_status', '已关闭', 'closed', 4, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_seat_status', '在线', 'online', 1, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_seat_status', '忙碌', 'busy', 2, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_seat_status', '离线', 'offline', 3, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_transfer_reason', '技能不匹配', 'skill_mismatch', 1, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_transfer_reason', '工作量过大', 'workload', 2, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_transfer_reason', '用户要求', 'user_request', 3, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_transfer_reason', '问题升级', 'escalation', 4, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_transfer_reason', '换班交接', 'shift_change', 5, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_ticket_status', '待处理', 'PENDING', 1, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_ticket_status', '处理中', 'PROCESSING', 2, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_ticket_status', '待确认', 'CONFIRMING', 3, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_ticket_status', '已关闭', 'CLOSED', 4, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_ticket_priority', '低', 'LOW', 1, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_ticket_priority', '中', 'MEDIUM', 2, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_ticket_priority', '高', 'HIGH', 3, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_ticket_priority', '紧急', 'URGENT', 4, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_ticket_type', '咨询', 'consultation', 1, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_ticket_type', '投诉', 'complaint', 2, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_ticket_type', '故障报告', 'bug_report', 3, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_ticket_type', '功能建议', 'feature_request', 4, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_ticket_type', '退款', 'refund', 5, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('livechat_ticket_type', '其他', 'other', 6, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('stats_event_type', '页面浏览', 'page_view', 1, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('stats_event_type', '点击', 'click', 2, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('stats_event_type', '注册', 'register', 3, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('stats_event_type', '登录', 'login', 4, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('stats_event_type', '对话', 'chat', 5, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('stats_event_type', '工具使用', 'tool_use', 6, 0, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
