-- AAF 初始数据库迁移
-- 表：sys_user, doc_document, autodev_request, autodev_generated_code, autodev_execution_log

-- ==================== 用户模块 ====================

create table sys_user (
    id          bigint generated by default as identity primary key,
    username    varchar(50)  not null unique,
    password    varchar(200) not null,
    nickname    varchar(100),
    status      integer      not null default 0,
    create_by   bigint,
    create_time timestamp(6) not null default current_timestamp,
    update_by   bigint,
    update_time timestamp(6) not null default current_timestamp,
    delete_time timestamp(6),
    deleted     boolean      not null default false,
    remark      varchar(255)
);

comment on table sys_user is '系统用户';
comment on column sys_user.status is '0 正常 / 1 禁用';

-- 默认管理员 admin/admin
insert into sys_user (username, password, nickname, status)
values ('admin', '$2a$10$UyqdQK.M7V9FE4IzbbzeUeQnU.NsumDR.RCviFq4Pt04Y/F4VWLKC', '管理员', 0);

-- ==================== 文档模块 ====================

create table doc_document (
    id          bigint generated by default as identity primary key,
    title       varchar(200) not null,
    file_path   varchar(500),
    content     text,
    doc_type    varchar(50)  not null default 'spec',
    version     integer      not null default 1,
    status      varchar(20)  not null default 'active',
    create_by   bigint,
    create_time timestamp(6) not null default current_timestamp,
    update_by   bigint,
    update_time timestamp(6) not null default current_timestamp,
    delete_time timestamp(6),
    deleted     boolean      not null default false,
    remark      varchar(255)
);

comment on table doc_document is '文档';
comment on column doc_document.doc_type is 'spec / design / task / guide / explanation';
comment on column doc_document.status is 'active / archived';

-- ==================== Auto Dev 模块 ====================

create table autodev_request (
    id              bigint generated by default as identity primary key,
    requirement     text         not null,
    status          varchar(20)  not null default 'pending',
    planning_result jsonb,
    review_result   jsonb,
    create_by       bigint,
    create_time     timestamp(6) not null default current_timestamp,
    update_by       bigint,
    update_time     timestamp(6) not null default current_timestamp,
    completed_at    timestamp(6),
    delete_time     timestamp(6),
    deleted         boolean      not null default false,
    remark          varchar(255)
);

comment on table autodev_request is 'AI 代码生成请求';
comment on column autodev_request.status is 'pending / running / success / failed';

create table autodev_generated_code (
    id          bigint generated by default as identity primary key,
    request_id  bigint       not null references autodev_request(id),
    file_path   varchar(500) not null,
    content     text         not null,
    create_by   bigint,
    create_time timestamp(6) not null default current_timestamp,
    update_by   bigint,
    update_time timestamp(6) not null default current_timestamp,
    delete_time timestamp(6),
    deleted     boolean      not null default false,
    remark      varchar(255)
);

comment on table autodev_generated_code is 'AI 生成的代码文件';

create table autodev_execution_log (
    id          bigint generated by default as identity primary key,
    request_id  bigint,
    source      varchar(50)  not null,
    agent       varchar(50),
    input       text,
    output      text,
    status      varchar(20)  not null default 'running',
    duration_ms bigint,
    create_by   bigint,
    create_time timestamp(6) not null default current_timestamp,
    update_by   bigint,
    update_time timestamp(6) not null default current_timestamp,
    delete_time timestamp(6),
    deleted     boolean      not null default false,
    remark      varchar(255)
);

comment on table autodev_execution_log is 'Agent 执行日志';
comment on column autodev_execution_log.source is 'agent / kiro-cli';
comment on column autodev_execution_log.status is 'running / success / failed';
