-- NexusKB v20：直接创建最终可信知识 schema，PostgreSQL 成为唯一真理源。

-- 时态列统一使用 UTC；attributes 字节上限按 UTF8 计算。
SET LOCAL TIME ZONE 'UTC';
DO $$
BEGIN
    IF current_setting('TimeZone') <> 'UTC' THEN
        RAISE EXCEPTION 'v20 要求迁移会话使用 UTC，当前为 %', current_setting('TimeZone');
    END IF;
    IF current_setting('server_encoding') <> 'UTF8' THEN
        RAISE EXCEPTION 'v20 attributes 字节上限要求数据库编码为 UTF8';
    END IF;
END $$;

CREATE TABLE ai_knowledge_base (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stable_id            UUID NOT NULL DEFAULT gen_random_uuid(),
    version              INTEGER NOT NULL DEFAULT 0,
    org_id               BIGINT,
    workspace_id         BIGINT,
    visibility           VARCHAR(24) NOT NULL DEFAULT 'PRIVATE',
    scope_code           VARCHAR(128),
    name                 VARCHAR(200) NOT NULL,
    description          VARCHAR(1000),
    embedding_model      VARCHAR(100),
    chunk_strategy       VARCHAR(50),
    chunk_size           INTEGER DEFAULT 512,
    chunk_overlap        INTEGER DEFAULT 64,
    status               INTEGER NOT NULL DEFAULT 0,
    auto_inject          BOOLEAN NOT NULL DEFAULT FALSE,
    projection_watermark BIGINT NOT NULL DEFAULT 0,
    create_by            BIGINT,
    create_by_type       VARCHAR(16),
    create_time          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by            BIGINT,
    update_by_type       VARCHAR(16),
    update_time          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id             BIGINT,
    delete_time          TIMESTAMP(6),
    deleted              BOOLEAN NOT NULL DEFAULT FALSE,
    remark               TEXT,
    CONSTRAINT uk_ai_knowledge_base_stable_v20 UNIQUE (stable_id),
    CONSTRAINT uk_ai_knowledge_base_identity_v20 UNIQUE (stable_id, id),
    CONSTRAINT ck_ai_knowledge_base_visibility_v20
        CHECK (visibility IN ('PRIVATE', 'ORG', 'SYSTEM_PUBLIC'))
);
COMMENT ON TABLE ai_knowledge_base IS '知识库';
CREATE INDEX idx_ai_knowledge_base_public_v20
    ON ai_knowledge_base (visibility, status) WHERE deleted = FALSE;

CREATE TABLE ai_knowledge_document (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stable_id          UUID NOT NULL DEFAULT gen_random_uuid(),
    version            INTEGER NOT NULL DEFAULT 0,
    org_id             BIGINT,
    workspace_id       BIGINT,
    knowledge_base_id  BIGINT NOT NULL REFERENCES ai_knowledge_base(id),
    source_document_id BIGINT REFERENCES doc_document(id),
    uploaded_by        BIGINT,
    source_type        VARCHAR(32) NOT NULL DEFAULT 'FILE',
    source_key         VARCHAR(1000),
    source_uri         VARCHAR(2000),
    active_run_id      UUID,
    ingest_fence       BIGINT NOT NULL DEFAULT 0,
    title              VARCHAR(500) NOT NULL,
    file_path          VARCHAR(1000),
    file_type          VARCHAR(50),
    file_size          BIGINT,
    content_hash       VARCHAR(64),
    status             INTEGER NOT NULL DEFAULT 0,
    error_message      VARCHAR(2000),
    chunk_count        INTEGER DEFAULT 0,
    create_by          BIGINT,
    create_by_type     VARCHAR(16),
    create_time        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by          BIGINT,
    update_by_type     VARCHAR(16),
    update_time        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id           BIGINT,
    delete_time        TIMESTAMP(6),
    deleted            BOOLEAN NOT NULL DEFAULT FALSE,
    remark             TEXT,
    CONSTRAINT uk_ai_knowledge_document_stable_v20 UNIQUE (stable_id),
    CONSTRAINT uk_ai_knowledge_document_base_v20 UNIQUE (id, knowledge_base_id),
    CONSTRAINT ck_ai_knowledge_document_source_type_v20
        CHECK (source_type IN ('FILE', 'URL', 'BUSINESS_OBJECT', 'SYSTEM'))
);
COMMENT ON TABLE ai_knowledge_document IS '知识库文档';
CREATE INDEX idx_ai_knowledge_document_base_v20
    ON ai_knowledge_document (knowledge_base_id);
CREATE UNIQUE INDEX uk_ai_knowledge_document_source_v20
    ON ai_knowledge_document (knowledge_base_id, source_type, source_key)
    WHERE deleted = FALSE AND source_key IS NOT NULL;

CREATE TABLE ai_knowledge_ingest_run (
    id                        UUID PRIMARY KEY,
    knowledge_base_id         BIGINT NOT NULL REFERENCES ai_knowledge_base(id),
    document_id               BIGINT NOT NULL,
    run_no                    BIGINT NOT NULL,
    ingest_fingerprint        VARCHAR(64) NOT NULL,
    payer_user_id             BIGINT NOT NULL,
    status                    VARCHAR(20) NOT NULL,
    parser_version                     VARCHAR(64) NOT NULL,
    chunk_config_digest                VARCHAR(64) NOT NULL,
    extraction_prompt_snapshot         TEXT NOT NULL,
    extraction_prompt_digest           VARCHAR(64) NOT NULL,
    extraction_prompt_version          INTEGER NOT NULL,
    extraction_user_prompt_snapshot    TEXT NOT NULL DEFAULT '',
    extraction_user_prompt_digest      VARCHAR(64) NOT NULL DEFAULT '',
    extraction_user_prompt_version     INTEGER NOT NULL DEFAULT 1,
    extraction_output_contract_version VARCHAR(64) NOT NULL,
    extraction_model_id                VARCHAR(128) NOT NULL,
    entity_resolution_prompt_snapshot  TEXT NOT NULL,
    entity_resolution_prompt_digest    VARCHAR(64) NOT NULL,
    entity_resolution_prompt_version   INTEGER NOT NULL,
    entity_resolution_user_prompt_snapshot TEXT NOT NULL DEFAULT '',
    entity_resolution_user_prompt_digest VARCHAR(64) NOT NULL DEFAULT '',
    entity_resolution_user_prompt_version INTEGER NOT NULL DEFAULT 1,
    entity_resolution_output_contract_version VARCHAR(64) NOT NULL,
    entity_resolution_model_id         VARCHAR(128) NOT NULL,
    normalization_version              VARCHAR(32) NOT NULL,
    embedding_model_id                 VARCHAR(128) NOT NULL,
    expected_active_run_id    UUID,
    fencing_token             BIGINT NOT NULL,
    error_message             VARCHAR(2000),
    started_at                TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ready_at                  TIMESTAMP(6),
    published_at              TIMESTAMP(6),
    finished_at               TIMESTAMP(6),
    CONSTRAINT uk_ai_knowledge_ingest_run_no_v20 UNIQUE (document_id, run_no),
    CONSTRAINT uk_ai_knowledge_ingest_run_source_v20
        UNIQUE (id, document_id, knowledge_base_id),
    CONSTRAINT uk_ai_knowledge_ingest_run_base_v20 UNIQUE (id, knowledge_base_id),
    CONSTRAINT fk_ai_knowledge_ingest_run_document_v20
        FOREIGN KEY (document_id, knowledge_base_id)
        REFERENCES ai_knowledge_document(id, knowledge_base_id),
    CONSTRAINT ck_ai_knowledge_ingest_status_v20
        CHECK (status IN ('QUEUED', 'PROCESSING', 'READY', 'PUBLISHED', 'SUPERSEDED', 'FAILED')),
    CONSTRAINT fk_ai_knowledge_ingest_expected_v20
        FOREIGN KEY (expected_active_run_id, document_id, knowledge_base_id)
        REFERENCES ai_knowledge_ingest_run(id, document_id, knowledge_base_id)
);
CREATE UNIQUE INDEX uk_ai_knowledge_ingest_fingerprint_v20
    ON ai_knowledge_ingest_run (document_id, ingest_fingerprint)
    WHERE status <> 'SUPERSEDED';
CREATE UNIQUE INDEX uk_ai_knowledge_ingest_published_v20
    ON ai_knowledge_ingest_run (document_id) WHERE status = 'PUBLISHED';

-- document.active_run_id 与 PUBLISHED run 的循环一致性由后文延迟约束触发器保证，
-- 避免建表后的补充约束语句。

CREATE TABLE ai_knowledge_ingest_unit (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id              UUID NOT NULL REFERENCES ai_knowledge_ingest_run(id) ON DELETE CASCADE,
    stage               VARCHAR(32) NOT NULL,
    unit_key            VARCHAR(200) NOT NULL,
    input_digest        VARCHAR(64) NOT NULL,
    output_json         JSONB,
    invocation_id       VARCHAR(128) NOT NULL,
    provider_request_id VARCHAR(256),
    usage_key           VARCHAR(500) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    occurred_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    reservation_token   UUID,
    lease_until         TIMESTAMP WITH TIME ZONE,
    error_message       VARCHAR(2000),
    update_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_knowledge_ingest_unit_v20 UNIQUE (run_id, stage, unit_key),
    CONSTRAINT uk_ai_knowledge_ingest_usage_v20 UNIQUE (usage_key),
    CONSTRAINT ck_ai_knowledge_ingest_unit_status_v20
        CHECK (status IN ('RESERVED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'UNKNOWN'))
);

CREATE TABLE ai_knowledge_chunk (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stable_id         UUID NOT NULL DEFAULT gen_random_uuid(),
    run_id            UUID NOT NULL,
    document_id       BIGINT NOT NULL,
    knowledge_base_id BIGINT NOT NULL,
    content           TEXT NOT NULL,
    content_hash      VARCHAR(64) NOT NULL,
    chunk_index       INTEGER NOT NULL,
    token_count       INTEGER NOT NULL DEFAULT 0,
    section_path      VARCHAR(1000),
    page_no           INTEGER,
    start_offset      INTEGER,
    end_offset        INTEGER,
    metadata          JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_knowledge_chunk_stable_v20 UNIQUE (stable_id),
    CONSTRAINT uk_ai_knowledge_chunk_run_index_v20 UNIQUE (run_id, chunk_index),
    CONSTRAINT uk_ai_knowledge_chunk_source_v20
        UNIQUE (stable_id, run_id, document_id, knowledge_base_id),
    CONSTRAINT fk_ai_knowledge_chunk_source_v20
        FOREIGN KEY (run_id, document_id, knowledge_base_id)
        REFERENCES ai_knowledge_ingest_run(id, document_id, knowledge_base_id) ON DELETE CASCADE,
    CONSTRAINT ck_ai_knowledge_chunk_offsets_v20
        CHECK ((start_offset IS NULL AND end_offset IS NULL)
            OR (start_offset IS NOT NULL AND end_offset IS NOT NULL
                AND 0 <= start_offset AND start_offset <= end_offset))
);
CREATE INDEX idx_ai_knowledge_chunk_run_v20
    ON ai_knowledge_chunk (run_id, chunk_index);
CREATE INDEX idx_ai_knowledge_chunk_base_v20 ON ai_knowledge_chunk (knowledge_base_id);
CREATE INDEX idx_ai_knowledge_chunk_fts_v20
    ON ai_knowledge_chunk USING GIN (to_tsvector('simple', content));

CREATE TABLE ai_knowledge_embedding (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chunk_id          UUID NOT NULL,
    run_id            UUID NOT NULL,
    document_id       BIGINT NOT NULL,
    knowledge_base_id UUID NOT NULL,
    knowledge_base_pk BIGINT NOT NULL,
    model_id          VARCHAR(128) NOT NULL,
    embedding_version VARCHAR(32) NOT NULL,
    content_hash      VARCHAR(64) NOT NULL,
    content           TEXT NOT NULL,
    metadata          JSONB NOT NULL DEFAULT '{}'::jsonb,
    embedding         vector(1536) NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_knowledge_embedding_v20
        UNIQUE (chunk_id, model_id, embedding_version),
    CONSTRAINT fk_ai_knowledge_embedding_base_v20
        FOREIGN KEY (knowledge_base_id, knowledge_base_pk)
        REFERENCES ai_knowledge_base(stable_id, id),
    CONSTRAINT fk_ai_knowledge_embedding_source_v20
        FOREIGN KEY (chunk_id, run_id, document_id, knowledge_base_pk)
        REFERENCES ai_knowledge_chunk(stable_id, run_id, document_id, knowledge_base_id)
        ON DELETE CASCADE
);
CREATE INDEX idx_ai_knowledge_embedding_base_v20
    ON ai_knowledge_embedding (knowledge_base_id);
CREATE INDEX idx_ai_knowledge_embedding_hnsw_v20 ON ai_knowledge_embedding
    USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

CREATE TABLE ai_knowledge_entity (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    knowledge_base_id BIGINT NOT NULL REFERENCES ai_knowledge_base(id),
    canonical_name    VARCHAR(500) NOT NULL,
    entity_type       VARCHAR(100) NOT NULL,
    entity_key        VARCHAR(64) NOT NULL,
    description       TEXT,
    review_status     VARCHAR(20) NOT NULL DEFAULT 'RESOLVED',
    merged_into_id    UUID,
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_knowledge_entity_key_v20 UNIQUE (knowledge_base_id, entity_key),
    CONSTRAINT uk_ai_knowledge_entity_base_v20 UNIQUE (id, knowledge_base_id),
    CONSTRAINT fk_ai_knowledge_entity_merge_v20
        FOREIGN KEY (merged_into_id, knowledge_base_id)
        REFERENCES ai_knowledge_entity(id, knowledge_base_id),
    CONSTRAINT ck_ai_knowledge_entity_merge_v20
        CHECK (merged_into_id IS NULL OR merged_into_id <> id),
    CONSTRAINT ck_ai_knowledge_entity_review_v20
        CHECK (review_status IN ('RESOLVED', 'REVIEW'))
);
CREATE INDEX idx_ai_knowledge_entity_name_v20
    ON ai_knowledge_entity (knowledge_base_id, lower(canonical_name));

CREATE TABLE ai_knowledge_entity_alias (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    knowledge_base_id BIGINT NOT NULL,
    entity_id         UUID NOT NULL,
    normalized_alias  VARCHAR(500) NOT NULL,
    confidence        DOUBLE PRECISION NOT NULL,
    source_run_id     UUID NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_knowledge_entity_alias_v20
        UNIQUE (knowledge_base_id, normalized_alias, entity_id),
    CONSTRAINT fk_ai_knowledge_entity_alias_entity_v20
        FOREIGN KEY (entity_id, knowledge_base_id)
        REFERENCES ai_knowledge_entity(id, knowledge_base_id),
    CONSTRAINT fk_ai_knowledge_entity_alias_run_v20
        FOREIGN KEY (source_run_id, knowledge_base_id)
        REFERENCES ai_knowledge_ingest_run(id, knowledge_base_id)
);
CREATE INDEX idx_ai_knowledge_entity_alias_lookup_v20
    ON ai_knowledge_entity_alias (knowledge_base_id, normalized_alias);

CREATE TABLE ai_knowledge_entity_embedding (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entity_id         UUID NOT NULL,
    knowledge_base_id BIGINT NOT NULL,
    source_run_id     UUID NOT NULL,
    model_id          VARCHAR(128) NOT NULL,
    embedding         vector(1536) NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_knowledge_entity_embedding_v20 UNIQUE (entity_id, model_id),
    CONSTRAINT fk_ai_knowledge_entity_embedding_entity_v20
        FOREIGN KEY (entity_id, knowledge_base_id)
        REFERENCES ai_knowledge_entity(id, knowledge_base_id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_knowledge_entity_embedding_run_v20
        FOREIGN KEY (source_run_id, knowledge_base_id)
        REFERENCES ai_knowledge_ingest_run(id, knowledge_base_id)
);
CREATE INDEX idx_ai_knowledge_entity_embedding_hnsw_v20
    ON ai_knowledge_entity_embedding USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE TABLE ai_knowledge_fact (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    knowledge_base_id BIGINT NOT NULL REFERENCES ai_knowledge_base(id),
    subject_entity_id UUID NOT NULL,
    predicate         VARCHAR(500) NOT NULL,
    object_kind       VARCHAR(16) NOT NULL,
    object_entity_id  UUID,
    object_literal    TEXT,
    fact_key          VARCHAR(64) NOT NULL,
    confidence        DOUBLE PRECISION NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_knowledge_fact_key_v20 UNIQUE (knowledge_base_id, fact_key),
    CONSTRAINT uk_ai_knowledge_fact_base_v20 UNIQUE (id, knowledge_base_id),
    CONSTRAINT fk_ai_knowledge_fact_subject_v20
        FOREIGN KEY (subject_entity_id, knowledge_base_id)
        REFERENCES ai_knowledge_entity(id, knowledge_base_id),
    CONSTRAINT fk_ai_knowledge_fact_object_v20
        FOREIGN KEY (object_entity_id, knowledge_base_id)
        REFERENCES ai_knowledge_entity(id, knowledge_base_id),
    CONSTRAINT ck_ai_knowledge_fact_object_v20 CHECK (
        (object_kind = 'ENTITY' AND object_entity_id IS NOT NULL AND object_literal IS NULL)
        OR (object_kind = 'LITERAL' AND object_entity_id IS NULL AND object_literal IS NOT NULL)
    )
);

CREATE TABLE ai_knowledge_evidence (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id            UUID NOT NULL,
    document_id       BIGINT NOT NULL,
    knowledge_base_id BIGINT NOT NULL,
    focus_chunk_id    UUID NOT NULL,
    quote             TEXT NOT NULL,
    quote_hash               VARCHAR(64) NOT NULL,
    context_chunk_ids        UUID[] NOT NULL DEFAULT '{}',
    reference_time           TIMESTAMP WITH TIME ZONE,
    reference_time_precision VARCHAR(16),
    reference_time_source    VARCHAR(32),
    created_at               TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_knowledge_evidence_quote_v20
        UNIQUE (run_id, focus_chunk_id, quote_hash),
    CONSTRAINT uk_ai_knowledge_evidence_base_v20 UNIQUE (id, knowledge_base_id),
    CONSTRAINT fk_ai_knowledge_evidence_source_v20
        FOREIGN KEY (focus_chunk_id, run_id, document_id, knowledge_base_id)
        REFERENCES ai_knowledge_chunk(stable_id, run_id, document_id, knowledge_base_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_ai_knowledge_evidence_reference_time_v20 CHECK (
        (reference_time IS NULL
            AND reference_time_precision IS NULL
            AND reference_time_source IS NULL)
        OR (reference_time IS NOT NULL
            AND reference_time_precision IN ('EXACT', 'DAY', 'MONTH', 'YEAR', 'UNKNOWN')
            AND reference_time_source IN ('SOURCE', 'DOCUMENT', 'EXPLICIT'))
    )
);

CREATE TABLE ai_knowledge_evidence_span (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    evidence_id  UUID NOT NULL REFERENCES ai_knowledge_evidence(id) ON DELETE CASCADE,
    start_offset INTEGER NOT NULL,
    end_offset   INTEGER NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_knowledge_evidence_span_v20
        UNIQUE (evidence_id, start_offset, end_offset),
    CONSTRAINT ck_ai_knowledge_evidence_span_v20
        CHECK (start_offset >= 0 AND end_offset > start_offset)
);

CREATE OR REPLACE FUNCTION validate_ai_knowledge_assertion_attributes_v20(
    checked_attributes JSONB)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
STRICT
PARALLEL SAFE
AS $$
    SELECT jsonb_typeof(checked_attributes) = 'object'
       AND octet_length(convert_to(checked_attributes::text, 'UTF8')) <= 16384
       AND (SELECT COUNT(*) FROM jsonb_object_keys(checked_attributes)) <= 64
       AND NOT EXISTS (
           SELECT 1
           FROM jsonb_each(checked_attributes) attribute
           WHERE attribute.key !~ '^[A-Za-z][A-Za-z0-9_.-]{0,63}$'
              OR attribute.key IN (
                  'assertionId', 'factId', 'evidenceId', 'validAt', 'invalidAt',
                  'recordedAt', 'expiredAt', 'expirationReason', 'referenceTime',
                  'knowledgeBaseId', 'documentId', 'sourceId', 'runId')
              OR jsonb_typeof(attribute.value) NOT IN ('string', 'number', 'boolean', 'array')
              OR (jsonb_typeof(attribute.value) = 'array' AND EXISTS (
                  SELECT 1
                  FROM jsonb_array_elements(attribute.value) item
                  WHERE jsonb_typeof(item) NOT IN ('string', 'number', 'boolean')
              ))
       );
$$;

CREATE TABLE ai_knowledge_fact_evidence (
    assertion_id       UUID NOT NULL DEFAULT gen_random_uuid(),
    fact_id            UUID NOT NULL,
    evidence_id        UUID NOT NULL,
    knowledge_base_id  BIGINT NOT NULL,
    extract_confidence DOUBLE PRECISION NOT NULL,
    valid_at           TIMESTAMP WITH TIME ZONE,
    invalid_at         TIMESTAMP WITH TIME ZONE,
    recorded_at        TIMESTAMP WITH TIME ZONE,
    expired_at         TIMESTAMP WITH TIME ZONE,
    expiration_reason  VARCHAR(32),
    attributes         JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (fact_id, evidence_id),
    CONSTRAINT uk_ai_knowledge_assertion_id_v20 UNIQUE (assertion_id),
    CONSTRAINT fk_ai_knowledge_fact_evidence_fact_v20
        FOREIGN KEY (fact_id, knowledge_base_id)
        REFERENCES ai_knowledge_fact(id, knowledge_base_id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_knowledge_fact_evidence_evidence_v20
        FOREIGN KEY (evidence_id, knowledge_base_id)
        REFERENCES ai_knowledge_evidence(id, knowledge_base_id) ON DELETE CASCADE,
    CONSTRAINT ck_ai_knowledge_assertion_valid_interval_v20
        CHECK (valid_at IS NULL OR invalid_at IS NULL OR valid_at < invalid_at),
    CONSTRAINT ck_ai_knowledge_assertion_system_interval_v20
        CHECK (recorded_at IS NULL OR expired_at IS NULL OR recorded_at <= expired_at),
    CONSTRAINT ck_ai_knowledge_assertion_expiration_v20 CHECK (
        (expired_at IS NULL AND expiration_reason IS NULL)
        OR (recorded_at IS NOT NULL
            AND expired_at IS NOT NULL
            AND expiration_reason IN (
                'SOURCE_SUPERSEDED', 'SOURCE_REVOKED', 'CONTRADICTED'))
    ),
    CONSTRAINT ck_ai_knowledge_assertion_attributes_v20
        CHECK (validate_ai_knowledge_assertion_attributes_v20(attributes))
);
CREATE INDEX idx_ai_knowledge_evidence_document_run_v20
    ON ai_knowledge_evidence (document_id, run_id, id);
CREATE INDEX idx_ai_knowledge_assertion_current_fact_v20
    ON ai_knowledge_fact_evidence (fact_id, recorded_at)
    WHERE recorded_at IS NOT NULL AND expired_at IS NULL;
CREATE INDEX idx_ai_knowledge_assertion_evidence_v20
    ON ai_knowledge_fact_evidence (evidence_id, recorded_at, expired_at);
CREATE INDEX idx_ai_knowledge_assertion_asof_v20
    ON ai_knowledge_fact_evidence
       (fact_id, recorded_at, expired_at, valid_at, invalid_at);

CREATE OR REPLACE FUNCTION check_ai_knowledge_generation_consistency_v20(
    checked_document_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    active_run UUID;
    published_count BIGINT;
    matching_count BIGINT;
BEGIN
    SELECT document.active_run_id
    INTO active_run
    FROM ai_knowledge_document document
    WHERE document.id = checked_document_id;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    SELECT COUNT(*),
           COUNT(*) FILTER (WHERE run.id IS NOT DISTINCT FROM active_run)
    INTO published_count, matching_count
    FROM ai_knowledge_ingest_run run
    WHERE run.document_id = checked_document_id
      AND run.status = 'PUBLISHED';

    IF active_run IS NULL AND published_count <> 0 THEN
        RAISE EXCEPTION
            'document % 没有 active_run_id，但存在 % 个 PUBLISHED run',
            checked_document_id, published_count;
    END IF;
    IF active_run IS NOT NULL
       AND (published_count <> 1 OR matching_count <> 1) THEN
        RAISE EXCEPTION
            'document % 的 active_run_id % 与 PUBLISHED run 不一致',
            checked_document_id, active_run;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM ai_knowledge_fact_evidence assertion
        JOIN ai_knowledge_evidence evidence ON evidence.id = assertion.evidence_id
        JOIN ai_knowledge_ingest_run run ON run.id = evidence.run_id
        WHERE evidence.document_id = checked_document_id
          AND (
              (run.status IN ('QUEUED', 'PROCESSING', 'READY', 'FAILED')
               AND (assertion.recorded_at IS NOT NULL
                    OR assertion.expired_at IS NOT NULL
                    OR assertion.expiration_reason IS NOT NULL))
              OR (run.status = 'PUBLISHED' AND assertion.recorded_at IS NULL)
              OR (run.status = 'SUPERSEDED'
                  AND (assertion.recorded_at IS NULL
                       OR assertion.expired_at IS NULL
                       OR assertion.expiration_reason IS NULL))
          )
    ) THEN
        RAISE EXCEPTION 'document % 存在与 run 状态不一致的断言时间', checked_document_id;
    END IF;
END;
$$;

-- 延迟触发器每次按事务最终状态检查；不得缓存结果，否则 SET CONSTRAINTS 后的继续写入可能绕过提交校验。
CREATE OR REPLACE FUNCTION check_ai_knowledge_assertion_v20(
    checked_assertion_id UUID)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    assertion_row RECORD;
BEGIN
    SELECT run.status, assertion.recorded_at, assertion.expired_at,
           assertion.expiration_reason
    INTO assertion_row
    FROM ai_knowledge_fact_evidence assertion
    JOIN ai_knowledge_evidence evidence ON evidence.id = assertion.evidence_id
    JOIN ai_knowledge_ingest_run run ON run.id = evidence.run_id
    WHERE assertion.assertion_id = checked_assertion_id;
    IF NOT FOUND THEN
        RETURN;
    END IF;

    IF (assertion_row.status IN ('QUEUED', 'PROCESSING', 'READY', 'FAILED')
        AND (assertion_row.recorded_at IS NOT NULL
             OR assertion_row.expired_at IS NOT NULL
             OR assertion_row.expiration_reason IS NOT NULL))
       OR (assertion_row.status = 'PUBLISHED'
           AND assertion_row.recorded_at IS NULL)
       OR (assertion_row.status = 'SUPERSEDED'
           AND (assertion_row.recorded_at IS NULL
                OR assertion_row.expired_at IS NULL
                OR assertion_row.expiration_reason IS NULL)) THEN
        RAISE EXCEPTION 'assertion % 与 run 状态 % 不一致',
            checked_assertion_id, assertion_row.status;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION enforce_ai_knowledge_document_generation_v20()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM check_ai_knowledge_generation_consistency_v20(NEW.id);
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION enforce_ai_knowledge_run_generation_v20()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        PERFORM check_ai_knowledge_generation_consistency_v20(OLD.document_id);
    ELSIF TG_OP = 'UPDATE' THEN
        PERFORM check_ai_knowledge_generation_consistency_v20(OLD.document_id);
        IF NEW.document_id IS DISTINCT FROM OLD.document_id THEN
            PERFORM check_ai_knowledge_generation_consistency_v20(NEW.document_id);
        END IF;
    ELSE
        PERFORM check_ai_knowledge_generation_consistency_v20(NEW.document_id);
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION enforce_ai_knowledge_assertion_generation_v20()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM check_ai_knowledge_assertion_v20(
        CASE WHEN TG_OP = 'DELETE' THEN OLD.assertion_id ELSE NEW.assertion_id END);
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER ct_ai_knowledge_document_generation_v20
AFTER INSERT OR UPDATE OF active_run_id ON ai_knowledge_document
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION enforce_ai_knowledge_document_generation_v20();

CREATE CONSTRAINT TRIGGER ct_ai_knowledge_run_generation_v20
AFTER INSERT OR UPDATE OF id, document_id, knowledge_base_id, status OR DELETE
ON ai_knowledge_ingest_run
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION enforce_ai_knowledge_run_generation_v20();

CREATE CONSTRAINT TRIGGER ct_ai_knowledge_assertion_generation_v20
AFTER INSERT OR UPDATE OR DELETE ON ai_knowledge_fact_evidence
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION enforce_ai_knowledge_assertion_generation_v20();

CREATE TABLE ai_knowledge_graph_outbox (
    event_id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_key            VARCHAR(500) NOT NULL UNIQUE,
    knowledge_base_id    BIGINT NOT NULL REFERENCES ai_knowledge_base(id),
    aggregate_type       VARCHAR(32) NOT NULL,
    aggregate_id         UUID NOT NULL,
    run_id               UUID,
    projection_watermark BIGINT NOT NULL,
    event_type           VARCHAR(32) NOT NULL,
    status            VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    attempts          INTEGER NOT NULL DEFAULT 0,
    available_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    error_message     VARCHAR(2000),
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_knowledge_graph_outbox_run_v20
        FOREIGN KEY (run_id, knowledge_base_id)
        REFERENCES ai_knowledge_ingest_run(id, knowledge_base_id),
    CONSTRAINT ck_ai_knowledge_graph_outbox_status_v20
        CHECK (status IN ('PENDING', 'PROCESSING', 'DONE', 'DEAD'))
);
CREATE INDEX idx_ai_knowledge_graph_outbox_poll_v20
    ON ai_knowledge_graph_outbox (status, available_at, created_at);

CREATE TABLE ai_knowledge_projection_checkpoint (
    knowledge_base_id BIGINT NOT NULL REFERENCES ai_knowledge_base(id),
    projection_kind   VARCHAR(16) NOT NULL,
    desired_watermark BIGINT NOT NULL DEFAULT 0,
    applied_watermark BIGINT NOT NULL DEFAULT 0,
    rebuild_request_key VARCHAR(200),
    status            VARCHAR(16) NOT NULL,
    error_message     VARCHAR(2000),
    updated_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (knowledge_base_id, projection_kind),
    CONSTRAINT ck_ai_knowledge_projection_watermark_v20
        CHECK (desired_watermark >= 0 AND applied_watermark >= 0
               AND applied_watermark <= desired_watermark),
    CONSTRAINT ck_ai_knowledge_projection_kind_v20
        CHECK (projection_kind IN ('PGVECTOR', 'NEO4J')),
    CONSTRAINT ck_ai_knowledge_projection_status_v20
        CHECK (status IN ('READY', 'REBUILDING', 'DEGRADED'))
);
