-- ============================================================
-- AI 基础设施 Schema
-- 包含：知识库、记忆、模型管理、Prompt模板、Token用量、Agent、Assistant、Team
-- ============================================================

-- ============================================================
-- 知识库
-- ============================================================

CREATE TABLE ai_knowledge_base (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(200) NOT NULL,
    description     VARCHAR(1000),
    embedding_model VARCHAR(100),
    chunk_strategy  VARCHAR(50),
    chunk_size      INTEGER          DEFAULT 512,
    chunk_overlap   INTEGER          DEFAULT 64,
    status          INTEGER      NOT NULL DEFAULT 0,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE ai_knowledge_base IS '知识库';

CREATE TABLE ai_knowledge_document (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    knowledge_base_id BIGINT       NOT NULL REFERENCES ai_knowledge_base(id),
    title             VARCHAR(500) NOT NULL,
    file_path         VARCHAR(1000),
    file_type         VARCHAR(50),
    file_size         BIGINT,
    content_hash      VARCHAR(64),
    status            INTEGER      NOT NULL DEFAULT 0,
    error_message     VARCHAR(2000),
    chunk_count       INTEGER          DEFAULT 0,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id          BIGINT,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            TEXT
);

COMMENT ON TABLE ai_knowledge_document IS '知识库文档';
CREATE INDEX idx_ai_knowledge_document_base ON ai_knowledge_document(knowledge_base_id);

CREATE TABLE ai_knowledge_chunk (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id       BIGINT       NOT NULL REFERENCES ai_knowledge_document(id),
    knowledge_base_id BIGINT       NOT NULL REFERENCES ai_knowledge_base(id),
    content           TEXT         NOT NULL,
    chunk_index       INTEGER      NOT NULL DEFAULT 0,
    metadata          JSONB,
    token_count       INTEGER          DEFAULT 0,
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ai_knowledge_chunk IS '知识库文本块';
CREATE INDEX idx_ai_knowledge_chunk_document ON ai_knowledge_chunk(document_id);
CREATE INDEX idx_ai_knowledge_chunk_base ON ai_knowledge_chunk(knowledge_base_id);

CREATE TABLE ai_knowledge_embedding (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    content           TEXT,
    metadata          JSONB,
    embedding         vector(1536),
    chunk_id          BIGINT       REFERENCES ai_knowledge_chunk(id),
    knowledge_base_id BIGINT       REFERENCES ai_knowledge_base(id),
    model_name        VARCHAR(50),
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ai_knowledge_embedding IS '知识库向量嵌入（兼容 Spring AI VectorStore）';
COMMENT ON COLUMN ai_knowledge_embedding.embedding IS '固定 1536 维：写入的嵌入须由 1536 维模型生成；更换嵌入维度需迁移本列与索引';
CREATE INDEX idx_ai_knowledge_embedding_chunk ON ai_knowledge_embedding(chunk_id);
CREATE INDEX idx_ai_knowledge_embedding_base ON ai_knowledge_embedding(knowledge_base_id);
CREATE INDEX idx_ai_knowledge_embedding_hnsw ON ai_knowledge_embedding
    USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- ============================================================
-- 记忆
-- ============================================================

CREATE TABLE ai_memory_atom (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          BIGINT                   NOT NULL,
    scope            VARCHAR(20)              NOT NULL,
    content          TEXT                     NOT NULL,
    embedding        vector(1536),
    event_time       TIMESTAMP WITH TIME ZONE NOT NULL,
    valid_from       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    valid_to         TIMESTAMP WITH TIME ZONE,
    weight           DOUBLE PRECISION         NOT NULL DEFAULT 0.5,
    access_count     INTEGER                  NOT NULL DEFAULT 0,
    last_accessed_at TIMESTAMP WITH TIME ZONE,
    tags             TEXT[],
    metadata         JSONB,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE ai_memory_atom IS '记忆原子：scope = short_term / long_term / episodic / procedural';
COMMENT ON COLUMN ai_memory_atom.embedding IS '固定 1536 维：须与知识库嵌入使用同一 1536 维模型，便于记忆/知识跨域检索';
CREATE INDEX idx_ai_memory_atom_user_scope  ON ai_memory_atom(user_id, scope);
CREATE INDEX idx_ai_memory_atom_user_event  ON ai_memory_atom(user_id, event_time DESC);
CREATE INDEX idx_ai_memory_atom_user_weight ON ai_memory_atom(user_id, weight DESC);
CREATE INDEX idx_ai_memory_atom_tags        ON ai_memory_atom USING GIN(tags);
CREATE INDEX idx_ai_memory_atom_embedding   ON ai_memory_atom
    USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

CREATE TABLE ai_memory_relation (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id      UUID             NOT NULL REFERENCES ai_memory_atom(id) ON DELETE CASCADE,
    target_id      UUID             NOT NULL REFERENCES ai_memory_atom(id) ON DELETE CASCADE,
    relation_type  VARCHAR(50)      NOT NULL,
    weight         DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    edge_text      TEXT,
    edge_embedding vector(1536),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE ai_memory_relation IS '记忆原子间关系（用于 BundleSearch 图路由）';
CREATE INDEX idx_ai_memory_relation_source ON ai_memory_relation(source_id);
CREATE INDEX idx_ai_memory_relation_target ON ai_memory_relation(target_id);


-- ============================================================
-- 模型管理
-- ============================================================

CREATE TABLE ai_model_provider (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER          NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    provider_code       VARCHAR(64)      NOT NULL UNIQUE,
    provider_name       VARCHAR(128)     NOT NULL,
    provider_type       VARCHAR(32)      NOT NULL DEFAULT 'OPENAI_COMPAT',
    base_url            VARCHAR(512),
    api_key_encrypted   VARCHAR(1024),
    enabled             BOOLEAN          NOT NULL DEFAULT TRUE,
    sort_order          INTEGER          DEFAULT 100,
    icon                VARCHAR(100),
    description         TEXT,
    owner_id            BIGINT,
    create_by           BIGINT,
    create_by_type      VARCHAR(16),
    create_time         TIMESTAMP(6),
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6),
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN          NOT NULL DEFAULT FALSE,
    remark              TEXT
);

COMMENT ON TABLE ai_model_provider IS 'AI 模型供应商配置：统一维护同一供应商共享的 baseUrl 与 API Key';
COMMENT ON COLUMN ai_model_provider.provider_code IS '供应商编码：aliyun / volcengine / deepseek / third_party 等';
COMMENT ON COLUMN ai_model_provider.provider_type IS '默认协议类型：OPENAI_COMPAT / ANTHROPIC / OLLAMA';
COMMENT ON COLUMN ai_model_provider.api_key_encrypted IS '供应商级 API Key（加密存储）';

CREATE TABLE ai_model (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER          NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    model_id            VARCHAR(128)     NOT NULL UNIQUE,
    display_name        VARCHAR(128)     NOT NULL,
    provider_id         BIGINT,
    provider            VARCHAR(32)      NOT NULL,
    provider_type       VARCHAR(32)      NOT NULL DEFAULT 'OPENAI_COMPAT',
    model_name          VARCHAR(128)     NOT NULL,
    base_url            VARCHAR(512),
    api_key_encrypted   VARCHAR(1024),
    temperature         DOUBLE PRECISION,
    max_tokens          INTEGER,
    context_window      INTEGER,
    enable_thinking     BOOLEAN              DEFAULT FALSE,
    enabled             BOOLEAN          NOT NULL DEFAULT TRUE,
    capabilities        VARCHAR(256),
    input_price_per_k   NUMERIC(10, 6),
    output_price_per_k  NUMERIC(10, 6),
    fallback_model_id   VARCHAR(64),
    sort_order          INTEGER              DEFAULT 100,
    -- n1n.ai 价格相关字段
    model_ratio         NUMERIC(10, 6)   DEFAULT 1.0,
    completion_ratio    NUMERIC(10, 6)   DEFAULT 1.0,
    cache_ratio         NUMERIC(10, 6),
    audio_ratio         NUMERIC(10, 6),
    audio_completion_ratio NUMERIC(10, 6),
    step_ratios         JSONB,
    -- 能力与类型
    tags                VARCHAR(200),
    model_type          VARCHAR(50),
    supported_endpoints JSONB,
    -- 配额管理
    quota_type          SMALLINT         DEFAULT 0,
    model_price         NUMERIC(10, 6),
    -- 分组与供应商
    enable_groups       JSONB,
    vendor_id           BIGINT,
    vendor_name         VARCHAR(100),
    vendor_icon         VARCHAR(100),
    -- 显示
    icon                VARCHAR(100),
    description         TEXT,
    official_price      JSONB,
    -- 元数据
    owner_id            BIGINT,
    create_by           BIGINT,
    create_by_type      VARCHAR(16),
    create_time         TIMESTAMP(6),
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6),
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN          NOT NULL DEFAULT FALSE,
    remark              TEXT,
    image_config        JSONB,
    CONSTRAINT fk_ai_model_provider FOREIGN KEY (provider_id) REFERENCES ai_model_provider(id)
);

COMMENT ON TABLE ai_model IS 'AI 模型配置';
COMMENT ON COLUMN ai_model.provider_type     IS '协议类型：OPENAI_COMPAT / ANTHROPIC / OLLAMA';
COMMENT ON COLUMN ai_model.capabilities      IS '能力标记：CHAT,VISION,EMBEDDING,IMAGE_GEN,AUDIO,RERANK';
COMMENT ON COLUMN ai_model.image_config      IS '图像生成能力配置。ratio 模式：{"mode":"ratio","sizes":{"1:1":[[1024,1024],[1536,1536]],...},"features":{"edit":true,"seed":true,"promptExtend":true,"negativePrompt":true,"maxImages":6}}；fixed 模式：{"mode":"fixed","sizes":[[2688,1536],[2048,2048],[1536,2688]],"features":{...}}';
COMMENT ON COLUMN ai_model.input_price_per_k IS '输入 Token 单价（元/千Token）';
COMMENT ON COLUMN ai_model.output_price_per_k IS '输出 Token 单价（元/千Token）';
COMMENT ON COLUMN ai_model.model_ratio       IS '模型价格倍率（基础系数）';
COMMENT ON COLUMN ai_model.completion_ratio  IS '输出 Token 倍率';
COMMENT ON COLUMN ai_model.cache_ratio       IS '缓存 Token 倍率';
COMMENT ON COLUMN ai_model.audio_ratio       IS '音频输入倍率';
COMMENT ON COLUMN ai_model.audio_completion_ratio IS '音频输出倍率';
COMMENT ON COLUMN ai_model.step_ratios       IS '阶梯计费配置（JSON 数组）';
COMMENT ON COLUMN ai_model.tags              IS '能力标签（逗号分隔）：对话、识图、思考、工具等';
COMMENT ON COLUMN ai_model.model_type        IS '模型类型：文本、图像、音视频、检索';
COMMENT ON COLUMN ai_model.supported_endpoints IS '支持的接口类型（JSON 数组）';
COMMENT ON COLUMN ai_model.quota_type        IS '配额类型：0=token计费，1=次数计费，3/4=视频计费';
COMMENT ON COLUMN ai_model.model_price       IS '固定价格（quota_type=1 时使用）';
COMMENT ON COLUMN ai_model.enable_groups     IS '启用的用户组（JSON 数组）';
COMMENT ON COLUMN ai_model.provider_id       IS '供应商配置 ID（关联 ai_model_provider）';
COMMENT ON COLUMN ai_model.vendor_id         IS '供应商 ID（关联 vendor 表）';
COMMENT ON COLUMN ai_model.vendor_name       IS '供应商名称';
COMMENT ON COLUMN ai_model.official_price    IS '官方定价参考（JSON）';

CREATE TABLE ai_model_preference (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     INTEGER      NOT NULL DEFAULT 0,
    org_id      BIGINT,
    workspace_id BIGINT,
    scope       VARCHAR(16)  NOT NULL,
    scope_id    BIGINT,
    capability  VARCHAR(32)  NOT NULL,
    model_ids   JSONB        NOT NULL,
    owner_id    BIGINT,
    create_by   BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by   BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    remark      VARCHAR(255),
    CONSTRAINT uq_model_preference UNIQUE (scope, scope_id, capability)
);

COMMENT ON TABLE ai_model_preference IS '模型偏好配置';
COMMENT ON COLUMN ai_model_preference.scope     IS 'USER=用户级别 / SYSTEM=系统默认';
COMMENT ON COLUMN ai_model_preference.scope_id  IS '用户ID（scope=USER时），SYSTEM时为null';
COMMENT ON COLUMN ai_model_preference.capability IS '能力类型：CHAT/EMBEDDING/IMAGE_GEN/SPEECH_ASR等';
COMMENT ON COLUMN ai_model_preference.model_ids  IS '有序渠道列表，如 ["n1n:gpt-4o","openrouter:gpt-4o","openai:gpt-4o"]，按顺序降级';

CREATE TABLE ai_prompt_template (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    name             VARCHAR(128) NOT NULL,
    template_version INTEGER          NOT NULL DEFAULT 1,
    content          TEXT         NOT NULL,
    description      VARCHAR(512),
    variables        TEXT,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    category         VARCHAR(64),
    owner_id         BIGINT,
    create_by        BIGINT,
    create_by_type   VARCHAR(16),
    create_time      TIMESTAMP(6),
    update_by        BIGINT,
    update_by_type   VARCHAR(16),
    update_time      TIMESTAMP(6),
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    remark           TEXT,
    UNIQUE (name, template_version)
);

COMMENT ON TABLE ai_prompt_template IS 'Prompt 模板';

-- ============================================================
-- Token 用量
-- ============================================================

CREATE TABLE ai_token_usage (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    usage_id          VARCHAR(64)  NOT NULL,
    conversation_id   BIGINT,
    model_id          BIGINT       NOT NULL REFERENCES ai_model(id),
    prompt_tokens     BIGINT       NOT NULL,
    completion_tokens BIGINT       NOT NULL,
    total_tokens      BIGINT       NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ai_token_usage IS 'Token 用量记录（计费真理源）：扣费/额度核算以本表为准，ai_llm_call_log 仅为调用明细日志、不参与扣费';
COMMENT ON COLUMN ai_token_usage.usage_id IS '用量流水号，用于关联 credit_transaction.biz_id';
CREATE UNIQUE INDEX uk_ai_token_usage_usage_id ON ai_token_usage (usage_id);
CREATE INDEX idx_ai_token_usage_user_created  ON ai_token_usage (user_id, created_at);
CREATE INDEX idx_ai_token_usage_model_created ON ai_token_usage (model_id, created_at);

-- ============================================================
-- Agent / Assistant / Team
-- ============================================================

CREATE TABLE ai_agent_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    agent_id        VARCHAR(64)  NOT NULL UNIQUE,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    system_prompt   TEXT,
    model_id        BIGINT REFERENCES ai_model(id),
    capabilities    TEXT,
    tools           TEXT,
    allowed_tools   TEXT,
    mcp_servers     TEXT,
    max_iterations  INTEGER          NOT NULL DEFAULT 10,
    timeout_seconds INTEGER          NOT NULL DEFAULT 120,
    memory_config   JSONB,
    status          VARCHAR(16)  NOT NULL DEFAULT 'active',
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6),
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6),
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE ai_agent_definition IS 'Agent 定义';

CREATE TABLE ai_persona (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER      NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    name          VARCHAR(128) NOT NULL,
    persona       TEXT,
    system_prompt TEXT,
    avatar_url    VARCHAR(512),
    status        VARCHAR(16)  NOT NULL DEFAULT 'active',
    owner_id      BIGINT,
    create_by     BIGINT,
    create_by_type VARCHAR(16),
    create_time   TIMESTAMP(6),
    update_by     BIGINT,
    update_by_type VARCHAR(16),
    update_time   TIMESTAMP(6),
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    remark        TEXT
);

COMMENT ON TABLE ai_persona IS '人格模板：定义助理的名称、性格、系统提示词和头像，可被多个 Assistant 复用';
COMMENT ON COLUMN ai_persona.owner_id IS 'NULL=系统公共模板（所有用户可选）；有值=用户私有人格（仅所属用户可用）';

CREATE TABLE ai_role (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        INTEGER      NOT NULL DEFAULT 0,
    org_id         BIGINT,
    workspace_id   BIGINT,
    name           VARCHAR(128) NOT NULL,
    description    VARCHAR(512),
    skill_ids      TEXT,
    tool_whitelist TEXT,
    status         VARCHAR(16)  NOT NULL DEFAULT 'active',
    owner_id       BIGINT,
    create_by      BIGINT,
    create_by_type VARCHAR(16),
    create_time    TIMESTAMP(6),
    update_by      BIGINT,
    update_by_type VARCHAR(16),
    update_time    TIMESTAMP(6),
    delete_time    TIMESTAMP(6),
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    remark         TEXT
);

COMMENT ON TABLE  ai_role              IS 'Role（能力配置）：定义可复用的技能集与工具授权池（tool_whitelist），经 ai_assistant_role 挂载到助理，可跨助理复用';
COMMENT ON COLUMN ai_role.skill_ids      IS '绑定的技能 ID 列表（JSON 数组），技能为全局/可复用定义，统一经角色挂载';
COMMENT ON COLUMN ai_role.tool_whitelist IS '工具授权池（JSON 数组）：角色级工具上限，运行时与 Agent 级 allowed_tools 取交集后收窄';

CREATE TABLE ai_assistant (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    user_id           BIGINT       NOT NULL,
    delegator_id      BIGINT,
    permission_scope  JSONB,
    persona_id        BIGINT       NOT NULL REFERENCES ai_persona(id),
    default_role_id   BIGINT       NOT NULL REFERENCES ai_role(id),
    model_id          BIGINT       REFERENCES ai_model(id),
    memory_strategy   VARCHAR(32)  NOT NULL DEFAULT 'HYBRID',
    knowledge_base_id BIGINT,
    status            VARCHAR(16)  NOT NULL DEFAULT 'active',
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6),
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6),
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            TEXT
);

COMMENT ON TABLE  ai_assistant                IS 'Assistant 定义（Actor + 默认 Role + 记忆策略）';
COMMENT ON COLUMN ai_assistant.persona_id      IS '人格模板 ID（FK → ai_persona.id）';
COMMENT ON COLUMN ai_assistant.default_role_id IS '默认角色主键 ID（FK → ai_role.id）';
COMMENT ON COLUMN ai_assistant.model_id        IS '助理对话主模型（FK → ai_model.id，可空）；为空时由 CapabilityRouter 按 ai_model_preference 路由：显式绑定 → 用户偏好 → 系统默认';
CREATE INDEX idx_ai_assistant_user ON ai_assistant (user_id);

CREATE TABLE ai_assistant_role (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        INTEGER      NOT NULL DEFAULT 0,
    org_id         BIGINT,
    workspace_id   BIGINT,
    assistant_id   BIGINT       NOT NULL REFERENCES ai_assistant(id),
    role_id        BIGINT       NOT NULL REFERENCES ai_role(id),
    is_default     BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order     INTEGER      NOT NULL DEFAULT 100,
    owner_id       BIGINT,
    create_by      BIGINT,
    create_by_type VARCHAR(16),
    create_time    TIMESTAMP(6),
    update_by      BIGINT,
    update_by_type VARCHAR(16),
    update_time    TIMESTAMP(6),
    delete_time    TIMESTAMP(6),
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    remark         TEXT,
    CONSTRAINT uq_ai_assistant_role UNIQUE (assistant_id, role_id)
);

COMMENT ON TABLE  ai_assistant_role              IS '助理-角色关联（M:N）：一个角色可跨助理复用，一个助理可挂载多个角色';
COMMENT ON COLUMN ai_assistant_role.is_default   IS '冗余镜像 ai_assistant.default_role_id：以 ai_assistant.default_role_id 为默认角色的唯一真理源，本列仅为联表查询便利，须与之保持一致';
COMMENT ON COLUMN ai_assistant_role.sort_order   IS '排序值（越小越靠前）';
CREATE INDEX idx_ai_assistant_role_assistant ON ai_assistant_role (assistant_id);
CREATE INDEX idx_ai_assistant_role_role      ON ai_assistant_role (role_id);

CREATE TABLE ai_skill_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    agent_id        BIGINT REFERENCES ai_agent_definition(id),
    trigger_intent  TEXT,
    system_prompt   TEXT,
    instructions    TEXT,
    priority        INTEGER          NOT NULL DEFAULT 0,
    built_in        BOOLEAN      NOT NULL DEFAULT FALSE,
    is_global       BOOLEAN      NOT NULL DEFAULT FALSE,
    skill_version   VARCHAR(16),
    status          VARCHAR(16)  NOT NULL DEFAULT 'active',
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6),
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6),
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE ai_skill_definition IS '技能定义：全局/可复用，私有性由 owner_id 区分，统一经角色（ai_role.skill_ids）挂载';
COMMENT ON COLUMN ai_skill_definition.owner_id IS 'NULL=系统公共技能（所有角色可挂载）；有值=用户私有技能（仅所属用户可挂载）';

CREATE TABLE ai_action_catalog (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                  INTEGER      NOT NULL DEFAULT 0,
    org_id                   BIGINT,
    workspace_id             BIGINT,
    action_key               VARCHAR(120) NOT NULL,
    entity_slug              VARCHAR(120),
    display_name             VARCHAR(120) NOT NULL,
    description              VARCHAR(500),
    enabled                  BOOLEAN      NOT NULL DEFAULT TRUE,
    risk_level               VARCHAR(16)  NOT NULL DEFAULT 'low',
    require_confirm          BOOLEAN      NOT NULL DEFAULT FALSE,
    permission_code_override VARCHAR(120),
    entitlement_code         VARCHAR(64),
    cost_expression          VARCHAR(255),
    input_schema             TEXT,
    output_schema            TEXT,
    sort_order               INTEGER      NOT NULL DEFAULT 100,
    create_by                BIGINT,
    create_by_type           VARCHAR(16),
    create_time              TIMESTAMP(6),
    update_by                BIGINT,
    update_by_type           VARCHAR(16),
    update_time              TIMESTAMP(6),
    owner_id                 BIGINT,
    delete_time              TIMESTAMP(6),
    deleted                  BOOLEAN      NOT NULL DEFAULT FALSE,
    remark                   VARCHAR(255),
    CONSTRAINT uq_ai_action_catalog UNIQUE (entity_slug, action_key)
);

COMMENT ON TABLE ai_action_catalog IS 'AI 业务动作目录：代码 Adapter 定义能力边界，目录定义开放策略';
COMMENT ON COLUMN ai_action_catalog.action_key IS '动作标识，如 query/detail/create/update/delete';
COMMENT ON COLUMN ai_action_catalog.entity_slug IS '实体标识，如 system-role；专用业务动作可为空或使用业务域标识';
COMMENT ON COLUMN ai_action_catalog.risk_level IS '风险等级：low/medium/high';
COMMENT ON COLUMN ai_action_catalog.require_confirm IS '是否需要人工确认';
COMMENT ON COLUMN ai_action_catalog.permission_code_override IS '权限码覆写；为空时使用 Adapter 默认权限码';
COMMENT ON COLUMN ai_action_catalog.entitlement_code IS '权益编码；为空表示不走权益扣减';
COMMENT ON COLUMN ai_action_catalog.cost_expression IS '权益消耗表达式';
COMMENT ON COLUMN ai_action_catalog.input_schema IS '输入 JSON Schema，供 AI 发现能力与参数约束';
COMMENT ON COLUMN ai_action_catalog.output_schema IS '输出 JSON Schema';
CREATE INDEX idx_ai_action_catalog_entity ON ai_action_catalog (entity_slug);
CREATE INDEX idx_ai_action_catalog_enabled ON ai_action_catalog (enabled, sort_order);

CREATE TABLE ai_tool_catalog (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    tool_name        VARCHAR(120) NOT NULL UNIQUE,
    source           VARCHAR(32)  NOT NULL DEFAULT 'LOCAL',
    enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    tool_type        VARCHAR(32)  NOT NULL DEFAULT 'FUNCTION',
    category         VARCHAR(64),
    risk_level       VARCHAR(16)  NOT NULL DEFAULT 'LOW',
    read_only        BOOLEAN      NOT NULL DEFAULT FALSE,
    require_confirm  BOOLEAN      NOT NULL DEFAULT FALSE,
    permission_code  VARCHAR(120),
    entitlement_code VARCHAR(64),
    cost_expression  VARCHAR(255),
    input_schema     TEXT,
    output_schema    TEXT,
    sort_order       INTEGER      NOT NULL DEFAULT 100,
    create_by        BIGINT,
    create_by_type   VARCHAR(16),
    create_time      TIMESTAMP(6),
    update_by        BIGINT,
    update_by_type   VARCHAR(16),
    update_time      TIMESTAMP(6),
    owner_id         BIGINT,
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    remark           VARCHAR(255)
);

COMMENT ON TABLE ai_tool_catalog IS 'AI 工具目录：ToolCallback/MCP 定义能力边界，目录定义开放策略';
COMMENT ON COLUMN ai_tool_catalog.tool_name IS '工具名，对应 ToolCallback 或 MCP 工具名';
COMMENT ON COLUMN ai_tool_catalog.source IS '工具来源：LOCAL/MCP/CUSTOM/GENERATED';
COMMENT ON COLUMN ai_tool_catalog.tool_type IS '工具类型：FUNCTION/MCP/HTTP/SCRIPT/WORKFLOW/AGENT/GENERATIVE';
COMMENT ON COLUMN ai_tool_catalog.category IS '工具分类：BUSINESS_ACTION/IMAGE_GENERATION/VIDEO_GENERATION/MUSIC_GENERATION/MODEL3D_GENERATION 等';
COMMENT ON COLUMN ai_tool_catalog.risk_level IS '风险等级：NONE/LOW/MEDIUM/HIGH/CRITICAL';
COMMENT ON COLUMN ai_tool_catalog.read_only IS '是否只读工具';
COMMENT ON COLUMN ai_tool_catalog.require_confirm IS '是否强制人工确认';
COMMENT ON COLUMN ai_tool_catalog.permission_code IS '工具权限码；为空时使用 tool:{toolName}:execute 和 tool:default:execute';
COMMENT ON COLUMN ai_tool_catalog.entitlement_code IS '权益/积分门控编码；为空表示不检查额度';
COMMENT ON COLUMN ai_tool_catalog.cost_expression IS '预估消耗表达式；第一版支持固定数字';
CREATE INDEX idx_ai_tool_catalog_enabled ON ai_tool_catalog (enabled, sort_order);

CREATE TABLE ai_team (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                   INTEGER      NOT NULL DEFAULT 0,
    org_id                    BIGINT,
    workspace_id              BIGINT,
    name                      VARCHAR(128) NOT NULL,
    description               VARCHAR(512),
    collaboration_mode        VARCHAR(32)  NOT NULL DEFAULT 'LEADER_COORDINATED',
    coordinator_assistant_id  BIGINT REFERENCES ai_assistant(id),
    status                    VARCHAR(16)  NOT NULL DEFAULT 'active',
    owner_id                  BIGINT,
    create_by                 BIGINT,
    create_by_type            VARCHAR(16),
    create_time               TIMESTAMP(6),
    update_by                 BIGINT,
    update_by_type            VARCHAR(16),
    update_time               TIMESTAMP(6),
    delete_time               TIMESTAMP(6),
    deleted                   BOOLEAN      NOT NULL DEFAULT FALSE,
    remark                    TEXT
);

COMMENT ON TABLE ai_team IS '多智能体团队';

CREATE TABLE ai_team_member (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id      BIGINT       NOT NULL REFERENCES ai_team(id),
    assistant_id BIGINT       NOT NULL REFERENCES ai_assistant(id),
    role         VARCHAR(32)  NOT NULL DEFAULT 'member',
    capabilities TEXT,
    created_at   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (team_id, assistant_id)
);

COMMENT ON TABLE ai_team_member IS '团队成员';

CREATE TABLE ai_team_task (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id             BIGINT       NOT NULL REFERENCES ai_team(id),
    task_id             VARCHAR(64)  NOT NULL UNIQUE,
    parent_task_id      VARCHAR(64),
    assignee_id         BIGINT       REFERENCES ai_assistant(id),
    description         TEXT         NOT NULL,
    required_capability VARCHAR(128),
    status              VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    dependencies        TEXT,
    priority            INTEGER      NOT NULL DEFAULT 0,
    progress            INTEGER      NOT NULL DEFAULT 0,
    result              TEXT,
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ai_team_task IS '团队任务';
CREATE INDEX idx_ai_team_task_team_status ON ai_team_task (team_id, status);

-- ============================================================
-- 种子数据
-- ============================================================

-- 系统默认模型偏好
-- 注：向量列固定 vector(1536)，EMBEDDING 默认须选 1536 维模型（qwen:embedding 为 1024 维，不兼容）
INSERT INTO ai_model_preference (scope, scope_id, capability, model_ids)
VALUES
    ('SYSTEM', NULL, 'CHAT',      '["n1n:claude-sonnet-4-6"]'),
    ('SYSTEM', NULL, 'EMBEDDING', '["openai:text-embedding-3"]'),
    ('SYSTEM', NULL, 'IMAGE_GEN', '["openai:dall-e-3"]')
ON CONFLICT ON CONSTRAINT uq_model_preference DO NOTHING;

-- 第一期 12 个 provider 代表模型
-- capabilities: CHAT / EMBEDDING / VISION / IMAGE_GEN / AUDIO / RERANK
INSERT INTO ai_model (model_id, display_name, provider, provider_type, model_name, base_url,
                      capabilities, context_window, sort_order, enabled)
VALUES
-- P0: OpenAI
('n1n:text-embedding-3',  'text-embedding-3',   'n1n',     'OPENAI_COMPAT', 'text-embedding-3-small',     'https://llm-api.net/v1',                        'EMBEDDING',   8191,    1,  true),
('n1n:claude-sonnet-4-6', 'Claude Sonnet 4.6',  'n1n',     'OPENAI_COMPAT', 'claude-sonnet-4-6',          'https://llm-api.net/v1',                        'CHAT,VISION',   8191,  2,  true),
('n1n:claude-opus-4-8',   'Claude Ops 4.8',     'n1n',     'OPENAI_COMPAT', 'claude-opus-4-8',            'https://llm-api.net/v1',                        'CHAT,VISION',   8191,  3,  true),
('n1n:claude-fable-5',    'Claude Fable 5',     'n1n',     'OPENAI_COMPAT', 'claude-fable-5',             'https://llm-api.net/v1',                        'CHAT,VISION',   8191,  4,  true),
('n1n:gpt-5.4',           'GPT-4o',             'n1n',     'OPENAI_COMPAT', 'gpt-5.4',                   'https://llm-api.net/v1',                         'CHAT,VISION', 128000, 10,  true),
('n1n:gpt-5.4-mini',      'GPT-4o Mini',        'n1n',     'OPENAI_COMPAT', 'gpt-5.4-mini',              'https://llm-api.net/v1',                         'CHAT,VISION', 128000, 11,  true),

-- P0: DeepSeek
('deepseek:chat',           'DeepSeek Chat',      'deepseek',   'OPENAI_COMPAT', 'deepseek-chat',              'https://api.deepseek.com/v1',                       'CHAT',        64000,  20,  true),
('deepseek:reasoner',       'DeepSeek R1',        'deepseek',   'OPENAI_COMPAT', 'deepseek-reasoner',          'https://api.deepseek.com/v1',                       'CHAT',        64000,  21,  true),
-- P0: 通义千问
('qwen:qwen3.7-max',        'Qwen Max',           'qwen',       'OPENAI_COMPAT', 'qwen3.7-max',                   'https://dashscope.aliyuncs.com/compatible-mode/v1', 'CHAT',        32000,   30,  true),
('qwen:qwen3.7-plus',       'Qwen Plus',          'qwen',       'OPENAI_COMPAT', 'qwen3.7-plus',                  'https://dashscope.aliyuncs.com/compatible-mode/v1', 'CHAT',        1000000, 31,  true),
('qwen:qwen3.6-flash',      'Qwen Flash',         'qwen',      'OPENAI_COMPAT', 'qwen3.6-flash',                  'https://dashscope.aliyuncs.com/compatible-mode/v1', 'CHAT',        1000000, 32,  true),
('qwen:text-embedding-v4',  'Qwen Embedding',     'qwen',       'OPENAI_COMPAT', 'text-embedding-v4',            'https://dashscope.aliyuncs.com/compatible-mode/v1',  'EMBEDDING',       192, 33,  true),
-- -- P0: 月之暗面
-- ('moonshot:v1-128k',        'Kimi 128k',          'moonshot',   'OPENAI_COMPAT', 'moonshot-v1-128k',           'https://api.moonshot.cn/v1',                        'CHAT',        128000, 40,  true),
-- -- P1: 智谱
-- ('zhipu:glm-4',             'GLM-4',              'zhipu',      'OPENAI_COMPAT', 'glm-4',                      'https://open.bigmodel.cn/api/paas/v4',              'CHAT',        128000, 50,  true),
-- ('zhipu:glm-4v',            'GLM-4V',             'zhipu',      'OPENAI_COMPAT', 'glm-4v',                     'https://open.bigmodel.cn/api/paas/v4',              'CHAT,VISION', 2000,   51,  true),
-- -- P1: Anthropic
-- ('anthropic:claude-3-5-sonnet', 'Claude 3.5 Sonnet', 'anthropic', 'ANTHROPIC',  'claude-3-5-sonnet-20241022', 'https://api.anthropic.com',                         'CHAT,VISION', 200000, 60,  true),
-- ('anthropic:claude-3-haiku',    'Claude 3 Haiku',    'anthropic', 'ANTHROPIC',  'claude-3-haiku-20240307',    'https://api.anthropic.com',                         'CHAT,VISION', 200000, 61,  true),
-- -- P1: Ollama（本地，默认禁用）
-- ('ollama:llama3',           'Llama 3',            'ollama',     'OLLAMA',        'llama3',                     'http://localhost:11434',                            'CHAT',        8192,   70,  false),
-- ('ollama:qwen2.5',          'Qwen2.5 Local',      'ollama',     'OLLAMA',        'qwen2.5',                    'http://localhost:11434',                            'CHAT',        32768,  71,  false),
-- -- P1: 聚合平台
-- ('openrouter:claude-3-5',   'Claude 3.5 via OR',  'openrouter', 'OPENAI_COMPAT', 'anthropic/claude-3.5-sonnet','https://openrouter.ai/api/v1',                     'CHAT,VISION', 200000, 80,  true),
-- ('openrouter:gpt-4o',       'GPT-4o via OR',      'openrouter', 'OPENAI_COMPAT', 'openai/gpt-4o',              'https://openrouter.ai/api/v1',                     'CHAT,VISION', 128000, 81,  true),
-- ('linkai:gpt-4o',           'GPT-4o via LinkAI',  'linkai',     'OPENAI_COMPAT', 'gpt-4o',                     'https://api.link-ai.tech/v1',                      'CHAT,VISION', 128000, 100, true),
-- -- P1: 阶跃星辰
-- ('stepfun:step-2',          'Step-2',             'stepfun',    'OPENAI_COMPAT', 'step-2-16k',                 'https://api.stepfun.com/v1',                        'CHAT',        16000,  110, true),
-- ('stepfun:step-1v',         'Step-1V（视觉）',     'stepfun',    'OPENAI_COMPAT', 'step-1v-8k',                 'https://api.stepfun.com/v1',                        'CHAT,VISION', 8000,   111, true),
-- -- P1: 火山引擎
-- ('volcengine:doubao-pro',   'Doubao Pro',         'volcengine', 'OPENAI_COMPAT', 'doubao-pro-32k',             'https://ark.cn-beijing.volces.com/api/v3',          'CHAT',        32000,  120, true),
-- ('volcengine:doubao-lite',  'Doubao Lite',        'volcengine', 'OPENAI_COMPAT', 'doubao-lite-32k',            'https://ark.cn-beijing.volces.com/api/v3',          'CHAT',        32000,  121, true),
-- P1: 图像生成
('qwen:wan2.7-image',       '万相 Wan2.7',         'qwen',       'DASHSCOPE',     'wan2.7-image',                   'https://dashscope.aliyuncs.com',        'IMAGE_GEN', null, 210, true),
('qwen:qwen-image-2.0',       '千问图像 2.0',        'qwen',        'DASHSCOPE',     'qwen-image-2.0',                 'https://dashscope.aliyuncs.com',        'IMAGE_GEN', null, 211, true),
('n1n:gpt-image-2',         'GPT Image 2',         'n1n',        'OPENAI_COMPAT',  'gpt-image-2',                             'https://llm-api.net/v1',         'IMAGE_GEN', null, 212, true),
('n1n:gemini-3.1-flash-image-preview', 'Gemini 3.1 Flash Image', 'n1n',    'OPENAI_COMPAT', 'gemini-3.1-flash-image-preview', 'https://llm-api.net/v1',         'CHAT,IMAGE_GEN', null, 220, true),
('n1n:gemini-3-pro-image-preview',     'Gemini 3 Pro Image',     'n1n',    'OPENAI_COMPAT', 'gemini-3-pro-image-preview',     'https://llm-api.net/v1',         'CHAT,IMAGE_GEN', null, 221, true),
('n1n:doubao-260128seedream-5-0-',            '豆包 Seedream 5.0',      'n1n',    'OPENAI_COMPAT', 'doubao-seedream-5-0-260128',     'https://llm-api.net/v1',         'IMAGE_GEN',      null, 230, true),
-- P1: 视频生成
('qwen:happyhorse-1.0-i2v',   'HappyHorse',   'qwen',  'DASHSCOPE', 'happyhorse-1.0-i2v',               'https://dashscope.aliyuncs.com', 'VIDEO_GEN',       null, 350, true),
-- P1: 重排序
('qwen:qwen3-rerank',      'GTE Rerank v2',      'qwen',  'DASHSCOPE', 'qwen3-rerank',                     'https://dashscope.aliyuncs.com', 'RERANK',          null, 360, true),
-- P1: 语音识别（ASR）
('qwen:fun-asr-realtime',    '通义 ASR Flash',     'qwen',  'DASHSCOPE', 'fun-asr-realtime',                'https://dashscope.aliyuncs.com', 'SPEECH_ASR',      null, 310, true),
-- P1: 语音合成（TTS）
('qwen:cosyvoice-v3-flash', 'CosyVoice 3 Flash',  'qwen',  'DASHSCOPE', 'cosyvoice-v3-flash',             'https://dashscope.aliyuncs.com', 'SPEECH_TTS',      null, 320, true),
('qwen:cosyvoice-v3-plus',  'CosyVoice 3 Plus',   'qwen',  'DASHSCOPE', 'cosyvoice-v3-plus',              'https://dashscope.aliyuncs.com', 'SPEECH_TTS',      null, 321, true),
-- P1: 音乐生成
('qwen:fun-music-v1',       '文生音乐 v1',         'qwen',  'DASHSCOPE', 'fun-music-v1',            'https://dashscope.aliyuncs.com', 'MUSIC_GEN',       null, 330, true),
-- P1: 全模态实时
('qwen:qwen3-omni-flash-realtime',   'Qwen3 Omni Flash Realtime',   'qwen', 'DASHSCOPE', 'qwen-omni-flash-realtime',      'https://dashscope.aliyuncs.com', 'OMNI_REALTIME', null, 340, true),
('qwen:qwen3.5-omni-plus-realtime',  'Qwen3.5 Omni Plus Realtime',  'qwen', 'DASHSCOPE', 'qwen3.5-omni-plus-realtime',   'https://dashscope.aliyuncs.com', 'OMNI_REALTIME', null, 343, true)
ON CONFLICT (model_id) DO NOTHING;


-- ============================================================
-- 对话任务与持久执行（Durable Execution）
-- ============================================================

CREATE TABLE ai_chat_task (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    conversation_id BIGINT    NOT NULL,
    creator_id   BIGINT       NOT NULL,
    title        VARCHAR(500) NOT NULL,
    description  TEXT,
    status       VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    priority     INTEGER      NOT NULL DEFAULT 0,
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    scheduled_at TIMESTAMP(6),
    result       TEXT,
    owner_id     BIGINT,
    create_by    BIGINT,
    create_by_type VARCHAR(16),
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_by_type VARCHAR(16),
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       TEXT
);

COMMENT ON TABLE ai_chat_task IS '对话任务：用户在会话中提交的任务队列，助理按优先级逐个执行';
COMMENT ON COLUMN ai_chat_task.conversation_id IS '所属会话 ID（FK 语义指向 conversation.id，即 HarnessAgent 的 sessionId）';
COMMENT ON COLUMN ai_chat_task.status IS 'PENDING/RUNNING/DONE/FAILED/CANCELLED';
COMMENT ON COLUMN ai_chat_task.scheduled_at IS '定时执行时间，NULL 表示立即可执行';
CREATE INDEX idx_ai_chat_task_conversation ON ai_chat_task(conversation_id, deleted);
CREATE INDEX idx_ai_chat_task_status  ON ai_chat_task(status, scheduled_at) WHERE deleted = FALSE;

CREATE TABLE ai_task_execution (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER      NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    task_id             BIGINT       NOT NULL,
    parent_execution_id BIGINT,
    subtask_key         VARCHAR(100),
    attempt_no          INTEGER      NOT NULL DEFAULT 1,
    status              VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    role                VARCHAR(100),
    agent_id            BIGINT       REFERENCES ai_agent_definition(id),
    checkpoint_id       BIGINT,
    started_at          TIMESTAMP(6),
    ended_at            TIMESTAMP(6),
    error_message       TEXT,
    owner_id            BIGINT,
    create_by           BIGINT,
    create_by_type      VARCHAR(16),
    create_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    remark              TEXT
);

COMMENT ON TABLE ai_task_execution IS '任务执行实例：一个 ChatTask 可多次执行（重试），支持主/子关系（多实例协调）';
COMMENT ON COLUMN ai_task_execution.parent_execution_id IS '子任务指向主执行实例，NULL=主执行';
COMMENT ON COLUMN ai_task_execution.subtask_key IS '子任务标识，如 backend/frontend';
COMMENT ON COLUMN ai_task_execution.agent_id IS '本次执行所用的 Agent 定义（FK → ai_agent_definition.id）；NULL=助理本体执行/无具体 Agent。用于子 agent 委派拓扑追溯';
COMMENT ON COLUMN ai_task_execution.status IS 'PENDING/RUNNING/DONE/FAILED/CANCELLED/WAITING_APPROVAL';
CREATE INDEX idx_ai_task_execution_task   ON ai_task_execution(task_id, status) WHERE deleted = FALSE;
CREATE INDEX idx_ai_task_execution_parent ON ai_task_execution(parent_execution_id) WHERE parent_execution_id IS NOT NULL;

CREATE TABLE ai_task_checkpoint (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT       NOT NULL,
    scope        VARCHAR(20)  NOT NULL,
    step_index   INTEGER      NOT NULL DEFAULT 0,
    state_json   JSONB        NOT NULL,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ai_task_checkpoint IS '执行检查点快照：支持从最近检查点恢复';
COMMENT ON COLUMN ai_task_checkpoint.scope IS 'coordinator（主实例）/ subtask（子实例）/ agent_step（步骤级）';
COMMENT ON COLUMN ai_task_checkpoint.state_json IS '状态快照：TaskBoard / 步骤进度 / 工作记忆';
CREATE INDEX idx_ai_task_checkpoint_exec ON ai_task_checkpoint(execution_id, scope);

CREATE TABLE ai_task_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id      BIGINT       NOT NULL,
    execution_id BIGINT,
    subtask_key  VARCHAR(100),
    type         VARCHAR(50)  NOT NULL,
    payload_json JSONB,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ai_task_event IS '任务事件日志（append-only）：完整审计轨迹，支持 SSE 实时推送';
COMMENT ON COLUMN ai_task_event.type IS 'task_started/subtask_forked/step_started/step_completed/tool_called/checkpoint_saved/error/task_completed 等';
CREATE INDEX idx_ai_task_event_task      ON ai_task_event(task_id, create_time);
CREATE INDEX idx_ai_task_event_execution ON ai_task_event(execution_id);


-- ============================================================
-- MCP 服务器注册
-- ============================================================

CREATE TABLE ai_mcp_server (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     INTEGER      NOT NULL DEFAULT 0,
    name        VARCHAR(128) NOT NULL UNIQUE,
    url         VARCHAR(512) NOT NULL,
    description VARCHAR(512),
    transport   VARCHAR(16)  NOT NULL DEFAULT 'HTTP',
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    status      VARCHAR(16)  NOT NULL DEFAULT 'disconnected',
    create_time TIMESTAMP(6),
    update_time TIMESTAMP(6)
);

COMMENT ON TABLE ai_mcp_server IS 'MCP 服务器注册：工具发现与连接管理';
COMMENT ON COLUMN ai_mcp_server.transport IS '传输协议：HTTP / SSE / STDIO';
COMMENT ON COLUMN ai_mcp_server.status IS '连接状态：connected / disconnected / error';


-- ============================================================
-- 价值观规则
-- ============================================================

CREATE TABLE ai_value_rule (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     INTEGER      NOT NULL DEFAULT 0,
    org_id      BIGINT,
    workspace_id BIGINT,
    name        VARCHAR(128) NOT NULL,
    rule_type   VARCHAR(32)  NOT NULL DEFAULT 'FORBIDDEN',
    condition   TEXT         NOT NULL,
    priority    INTEGER      NOT NULL DEFAULT 0,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    scope       VARCHAR(16)  NOT NULL DEFAULT 'GLOBAL',
    tenant_id   BIGINT,
    create_by   BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by   BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id    BIGINT,
    delete_time TIMESTAMP(6),
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    remark      TEXT
);

COMMENT ON TABLE ai_value_rule IS '价值观/伦理约束规则：Agent 执行前内容过滤';
COMMENT ON COLUMN ai_value_rule.rule_type IS '规则类型：FORBIDDEN / REQUIRED / PREFERRED';
COMMENT ON COLUMN ai_value_rule.condition IS '规则条件描述（用于 LLM 判断或关键词匹配）';
COMMENT ON COLUMN ai_value_rule.scope IS '作用范围：GLOBAL / TENANT';
CREATE INDEX idx_ai_value_rule_enabled ON ai_value_rule(enabled, priority) WHERE deleted = FALSE;

-- ============================================================
-- AI 决策日志
-- ============================================================

CREATE TABLE ai_decision_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type      VARCHAR(16)  NOT NULL,
    scope_id        VARCHAR(128) NOT NULL,
    decision_point  TEXT         NOT NULL,
    options         JSONB,
    chosen_option   TEXT,
    rationale       TEXT,
    confidence      DOUBLE PRECISION,
    is_verifiable   BOOLEAN,
    review_status   VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    reviewer_id     BIGINT,
    reviewed_at     TIMESTAMP(6),
    review_comment  TEXT,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ai_decision_log IS 'AI 自主决策审计日志（append-only），支持异步人工审查';
COMMENT ON COLUMN ai_decision_log.scope_type IS 'AGENT / ASSISTANT / TEAM';
COMMENT ON COLUMN ai_decision_log.scope_id IS '对应执行实例 ID';
COMMENT ON COLUMN ai_decision_log.options IS '备选方案：[{option, pros, cons}]';
COMMENT ON COLUMN ai_decision_log.confidence IS '置信度 0.0~1.0';
COMMENT ON COLUMN ai_decision_log.review_status IS 'PENDING / APPROVED / REJECTED';
COMMENT ON COLUMN ai_decision_log.reviewed_at IS '人工审查完成时间，NULL=尚未审查';
COMMENT ON COLUMN ai_decision_log.review_comment IS '审查意见（批准/驳回理由），供异步审查留痕';
CREATE INDEX idx_ai_decision_log_scope  ON ai_decision_log(scope_type, scope_id);
CREATE INDEX idx_ai_decision_log_review ON ai_decision_log(review_status) WHERE review_status = 'PENDING';


-- ============================================================
-- 工具调用记录
-- ============================================================

CREATE TABLE ai_tool_call_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id          BIGINT,
    workspace_id    BIGINT,
    -- 调用上下文
    execution_id    BIGINT       REFERENCES ai_task_execution(id),
    session_id      BIGINT,
    user_id         BIGINT,
    call_id         VARCHAR(64)  NOT NULL,          -- LLM 返回的 tool_call_id（Function Calling）
    -- 工具信息
    tool_name       VARCHAR(120) NOT NULL,
    tool_source     VARCHAR(32)  NOT NULL DEFAULT 'LOCAL',  -- LOCAL/MCP
    -- 调用内容
    arguments       JSONB,                                  -- 入参（LLM 传入）
    result          TEXT,                                   -- 执行结果（截断存储，超长存 OSS/路径）
    result_summary  VARCHAR(500),                           -- 结果摘要（供 UI 展示）
    -- 执行状态
    status          VARCHAR(16)  NOT NULL DEFAULT 'SUCCESS', -- SUCCESS/FAILED/TIMEOUT/REJECTED
    error_message   TEXT,
    duration_ms     INTEGER,                                -- 执行耗时（毫秒）
    -- 风控
    risk_level      VARCHAR(16)  NOT NULL DEFAULT 'LOW',
    confirmed_by    BIGINT,                                 -- 人工确认者，NULL=无需确认
    confirmed_at    TIMESTAMP(6),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE  ai_tool_call_log               IS '工具调用记录（append-only）';
COMMENT ON COLUMN ai_tool_call_log.call_id        IS 'LLM Function Calling 返回的 tool_call_id';
COMMENT ON COLUMN ai_tool_call_log.tool_source    IS '工具来源：LOCAL/MCP';
COMMENT ON COLUMN ai_tool_call_log.arguments      IS '大模型传入的调用参数（原始 JSON）';
COMMENT ON COLUMN ai_tool_call_log.result         IS '工具执行结果，超过 64KB 时截断，完整结果存外部存储';
COMMENT ON COLUMN ai_tool_call_log.status         IS '执行状态：SUCCESS/FAILED/TIMEOUT/REJECTED（风控拦截）';
COMMENT ON COLUMN ai_tool_call_log.confirmed_by   IS '人工确认操作者，NULL 表示无需确认或系统自动放行';

CREATE INDEX idx_ai_tool_call_log_execution ON ai_tool_call_log(execution_id);
CREATE INDEX idx_ai_tool_call_log_session   ON ai_tool_call_log(session_id, create_time);
CREATE INDEX idx_ai_tool_call_log_tool      ON ai_tool_call_log(tool_name, create_time);
CREATE INDEX idx_ai_tool_call_log_call_id   ON ai_tool_call_log(call_id);

-- ============================================================
-- 大模型调用记录
-- ============================================================

CREATE TABLE ai_llm_call_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id           BIGINT,
    workspace_id     BIGINT,
    -- 调用上下文
    execution_id     BIGINT       REFERENCES ai_task_execution(id),
    session_id       BIGINT,
    user_id          BIGINT,
    -- 模型信息
    model_id         VARCHAR(128) NOT NULL,                 -- ai_model.model_id（不用 FK，容许模型删除后日志仍在）
    provider         VARCHAR(32)  NOT NULL,
    -- 调用内容
    call_purpose     VARCHAR(64),                           -- 调用意图：CHAT/PLANNING/SUMMARIZE/EMBEDDING 等
    system_prompt    TEXT,
    messages         JSONB,                                 -- 完整消息列表（含 tool_calls / tool_results）
    response         TEXT,                                  -- 模型输出文本
    finish_reason    VARCHAR(32),                           -- stop/tool_calls/length/content_filter
    -- Token 用量
    prompt_tokens    INTEGER      NOT NULL DEFAULT 0,
    completion_tokens INTEGER     NOT NULL DEFAULT 0,
    total_tokens     INTEGER      NOT NULL DEFAULT 0,
    -- 性能
    ttfb_ms          INTEGER,                               -- 首 Token 延迟（毫秒）
    duration_ms      INTEGER,                               -- 总耗时（毫秒）
    -- 状态
    status           VARCHAR(16)  NOT NULL DEFAULT 'SUCCESS', -- SUCCESS/FAILED/TIMEOUT/RATE_LIMITED
    error_code       VARCHAR(64),
    error_message    TEXT,
    -- 追踪
    trace_id         VARCHAR(64),                           -- 链路追踪 ID，对接 OpenTelemetry
    create_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE  ai_llm_call_log                 IS '大模型调用记录（append-only）：可观测/分析用途的调用明细，token 字段不参与扣费，计费以 ai_token_usage 为准';
COMMENT ON COLUMN ai_llm_call_log.model_id         IS '对应 ai_model.model_id，不用外键以允许模型下线后日志保留';
COMMENT ON COLUMN ai_llm_call_log.call_purpose     IS '调用意图：CHAT/TOOL_DECISION/PLANNING/SUMMARIZE/EMBEDDING 等';
COMMENT ON COLUMN ai_llm_call_log.messages         IS '完整消息列表，含 function_call 和 tool 角色消息';
COMMENT ON COLUMN ai_llm_call_log.finish_reason    IS 'stop=正常结束 / tool_calls=触发工具 / length=截断 / content_filter=安全拦截';
COMMENT ON COLUMN ai_llm_call_log.ttfb_ms          IS '首 Token 延迟，流式场景有效';
COMMENT ON COLUMN ai_llm_call_log.trace_id         IS '链路追踪 ID，便于与 OpenTelemetry / Langfuse 对接';

CREATE INDEX idx_ai_llm_call_log_execution ON ai_llm_call_log(execution_id);
CREATE INDEX idx_ai_llm_call_log_session   ON ai_llm_call_log(session_id, create_time);
CREATE INDEX idx_ai_llm_call_log_model     ON ai_llm_call_log(model_id, create_time);
CREATE INDEX idx_ai_llm_call_log_user      ON ai_llm_call_log(user_id, create_time);
CREATE INDEX idx_ai_llm_call_log_trace     ON ai_llm_call_log(trace_id) WHERE trace_id IS NOT NULL;


-- ============================================================
-- 技能触发记录
-- ============================================================

CREATE TABLE ai_skill_trigger_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    -- 触发上下文
    execution_id BIGINT       REFERENCES ai_task_execution(id),
    session_id   BIGINT,
    user_id      BIGINT,
    assistant_id BIGINT       REFERENCES ai_assistant(id),
    -- 技能信息
    skill_id     BIGINT       NOT NULL REFERENCES ai_skill_definition(id),
    skill_name   VARCHAR(128) NOT NULL,              -- 冗余存储，防技能改名后日志失真
    -- 意图匹配
    user_input   TEXT,                               -- 触发时的原始用户输入
    matched_intent VARCHAR(256),                     -- 命中的意图关键词/表达式
    match_score  DOUBLE PRECISION,                   -- 匹配置信度 0.0~1.0
    -- 执行状态
    status       VARCHAR(16)  NOT NULL DEFAULT 'SUCCESS', -- SUCCESS/FAILED/SKIPPED（被更高优先级技能覆盖）
    error_message TEXT,
    duration_ms  INTEGER,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE  ai_skill_trigger_log              IS '技能触发记录（append-only）';
COMMENT ON COLUMN ai_skill_trigger_log.skill_name    IS '触发时的技能名称冗余，防止技能改名后历史日志失真';
COMMENT ON COLUMN ai_skill_trigger_log.matched_intent IS '命中的意图表达式或关键词，对应 ai_skill_definition.trigger_intent';
COMMENT ON COLUMN ai_skill_trigger_log.match_score   IS '意图匹配置信度 0.0~1.0';
COMMENT ON COLUMN ai_skill_trigger_log.status        IS 'SUCCESS=正常触发执行 / FAILED=执行异常 / SKIPPED=被更高优先级技能覆盖';

CREATE INDEX idx_ai_skill_trigger_log_skill     ON ai_skill_trigger_log(skill_id, create_time);
CREATE INDEX idx_ai_skill_trigger_log_session   ON ai_skill_trigger_log(session_id, create_time);
CREATE INDEX idx_ai_skill_trigger_log_execution ON ai_skill_trigger_log(execution_id);


-- ============================================================
-- AI 工作流执行记录
-- 注：审批流运行时由 Flowable 自身表管理，此处仅记录 AI 工作流（LlmNode/AgentNode 等节点）的执行链路
-- ============================================================

CREATE TABLE ai_workflow_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id          BIGINT,
    workspace_id    BIGINT,
    -- 关联上下文
    execution_id    BIGINT       REFERENCES ai_task_execution(id),
    session_id      BIGINT,
    user_id         BIGINT,
    -- 工作流定义（Flowable process definition key）
    workflow_key    VARCHAR(128) NOT NULL,
    workflow_name   VARCHAR(128),                          -- 触发时冗余，防定义改名
    workflow_version INTEGER     NOT NULL DEFAULT 1,
    -- Flowable 运行时关联
    process_instance_id VARCHAR(64),                       -- Flowable processInstanceId
    -- 输入 / 输出
    input           JSONB,
    output          JSONB,
    -- 执行状态
    status          VARCHAR(16)  NOT NULL DEFAULT 'RUNNING', -- RUNNING/DONE/FAILED/CANCELLED
    error_message   TEXT,
    started_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at        TIMESTAMP(6),
    duration_ms     INTEGER
);

COMMENT ON TABLE  ai_workflow_run                       IS 'AI 工作流执行实例（append-only）';
COMMENT ON COLUMN ai_workflow_run.workflow_key           IS '对应 Flowable process definition key';
COMMENT ON COLUMN ai_workflow_run.workflow_name          IS '触发时冗余存储，防工作流改名后日志失真';
COMMENT ON COLUMN ai_workflow_run.process_instance_id    IS 'Flowable processInstanceId，用于关联 Flowable 审计表';
COMMENT ON COLUMN ai_workflow_run.status                 IS 'RUNNING/DONE/FAILED/CANCELLED';

CREATE INDEX idx_ai_workflow_run_execution ON ai_workflow_run(execution_id);
CREATE INDEX idx_ai_workflow_run_session   ON ai_workflow_run(session_id, started_at);
CREATE INDEX idx_ai_workflow_run_key       ON ai_workflow_run(workflow_key, started_at);
CREATE INDEX idx_ai_workflow_run_process   ON ai_workflow_run(process_instance_id) WHERE process_instance_id IS NOT NULL;

-- 节点执行记录：记录每个 AI 节点（LlmNode/AgentNode/KnowledgeNode 等）的执行详情
CREATE TABLE ai_workflow_node_run (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id       BIGINT       NOT NULL REFERENCES ai_workflow_run(id),
    -- 节点信息（来自 Flowable activity）
    node_id      VARCHAR(64)  NOT NULL,                   -- Flowable activityId
    node_name    VARCHAR(128),
    node_type    VARCHAR(32)  NOT NULL,                   -- LLM/AGENT/KNOWLEDGE/CONDITION/CODE/HTTP 等
    -- 关联其他调用日志（可选，便于下钻）
    llm_call_id  BIGINT       REFERENCES ai_llm_call_log(id),
    tool_call_id BIGINT       REFERENCES ai_tool_call_log(id),
    -- 输入 / 输出
    input        JSONB,
    output       JSONB,
    -- 执行状态
    status       VARCHAR(16)  NOT NULL DEFAULT 'SUCCESS', -- SUCCESS/FAILED/SKIPPED
    error_message TEXT,
    started_at   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at     TIMESTAMP(6),
    duration_ms  INTEGER
);

COMMENT ON TABLE  ai_workflow_node_run              IS 'AI 工作流节点执行记录（append-only）';
COMMENT ON COLUMN ai_workflow_node_run.node_id       IS 'Flowable activityId，对应流程图中的节点 ID';
COMMENT ON COLUMN ai_workflow_node_run.node_type     IS '节点类型：LLM/AGENT/KNOWLEDGE/CONDITION/CODE/HTTP';
COMMENT ON COLUMN ai_workflow_node_run.llm_call_id   IS '关联 ai_llm_call_log，LLM 节点时有值';
COMMENT ON COLUMN ai_workflow_node_run.tool_call_id  IS '关联 ai_tool_call_log，工具节点时有值';

CREATE INDEX idx_ai_workflow_node_run_run  ON ai_workflow_node_run(run_id, started_at);
CREATE INDEX idx_ai_workflow_node_run_type ON ai_workflow_node_run(node_type, started_at);


-- ============================================================
-- 补充 ai_tool_call_log 调用来源字段（支持按编排类型统计）
-- ============================================================

-- caller_type：标识工具由哪种编排触发，支持按编排维度聚合统计
ALTER TABLE ai_tool_call_log
    ADD COLUMN caller_type VARCHAR(32) NOT NULL DEFAULT 'AGENT',   -- AGENT/WORKFLOW/SKILL/DIRECT
    ADD COLUMN caller_id   BIGINT,                                  -- 对应编排实例 ID（workflow_run.id / skill_trigger_log.id 等）
    ADD COLUMN tool_type   VARCHAR(32);                             -- 冗余 ai_tool_catalog.tool_type，避免 JOIN

COMMENT ON COLUMN ai_tool_call_log.caller_type IS '调用来源编排类型：AGENT=Agent直调 / WORKFLOW=工作流节点 / SKILL=技能触发 / DIRECT=API直调';
COMMENT ON COLUMN ai_tool_call_log.caller_id   IS '来源编排实例 ID：caller_type=WORKFLOW 时为 ai_workflow_node_run.id，SKILL 时为 ai_skill_trigger_log.id';
COMMENT ON COLUMN ai_tool_call_log.tool_type   IS '工具类型冗余（来自 ai_tool_catalog），避免统计时 JOIN：FUNCTION/MCP/HTTP/SCRIPT/WORKFLOW/AGENT';

CREATE INDEX idx_ai_tool_call_log_caller ON ai_tool_call_log(caller_type, status, create_time);
CREATE INDEX idx_ai_tool_call_log_type   ON ai_tool_call_log(tool_type, status, create_time);

-- ============================================================
-- Agent 步骤执行记录（ReAct 推理链）
-- ============================================================

CREATE TABLE ai_agent_step (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    -- 归属
    execution_id BIGINT       NOT NULL REFERENCES ai_task_execution(id),
    iteration    INTEGER      NOT NULL DEFAULT 1,   -- 第几轮 ReAct 循环
    -- 步骤类型：THOUGHT=推理 / ACTION=调用工具 / OBSERVATION=工具返回 / ANSWER=最终回答
    step_type    VARCHAR(16)  NOT NULL,
    -- 内容
    content      TEXT,                              -- Thought 文本 / Action 描述 / Observation 结果 / 最终答案
    -- 关联其他日志（ACTION 步骤时填充）
    tool_call_id BIGINT       REFERENCES ai_tool_call_log(id),
    llm_call_id  BIGINT       REFERENCES ai_llm_call_log(id),
    -- 状态
    status       VARCHAR(16)  NOT NULL DEFAULT 'SUCCESS',  -- SUCCESS/FAILED
    duration_ms  INTEGER,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE  ai_agent_step              IS 'Agent ReAct 步骤记录（append-only）：完整推理链审计';
COMMENT ON COLUMN ai_agent_step.iteration    IS '第几轮 ReAct 循环，从 1 开始';
COMMENT ON COLUMN ai_agent_step.step_type    IS 'THOUGHT=推理过程 / ACTION=工具调用决策 / OBSERVATION=工具返回结果 / ANSWER=最终回答';
COMMENT ON COLUMN ai_agent_step.tool_call_id IS 'step_type=ACTION 时关联 ai_tool_call_log';
COMMENT ON COLUMN ai_agent_step.llm_call_id  IS 'step_type=THOUGHT/ANSWER 时关联 ai_llm_call_log';

CREATE INDEX idx_ai_agent_step_execution ON ai_agent_step(execution_id, iteration, step_type);

-- 说明：消息反馈表 conversation_message_feedback 依赖 conversation_message，
--      而后者在 v8__chat_schema.sql 才创建，故该表定义移至 v8（与对话域内聚）。

-- ============================================================
-- 用量统计聚合（按天预聚合，避免实时扫描明细表）
-- ============================================================

CREATE TABLE ai_usage_daily (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_date       DATE         NOT NULL,
    -- 聚合维度（按需 GROUP BY，NULL=不按此维度细分）
    org_id          BIGINT,
    user_id         BIGINT,
    model_id        VARCHAR(128),
    caller_type     VARCHAR(32),                    -- AGENT/WORKFLOW/SKILL/DIRECT（同 tool_call_log）
    -- LLM 用量
    llm_calls       INTEGER      NOT NULL DEFAULT 0,
    llm_failed      INTEGER      NOT NULL DEFAULT 0,
    prompt_tokens   BIGINT       NOT NULL DEFAULT 0,
    completion_tokens BIGINT     NOT NULL DEFAULT 0,
    -- 工具调用
    tool_calls      INTEGER      NOT NULL DEFAULT 0,
    tool_failed     INTEGER      NOT NULL DEFAULT 0,
    -- 工作流
    workflow_runs   INTEGER      NOT NULL DEFAULT 0,
    workflow_failed INTEGER      NOT NULL DEFAULT 0,
    -- 技能触发
    skill_triggers  INTEGER      NOT NULL DEFAULT 0,
    skill_failed    INTEGER      NOT NULL DEFAULT 0,
    -- 更新时间（ETL Job 写入）
    updated_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (stat_date, org_id, user_id, model_id, caller_type)
);

COMMENT ON TABLE  ai_usage_daily              IS '用量统计日聚合（ETL Job 每日写入），用于报表和配额预警，避免扫描明细表';
COMMENT ON COLUMN ai_usage_daily.caller_type  IS '编排类型维度：AGENT/WORKFLOW/SKILL/DIRECT，NULL=全类型合计';
COMMENT ON COLUMN ai_usage_daily.model_id     IS 'NULL=全模型合计';

CREATE INDEX idx_ai_usage_daily_date_org  ON ai_usage_daily(stat_date, org_id);
CREATE INDEX idx_ai_usage_daily_date_user ON ai_usage_daily(stat_date, user_id) WHERE user_id IS NOT NULL;


-- ============================================================
-- 工作流执行记录补充 Token 字段
-- ============================================================

-- ai_workflow_run：汇总整次工作流的 token 消耗
ALTER TABLE ai_workflow_run
    ADD COLUMN prompt_tokens     BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN completion_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN total_tokens      BIGINT NOT NULL DEFAULT 0;

COMMENT ON COLUMN ai_workflow_run.prompt_tokens     IS '本次工作流所有 LLM 节点输入 Token 合计';
COMMENT ON COLUMN ai_workflow_run.completion_tokens IS '本次工作流所有 LLM 节点输出 Token 合计';
COMMENT ON COLUMN ai_workflow_run.total_tokens      IS '= prompt_tokens + completion_tokens';

-- ai_workflow_node_run：记录单个节点的 token 消耗（LLM 节点有值，其余节点为 0）
ALTER TABLE ai_workflow_node_run
    ADD COLUMN prompt_tokens     INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN completion_tokens INTEGER NOT NULL DEFAULT 0;

COMMENT ON COLUMN ai_workflow_node_run.prompt_tokens     IS 'LLM 节点输入 Token，非 LLM 节点为 0';
COMMENT ON COLUMN ai_workflow_node_run.completion_tokens IS 'LLM 节点输出 Token，非 LLM 节点为 0';

-- ai_llm_call_log：补充 workflow_run_id，打通 LLM 调用与工作流实例的关联
ALTER TABLE ai_llm_call_log
    ADD COLUMN workflow_run_id BIGINT REFERENCES ai_workflow_run(id);

COMMENT ON COLUMN ai_llm_call_log.workflow_run_id IS '关联工作流执行实例，非工作流场景为 NULL';

CREATE INDEX idx_ai_llm_call_log_workflow ON ai_llm_call_log(workflow_run_id) WHERE workflow_run_id IS NOT NULL;

-- ai_usage_daily：补充 workflow_key 维度，支持按流程模板聚合 token 消耗
ALTER TABLE ai_usage_daily
    ADD COLUMN workflow_key      VARCHAR(128),
    ADD COLUMN prompt_tokens_wf  BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN completion_tokens_wf BIGINT NOT NULL DEFAULT 0;

COMMENT ON COLUMN ai_usage_daily.workflow_key         IS '工作流模板 key，NULL=非工作流调用或全类型合计';
COMMENT ON COLUMN ai_usage_daily.prompt_tokens_wf     IS 'caller_type=WORKFLOW 时的输入 Token 聚合';
COMMENT ON COLUMN ai_usage_daily.completion_tokens_wf IS 'caller_type=WORKFLOW 时的输出 Token 聚合';


-- ============================================================
-- 模型量化分析：补齐关联字段
-- ============================================================

-- ai_tool_call_log 补充：
--   model_id       → 哪个模型决策发起了这次工具调用（Function Calling 来源）
--   workflow_run_id → 归属哪次工作流执行
--   param_valid    → LLM 生成的参数是否通过 Schema 校验（工具调用准确性核心指标）
ALTER TABLE ai_tool_call_log
    ADD COLUMN model_id        VARCHAR(128),
    ADD COLUMN workflow_run_id BIGINT REFERENCES ai_workflow_run(id),
    ADD COLUMN param_valid     BOOLEAN;

COMMENT ON COLUMN ai_tool_call_log.model_id        IS '发起 Function Calling 的模型 ID，关联 ai_model.model_id';
COMMENT ON COLUMN ai_tool_call_log.workflow_run_id IS '归属工作流执行实例，非工作流场景为 NULL';
COMMENT ON COLUMN ai_tool_call_log.param_valid     IS 'LLM 生成的参数是否通过 JSON Schema 校验；NULL=未校验，FALSE=参数非法被拦截';

CREATE INDEX idx_ai_tool_call_log_model    ON ai_tool_call_log(model_id, status, create_time) WHERE model_id IS NOT NULL;
CREATE INDEX idx_ai_tool_call_log_workflow ON ai_tool_call_log(workflow_run_id) WHERE workflow_run_id IS NOT NULL;

-- ============================================================
-- 模型能力量化分析日聚合表
-- 三维度：模型 × 工作流模板 × 日期
-- ETL Job 每日从 ai_llm_call_log + ai_tool_call_log 汇总写入
-- ============================================================

CREATE TABLE ai_model_daily (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_date            DATE         NOT NULL,
    model_id             VARCHAR(128) NOT NULL,
    -- 细分维度（NULL=不按此维度细分，表示该模型全局汇总）
    workflow_key         VARCHAR(128),                     -- 工作流模板 key
    caller_type          VARCHAR(32),                      -- AGENT/WORKFLOW/SKILL/DIRECT

    -- LLM 调用能力
    llm_calls            INTEGER      NOT NULL DEFAULT 0,  -- 总调用次数
    llm_success          INTEGER      NOT NULL DEFAULT 0,
    llm_failed           INTEGER      NOT NULL DEFAULT 0,
    llm_timeout          INTEGER      NOT NULL DEFAULT 0,
    llm_rate_limited     INTEGER      NOT NULL DEFAULT 0,

    -- Token 成本
    prompt_tokens        BIGINT       NOT NULL DEFAULT 0,
    completion_tokens    BIGINT       NOT NULL DEFAULT 0,
    total_tokens         BIGINT       NOT NULL DEFAULT 0,

    -- 延迟分布（毫秒，P50/P95/P99 由查询时用 percentile 函数计算，此处存均值和最大值够用）
    ttfb_avg_ms          INTEGER,                          -- 首 Token 平均延迟
    ttfb_p95_ms          INTEGER,                          -- 首 Token P95 延迟
    duration_avg_ms      INTEGER,                          -- 总耗时平均
    duration_p95_ms      INTEGER,                          -- 总耗时 P95

    -- 工具调用能力（该模型作为决策者的工具调用统计）
    tool_calls           INTEGER      NOT NULL DEFAULT 0,
    tool_success         INTEGER      NOT NULL DEFAULT 0,
    tool_failed          INTEGER      NOT NULL DEFAULT 0,
    tool_param_invalid   INTEGER      NOT NULL DEFAULT 0,  -- 参数校验失败次数（LLM 工具调用准确性）
    tool_param_valid     INTEGER      NOT NULL DEFAULT 0,  -- 参数校验通过次数

    -- finish_reason 分布（评估模型是否正常结束）
    finish_stop          INTEGER      NOT NULL DEFAULT 0,  -- 正常结束
    finish_tool_calls    INTEGER      NOT NULL DEFAULT 0,  -- 触发工具
    finish_length        INTEGER      NOT NULL DEFAULT 0,  -- 被截断（context 不足）
    finish_content_filter INTEGER     NOT NULL DEFAULT 0,  -- 安全拦截

    updated_at           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (stat_date, model_id, workflow_key, caller_type)
);

COMMENT ON TABLE  ai_model_daily                     IS '模型能力量化分析日聚合（ETL Job 每日写入）';
COMMENT ON COLUMN ai_model_daily.workflow_key         IS 'NULL=该模型全局汇总；有值=该模型在特定工作流中的表现';
COMMENT ON COLUMN ai_model_daily.caller_type          IS 'NULL=全编排类型合计；有值=特定编排类型（AGENT/WORKFLOW/SKILL/DIRECT）';
COMMENT ON COLUMN ai_model_daily.tool_param_invalid   IS 'LLM 生成参数不合法的次数，是模型 Function Calling 能力的核心负向指标';
COMMENT ON COLUMN ai_model_daily.finish_length        IS '输出被截断次数，高频说明该模型 context window 不足或 max_tokens 配置偏小';
COMMENT ON COLUMN ai_model_daily.ttfb_p95_ms          IS '首 Token P95 延迟，流式场景用户感知的关键指标';

CREATE INDEX idx_ai_model_daily_model_date    ON ai_model_daily(model_id, stat_date);
CREATE INDEX idx_ai_model_daily_workflow_date ON ai_model_daily(workflow_key, stat_date) WHERE workflow_key IS NOT NULL;


-- ============================================================
-- 模型评测（Tool Calling 准确率 / 能力基准）
-- 区别于生产日志：评测是预定义期望行为，对比实际行为，量化模型决策能力
-- ============================================================

-- 评测集：一组评测任务的集合，可绑定特定模型或工作流进行对比测试
CREATE TABLE ai_eval_suite (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(128) NOT NULL,
    description  VARCHAR(512),
    -- 评测类型：TOOL_CALLING=工具调用决策准确率 / WORKFLOW=工作流端到端 / QA=问答质量
    eval_type    VARCHAR(32)  NOT NULL DEFAULT 'TOOL_CALLING',
    org_id       BIGINT,
    workspace_id BIGINT,
    create_by    BIGINT,
    create_by_type VARCHAR(16),
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_by_type VARCHAR(16),
    update_time  TIMESTAMP(6),
    owner_id     BIGINT,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       TEXT,
    version      INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE  ai_eval_suite           IS '模型评测集';
COMMENT ON COLUMN ai_eval_suite.eval_type IS 'TOOL_CALLING=工具调用决策准确率 / WORKFLOW=工作流端到端 / QA=问答质量';

-- 评测用例：单条任务，定义输入和期望的工具调用行为
CREATE TABLE ai_eval_case (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suite_id        BIGINT       NOT NULL REFERENCES ai_eval_suite(id),
    name            VARCHAR(128),
    -- 输入：发给模型的用户消息（可含 system prompt）
    user_input      TEXT         NOT NULL,
    system_prompt   TEXT,
    -- 期望行为：期望模型触发的工具列表及参数约束
    -- 格式：[{"tool_name": "search_kb", "required": true, "param_rules": {"query": "非空"}}]
    expected_tools  JSONB        NOT NULL,
    -- 期望不触发工具的情况（模型应直接回答）
    expect_no_tool  BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order      INTEGER      NOT NULL DEFAULT 0,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE  ai_eval_case               IS '评测用例：定义输入和期望工具调用行为';
COMMENT ON COLUMN ai_eval_case.expected_tools IS '期望触发的工具列表，含必选/可选标记和参数规则；expect_no_tool=TRUE 时应为空数组';
COMMENT ON COLUMN ai_eval_case.expect_no_tool IS 'TRUE=该任务期望模型不触发工具直接回答，用于测试模型不过度调用工具的克制性';

CREATE INDEX idx_ai_eval_case_suite ON ai_eval_case(suite_id);

-- 评测运行：一次评测执行，指定模型+评测集，产生一组结果
CREATE TABLE ai_eval_run (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suite_id     BIGINT       NOT NULL REFERENCES ai_eval_suite(id),
    model_id     VARCHAR(128) NOT NULL,              -- 被评测的模型
    workflow_key VARCHAR(128),                       -- 可选：在特定工作流上下文中测试
    -- 汇总指标（所有 case 跑完后填入）
    total_cases  INTEGER      NOT NULL DEFAULT 0,
    passed       INTEGER      NOT NULL DEFAULT 0,   -- 工具触发完全符合期望
    partial      INTEGER      NOT NULL DEFAULT 0,   -- 部分工具触发正确
    failed       INTEGER      NOT NULL DEFAULT 0,   -- 未触发期望工具或触发了错误工具
    -- 准确率 = passed / total_cases
    accuracy     NUMERIC(5,4),
    -- Tool Calling 专项指标
    precision_score NUMERIC(5,4),                   -- 触发工具中正确的比例（避免过度调用）
    recall_score    NUMERIC(5,4),                   -- 期望工具中被触发的比例（避免漏调用）
    -- 平均 token 消耗（评测成本参考）
    avg_prompt_tokens     INTEGER,
    avg_completion_tokens INTEGER,
    status       VARCHAR(16)  NOT NULL DEFAULT 'RUNNING',  -- RUNNING/DONE/FAILED
    started_at   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at     TIMESTAMP(6),
    create_by    BIGINT,
    create_by_type VARCHAR(16),
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_by_type VARCHAR(16),
    update_time  TIMESTAMP(6),
    owner_id     BIGINT,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       TEXT,
    version      INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE  ai_eval_run                  IS '评测运行实例：指定模型对一个评测集的一次完整测试';
COMMENT ON COLUMN ai_eval_run.passed           IS '工具触发行为与 expected_tools 完全匹配的用例数';
COMMENT ON COLUMN ai_eval_run.partial          IS '部分工具触发正确（触发了期望工具但参数不完全符合，或多触发了非必选工具）';
COMMENT ON COLUMN ai_eval_run.precision_score  IS '精确率：实际触发工具中属于期望工具的比例，低=模型过度调用工具';
COMMENT ON COLUMN ai_eval_run.recall_score     IS '召回率：期望工具中被正确触发的比例，低=模型漏调用工具';

CREATE INDEX idx_ai_eval_run_suite ON ai_eval_run(suite_id, model_id);
CREATE INDEX idx_ai_eval_run_model ON ai_eval_run(model_id, started_at);

-- 评测用例结果：每条 case 的实际执行结果
CREATE TABLE ai_eval_case_result (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT       NOT NULL REFERENCES ai_eval_run(id),
    case_id         BIGINT       NOT NULL REFERENCES ai_eval_case(id),
    -- 实际触发的工具调用（来自 ai_tool_call_log，冗余快照避免日志被清理后失效）
    actual_tools    JSONB,       -- [{"tool_name": "search_kb", "arguments": {...}}]
    -- 判定结果
    verdict         VARCHAR(16)  NOT NULL DEFAULT 'FAILED',  -- PASS/PARTIAL/FAIL/NO_TOOL
    -- 详细得分（各 expected_tool 是否被正确触发）
    tool_scores     JSONB,       -- [{"tool_name": "search_kb", "triggered": true, "param_match": true}]
    -- 关联生产日志（便于回溯原始 LLM 调用）
    llm_call_id     BIGINT       REFERENCES ai_llm_call_log(id),
    prompt_tokens   INTEGER,
    completion_tokens INTEGER,
    duration_ms     INTEGER,
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE  ai_eval_case_result          IS '评测用例执行结果';
COMMENT ON COLUMN ai_eval_case_result.verdict  IS 'PASS=完全符合期望 / PARTIAL=部分符合 / FAIL=未触发或触发错误工具 / NO_TOOL=期望不调工具且模型确实未调';
COMMENT ON COLUMN ai_eval_case_result.tool_scores IS '每个期望工具的命中明细，格式：[{tool_name, triggered, param_match, actual_args}]';

CREATE INDEX idx_ai_eval_case_result_run     ON ai_eval_case_result(run_id, verdict);
CREATE INDEX idx_ai_eval_case_result_case    ON ai_eval_case_result(case_id);


-- ============================================================
-- 任务执行补充编排字段（支持重试时切换工作流）
-- ============================================================

-- ai_task_execution 补充当前使用的编排策略
-- attempt_no 已有，重试时新建一条记录 attempt_no+1，workflow_key 可换
ALTER TABLE ai_task_execution
    ADD COLUMN workflow_key    VARCHAR(128),   -- 本次执行使用的工作流模板 key，NULL=Agent 直接推理
    ADD COLUMN retry_reason    VARCHAR(256);   -- 重试原因（上次失败摘要，便于分析重试触发条件）

COMMENT ON COLUMN ai_task_execution.workflow_key IS '本次执行使用的工作流模板 key；重试时可切换不同编排；NULL=无编排直接由 Agent 处理';
COMMENT ON COLUMN ai_task_execution.retry_reason IS '重试原因摘要，如"工具调用超时"、"LLM 输出格式错误"，用于分析哪类错误触发了重试';

CREATE INDEX idx_ai_task_execution_workflow ON ai_task_execution(workflow_key) WHERE workflow_key IS NOT NULL;

-- ============================================================
-- 评测扩展：支持同一任务集跨模型 × 跨编排的矩阵对比
-- ============================================================

-- ai_eval_run 补充：标记本次运行属于哪个对比实验组
ALTER TABLE ai_eval_run
    ADD COLUMN experiment_id   BIGINT,         -- 关联 ai_eval_experiment.id，NULL=独立运行
    ADD COLUMN agent_mode      BOOLEAN NOT NULL DEFAULT FALSE;  -- TRUE=不走工作流，由 Agent 直接推理

COMMENT ON COLUMN ai_eval_run.experiment_id IS '所属对比实验组，同一 experiment 下的多个 run 可横向比较';
COMMENT ON COLUMN ai_eval_run.agent_mode    IS 'TRUE=本次评测用 Agent 直接推理（无工作流），与工作流模式对比基线';

-- 对比实验：将同一评测集分配给多个"模型 + 编排"组合，一次性触发并汇总结果
CREATE TABLE ai_eval_experiment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suite_id     BIGINT       NOT NULL REFERENCES ai_eval_suite(id),
    name         VARCHAR(128) NOT NULL,
    description  VARCHAR(512),
    -- 实验状态
    status       VARCHAR(16)  NOT NULL DEFAULT 'RUNNING',  -- RUNNING/DONE/FAILED
    org_id       BIGINT,
    workspace_id BIGINT,
    create_by    BIGINT,
    create_by_type VARCHAR(16),
    started_at   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at     TIMESTAMP(6),
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_by_type VARCHAR(16),
    update_time  TIMESTAMP(6),
    owner_id     BIGINT,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       TEXT,
    version      INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE ai_eval_experiment IS '对比实验：将同一评测集并发分配给多个「模型 × 编排」组合，汇总横向对比结果';

CREATE INDEX idx_ai_eval_experiment_suite ON ai_eval_experiment(suite_id);

-- 实验组合配置：每行定义一个"模型 + 编排"的参数组合
CREATE TABLE ai_eval_experiment_config (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experiment_id  BIGINT       NOT NULL REFERENCES ai_eval_experiment(id),
    config_name       VARCHAR(64)  NOT NULL,       -- 便于展示，如 "GPT-4o + 搜索工作流"
    model_id       VARCHAR(128) NOT NULL,
    workflow_key   VARCHAR(128),                -- NULL=Agent 直接推理（作为基线对照组）
    -- 执行后关联生成的 eval_run
    eval_run_id    BIGINT       REFERENCES ai_eval_run(id),
    -- 该组合的汇总指标（冗余自 eval_run，方便单表对比）
    accuracy       NUMERIC(5,4),
    precision_score NUMERIC(5,4),
    recall_score   NUMERIC(5,4),
    avg_prompt_tokens     INTEGER,
    avg_completion_tokens INTEGER,
    avg_duration_ms       INTEGER,
    status         VARCHAR(16)  NOT NULL DEFAULT 'PENDING',  -- PENDING/RUNNING/DONE/FAILED
    UNIQUE (experiment_id, model_id, workflow_key)
);

COMMENT ON TABLE  ai_eval_experiment_config              IS '实验参数组合（config）：每行对应一个「模型 × 编排」配置';
COMMENT ON COLUMN ai_eval_experiment_config.workflow_key IS 'NULL=Agent 直接推理，作为无编排基线对照组';
COMMENT ON COLUMN ai_eval_experiment_config.config_name     IS '展示名称，如"GPT-4o + 知识库检索流"，人工填写便于报告阅读';

CREATE INDEX idx_ai_eval_arm_experiment ON ai_eval_experiment_config(experiment_id);

-- ============================================================
-- AI 工作流定义与版本管理
-- 作为 Flowable 之上的版本管理层，支持草稿/审核/发布/AI优化等工作流
-- Flowable 只负责运行时执行，版本历史、变更原因、AI 建议等由此管理
-- ============================================================

-- 工作流定义（元数据，不含具体版本内容）
CREATE TABLE ai_workflow_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    workflow_key    VARCHAR(128) NOT NULL,           -- 全局唯一 key，对应 Flowable process key
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    category        VARCHAR(64),                    -- 分类：RAG/AGENT_CHAIN/CONTENT_GEN 等
    current_version INTEGER      NOT NULL DEFAULT 0, -- 当前生产版本号，0=尚未发布
    status          VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',  -- DRAFT/ACTIVE/DEPRECATED
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT,
    UNIQUE (workflow_key)
);

COMMENT ON TABLE  ai_workflow_definition                 IS 'AI 工作流定义元数据（Flowable 之上的版本管理层）';
COMMENT ON COLUMN ai_workflow_definition.workflow_key    IS '全局唯一标识，对应 Flowable process definition key';
COMMENT ON COLUMN ai_workflow_definition.current_version IS '当前生产发布版本号，指向 ai_workflow_version.version_no';
COMMENT ON COLUMN ai_workflow_definition.status          IS 'DRAFT=从未发布 / ACTIVE=有已发布版本 / DEPRECATED=已下线';

CREATE INDEX idx_ai_workflow_def_key    ON ai_workflow_definition(workflow_key) WHERE deleted = FALSE;
CREATE INDEX idx_ai_workflow_def_status ON ai_workflow_definition(status) WHERE deleted = FALSE;

-- 工作流版本（每次保存/发布生成一条记录）
CREATE TABLE ai_workflow_version (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    definition_id       BIGINT       NOT NULL REFERENCES ai_workflow_definition(id),
    version_no          INTEGER      NOT NULL,       -- 从 1 开始递增
    -- 版本状态
    status              VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',
    -- DRAFT=草稿（可编辑）/ REVIEWING=审核中 / PUBLISHED=已发布 / ARCHIVED=已归档
    -- 流程内容
    dsl_content         TEXT         NOT NULL,       -- 工作流 DSL（JSON/YAML），节点/连线/参数完整定义
    bpmn_xml            TEXT,                        -- 对应 Flowable 部署的 BPMN XML（发布后填入）
    flowable_def_id     VARCHAR(64),                 -- Flowable processDefinitionId（发布后填入）
    -- 变更溯源
    change_type         VARCHAR(16)  NOT NULL DEFAULT 'MANUAL',  -- MANUAL=人工 / AI=AI优化 / FORK=基于某版本派生
    change_summary      VARCHAR(512),                -- 本次修改摘要，如"优化知识库检索节点 prompt"
    base_version_no     INTEGER,                     -- FORK 时的来源版本号
    -- 评测关联（发布前可先跑评测，通过后再发布）
    eval_run_id         BIGINT       REFERENCES ai_eval_run(id),
    -- 审核
    reviewed_by         BIGINT,
    reviewed_at         TIMESTAMP(6),
    review_comment      TEXT,
    -- 元数据
    create_by           BIGINT,
    create_by_type      VARCHAR(16),                 -- USER=人工 / AI=AI自动生成
    create_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6),
    owner_id            BIGINT,
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    remark              TEXT,
    version             INTEGER      NOT NULL DEFAULT 0,
    UNIQUE (definition_id, version_no)
);

COMMENT ON TABLE  ai_workflow_version                IS 'AI 工作流版本记录（append-only，不允许修改历史版本）';
COMMENT ON COLUMN ai_workflow_version.version_no      IS '版本号从 1 开始，同一 definition 下单调递增';
COMMENT ON COLUMN ai_workflow_version.status          IS 'DRAFT=草稿可编辑 / REVIEWING=审核中 / PUBLISHED=生产运行 / ARCHIVED=已归档';
COMMENT ON COLUMN ai_workflow_version.dsl_content     IS '工作流完整 DSL，是版本的真理源；BPMN XML 由此生成';
COMMENT ON COLUMN ai_workflow_version.change_type     IS 'MANUAL=人工修改 / AI=AI自动优化建议被采纳 / FORK=基于某版本派生新工作流';
COMMENT ON COLUMN ai_workflow_version.base_version_no IS 'FORK 时的来源版本，NULL=全新创建';
COMMENT ON COLUMN ai_workflow_version.eval_run_id     IS '发布前关联的评测运行，可查看该版本在评测集上的得分';
COMMENT ON COLUMN ai_workflow_version.create_by_type  IS 'USER=人工创建 / AI=由 AI 自动生成（如自进化优化）';
COMMENT ON COLUMN ai_workflow_version.flowable_def_id IS 'Flowable processDefinitionId，status=PUBLISHED 后填入';

CREATE INDEX idx_ai_workflow_version_def     ON ai_workflow_version(definition_id, version_no);
CREATE INDEX idx_ai_workflow_version_status  ON ai_workflow_version(definition_id, status);
CREATE INDEX idx_ai_workflow_version_flowable ON ai_workflow_version(flowable_def_id) WHERE flowable_def_id IS NOT NULL;

-- 同步更新 ai_workflow_run：关联版本号（之前只有 workflow_key + workflow_version 整数，现在可精确追溯）
ALTER TABLE ai_workflow_run
    ADD COLUMN definition_id  BIGINT REFERENCES ai_workflow_definition(id),
    ADD COLUMN wf_version_id  BIGINT REFERENCES ai_workflow_version(id);

COMMENT ON COLUMN ai_workflow_run.definition_id IS '关联 ai_workflow_definition.id';
COMMENT ON COLUMN ai_workflow_run.wf_version_id IS '关联 ai_workflow_version.id，精确追溯本次执行用的是哪个版本';

-- 同步更新 ai_eval_experiment_config：支持指定具体版本进行评测对比
ALTER TABLE ai_eval_experiment_config
    ADD COLUMN wf_version_id  BIGINT REFERENCES ai_workflow_version(id);

COMMENT ON COLUMN ai_eval_experiment_config.wf_version_id IS '指定评测的工作流版本；NULL 时使用 workflow_key 对应的当前发布版本';


-- ============================================================
-- AI 工作流定义
-- ============================================================
CREATE TABLE IF NOT EXISTS ai_flow_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    mode            VARCHAR(32)  NOT NULL DEFAULT 'CHAT',
    definition      JSONB        NOT NULL DEFAULT '{}',
    status          VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',
    deployment_id   VARCHAR(64),
    published_at    TIMESTAMP(6),
    agent_callable  BOOLEAN      NOT NULL DEFAULT FALSE,
    require_confirm BOOLEAN      NOT NULL DEFAULT TRUE,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6),
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6),
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE  ai_flow_definition                IS 'AI 工作流定义（flow-editor 编辑态，发布后部署到 Flowable）';
COMMENT ON COLUMN ai_flow_definition.mode           IS '流程模式：CHAT / COMPLETION / AGENT';
COMMENT ON COLUMN ai_flow_definition.definition     IS '编辑态 JSON（ReactFlow 节点+连线）';
COMMENT ON COLUMN ai_flow_definition.status         IS '发布状态：DRAFT / PUBLISHED / DISABLED';
COMMENT ON COLUMN ai_flow_definition.deployment_id  IS 'Flowable deployment ID，发布后有值';
COMMENT ON COLUMN ai_flow_definition.agent_callable IS '是否允许智能体自动调用';
COMMENT ON COLUMN ai_flow_definition.require_confirm IS '智能体调用前是否需要用户确认';


-- ============================================================
-- AI 生成工具
-- ============================================================
CREATE TABLE IF NOT EXISTS ai_generated_tool (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    name             VARCHAR(64)  NOT NULL UNIQUE,
    description      VARCHAR(256),
    parameters_json  TEXT,
    code             TEXT         NOT NULL,
    creator_user_id  BIGINT       NOT NULL,
    visibility       VARCHAR(16)  NOT NULL DEFAULT 'PRIVATE',
    status           VARCHAR(16)  NOT NULL DEFAULT 'active',
    owner_id         BIGINT,
    create_by        BIGINT,
    create_by_type   VARCHAR(16),
    create_time      TIMESTAMP(6),
    update_by        BIGINT,
    update_by_type   VARCHAR(16),
    update_time      TIMESTAMP(6),
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    remark           TEXT
);

CREATE INDEX IF NOT EXISTS idx_ai_generated_tool_name       ON ai_generated_tool (name);
CREATE INDEX IF NOT EXISTS idx_ai_generated_tool_creator    ON ai_generated_tool (creator_user_id);
CREATE INDEX IF NOT EXISTS idx_ai_generated_tool_visibility ON ai_generated_tool (visibility);

COMMENT ON TABLE ai_generated_tool IS 'AI 动态生成的工具定义';

-- ============================================================
-- AI 产出记录
-- ============================================================
CREATE TABLE IF NOT EXISTS ai_output (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    session_id       BIGINT,
    task_id          BIGINT,
    execution_id     BIGINT,
    creator_id       BIGINT       NOT NULL,
    source_type      VARCHAR(30)  NOT NULL,
    category         VARCHAR(30)  NOT NULL,
    risk_level       VARCHAR(10)  NOT NULL DEFAULT 'LOW',
    title            VARCHAR(500) NOT NULL,
    description      TEXT,
    content_snapshot JSONB,
    revert_info      JSONB,
    status           VARCHAR(20)  NOT NULL DEFAULT 'EFFECTIVE',
    adjust_note      TEXT,
    owner_id         BIGINT,
    create_by        BIGINT,
    create_by_type   VARCHAR(16),
    create_time      TIMESTAMP(6),
    update_by        BIGINT,
    update_by_type   VARCHAR(16),
    update_time      TIMESTAMP(6),
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    remark           TEXT
);

COMMENT ON TABLE ai_output IS 'AI 产出记录——所有助理工作成果的统一归档';

-- ============================================================
-- 智能体执行运行记录
-- ============================================================
CREATE TABLE IF NOT EXISTS execution_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id    VARCHAR(128) NOT NULL UNIQUE,
    parent_run_id   BIGINT,
    agent_id        VARCHAR(64)  NOT NULL,
    agent_name      VARCHAR(128),
    user_id         BIGINT,
    conversation_id VARCHAR(64),
    input           TEXT,
    output          TEXT,
    status          VARCHAR(16)  NOT NULL,
    error_message   TEXT,
    token_input     INTEGER      NOT NULL DEFAULT 0,
    token_output    INTEGER      NOT NULL DEFAULT 0,
    started_at      TIMESTAMP(6) NOT NULL,
    finished_at     TIMESTAMP(6),
    duration_ms     BIGINT,
    retry_count     INTEGER      NOT NULL DEFAULT 0,
    metadata        JSONB
);

COMMENT ON TABLE execution_run IS '智能体执行运行记录';


-- ============================================================
-- 智能体执行步骤
-- ============================================================
CREATE TABLE IF NOT EXISTS execution_step (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         BIGINT       NOT NULL,
    parent_step_id BIGINT,
    step_index     INTEGER      NOT NULL,
    step_type      VARCHAR(32)  NOT NULL,
    agent_id       VARCHAR(64),
    tool_name      VARCHAR(128),
    input          TEXT,
    output         TEXT,
    status         VARCHAR(16)  NOT NULL,
    error_message  TEXT,
    started_at     TIMESTAMP(6) NOT NULL,
    finished_at    TIMESTAMP(6),
    duration_ms    BIGINT
);

CREATE INDEX IF NOT EXISTS idx_execution_step_run ON execution_step (run_id);
COMMENT ON TABLE execution_step IS '智能体执行步骤';

-- ============================================================
-- 工具调用审计记录
-- ============================================================
CREATE TABLE IF NOT EXISTS tool_call_audit (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT,
    session_id    VARCHAR(64),
    agent_id      VARCHAR(64),
    function_name VARCHAR(128) NOT NULL,
    arguments     TEXT,
    success       BOOLEAN      NOT NULL,
    output        TEXT,
    error_message TEXT,
    duration_ms   BIGINT,
    risk_level    VARCHAR(16),
    created_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE tool_call_audit IS '工具调用审计记录';



-- ============================================================
-- 知识库段落（文档分块最小检索单元）
-- ============================================================
CREATE TABLE IF NOT EXISTS ai_knowledge_segment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    document_id       BIGINT       NOT NULL,
    knowledge_base_id BIGINT       NOT NULL,
    content           TEXT         NOT NULL,
    position          INTEGER      NOT NULL,
    word_count        INTEGER,
    enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
    embedding         vector,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6),
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6),
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            TEXT
);

CREATE INDEX IF NOT EXISTS idx_knowledge_segment_doc ON ai_knowledge_segment (document_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_segment_kb  ON ai_knowledge_segment (knowledge_base_id);
COMMENT ON TABLE ai_knowledge_segment IS '知识库段落（文档分块最小检索单元）';
