-- ============================================================
-- AI 基础设施 Schema
-- 包含：模型管理、Prompt模板、Token用量、记忆、Agent、Assistant、Team
-- ============================================================

-- ============================================================
-- 模型管理
-- ============================================================

CREATE TABLE ai_model (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER          NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    model_id            VARCHAR(64)      NOT NULL UNIQUE,
    display_name        VARCHAR(128)     NOT NULL,
    provider            VARCHAR(32)      NOT NULL,
    provider_type       VARCHAR(32)      NOT NULL DEFAULT 'OPENAI_COMPAT',
    model_name          VARCHAR(128)     NOT NULL,
    base_url            VARCHAR(512),
    api_key_encrypted   VARCHAR(1024),
    temperature         DOUBLE PRECISION,
    max_tokens          INTEGER,
    context_window      INTEGER,
    enabled             BOOLEAN          NOT NULL DEFAULT TRUE,
    capabilities        VARCHAR(256),
    input_price_per_k   NUMERIC(10, 6),
    output_price_per_k  NUMERIC(10, 6),
    fallback_model_id   VARCHAR(64),
    sort_order          INTEGER              DEFAULT 100,
    create_by           BIGINT,
    create_time         TIMESTAMP(6),
    update_by           BIGINT,
    update_time         TIMESTAMP(6),
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN          NOT NULL DEFAULT FALSE,
    remark              TEXT
);

COMMENT ON TABLE ai_model IS 'AI 模型配置';
COMMENT ON COLUMN ai_model.provider_type     IS '协议类型：OPENAI_COMPAT / ANTHROPIC / OLLAMA';
COMMENT ON COLUMN ai_model.capabilities      IS '能力标记：CHAT,VISION,EMBEDDING,IMAGE_GEN,AUDIO,RERANK';
COMMENT ON COLUMN ai_model.input_price_per_k IS '输入 Token 单价（元/千Token）';
COMMENT ON COLUMN ai_model.output_price_per_k IS '输出 Token 单价（元/千Token）';

CREATE TABLE ai_model_preference (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     INTEGER      NOT NULL DEFAULT 0,
    scope       VARCHAR(16)  NOT NULL,
    scope_id    BIGINT,
    capability  VARCHAR(32)  NOT NULL,
    model_id    VARCHAR(64)  NOT NULL,
    create_by   BIGINT,
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by   BIGINT,
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    remark      VARCHAR(255),
    CONSTRAINT uq_model_preference UNIQUE (scope, scope_id, capability)
);

COMMENT ON TABLE ai_model_preference IS '模型偏好配置';
COMMENT ON COLUMN ai_model_preference.scope      IS 'USER=用户级别 / SYSTEM=系统默认';
COMMENT ON COLUMN ai_model_preference.scope_id   IS '用户ID（scope=USER时），SYSTEM时为null';
COMMENT ON COLUMN ai_model_preference.capability IS '能力类型：CHAT/EMBEDDING/IMAGE_GEN/SPEECH_ASR等';

CREATE TABLE ai_prompt_template (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    name             VARCHAR(128) NOT NULL,
    template_version INTEGER          NOT NULL DEFAULT 1,
    content          TEXT         NOT NULL,
    description      VARCHAR(512),
    variables        TEXT,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    category         VARCHAR(64),
    create_by        BIGINT,
    create_time      TIMESTAMP(6),
    update_by        BIGINT,
    update_time      TIMESTAMP(6),
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    remark           TEXT,
    UNIQUE (name, template_version)
);

COMMENT ON TABLE ai_prompt_template IS 'Prompt 模板';

-- ============================================================
-- Token 用量
-- ============================================================

CREATE TABLE ai_token_usage (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    conversation_id   VARCHAR(64),
    model_id          VARCHAR(64)  NOT NULL,
    prompt_tokens     BIGINT       NOT NULL,
    completion_tokens BIGINT       NOT NULL,
    total_tokens      BIGINT       NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ai_token_usage IS 'Token 用量记录';
CREATE INDEX idx_ai_token_usage_user_created  ON ai_token_usage (user_id, created_at);
CREATE INDEX idx_ai_token_usage_model_created ON ai_token_usage (model_id, created_at);

-- ============================================================
-- 记忆
-- ============================================================

CREATE TABLE ai_long_term_memory (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT           NOT NULL,
    content          TEXT             NOT NULL,
    source_id        VARCHAR(128),
    memory_type      VARCHAR(32)      NOT NULL,
    importance       DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    last_accessed_at TIMESTAMP(6),
    access_count     INTEGER              NOT NULL DEFAULT 0,
    event_time       TIMESTAMP(6),
    created_at       TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ai_long_term_memory IS '长期记忆';
CREATE INDEX idx_ai_long_term_memory_user ON ai_long_term_memory (user_id, importance DESC);

CREATE TABLE ai_procedural_memory (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER          NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    user_id       BIGINT,
    task_type     VARCHAR(64)      NOT NULL,
    category      VARCHAR(64),
    title         VARCHAR(256)     NOT NULL,
    content       TEXT             NOT NULL,
    success_count INTEGER              NOT NULL DEFAULT 0,
    use_count     INTEGER              NOT NULL DEFAULT 0,
    quality_score DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    create_by     BIGINT,
    create_time   TIMESTAMP(6),
    update_by     BIGINT,
    update_time   TIMESTAMP(6),
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN          NOT NULL DEFAULT FALSE,
    remark        TEXT
);

COMMENT ON TABLE ai_procedural_memory IS '程序性记忆';
CREATE INDEX idx_ai_procedural_memory_user ON ai_procedural_memory (user_id, category);

-- ============================================================
-- Agent / Assistant / Team
-- ============================================================

CREATE TABLE ai_agent_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    agent_id        VARCHAR(64)  NOT NULL UNIQUE,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    system_prompt   TEXT,
    model_id        VARCHAR(64),
    capabilities    TEXT,
    tools           TEXT,
    mcp_servers     TEXT,
    max_iterations  INTEGER          NOT NULL DEFAULT 10,
    timeout_seconds INTEGER          NOT NULL DEFAULT 120,
    status          VARCHAR(16)  NOT NULL DEFAULT 'active',
    create_by       BIGINT,
    create_time     TIMESTAMP(6),
    update_by       BIGINT,
    update_time     TIMESTAMP(6),
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE ai_agent_definition IS 'Agent 定义';

CREATE TABLE ai_actor (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER      NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    actor_id      VARCHAR(64)  NOT NULL UNIQUE,
    name          VARCHAR(128) NOT NULL,
    persona       TEXT,
    system_prompt TEXT,
    avatar_url    VARCHAR(512),
    status        VARCHAR(16)  NOT NULL DEFAULT 'active',
    create_by     BIGINT,
    create_time   TIMESTAMP(6),
    update_by     BIGINT,
    update_time   TIMESTAMP(6),
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    remark        TEXT
);

COMMENT ON TABLE ai_actor IS 'Actor（人格载体）';

CREATE TABLE ai_role (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        INTEGER      NOT NULL DEFAULT 0,
    org_id         BIGINT,
    workspace_id   BIGINT,
    role_id        VARCHAR(64)  NOT NULL UNIQUE,
    name           VARCHAR(128) NOT NULL,
    description    VARCHAR(512),
    skill_ids      TEXT,
    tool_whitelist TEXT,
    status         VARCHAR(16)  NOT NULL DEFAULT 'active',
    create_by      BIGINT,
    create_time    TIMESTAMP(6),
    update_by      BIGINT,
    update_time    TIMESTAMP(6),
    delete_time    TIMESTAMP(6),
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    remark         TEXT
);

COMMENT ON TABLE ai_role IS 'Role（能力配置）：定义助理的技能集和工具白名单';

CREATE TABLE ai_assistant (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    assistant_id      VARCHAR(64)  NOT NULL UNIQUE,
    user_id           BIGINT       NOT NULL,
    actor_id          VARCHAR(64)  NOT NULL,
    role_id           VARCHAR(64)  NOT NULL,
    memory_strategy   VARCHAR(32)  NOT NULL DEFAULT 'HYBRID',
    knowledge_base_id BIGINT,
    status            VARCHAR(16)  NOT NULL DEFAULT 'active',
    create_by         BIGINT,
    create_time       TIMESTAMP(6),
    update_by         BIGINT,
    update_time       TIMESTAMP(6),
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            TEXT
);

COMMENT ON TABLE ai_assistant IS 'Assistant 定义（Actor + Role + 记忆策略）';
CREATE INDEX idx_ai_assistant_user ON ai_assistant (user_id);

CREATE TABLE ai_skill_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    skill_id        VARCHAR(64)  NOT NULL UNIQUE,
    assistant_id    VARCHAR(64),
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    agent_id        VARCHAR(64),
    trigger_intent  TEXT,
    system_prompt   TEXT,
    instructions    TEXT,
    tools           TEXT,
    priority        INTEGER          NOT NULL DEFAULT 0,
    built_in        BOOLEAN      NOT NULL DEFAULT FALSE,
    skill_version   VARCHAR(16),
    status          VARCHAR(16)  NOT NULL DEFAULT 'active',
    create_by       BIGINT,
    create_time     TIMESTAMP(6),
    update_by       BIGINT,
    update_time     TIMESTAMP(6),
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE ai_skill_definition IS '技能定义';
CREATE INDEX idx_ai_skill_definition_assistant ON ai_skill_definition (assistant_id);

CREATE TABLE ai_team (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version            INTEGER      NOT NULL DEFAULT 0,
    org_id             BIGINT,
    workspace_id       BIGINT,
    team_id            VARCHAR(64)  NOT NULL UNIQUE,
    name               VARCHAR(128) NOT NULL,
    description        VARCHAR(512),
    collaboration_mode VARCHAR(32)  NOT NULL DEFAULT 'LEADER_COORDINATED',
    status             VARCHAR(16)  NOT NULL DEFAULT 'active',
    create_by          BIGINT,
    create_time        TIMESTAMP(6),
    update_by          BIGINT,
    update_time        TIMESTAMP(6),
    delete_time        TIMESTAMP(6),
    deleted            BOOLEAN      NOT NULL DEFAULT FALSE,
    remark             TEXT
);

COMMENT ON TABLE ai_team IS '多智能体团队';

CREATE TABLE ai_team_member (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id      VARCHAR(64)  NOT NULL,
    assistant_id VARCHAR(64)  NOT NULL,
    role         VARCHAR(32)  NOT NULL DEFAULT 'member',
    capabilities TEXT,
    created_at   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (team_id, assistant_id)
);

COMMENT ON TABLE ai_team_member IS '团队成员';

CREATE TABLE ai_team_task (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id             VARCHAR(64)  NOT NULL,
    task_id             VARCHAR(64)  NOT NULL UNIQUE,
    parent_task_id      VARCHAR(64),
    assignee_id         VARCHAR(64),
    description         TEXT         NOT NULL,
    required_capability VARCHAR(128),
    status              VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    dependencies        TEXT,
    priority            INTEGER          NOT NULL DEFAULT 0,
    progress            INTEGER          NOT NULL DEFAULT 0,
    result              TEXT,
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ai_team_task IS '团队任务';
CREATE INDEX idx_ai_team_task_team_status ON ai_team_task (team_id, status);

-- ============================================================
-- 种子数据
-- ============================================================

-- 系统默认模型偏好
INSERT INTO ai_model_preference (scope, scope_id, capability, model_id)
VALUES
    ('SYSTEM', NULL, 'CHAT',      'deepseek:chat'),
    ('SYSTEM', NULL, 'EMBEDDING', 'qwen:embedding'),
    ('SYSTEM', NULL, 'IMAGE_GEN', 'openai:dall-e-3')
ON CONFLICT ON CONSTRAINT uq_model_preference DO NOTHING;

-- 第一期 12 个 provider 代表模型
-- capabilities: CHAT / EMBEDDING / VISION / IMAGE_GEN / AUDIO / RERANK
INSERT INTO ai_model (model_id, display_name, provider, provider_type, model_name, base_url,
                      capabilities, context_window, sort_order, enabled)
VALUES
-- P0: OpenAI
('openai:gpt-4o',           'GPT-4o',            'openai',     'OPENAI_COMPAT', 'gpt-4o',                     'https://api.openai.com/v1',                         'CHAT,VISION', 128000, 10,  true),
('openai:gpt-4o-mini',      'GPT-4o Mini',        'openai',     'OPENAI_COMPAT', 'gpt-4o-mini',                'https://api.openai.com/v1',                         'CHAT,VISION', 128000, 11,  true),
('openai:o1',               'o1',                 'openai',     'OPENAI_COMPAT', 'o1',                         'https://api.openai.com/v1',                         'CHAT',        200000, 12,  true),
('openai:text-embedding-3', 'text-embedding-3',   'openai',     'OPENAI_COMPAT', 'text-embedding-3-small',     'https://api.openai.com/v1',                         'EMBEDDING',   8191,   13,  true),
-- P0: DeepSeek
('deepseek:chat',           'DeepSeek Chat',      'deepseek',   'OPENAI_COMPAT', 'deepseek-chat',              'https://api.deepseek.com/v1',                       'CHAT',        64000,  20,  true),
('deepseek:reasoner',       'DeepSeek R1',        'deepseek',   'OPENAI_COMPAT', 'deepseek-reasoner',          'https://api.deepseek.com/v1',                       'CHAT',        64000,  21,  true),
-- P0: 通义千问
('qwen:max',                'Qwen Max',           'qwen',       'OPENAI_COMPAT', 'qwen-max',                   'https://dashscope.aliyuncs.com/compatible-mode/v1', 'CHAT',        32000,  30,  true),
('qwen:long',               'Qwen Long',          'qwen',       'OPENAI_COMPAT', 'qwen-long',                  'https://dashscope.aliyuncs.com/compatible-mode/v1', 'CHAT',        1000000,31,  true),
('qwen:embedding',          'Qwen Embedding',     'qwen',       'OPENAI_COMPAT', 'text-embedding-v3',          'https://dashscope.aliyuncs.com/compatible-mode/v1', 'EMBEDDING',   8192,   32,  true),
-- P0: 月之暗面
('moonshot:v1-128k',        'Kimi 128k',          'moonshot',   'OPENAI_COMPAT', 'moonshot-v1-128k',           'https://api.moonshot.cn/v1',                        'CHAT',        128000, 40,  true),
-- P1: 智谱
('zhipu:glm-4',             'GLM-4',              'zhipu',      'OPENAI_COMPAT', 'glm-4',                      'https://open.bigmodel.cn/api/paas/v4',              'CHAT',        128000, 50,  true),
('zhipu:glm-4v',            'GLM-4V',             'zhipu',      'OPENAI_COMPAT', 'glm-4v',                     'https://open.bigmodel.cn/api/paas/v4',              'CHAT,VISION', 2000,   51,  true),
-- P1: Anthropic
('anthropic:claude-3-5-sonnet', 'Claude 3.5 Sonnet', 'anthropic', 'ANTHROPIC',  'claude-3-5-sonnet-20241022', 'https://api.anthropic.com',                         'CHAT,VISION', 200000, 60,  true),
('anthropic:claude-3-haiku',    'Claude 3 Haiku',    'anthropic', 'ANTHROPIC',  'claude-3-haiku-20240307',    'https://api.anthropic.com',                         'CHAT,VISION', 200000, 61,  true),
-- P1: Ollama（本地，默认禁用）
('ollama:llama3',           'Llama 3',            'ollama',     'OLLAMA',        'llama3',                     'http://localhost:11434',                            'CHAT',        8192,   70,  false),
('ollama:qwen2.5',          'Qwen2.5 Local',      'ollama',     'OLLAMA',        'qwen2.5',                    'http://localhost:11434',                            'CHAT',        32768,  71,  false),
-- P1: 聚合平台
('openrouter:claude-3-5',   'Claude 3.5 via OR',  'openrouter', 'OPENAI_COMPAT', 'anthropic/claude-3.5-sonnet','https://openrouter.ai/api/v1',                     'CHAT,VISION', 200000, 80,  true),
('openrouter:gpt-4o',       'GPT-4o via OR',      'openrouter', 'OPENAI_COMPAT', 'openai/gpt-4o',              'https://openrouter.ai/api/v1',                     'CHAT,VISION', 128000, 81,  true),
('n1n:gpt-4o',              'GPT-4o via n1n',     'n1n',        'OPENAI_COMPAT', 'gpt-4o',                     'https://api.n1n.ai/v1',                             'CHAT,VISION', 128000, 90,  true),
('linkai:gpt-4o',           'GPT-4o via LinkAI',  'linkai',     'OPENAI_COMPAT', 'gpt-4o',                     'https://api.link-ai.tech/v1',                      'CHAT,VISION', 128000, 100, true),
-- P1: 阶跃星辰
('stepfun:step-2',          'Step-2',             'stepfun',    'OPENAI_COMPAT', 'step-2-16k',                 'https://api.stepfun.com/v1',                        'CHAT',        16000,  110, true),
('stepfun:step-1v',         'Step-1V（视觉）',     'stepfun',    'OPENAI_COMPAT', 'step-1v-8k',                 'https://api.stepfun.com/v1',                        'CHAT,VISION', 8000,   111, true),
-- P1: 火山引擎
('volcengine:doubao-pro',   'Doubao Pro',         'volcengine', 'OPENAI_COMPAT', 'doubao-pro-32k',             'https://ark.cn-beijing.volces.com/api/v3',          'CHAT',        32000,  120, true),
('volcengine:doubao-lite',  'Doubao Lite',        'volcengine', 'OPENAI_COMPAT', 'doubao-lite-32k',            'https://ark.cn-beijing.volces.com/api/v3',          'CHAT',        32000,  121, true)
ON CONFLICT (model_id) DO NOTHING;


-- ============================================================
-- AIGC 素材库
-- ============================================================

CREATE TABLE media_asset (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(200)   NOT NULL,
    type              VARCHAR(20)    NOT NULL,
    url               VARCHAR(1000)  NOT NULL,
    thumbnail_url     VARCHAR(1000),
    size              BIGINT,
    width             INTEGER,
    height            INTEGER,
    duration          NUMERIC(10,2),
    generation_params JSONB,
    tags              VARCHAR(500),
    category_id       BIGINT,
    user_id           BIGINT         NOT NULL,
    create_by         BIGINT,
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE media_asset IS 'AIGC 素材库';
COMMENT ON COLUMN media_asset.type IS '素材类型：IMAGE/VIDEO/AUDIO/MODEL_3D';
COMMENT ON COLUMN media_asset.generation_params IS 'AI 生成参数（prompt、模型等）';

CREATE INDEX idx_media_asset_user_id ON media_asset (user_id);
CREATE INDEX idx_media_asset_type ON media_asset (user_id, type);
CREATE INDEX idx_media_asset_category ON media_asset (category_id);

-- 素材分类（多级树形）
CREATE TABLE media_category (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(100)   NOT NULL,
    parent_id         BIGINT,
    sort_order        INTEGER        NOT NULL DEFAULT 0,
    create_by         BIGINT,
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE media_category IS '素材分类（多级树形）';
CREATE INDEX idx_media_category_parent ON media_category (parent_id);

-- 素材标签
CREATE TABLE media_tag (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(50)    NOT NULL,
    color             VARCHAR(20),
    create_by         BIGINT,
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE media_tag IS '素材标签';

-- 素材-标签关联表
CREATE TABLE media_asset_tag (
    asset_id          BIGINT         NOT NULL,
    tag_id            BIGINT         NOT NULL,
    PRIMARY KEY (asset_id, tag_id)
);

COMMENT ON TABLE media_asset_tag IS '素材-标签关联';
CREATE INDEX idx_media_asset_tag_asset ON media_asset_tag (asset_id);
CREATE INDEX idx_media_asset_tag_tag ON media_asset_tag (tag_id);

-- 素材变体关联
CREATE TABLE media_asset_variant (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    original_asset_id BIGINT         NOT NULL,
    variant_asset_id  BIGINT         NOT NULL,
    params_diff       JSONB,
    create_by         BIGINT,
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE media_asset_variant IS '素材变体关联';
CREATE INDEX idx_media_variant_original ON media_asset_variant (original_asset_id);
CREATE INDEX idx_media_variant_variant ON media_asset_variant (variant_asset_id);

-- 批量生成任务
CREATE TABLE batch_generation_task (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    user_id           BIGINT         NOT NULL,
    status            VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    total_count       INTEGER        NOT NULL DEFAULT 0,
    completed_count   INTEGER        NOT NULL DEFAULT 0,
    failed_count      INTEGER        NOT NULL DEFAULT 0,
    params            JSONB,
    create_by         BIGINT,
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE batch_generation_task IS 'AIGC 批量生成任务';
CREATE INDEX idx_batch_task_user ON batch_generation_task (user_id);
CREATE INDEX idx_batch_task_status ON batch_generation_task (status);

-- 生成参数模板
CREATE TABLE generation_template (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(100)   NOT NULL,
    category          VARCHAR(50),
    prompt            TEXT           NOT NULL,
    negative_prompt   TEXT,
    model             VARCHAR(100),
    width             INTEGER,
    height            INTEGER,
    steps             INTEGER,
    seed              BIGINT,
    is_public         BOOLEAN        NOT NULL DEFAULT FALSE,
    usage_count       INTEGER        NOT NULL DEFAULT 0,
    user_id           BIGINT         NOT NULL,
    create_by         BIGINT,
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE generation_template IS 'AIGC 生成参数模板';
CREATE INDEX idx_gen_template_user ON generation_template (user_id);
CREATE INDEX idx_gen_template_category ON generation_template (category);
CREATE INDEX idx_gen_template_public ON generation_template (is_public);

-- 视频模板
CREATE TABLE video_template (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(100)   NOT NULL,
    type              VARCHAR(30)    NOT NULL,
    params            TEXT,
    preview_url       VARCHAR(500),
    thumbnail_url     VARCHAR(500),
    user_id           BIGINT,
    create_by         BIGINT,
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE video_template IS 'AIGC 视频模板';
CREATE INDEX idx_video_template_type ON video_template (type);

-- 生成历史
CREATE TABLE generation_history (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    user_id           BIGINT         NOT NULL,
    type              VARCHAR(20)    NOT NULL,
    prompt            TEXT,
    model             VARCHAR(100),
    params            TEXT,
    result_url        VARCHAR(500),
    asset_id          BIGINT,
    session_id        BIGINT,
    create_by         BIGINT,
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE generation_history IS 'AIGC 生成历史记录';
CREATE INDEX idx_gen_history_user ON generation_history (user_id);
CREATE INDEX idx_gen_history_type ON generation_history (user_id, type);
CREATE INDEX idx_gen_history_session ON generation_history (session_id);


-- ============================================================
-- 智能体执行追踪 Schema
-- 包含：执行运行记录、执行步骤
-- ============================================================

CREATE TABLE execution_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id    VARCHAR(128) NOT NULL UNIQUE,
    parent_run_id   BIGINT REFERENCES execution_run(id),
    agent_id        VARCHAR(64)  NOT NULL,
    agent_name      VARCHAR(128),
    user_id         BIGINT,
    conversation_id VARCHAR(64),
    input           TEXT,
    output          TEXT,
    status          VARCHAR(16)  NOT NULL,
    error_message   TEXT,
    token_input     INTEGER      NOT NULL DEFAULT 0,
    token_output    INTEGER      NOT NULL DEFAULT 0,
    started_at      TIMESTAMPTZ  NOT NULL,
    finished_at     TIMESTAMPTZ,
    duration_ms     BIGINT,
    retry_count     INTEGER      NOT NULL DEFAULT 0,
    metadata        JSONB
);

COMMENT ON TABLE execution_run IS '智能体执行运行记录';
CREATE INDEX idx_execution_run_user   ON execution_run(user_id, started_at DESC);
CREATE INDEX idx_execution_run_agent  ON execution_run(agent_id, started_at DESC);
CREATE INDEX idx_execution_run_status ON execution_run(status) WHERE status != 'SUCCESS';
CREATE INDEX idx_execution_run_parent ON execution_run(parent_run_id) WHERE parent_run_id IS NOT NULL;

CREATE TABLE execution_step (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT       NOT NULL REFERENCES execution_run(id),
    parent_step_id  BIGINT REFERENCES execution_step(id),
    step_index      INTEGER      NOT NULL,
    step_type       VARCHAR(32)  NOT NULL,
    agent_id        VARCHAR(64),
    tool_name       VARCHAR(128),
    input           TEXT,
    output          TEXT,
    status          VARCHAR(16)  NOT NULL,
    error_message   TEXT,
    started_at      TIMESTAMPTZ  NOT NULL,
    finished_at     TIMESTAMPTZ,
    duration_ms     BIGINT
);

COMMENT ON TABLE execution_step IS '智能体执行步骤';
CREATE INDEX idx_execution_step_run ON execution_step(run_id, step_index);



-- ============================================================
-- 知识库段落
-- ============================================================

CREATE TABLE knowledge_segment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    document_id       BIGINT       NOT NULL,
    knowledge_base_id BIGINT       NOT NULL,
    content           TEXT         NOT NULL,
    position          INTEGER      NOT NULL,
    word_count        INTEGER,
    enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
    embedding         vector(1536),
    create_by         BIGINT,
    create_time       TIMESTAMP(6),
    update_by         BIGINT,
    update_time       TIMESTAMP(6),
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            TEXT
);

COMMENT ON TABLE knowledge_segment IS '知识库段落（文档分块后的最小检索单元）';
COMMENT ON COLUMN knowledge_segment.document_id IS '所属文档 ID';
COMMENT ON COLUMN knowledge_segment.knowledge_base_id IS '所属知识库 ID';
COMMENT ON COLUMN knowledge_segment.position IS '段落在文档中的位置（从 0 开始）';
COMMENT ON COLUMN knowledge_segment.embedding IS '向量嵌入（PgVector 1536 维）';

CREATE INDEX idx_knowledge_segment_doc ON knowledge_segment (document_id);
CREATE INDEX idx_knowledge_segment_base ON knowledge_segment (knowledge_base_id);
CREATE INDEX idx_knowledge_segment_embedding
    ON knowledge_segment USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- ============================================================
-- 补充种子数据
-- ============================================================

-- 字典类型
INSERT INTO sys_dict_type (name, type, status, create_time, update_time)
VALUES
    ('记忆范围', 'ai_memory_scope', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Agent 状态', 'ai_agent_status', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('模型厂商类型', 'ai_provider_type', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

-- 字典数据：记忆范围
INSERT INTO sys_dict_data (dict_type, label, value, sort, status)
VALUES
    ('ai_memory_scope', '短期记忆', 'short_term', 1, 0),
    ('ai_memory_scope', '长期记忆', 'long_term', 2, 0),
    ('ai_memory_scope', '情景记忆', 'episodic', 3, 0),
    ('ai_memory_scope', '程序性记忆', 'procedural', 4, 0)
ON CONFLICT DO NOTHING;

-- 字典数据：Agent 状态
INSERT INTO sys_dict_data (dict_type, label, value, sort, status)
VALUES
    ('ai_agent_status', '活跃', 'active', 1, 0),
    ('ai_agent_status', '停用', 'inactive', 2, 0),
    ('ai_agent_status', '已归档', 'archived', 3, 0)
ON CONFLICT DO NOTHING;

-- 字典数据：模型厂商类型
INSERT INTO sys_dict_data (dict_type, label, value, sort, status)
VALUES
    ('ai_provider_type', 'OpenAI 兼容', 'OPENAI_COMPAT', 1, 0),
    ('ai_provider_type', 'Anthropic', 'ANTHROPIC', 2, 0),
    ('ai_provider_type', 'Ollama 本地', 'OLLAMA', 3, 0)
ON CONFLICT DO NOTHING;

-- 默认 Actor（通用助手人格）
INSERT INTO ai_actor (actor_id, name, persona, system_prompt, status, create_time, update_time)
VALUES (
    'default-assistant',
    '通用助手',
    '友好、专业、简洁。用中文回答，必要时使用代码示例。',
    '你是一个通用 AI 助手，帮助用户解答问题、完成任务。保持友好专业的语气，回答简洁准确。',
    'active',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
) ON CONFLICT (actor_id) DO NOTHING;

-- 默认 Role（通用能力集）
INSERT INTO ai_role (role_id, name, description, skill_ids, tool_whitelist, status, create_time, update_time)
VALUES (
    'default-generalist',
    '通用能力集',
    '基础对话、知识问答、代码辅助',
    '[]',
    '[]',
    'active',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
) ON CONFLICT (role_id) DO NOTHING;

-- 默认 Assistant（绑定默认 Actor + Role）
INSERT INTO ai_assistant (assistant_id, user_id, actor_id, role_id, memory_strategy, status, create_time, update_time)
VALUES (
    'default-assistant',
    0,
    'default-assistant',
    'default-generalist',
    'HYBRID',
    'active',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
) ON CONFLICT (assistant_id) DO NOTHING;

-- 测试数据：deepseek:chat 模型配置（已在上方 seed 中包含，此处确保 api_key 占位）
UPDATE ai_model
SET api_key_encrypted = 'PLACEHOLDER_REPLACE_WITH_REAL_KEY',
    temperature = 0.7,
    max_tokens = 4096
WHERE model_id = 'deepseek:chat'
  AND api_key_encrypted IS NULL;
