-- AAF-031 协作与通知 + BaseEntity 扩展（org_id / workspace_id）
-- 表：sys_notification, sys_notification_preference, sys_record_version,
--      sys_activity_log, sys_comment, sys_subscription, sys_todo

-- ==================== BaseEntity 新增字段（已有表补列） ====================

ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS org_id BIGINT;
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS workspace_id BIGINT;

ALTER TABLE doc_document ADD COLUMN IF NOT EXISTS org_id BIGINT;
ALTER TABLE doc_document ADD COLUMN IF NOT EXISTS workspace_id BIGINT;

ALTER TABLE autodev_request ADD COLUMN IF NOT EXISTS org_id BIGINT;
ALTER TABLE autodev_request ADD COLUMN IF NOT EXISTS workspace_id BIGINT;

ALTER TABLE autodev_generated_code ADD COLUMN IF NOT EXISTS org_id BIGINT;
ALTER TABLE autodev_generated_code ADD COLUMN IF NOT EXISTS workspace_id BIGINT;

ALTER TABLE autodev_execution_log ADD COLUMN IF NOT EXISTS org_id BIGINT;
ALTER TABLE autodev_execution_log ADD COLUMN IF NOT EXISTS workspace_id BIGINT;

-- ==================== 通知 ====================

CREATE TABLE sys_notification (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL,
    type         VARCHAR(50)  NOT NULL,
    title        VARCHAR(200) NOT NULL,
    body         TEXT,
    entity_type  VARCHAR(100),
    entity_id    BIGINT,
    is_read      BOOLEAN      NOT NULL DEFAULT FALSE,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_notification IS '系统通知';
COMMENT ON COLUMN sys_notification.type IS '通知类型：system / task / mention / subscription';
COMMENT ON COLUMN sys_notification.is_read IS '是否已读';

CREATE INDEX idx_notification_user ON sys_notification (user_id);
CREATE INDEX idx_notification_user_read ON sys_notification (user_id, is_read);

-- ==================== 通知偏好 ====================

CREATE TABLE sys_notification_preference (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT NOT NULL UNIQUE,
    preferences  JSONB  NOT NULL DEFAULT '{}',
    quiet_start  TIME,
    quiet_end    TIME,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_notification_preference IS '通知偏好设置';
COMMENT ON COLUMN sys_notification_preference.preferences IS '按类别配置通道：{"task":{"inApp":true,"email":false}}';

-- ==================== 版本快照 ====================

CREATE TABLE sys_record_version (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    version      INTEGER      NOT NULL,
    data         JSONB        NOT NULL,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_record_version IS '实体版本快照';
COMMENT ON COLUMN sys_record_version.version IS '版本号（递增）';
COMMENT ON COLUMN sys_record_version.data IS '快照数据（完整 JSON）';

CREATE INDEX idx_record_version_entity ON sys_record_version (entity_type, entity_id, version DESC);

-- ==================== 活动日志 ====================

CREATE TABLE sys_activity_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    action       VARCHAR(50)  NOT NULL,
    changes      JSONB,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_activity_log IS '实体活动日志';
COMMENT ON COLUMN sys_activity_log.action IS '操作类型：create / update / delete / status_change';
COMMENT ON COLUMN sys_activity_log.changes IS '字段变更：[{"field":"status","oldValue":"draft","newValue":"published"}]';

CREATE INDEX idx_activity_log_entity ON sys_activity_log (entity_type, entity_id, create_time DESC);

-- ==================== 评论 ====================

CREATE TABLE sys_comment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    content      TEXT         NOT NULL,
    mentions     JSONB,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_comment IS '实体评论';
COMMENT ON COLUMN sys_comment.mentions IS '被@用户ID列表：[1, 2, 3]';

CREATE INDEX idx_comment_entity ON sys_comment (entity_type, entity_id, create_time DESC);

-- ==================== 字段订阅 ====================

CREATE TABLE sys_subscription (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT       NOT NULL,
    entity_type  VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    fields       JSONB,
    channels     JSONB,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_subscription IS '字段变更订阅';
COMMENT ON COLUMN sys_subscription.fields IS '订阅的字段列表：["status","assignee"]，null 表示全部';
COMMENT ON COLUMN sys_subscription.channels IS '通知通道：["inApp","email"]';

CREATE UNIQUE INDEX idx_subscription_unique ON sys_subscription (user_id, entity_type, entity_id) WHERE deleted = FALSE;

-- ==================== 待办 ====================

CREATE TABLE sys_todo (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id        BIGINT,
    workspace_id  BIGINT,
    assignee_id   BIGINT       NOT NULL,
    title         VARCHAR(200) NOT NULL,
    source_type   VARCHAR(50),
    source_entity VARCHAR(100),
    source_id     BIGINT,
    status        VARCHAR(20)  NOT NULL DEFAULT 'pending',
    due_date      TIMESTAMP(6),
    create_by     BIGINT,
    create_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by     BIGINT,
    update_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    remark        VARCHAR(255)
);

COMMENT ON TABLE sys_todo IS '待办事项';
COMMENT ON COLUMN sys_todo.source_type IS '来源类型：mention / task / workflow';
COMMENT ON COLUMN sys_todo.status IS '状态：pending / done / ignored';

CREATE INDEX idx_todo_assignee ON sys_todo (assignee_id, status);
