-- ============================================================
-- AI 基础设施 Schema
-- 包含：模型管理、Prompt模板、Token用量、记忆、Agent、Assistant、Team
-- ============================================================

-- ============================================================
-- 模型管理
-- ============================================================

CREATE TABLE ai_model_provider (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER          NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    provider_code       VARCHAR(64)      NOT NULL UNIQUE,
    provider_name       VARCHAR(128)     NOT NULL,
    provider_type       VARCHAR(32)      NOT NULL DEFAULT 'OPENAI_COMPAT',
    base_url            VARCHAR(512),
    api_key_encrypted   VARCHAR(1024),
    enabled             BOOLEAN          NOT NULL DEFAULT TRUE,
    sort_order          INTEGER          DEFAULT 100,
    icon                VARCHAR(100),
    description         TEXT,
    owner_id            BIGINT,
    create_by           BIGINT,
    create_by_type      VARCHAR(16),
    create_time         TIMESTAMP(6),
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6),
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN          NOT NULL DEFAULT FALSE,
    remark              TEXT
);

COMMENT ON TABLE ai_model_provider IS 'AI 模型供应商配置：统一维护同一供应商共享的 baseUrl 与 API Key';
COMMENT ON COLUMN ai_model_provider.provider_code IS '供应商编码：aliyun / volcengine / deepseek / third_party 等';
COMMENT ON COLUMN ai_model_provider.provider_type IS '默认协议类型：OPENAI_COMPAT / ANTHROPIC / OLLAMA';
COMMENT ON COLUMN ai_model_provider.api_key_encrypted IS '供应商级 API Key（加密存储）';

CREATE TABLE ai_model (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER          NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    model_id            VARCHAR(128)     NOT NULL UNIQUE,
    display_name        VARCHAR(128)     NOT NULL,
    provider_id         BIGINT,
    provider            VARCHAR(32)      NOT NULL,
    provider_type       VARCHAR(32)      NOT NULL DEFAULT 'OPENAI_COMPAT',
    model_name          VARCHAR(128)     NOT NULL,
    base_url            VARCHAR(512),
    api_key_encrypted   VARCHAR(1024),
    temperature         DOUBLE PRECISION,
    max_tokens          INTEGER,
    context_window      INTEGER,
    enabled             BOOLEAN          NOT NULL DEFAULT TRUE,
    capabilities        VARCHAR(256),
    input_price_per_k   NUMERIC(10, 6),
    output_price_per_k  NUMERIC(10, 6),
    fallback_model_id   VARCHAR(64),
    sort_order          INTEGER              DEFAULT 100,
    -- n1n.ai 价格相关字段
    model_ratio         NUMERIC(10, 6)   DEFAULT 1.0,
    completion_ratio    NUMERIC(10, 6)   DEFAULT 1.0,
    cache_ratio         NUMERIC(10, 6),
    audio_ratio         NUMERIC(10, 6),
    audio_completion_ratio NUMERIC(10, 6),
    step_ratios         JSONB,
    -- 能力与类型
    tags                VARCHAR(200),
    model_type          VARCHAR(50),
    supported_endpoints JSONB,
    -- 配额管理
    quota_type          SMALLINT         DEFAULT 0,
    model_price         NUMERIC(10, 6),
    -- 分组与供应商
    enable_groups       JSONB,
    vendor_id           BIGINT,
    vendor_name         VARCHAR(100),
    vendor_icon         VARCHAR(100),
    -- 显示
    icon                VARCHAR(100),
    description         TEXT,
    official_price      JSONB,
    -- 元数据
    owner_id            BIGINT,
    create_by           BIGINT,
    create_by_type      VARCHAR(16),
    create_time         TIMESTAMP(6),
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6),
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN          NOT NULL DEFAULT FALSE,
    remark              TEXT,
    CONSTRAINT fk_ai_model_provider FOREIGN KEY (provider_id) REFERENCES ai_model_provider(id)
);

COMMENT ON TABLE ai_model IS 'AI 模型配置';
COMMENT ON COLUMN ai_model.provider_type     IS '协议类型：OPENAI_COMPAT / ANTHROPIC / OLLAMA';
COMMENT ON COLUMN ai_model.capabilities      IS '能力标记：CHAT,VISION,EMBEDDING,IMAGE_GEN,AUDIO,RERANK';
COMMENT ON COLUMN ai_model.input_price_per_k IS '输入 Token 单价（元/千Token）';
COMMENT ON COLUMN ai_model.output_price_per_k IS '输出 Token 单价（元/千Token）';
COMMENT ON COLUMN ai_model.model_ratio       IS '模型价格倍率（基础系数）';
COMMENT ON COLUMN ai_model.completion_ratio  IS '输出 Token 倍率';
COMMENT ON COLUMN ai_model.cache_ratio       IS '缓存 Token 倍率';
COMMENT ON COLUMN ai_model.audio_ratio       IS '音频输入倍率';
COMMENT ON COLUMN ai_model.audio_completion_ratio IS '音频输出倍率';
COMMENT ON COLUMN ai_model.step_ratios       IS '阶梯计费配置（JSON 数组）';
COMMENT ON COLUMN ai_model.tags              IS '能力标签（逗号分隔）：对话、识图、思考、工具等';
COMMENT ON COLUMN ai_model.model_type        IS '模型类型：文本、图像、音视频、检索';
COMMENT ON COLUMN ai_model.supported_endpoints IS '支持的接口类型（JSON 数组）';
COMMENT ON COLUMN ai_model.quota_type        IS '配额类型：0=token计费，1=次数计费，3/4=视频计费';
COMMENT ON COLUMN ai_model.model_price       IS '固定价格（quota_type=1 时使用）';
COMMENT ON COLUMN ai_model.enable_groups     IS '启用的用户组（JSON 数组）';
COMMENT ON COLUMN ai_model.provider_id       IS '供应商配置 ID（关联 ai_model_provider）';
COMMENT ON COLUMN ai_model.vendor_id         IS '供应商 ID（关联 vendor 表）';
COMMENT ON COLUMN ai_model.vendor_name       IS '供应商名称';
COMMENT ON COLUMN ai_model.official_price    IS '官方定价参考（JSON）';

CREATE TABLE ai_model_preference (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     INTEGER      NOT NULL DEFAULT 0,
    org_id      BIGINT,
    workspace_id BIGINT,
    scope       VARCHAR(16)  NOT NULL,
    scope_id    BIGINT,
    capability  VARCHAR(32)  NOT NULL,
    model_id    VARCHAR(64)  NOT NULL,
    owner_id    BIGINT,
    create_by   BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by   BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    remark      VARCHAR(255),
    CONSTRAINT uq_model_preference UNIQUE (scope, scope_id, capability)
);

COMMENT ON TABLE ai_model_preference IS '模型偏好配置';
COMMENT ON COLUMN ai_model_preference.scope      IS 'USER=用户级别 / SYSTEM=系统默认';
COMMENT ON COLUMN ai_model_preference.scope_id   IS '用户ID（scope=USER时），SYSTEM时为null';
COMMENT ON COLUMN ai_model_preference.capability IS '能力类型：CHAT/EMBEDDING/IMAGE_GEN/SPEECH_ASR等';

CREATE TABLE ai_prompt_template (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    name             VARCHAR(128) NOT NULL,
    template_version INTEGER          NOT NULL DEFAULT 1,
    content          TEXT         NOT NULL,
    description      VARCHAR(512),
    variables        TEXT,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    category         VARCHAR(64),
    owner_id         BIGINT,
    create_by        BIGINT,
    create_by_type   VARCHAR(16),
    create_time      TIMESTAMP(6),
    update_by        BIGINT,
    update_by_type   VARCHAR(16),
    update_time      TIMESTAMP(6),
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    remark           TEXT,
    UNIQUE (name, template_version)
);

COMMENT ON TABLE ai_prompt_template IS 'Prompt 模板';

-- ============================================================
-- Token 用量
-- ============================================================

CREATE TABLE ai_token_usage (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    usage_id          VARCHAR(64)  NOT NULL,
    conversation_id   VARCHAR(64),
    model_id          VARCHAR(64)  NOT NULL,
    prompt_tokens     BIGINT       NOT NULL,
    completion_tokens BIGINT       NOT NULL,
    total_tokens      BIGINT       NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ai_token_usage IS 'Token 用量记录';
COMMENT ON COLUMN ai_token_usage.usage_id IS '用量流水号，用于关联 credit_transaction.biz_id';
CREATE UNIQUE INDEX uk_ai_token_usage_usage_id ON ai_token_usage (usage_id);
CREATE INDEX idx_ai_token_usage_user_created  ON ai_token_usage (user_id, created_at);
CREATE INDEX idx_ai_token_usage_model_created ON ai_token_usage (model_id, created_at);

-- ============================================================
-- 开发者商业授权与托管模型额度
-- 说明：仅管理开发者授权、订阅、额度、兑换码、子代理资格。
-- 真正模型代理服务需完成 ICP/生成式 AI 服务登记等合规确认后再启用。
-- ============================================================

CREATE TABLE developer_account (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version               INTEGER      NOT NULL DEFAULT 0,
    org_id                BIGINT,
    workspace_id          BIGINT,
    developer_code        VARCHAR(64)  NOT NULL,
    user_id               BIGINT       NOT NULL,
    name                  VARCHAR(120) NOT NULL,
    status                VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    license_id            VARCHAR(120),
    license_tier          VARCHAR(32)  NOT NULL DEFAULT 'FREE',
    allow_managed_gateway BOOLEAN      NOT NULL DEFAULT FALSE,
    allow_sub_proxy       BOOLEAN      NOT NULL DEFAULT FALSE,
    max_proxy_depth       INTEGER      NOT NULL DEFAULT 0,
    owner_id              BIGINT,
    create_by             BIGINT,
    create_by_type        VARCHAR(16),
    create_time           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by             BIGINT,
    update_by_type        VARCHAR(16),
    update_time           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time           TIMESTAMP(6),
    deleted               BOOLEAN      NOT NULL DEFAULT FALSE,
    remark                VARCHAR(255)
);

COMMENT ON TABLE developer_account IS '开发者账户：承载框架开发者授权、托管网关和子代理资格';
COMMENT ON COLUMN developer_account.allow_managed_gateway IS '是否允许使用 AAF 托管模型网关';
COMMENT ON COLUMN developer_account.allow_sub_proxy IS '是否允许开通子代理';
COMMENT ON COLUMN developer_account.max_proxy_depth IS '允许的最大子代理层级';
CREATE UNIQUE INDEX uk_developer_account_code ON developer_account(developer_code) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_developer_account_user ON developer_account(user_id) WHERE deleted = FALSE;

CREATE TABLE developer_subscription_plan (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version               INTEGER      NOT NULL DEFAULT 0,
    org_id                BIGINT,
    workspace_id          BIGINT,
    code                  VARCHAR(40)  NOT NULL,
    name                  VARCHAR(100) NOT NULL,
    duration_days         INTEGER      NOT NULL,
    price                 BIGINT       NOT NULL DEFAULT 0,
    included_tokens       BIGINT       NOT NULL DEFAULT 0,
    allow_managed_gateway BOOLEAN      NOT NULL DEFAULT FALSE,
    allow_sub_proxy       BOOLEAN      NOT NULL DEFAULT FALSE,
    max_proxy_depth       INTEGER      NOT NULL DEFAULT 0,
    status                VARCHAR(20)  NOT NULL DEFAULT 'ENABLED',
    sort_order            INTEGER      NOT NULL DEFAULT 100,
    owner_id              BIGINT,
    create_by             BIGINT,
    create_by_type        VARCHAR(16),
    create_time           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by             BIGINT,
    update_by_type        VARCHAR(16),
    update_time           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time           TIMESTAMP(6),
    deleted               BOOLEAN      NOT NULL DEFAULT FALSE,
    remark                VARCHAR(255)
);

COMMENT ON TABLE developer_subscription_plan IS '开发者订阅套餐';
CREATE UNIQUE INDEX uk_developer_subscription_plan_code ON developer_subscription_plan(code) WHERE deleted = FALSE;

CREATE TABLE developer_subscription (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        INTEGER      NOT NULL DEFAULT 0,
    org_id         BIGINT,
    workspace_id   BIGINT,
    developer_id   BIGINT       NOT NULL,
    plan_id        BIGINT       NOT NULL,
    start_at       TIMESTAMP(6) NOT NULL,
    end_at         TIMESTAMP(6),
    status         VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    source_id      BIGINT,
    owner_id       BIGINT,
    create_by      BIGINT,
    create_by_type VARCHAR(16),
    create_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by      BIGINT,
    update_by_type VARCHAR(16),
    update_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time    TIMESTAMP(6),
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    remark         VARCHAR(255)
);

COMMENT ON TABLE developer_subscription IS '开发者订阅实例';
CREATE INDEX idx_developer_subscription_developer ON developer_subscription(developer_id, status) WHERE deleted = FALSE;

CREATE TABLE developer_token_account (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER      NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    developer_id        BIGINT       NOT NULL,
    balance_tokens      BIGINT       NOT NULL DEFAULT 0,
    frozen_tokens       BIGINT       NOT NULL DEFAULT 0,
    total_earned_tokens BIGINT       NOT NULL DEFAULT 0,
    total_spent_tokens  BIGINT       NOT NULL DEFAULT 0,
    owner_id            BIGINT,
    create_by           BIGINT,
    create_by_type      VARCHAR(16),
    create_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    remark              VARCHAR(255)
);

COMMENT ON TABLE developer_token_account IS '开发者托管模型总 Token 池';
CREATE UNIQUE INDEX uk_developer_token_account ON developer_token_account(developer_id) WHERE deleted = FALSE;

CREATE TABLE developer_token_transaction (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version              INTEGER      NOT NULL DEFAULT 0,
    org_id               BIGINT,
    workspace_id         BIGINT,
    account_id           BIGINT       NOT NULL,
    developer_id         BIGINT       NOT NULL,
    type                 VARCHAR(20)  NOT NULL,
    amount_tokens        BIGINT       NOT NULL,
    balance_after_tokens BIGINT       NOT NULL,
    source               VARCHAR(80),
    biz_id               VARCHAR(120),
    owner_id             BIGINT,
    create_by            BIGINT,
    create_by_type       VARCHAR(16),
    create_time          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by            BIGINT,
    update_by_type       VARCHAR(16),
    update_time          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time          TIMESTAMP(6),
    deleted              BOOLEAN      NOT NULL DEFAULT FALSE,
    remark               VARCHAR(255)
);

COMMENT ON TABLE developer_token_transaction IS '开发者 Token 池流水';
CREATE INDEX idx_developer_token_tx_developer ON developer_token_transaction(developer_id, create_time) WHERE deleted = FALSE;
CREATE INDEX idx_developer_token_tx_biz ON developer_token_transaction(biz_id) WHERE deleted = FALSE;

CREATE TABLE developer_redeem_code (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                    INTEGER      NOT NULL DEFAULT 0,
    org_id                     BIGINT,
    workspace_id               BIGINT,
    code_hash                  VARCHAR(64)  NOT NULL,
    code_prefix                VARCHAR(20)  NOT NULL,
    token_amount               BIGINT       NOT NULL,
    status                     VARCHAR(20)  NOT NULL DEFAULT 'UNUSED',
    expires_at                 TIMESTAMP(6),
    redeemed_by_developer_id   BIGINT,
    redeemed_at                TIMESTAMP(6),
    owner_id                   BIGINT,
    create_by                  BIGINT,
    create_by_type             VARCHAR(16),
    create_time                TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by                  BIGINT,
    update_by_type             VARCHAR(16),
    update_time                TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time                TIMESTAMP(6),
    deleted                    BOOLEAN      NOT NULL DEFAULT FALSE,
    remark                     VARCHAR(255)
);

COMMENT ON TABLE developer_redeem_code IS '开发者 Token 兑换码';
CREATE UNIQUE INDEX uk_developer_redeem_code_hash ON developer_redeem_code(code_hash) WHERE deleted = FALSE;

CREATE TABLE developer_api_key (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        INTEGER      NOT NULL DEFAULT 0,
    org_id         BIGINT,
    workspace_id   BIGINT,
    developer_id   BIGINT       NOT NULL,
    name           VARCHAR(120) NOT NULL,
    key_hash       VARCHAR(64)  NOT NULL,
    key_prefix     VARCHAR(24)  NOT NULL,
    scopes         VARCHAR(255) NOT NULL DEFAULT 'gateway:chat',
    enabled        BOOLEAN      NOT NULL DEFAULT TRUE,
    expires_at     TIMESTAMPTZ,
    last_used_at   TIMESTAMPTZ,
    owner_id       BIGINT,
    create_by      BIGINT,
    create_by_type VARCHAR(16),
    create_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by      BIGINT,
    update_by_type VARCHAR(16),
    update_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time    TIMESTAMP(6),
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    remark         VARCHAR(255)
);

COMMENT ON TABLE developer_api_key IS '开发者调用 AAF Model Gateway 的 API Key，当前仅管理，不启用代理执行入口';
CREATE UNIQUE INDEX uk_developer_api_key_hash ON developer_api_key(key_hash) WHERE deleted = FALSE;
CREATE INDEX idx_developer_api_key_developer ON developer_api_key(developer_id) WHERE deleted = FALSE;

CREATE TABLE developer_proxy (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER      NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    parent_developer_id BIGINT       NOT NULL,
    child_developer_id  BIGINT       NOT NULL,
    proxy_depth         INTEGER      NOT NULL DEFAULT 1,
    status              VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    token_limit         BIGINT,
    allow_sub_proxy     BOOLEAN      NOT NULL DEFAULT FALSE,
    owner_id            BIGINT,
    create_by           BIGINT,
    create_by_type      VARCHAR(16),
    create_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    remark              VARCHAR(255)
);

COMMENT ON TABLE developer_proxy IS '开发者子代理配置，用于受控分销层级';
CREATE UNIQUE INDEX uk_developer_proxy_pair ON developer_proxy(parent_developer_id, child_developer_id) WHERE deleted = FALSE;

-- ============================================================
-- 记忆
-- ============================================================

CREATE TABLE ai_long_term_memory (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT           NOT NULL,
    content          TEXT             NOT NULL,
    source_id        VARCHAR(128),
    memory_type      VARCHAR(32)      NOT NULL,
    importance       DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    last_accessed_at TIMESTAMP(6),
    access_count     INTEGER              NOT NULL DEFAULT 0,
    event_time       TIMESTAMP(6),
    created_at       TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ai_long_term_memory IS '长期记忆';
CREATE INDEX idx_ai_long_term_memory_user ON ai_long_term_memory (user_id, importance DESC);

CREATE TABLE ai_procedural_memory (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER          NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    user_id       BIGINT,
    task_type     VARCHAR(64)      NOT NULL,
    category      VARCHAR(64),
    title         VARCHAR(256)     NOT NULL,
    content       TEXT             NOT NULL,
    success_count INTEGER              NOT NULL DEFAULT 0,
    use_count     INTEGER              NOT NULL DEFAULT 0,
    quality_score DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    owner_id      BIGINT,
    create_by     BIGINT,
    create_by_type VARCHAR(16),
    create_time   TIMESTAMP(6),
    update_by     BIGINT,
    update_by_type VARCHAR(16),
    update_time   TIMESTAMP(6),
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN          NOT NULL DEFAULT FALSE,
    remark        TEXT
);

COMMENT ON TABLE ai_procedural_memory IS '程序性记忆';
CREATE INDEX idx_ai_procedural_memory_user ON ai_procedural_memory (user_id, category);

-- ============================================================
-- Agent / Assistant / Team
-- ============================================================

CREATE TABLE ai_agent_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    agent_id        VARCHAR(64)  NOT NULL UNIQUE,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    system_prompt   TEXT,
    model_id        VARCHAR(64),
    capabilities    TEXT,
    tools           TEXT,
    allowed_tools   TEXT,
    mcp_servers     TEXT,
    max_iterations  INTEGER          NOT NULL DEFAULT 10,
    timeout_seconds INTEGER          NOT NULL DEFAULT 120,
    memory_config   JSONB,
    status          VARCHAR(16)  NOT NULL DEFAULT 'active',
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6),
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6),
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE ai_agent_definition IS 'Agent 定义';

CREATE TABLE ai_actor (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER      NOT NULL DEFAULT 0,
    org_id        BIGINT,
    workspace_id  BIGINT,
    actor_id      VARCHAR(64)  NOT NULL UNIQUE,
    name          VARCHAR(128) NOT NULL,
    persona       TEXT,
    system_prompt TEXT,
    avatar_url    VARCHAR(512),
    status        VARCHAR(16)  NOT NULL DEFAULT 'active',
    owner_id      BIGINT,
    create_by     BIGINT,
    create_by_type VARCHAR(16),
    create_time   TIMESTAMP(6),
    update_by     BIGINT,
    update_by_type VARCHAR(16),
    update_time   TIMESTAMP(6),
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    remark        TEXT
);

COMMENT ON TABLE ai_actor IS 'Actor（人格载体）';

CREATE TABLE ai_role (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        INTEGER      NOT NULL DEFAULT 0,
    org_id         BIGINT,
    workspace_id   BIGINT,
    role_id        VARCHAR(64)  NOT NULL UNIQUE,
    name           VARCHAR(128) NOT NULL,
    description    VARCHAR(512),
    skill_ids      TEXT,
    tool_whitelist TEXT,
    status         VARCHAR(16)  NOT NULL DEFAULT 'active',
    owner_id       BIGINT,
    create_by      BIGINT,
    create_by_type VARCHAR(16),
    create_time    TIMESTAMP(6),
    update_by      BIGINT,
    update_by_type VARCHAR(16),
    update_time    TIMESTAMP(6),
    delete_time    TIMESTAMP(6),
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    remark         TEXT
);

COMMENT ON TABLE ai_role IS 'Role（能力配置）：定义助理的技能集和工具白名单';

CREATE TABLE ai_assistant (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    assistant_id      VARCHAR(64)  NOT NULL UNIQUE,
    user_id           BIGINT       NOT NULL,
    actor_id          VARCHAR(64)  NOT NULL,
    role_id           VARCHAR(64)  NOT NULL,
    memory_strategy   VARCHAR(32)  NOT NULL DEFAULT 'HYBRID',
    knowledge_base_id BIGINT,
    status            VARCHAR(16)  NOT NULL DEFAULT 'active',
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6),
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6),
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            TEXT
);

COMMENT ON TABLE ai_assistant IS 'Assistant 定义（Actor + Role + 记忆策略）';
CREATE INDEX idx_ai_assistant_user ON ai_assistant (user_id);

CREATE TABLE ai_skill_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    skill_id        VARCHAR(64)  NOT NULL UNIQUE,
    assistant_id    VARCHAR(64),
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    agent_id        VARCHAR(64),
    trigger_intent  TEXT,
    system_prompt   TEXT,
    instructions    TEXT,
    tools           TEXT,
    priority        INTEGER          NOT NULL DEFAULT 0,
    built_in        BOOLEAN      NOT NULL DEFAULT FALSE,
    is_global       BOOLEAN      NOT NULL DEFAULT FALSE,
    skill_version   VARCHAR(16),
    status          VARCHAR(16)  NOT NULL DEFAULT 'active',
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6),
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6),
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          TEXT
);

COMMENT ON TABLE ai_skill_definition IS '技能定义';
CREATE INDEX idx_ai_skill_definition_assistant ON ai_skill_definition (assistant_id);

CREATE TABLE ai_action_catalog (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                  INTEGER      NOT NULL DEFAULT 0,
    org_id                   BIGINT,
    workspace_id             BIGINT,
    action_key               VARCHAR(120) NOT NULL,
    entity_slug              VARCHAR(120),
    display_name             VARCHAR(120) NOT NULL,
    description              VARCHAR(500),
    enabled                  BOOLEAN      NOT NULL DEFAULT TRUE,
    risk_level               VARCHAR(16)  NOT NULL DEFAULT 'low',
    require_confirm          BOOLEAN      NOT NULL DEFAULT FALSE,
    permission_code_override VARCHAR(120),
    entitlement_code         VARCHAR(64),
    cost_expression          VARCHAR(255),
    input_schema             TEXT,
    output_schema            TEXT,
    sort_order               INTEGER      NOT NULL DEFAULT 100,
    create_by                BIGINT,
    create_by_type           VARCHAR(16),
    create_time              TIMESTAMP(6),
    update_by                BIGINT,
    update_by_type           VARCHAR(16),
    update_time              TIMESTAMP(6),
    owner_id                 BIGINT,
    delete_time              TIMESTAMP(6),
    deleted                  BOOLEAN      NOT NULL DEFAULT FALSE,
    remark                   VARCHAR(255),
    CONSTRAINT uq_ai_action_catalog UNIQUE (entity_slug, action_key)
);

COMMENT ON TABLE ai_action_catalog IS 'AI 业务动作目录：代码 Adapter 定义能力边界，目录定义开放策略';
COMMENT ON COLUMN ai_action_catalog.action_key IS '动作标识，如 query/detail/create/update/delete';
COMMENT ON COLUMN ai_action_catalog.entity_slug IS '实体标识，如 system-role；专用业务动作可为空或使用业务域标识';
COMMENT ON COLUMN ai_action_catalog.risk_level IS '风险等级：low/medium/high';
COMMENT ON COLUMN ai_action_catalog.require_confirm IS '是否需要人工确认';
COMMENT ON COLUMN ai_action_catalog.permission_code_override IS '权限码覆写；为空时使用 Adapter 默认权限码';
COMMENT ON COLUMN ai_action_catalog.entitlement_code IS '权益编码；为空表示不走权益扣减';
COMMENT ON COLUMN ai_action_catalog.cost_expression IS '权益消耗表达式';
COMMENT ON COLUMN ai_action_catalog.input_schema IS '输入 JSON Schema，供 AI 发现能力与参数约束';
COMMENT ON COLUMN ai_action_catalog.output_schema IS '输出 JSON Schema';
CREATE INDEX idx_ai_action_catalog_entity ON ai_action_catalog (entity_slug);
CREATE INDEX idx_ai_action_catalog_enabled ON ai_action_catalog (enabled, sort_order);

CREATE TABLE ai_tool_catalog (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    tool_name        VARCHAR(120) NOT NULL UNIQUE,
    source           VARCHAR(32)  NOT NULL DEFAULT 'LOCAL',
    enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    tool_type        VARCHAR(32)  NOT NULL DEFAULT 'FUNCTION',
    category         VARCHAR(64),
    risk_level       VARCHAR(16)  NOT NULL DEFAULT 'LOW',
    read_only        BOOLEAN      NOT NULL DEFAULT FALSE,
    require_confirm  BOOLEAN      NOT NULL DEFAULT FALSE,
    permission_code  VARCHAR(120),
    entitlement_code VARCHAR(64),
    cost_expression  VARCHAR(255),
    input_schema     TEXT,
    output_schema    TEXT,
    sort_order       INTEGER      NOT NULL DEFAULT 100,
    create_by        BIGINT,
    create_by_type   VARCHAR(16),
    create_time      TIMESTAMP(6),
    update_by        BIGINT,
    update_by_type   VARCHAR(16),
    update_time      TIMESTAMP(6),
    owner_id         BIGINT,
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    remark           VARCHAR(255)
);

COMMENT ON TABLE ai_tool_catalog IS 'AI 工具目录：ToolCallback/MCP 定义能力边界，目录定义开放策略';
COMMENT ON COLUMN ai_tool_catalog.tool_name IS '工具名，对应 ToolCallback 或 MCP 工具名';
COMMENT ON COLUMN ai_tool_catalog.source IS '工具来源：LOCAL/MCP/CUSTOM/GENERATED';
COMMENT ON COLUMN ai_tool_catalog.tool_type IS '工具类型：FUNCTION/MCP/HTTP/SCRIPT/WORKFLOW/AGENT/GENERATIVE';
COMMENT ON COLUMN ai_tool_catalog.category IS '工具分类：BUSINESS_ACTION/IMAGE_GENERATION/VIDEO_GENERATION/MUSIC_GENERATION/MODEL3D_GENERATION 等';
COMMENT ON COLUMN ai_tool_catalog.risk_level IS '风险等级：NONE/LOW/MEDIUM/HIGH/CRITICAL';
COMMENT ON COLUMN ai_tool_catalog.read_only IS '是否只读工具';
COMMENT ON COLUMN ai_tool_catalog.require_confirm IS '是否强制人工确认';
COMMENT ON COLUMN ai_tool_catalog.permission_code IS '工具权限码；为空时使用 tool:{toolName}:execute 和 tool:default:execute';
COMMENT ON COLUMN ai_tool_catalog.entitlement_code IS '权益/积分门控编码；为空表示不检查额度';
COMMENT ON COLUMN ai_tool_catalog.cost_expression IS '预估消耗表达式；第一版支持固定数字';
CREATE INDEX idx_ai_tool_catalog_enabled ON ai_tool_catalog (enabled, sort_order);

CREATE TABLE ai_team (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                   INTEGER      NOT NULL DEFAULT 0,
    org_id                    BIGINT,
    workspace_id              BIGINT,
    team_id                   VARCHAR(64)  NOT NULL UNIQUE,
    name                      VARCHAR(128) NOT NULL,
    description               VARCHAR(512),
    collaboration_mode        VARCHAR(32)  NOT NULL DEFAULT 'LEADER_COORDINATED',
    coordinator_assistant_id  VARCHAR(64),
    status                    VARCHAR(16)  NOT NULL DEFAULT 'active',
    owner_id                  BIGINT,
    create_by                 BIGINT,
    create_by_type            VARCHAR(16),
    create_time               TIMESTAMP(6),
    update_by                 BIGINT,
    update_by_type            VARCHAR(16),
    update_time               TIMESTAMP(6),
    delete_time               TIMESTAMP(6),
    deleted                   BOOLEAN      NOT NULL DEFAULT FALSE,
    remark                    TEXT
);

COMMENT ON TABLE ai_team IS '多智能体团队';

CREATE TABLE ai_team_member (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id      VARCHAR(64)  NOT NULL,
    assistant_id VARCHAR(64)  NOT NULL,
    role         VARCHAR(32)  NOT NULL DEFAULT 'member',
    capabilities TEXT,
    created_at   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (team_id, assistant_id)
);

COMMENT ON TABLE ai_team_member IS '团队成员';

CREATE TABLE ai_team_task (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id             VARCHAR(64)  NOT NULL,
    task_id             VARCHAR(64)  NOT NULL UNIQUE,
    parent_task_id      VARCHAR(64),
    assignee_id         VARCHAR(64),
    description         TEXT         NOT NULL,
    required_capability VARCHAR(128),
    status              VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    dependencies        TEXT,
    priority            INTEGER          NOT NULL DEFAULT 0,
    progress            INTEGER          NOT NULL DEFAULT 0,
    result              TEXT,
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ai_team_task IS '团队任务';
CREATE INDEX idx_ai_team_task_team_status ON ai_team_task (team_id, status);

-- ============================================================
-- 种子数据
-- ============================================================

-- 系统默认模型偏好
INSERT INTO ai_model_preference (scope, scope_id, capability, model_id)
VALUES
    ('SYSTEM', NULL, 'CHAT',      'deepseek:chat'),
    ('SYSTEM', NULL, 'EMBEDDING', 'qwen:embedding'),
    ('SYSTEM', NULL, 'IMAGE_GEN', 'openai:dall-e-3')
ON CONFLICT ON CONSTRAINT uq_model_preference DO NOTHING;

-- 第一期 12 个 provider 代表模型
-- capabilities: CHAT / EMBEDDING / VISION / IMAGE_GEN / AUDIO / RERANK
INSERT INTO ai_model (model_id, display_name, provider, provider_type, model_name, base_url,
                      capabilities, context_window, sort_order, enabled)
VALUES
-- P0: OpenAI
('openai:gpt-4o',           'GPT-4o',            'openai',     'OPENAI_COMPAT', 'gpt-4o',                     'https://api.openai.com/v1',                         'CHAT,VISION', 128000, 10,  true),
('openai:gpt-4o-mini',      'GPT-4o Mini',        'openai',     'OPENAI_COMPAT', 'gpt-4o-mini',                'https://api.openai.com/v1',                         'CHAT,VISION', 128000, 11,  true),
('openai:o1',               'o1',                 'openai',     'OPENAI_COMPAT', 'o1',                         'https://api.openai.com/v1',                         'CHAT',        200000, 12,  true),
('openai:text-embedding-3', 'text-embedding-3',   'openai',     'OPENAI_COMPAT', 'text-embedding-3-small',     'https://api.openai.com/v1',                         'EMBEDDING',   8191,   13,  true),
-- P0: DeepSeek
('deepseek:chat',           'DeepSeek Chat',      'deepseek',   'OPENAI_COMPAT', 'deepseek-chat',              'https://api.deepseek.com/v1',                       'CHAT',        64000,  20,  true),
('deepseek:reasoner',       'DeepSeek R1',        'deepseek',   'OPENAI_COMPAT', 'deepseek-reasoner',          'https://api.deepseek.com/v1',                       'CHAT',        64000,  21,  true),
-- P0: 通义千问
('qwen:max',                'Qwen Max',           'qwen',       'OPENAI_COMPAT', 'qwen-max',                   'https://dashscope.aliyuncs.com/compatible-mode/v1', 'CHAT',        32000,  30,  true),
('qwen:long',               'Qwen Long',          'qwen',       'OPENAI_COMPAT', 'qwen-long',                  'https://dashscope.aliyuncs.com/compatible-mode/v1', 'CHAT',        1000000,31,  true),
('qwen:embedding',          'Qwen Embedding',     'qwen',       'OPENAI_COMPAT', 'text-embedding-v3',          'https://dashscope.aliyuncs.com/compatible-mode/v1', 'EMBEDDING',   8192,   32,  true),
-- P0: 月之暗面
('moonshot:v1-128k',        'Kimi 128k',          'moonshot',   'OPENAI_COMPAT', 'moonshot-v1-128k',           'https://api.moonshot.cn/v1',                        'CHAT',        128000, 40,  true),
-- P1: 智谱
('zhipu:glm-4',             'GLM-4',              'zhipu',      'OPENAI_COMPAT', 'glm-4',                      'https://open.bigmodel.cn/api/paas/v4',              'CHAT',        128000, 50,  true),
('zhipu:glm-4v',            'GLM-4V',             'zhipu',      'OPENAI_COMPAT', 'glm-4v',                     'https://open.bigmodel.cn/api/paas/v4',              'CHAT,VISION', 2000,   51,  true),
-- P1: Anthropic
('anthropic:claude-3-5-sonnet', 'Claude 3.5 Sonnet', 'anthropic', 'ANTHROPIC',  'claude-3-5-sonnet-20241022', 'https://api.anthropic.com',                         'CHAT,VISION', 200000, 60,  true),
('anthropic:claude-3-haiku',    'Claude 3 Haiku',    'anthropic', 'ANTHROPIC',  'claude-3-haiku-20240307',    'https://api.anthropic.com',                         'CHAT,VISION', 200000, 61,  true),
-- P1: Ollama（本地，默认禁用）
('ollama:llama3',           'Llama 3',            'ollama',     'OLLAMA',        'llama3',                     'http://localhost:11434',                            'CHAT',        8192,   70,  false),
('ollama:qwen2.5',          'Qwen2.5 Local',      'ollama',     'OLLAMA',        'qwen2.5',                    'http://localhost:11434',                            'CHAT',        32768,  71,  false),
-- P1: 聚合平台
('openrouter:claude-3-5',   'Claude 3.5 via OR',  'openrouter', 'OPENAI_COMPAT', 'anthropic/claude-3.5-sonnet','https://openrouter.ai/api/v1',                     'CHAT,VISION', 200000, 80,  true),
('openrouter:gpt-4o',       'GPT-4o via OR',      'openrouter', 'OPENAI_COMPAT', 'openai/gpt-4o',              'https://openrouter.ai/api/v1',                     'CHAT,VISION', 128000, 81,  true),
('n1n:gpt-4o',              'GPT-4o via n1n',     'n1n',        'OPENAI_COMPAT', 'gpt-4o',                     'https://api.n1n.ai/v1',                             'CHAT,VISION', 128000, 90,  true),
('linkai:gpt-4o',           'GPT-4o via LinkAI',  'linkai',     'OPENAI_COMPAT', 'gpt-4o',                     'https://api.link-ai.tech/v1',                      'CHAT,VISION', 128000, 100, true),
-- P1: 阶跃星辰
('stepfun:step-2',          'Step-2',             'stepfun',    'OPENAI_COMPAT', 'step-2-16k',                 'https://api.stepfun.com/v1',                        'CHAT',        16000,  110, true),
('stepfun:step-1v',         'Step-1V（视觉）',     'stepfun',    'OPENAI_COMPAT', 'step-1v-8k',                 'https://api.stepfun.com/v1',                        'CHAT,VISION', 8000,   111, true),
-- P1: 火山引擎
('volcengine:doubao-pro',   'Doubao Pro',         'volcengine', 'OPENAI_COMPAT', 'doubao-pro-32k',             'https://ark.cn-beijing.volces.com/api/v3',          'CHAT',        32000,  120, true),
('volcengine:doubao-lite',  'Doubao Lite',        'volcengine', 'OPENAI_COMPAT', 'doubao-lite-32k',            'https://ark.cn-beijing.volces.com/api/v3',          'CHAT',        32000,  121, true)
ON CONFLICT (model_id) DO NOTHING;


-- ============================================================
-- AIGC 素材库
-- ============================================================

CREATE TABLE media_asset (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(200)   NOT NULL,
    type              VARCHAR(20)    NOT NULL,
    url               VARCHAR(1000)  NOT NULL,
    thumbnail_url     VARCHAR(1000),
    size              BIGINT,
    width             INTEGER,
    height            INTEGER,
    duration          NUMERIC(10,2),
    generation_params JSONB,
    tags              VARCHAR(500),
    category_id       BIGINT,
    user_id           BIGINT         NOT NULL,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE media_asset IS 'AIGC 素材库';
COMMENT ON COLUMN media_asset.type IS '素材类型：IMAGE/VIDEO/AUDIO/MODEL_3D';
COMMENT ON COLUMN media_asset.generation_params IS 'AI 生成参数（prompt、模型等）';

CREATE INDEX idx_media_asset_user_id ON media_asset (user_id);
CREATE INDEX idx_media_asset_type ON media_asset (user_id, type);
CREATE INDEX idx_media_asset_category ON media_asset (category_id);

-- 素材分类（多级树形）
CREATE TABLE media_category (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(100)   NOT NULL,
    parent_id         BIGINT,
    sort_order        INTEGER        NOT NULL DEFAULT 0,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE media_category IS '素材分类（多级树形）';
CREATE INDEX idx_media_category_parent ON media_category (parent_id);

-- 素材标签
CREATE TABLE media_tag (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(50)    NOT NULL,
    color             VARCHAR(20),
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE media_tag IS '素材标签';

-- 素材-标签关联表
CREATE TABLE media_asset_tag (
    asset_id          BIGINT         NOT NULL,
    tag_id            BIGINT         NOT NULL,
    PRIMARY KEY (asset_id, tag_id)
);

COMMENT ON TABLE media_asset_tag IS '素材-标签关联';
CREATE INDEX idx_media_asset_tag_asset ON media_asset_tag (asset_id);
CREATE INDEX idx_media_asset_tag_tag ON media_asset_tag (tag_id);

-- 素材变体关联
CREATE TABLE media_asset_variant (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    original_asset_id BIGINT         NOT NULL,
    variant_asset_id  BIGINT         NOT NULL,
    params_diff       JSONB,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE media_asset_variant IS '素材变体关联';
CREATE INDEX idx_media_variant_original ON media_asset_variant (original_asset_id);
CREATE INDEX idx_media_variant_variant ON media_asset_variant (variant_asset_id);

-- 批量生成任务
CREATE TABLE batch_generation_task (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    user_id           BIGINT         NOT NULL,
    status            VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    total_count       INTEGER        NOT NULL DEFAULT 0,
    completed_count   INTEGER        NOT NULL DEFAULT 0,
    failed_count      INTEGER        NOT NULL DEFAULT 0,
    params            JSONB,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE batch_generation_task IS 'AIGC 批量生成任务';
CREATE INDEX idx_batch_task_user ON batch_generation_task (user_id);
CREATE INDEX idx_batch_task_status ON batch_generation_task (status);

-- 生成参数模板
CREATE TABLE generation_template (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(100)   NOT NULL,
    category          VARCHAR(50),
    prompt            TEXT           NOT NULL,
    negative_prompt   TEXT,
    model             VARCHAR(100),
    width             INTEGER,
    height            INTEGER,
    steps             INTEGER,
    seed              BIGINT,
    is_public         BOOLEAN        NOT NULL DEFAULT FALSE,
    usage_count       INTEGER        NOT NULL DEFAULT 0,
    user_id           BIGINT         NOT NULL,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE generation_template IS 'AIGC 生成参数模板';
CREATE INDEX idx_gen_template_user ON generation_template (user_id);
CREATE INDEX idx_gen_template_category ON generation_template (category);
CREATE INDEX idx_gen_template_public ON generation_template (is_public);

-- 视频模板
CREATE TABLE video_template (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(100)   NOT NULL,
    type              VARCHAR(30)    NOT NULL,
    params            TEXT,
    preview_url       VARCHAR(500),
    thumbnail_url     VARCHAR(500),
    user_id           BIGINT,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE video_template IS 'AIGC 视频模板';
CREATE INDEX idx_video_template_type ON video_template (type);

-- 生成历史
CREATE TABLE generation_history (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    user_id           BIGINT         NOT NULL,
    type              VARCHAR(20)    NOT NULL,
    prompt            TEXT,
    model             VARCHAR(100),
    params            TEXT,
    result_url        VARCHAR(500),
    asset_id          BIGINT,
    session_id        BIGINT,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE generation_history IS 'AIGC 生成历史记录';
CREATE INDEX idx_gen_history_user ON generation_history (user_id);
CREATE INDEX idx_gen_history_type ON generation_history (user_id, type);
CREATE INDEX idx_gen_history_session ON generation_history (session_id);


-- ============================================================
-- 智能体执行追踪 Schema
-- 包含：执行运行记录、执行步骤
-- ============================================================

CREATE TABLE execution_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id    VARCHAR(128) NOT NULL UNIQUE,
    parent_run_id   BIGINT REFERENCES execution_run(id),
    agent_id        VARCHAR(64)  NOT NULL,
    agent_name      VARCHAR(128),
    user_id         BIGINT,
    conversation_id VARCHAR(64),
    input           TEXT,
    output          TEXT,
    status          VARCHAR(16)  NOT NULL,
    error_message   TEXT,
    token_input     INTEGER      NOT NULL DEFAULT 0,
    token_output    INTEGER      NOT NULL DEFAULT 0,
    started_at      TIMESTAMPTZ  NOT NULL,
    finished_at     TIMESTAMPTZ,
    duration_ms     BIGINT,
    retry_count     INTEGER      NOT NULL DEFAULT 0,
    metadata        JSONB
);

COMMENT ON TABLE execution_run IS '智能体执行运行记录';
CREATE INDEX idx_execution_run_user   ON execution_run(user_id, started_at DESC);
CREATE INDEX idx_execution_run_agent  ON execution_run(agent_id, started_at DESC);
CREATE INDEX idx_execution_run_status ON execution_run(status) WHERE status != 'SUCCESS';
CREATE INDEX idx_execution_run_parent ON execution_run(parent_run_id) WHERE parent_run_id IS NOT NULL;

CREATE TABLE execution_step (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT       NOT NULL REFERENCES execution_run(id),
    parent_step_id  BIGINT REFERENCES execution_step(id),
    step_index      INTEGER      NOT NULL,
    step_type       VARCHAR(32)  NOT NULL,
    agent_id        VARCHAR(64),
    tool_name       VARCHAR(128),
    input           TEXT,
    output          TEXT,
    status          VARCHAR(16)  NOT NULL,
    error_message   TEXT,
    started_at      TIMESTAMPTZ  NOT NULL,
    finished_at     TIMESTAMPTZ,
    duration_ms     BIGINT
);

COMMENT ON TABLE execution_step IS '智能体执行步骤';
CREATE INDEX idx_execution_step_run ON execution_step(run_id, step_index);



-- ============================================================
-- 知识库段落
-- ============================================================

CREATE TABLE knowledge_segment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    document_id       BIGINT       NOT NULL,
    knowledge_base_id BIGINT       NOT NULL,
    content           TEXT         NOT NULL,
    position          INTEGER      NOT NULL,
    word_count        INTEGER,
    enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
    embedding         vector(1536),
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6),
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6),
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            TEXT
);

COMMENT ON TABLE knowledge_segment IS '知识库段落（文档分块后的最小检索单元）';
COMMENT ON COLUMN knowledge_segment.document_id IS '所属文档 ID';
COMMENT ON COLUMN knowledge_segment.knowledge_base_id IS '所属知识库 ID';
COMMENT ON COLUMN knowledge_segment.position IS '段落在文档中的位置（从 0 开始）';
COMMENT ON COLUMN knowledge_segment.embedding IS '向量嵌入（PgVector 1536 维）';

CREATE INDEX idx_knowledge_segment_doc ON knowledge_segment (document_id);
CREATE INDEX idx_knowledge_segment_base ON knowledge_segment (knowledge_base_id);
CREATE INDEX idx_knowledge_segment_embedding
    ON knowledge_segment USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- ============================================================
-- 补充种子数据
-- ============================================================

-- 字典类型
INSERT INTO sys_dict_type (name, type, status, create_time, update_time)
VALUES
    ('记忆范围', 'ai_memory_scope', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Agent 状态', 'ai_agent_status', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('模型厂商类型', 'ai_provider_type', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

-- 字典数据：记忆范围
INSERT INTO sys_dict_data (dict_type, label, value, sort, status)
VALUES
    ('ai_memory_scope', '短期记忆', 'short_term', 1, 0),
    ('ai_memory_scope', '长期记忆', 'long_term', 2, 0),
    ('ai_memory_scope', '情景记忆', 'episodic', 3, 0),
    ('ai_memory_scope', '程序性记忆', 'procedural', 4, 0)
ON CONFLICT DO NOTHING;

-- 字典数据：Agent 状态
INSERT INTO sys_dict_data (dict_type, label, value, sort, status)
VALUES
    ('ai_agent_status', '活跃', 'active', 1, 0),
    ('ai_agent_status', '停用', 'inactive', 2, 0),
    ('ai_agent_status', '已归档', 'archived', 3, 0)
ON CONFLICT DO NOTHING;

-- 字典数据：模型厂商类型
INSERT INTO sys_dict_data (dict_type, label, value, sort, status)
VALUES
    ('ai_provider_type', 'OpenAI 兼容', 'OPENAI_COMPAT', 1, 0),
    ('ai_provider_type', 'Anthropic', 'ANTHROPIC', 2, 0),
    ('ai_provider_type', 'Ollama 本地', 'OLLAMA', 3, 0)
ON CONFLICT DO NOTHING;

-- 默认 Actor（通用助手人格）
INSERT INTO ai_actor (actor_id, name, persona, system_prompt, status, create_time, update_time)
VALUES (
    'default-assistant',
    '通用助手',
    '友好、专业、简洁。用中文回答，必要时使用代码示例。',
    '你是一个通用 AI 助手，帮助用户解答问题、完成任务。保持友好专业的语气，回答简洁准确。',
    'active',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
) ON CONFLICT (actor_id) DO NOTHING;

-- 默认 Role（通用能力集）
INSERT INTO ai_role (role_id, name, description, skill_ids, tool_whitelist, status, create_time, update_time)
VALUES (
    'default-generalist',
    '通用能力集',
    '基础对话、知识问答、代码辅助',
    '[]',
    '[]',
    'active',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
) ON CONFLICT (role_id) DO NOTHING;

-- 默认 Assistant（绑定默认 Actor + Role）
INSERT INTO ai_assistant (assistant_id, user_id, actor_id, role_id, memory_strategy, status, create_time, update_time)
VALUES (
    'default-assistant',
    0,
    'default-assistant',
    'default-generalist',
    'HYBRID',
    'active',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
) ON CONFLICT (assistant_id) DO NOTHING;

-- 测试数据：deepseek:chat 模型配置（已在上方 seed 中包含，此处确保 api_key 占位）
UPDATE ai_model
SET api_key_encrypted = 'PLACEHOLDER_REPLACE_WITH_REAL_KEY',
    temperature = 0.7,
    max_tokens = 4096
WHERE model_id = 'deepseek:chat'
  AND api_key_encrypted IS NULL;


-- ai_assistant 委托权限字段
ALTER TABLE ai_assistant ADD COLUMN IF NOT EXISTS delegator_id BIGINT;
ALTER TABLE ai_assistant ADD COLUMN IF NOT EXISTS permission_scope JSONB;

COMMENT ON COLUMN ai_assistant.delegator_id IS '委托者 ID（权限继承来源，默认等于 user_id）';
COMMENT ON COLUMN ai_assistant.permission_scope IS '权限边界配置（JSON）';

UPDATE ai_assistant SET delegator_id = user_id WHERE delegator_id IS NULL;


-- ============================================================
-- AI 对话任务队列
-- ============================================================

CREATE TABLE ai_chat_task (
    id              BIGSERIAL       PRIMARY KEY,
    version         INTEGER         NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    session_id      BIGINT          NOT NULL,
    creator_id      BIGINT          NOT NULL,
    title           VARCHAR(500)    NOT NULL,
    description     TEXT,
    status          VARCHAR(20)     NOT NULL DEFAULT 'pending',
    priority        INTEGER         DEFAULT 0,
    sort_order      INTEGER         DEFAULT 0,
    scheduled_at    TIMESTAMP,
    result          TEXT,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN         NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

CREATE INDEX idx_chat_task_session ON ai_chat_task(session_id, status, priority, sort_order);
CREATE INDEX idx_chat_task_scheduled ON ai_chat_task(status, scheduled_at) WHERE deleted = false;

COMMENT ON TABLE ai_chat_task IS 'AI 对话任务队列——与会话关联的持久化任务列表';
COMMENT ON COLUMN ai_chat_task.session_id IS '所属会话 ID';
COMMENT ON COLUMN ai_chat_task.status IS '状态：pending/running/done/failed/cancelled';
COMMENT ON COLUMN ai_chat_task.priority IS '优先级（数值越小越优先）';
COMMENT ON COLUMN ai_chat_task.sort_order IS '同优先级内排序序号';
COMMENT ON COLUMN ai_chat_task.scheduled_at IS '定时执行时间，NULL 表示立即可执行';
COMMENT ON COLUMN ai_chat_task.result IS '助理处理结果摘要';

-- ============================================================
-- AI 长任务持久执行（Durable Task Execution）
-- ============================================================

CREATE TABLE ai_task_execution (
    id                    BIGSERIAL       PRIMARY KEY,
    version               INTEGER         NOT NULL DEFAULT 0,
    org_id                BIGINT,
    workspace_id          BIGINT,
    task_id               BIGINT          NOT NULL REFERENCES ai_chat_task(id),
    parent_execution_id   BIGINT          REFERENCES ai_task_execution(id),
    subtask_key           VARCHAR(100),
    attempt_no            INTEGER         NOT NULL DEFAULT 1,
    status                VARCHAR(20)     NOT NULL DEFAULT 'pending',
    role                  VARCHAR(100),
    checkpoint_id         BIGINT,
    started_at            TIMESTAMP,
    ended_at              TIMESTAMP,
    error_message         TEXT,
    owner_id              BIGINT,
    create_by             BIGINT,
    create_by_type        VARCHAR(16),
    create_time           TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by             BIGINT,
    update_by_type        VARCHAR(16),
    update_time           TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time           TIMESTAMP,
    deleted               BOOLEAN         NOT NULL DEFAULT FALSE,
    remark                VARCHAR(255)
);

CREATE INDEX idx_task_execution_task ON ai_task_execution(task_id, attempt_no);
CREATE INDEX idx_task_execution_parent ON ai_task_execution(parent_execution_id) WHERE parent_execution_id IS NOT NULL;
CREATE INDEX idx_ai_task_execution_status ON ai_task_execution(status, update_time) WHERE status = 'running';

COMMENT ON TABLE ai_task_execution IS '任务执行实例——一个任务可多次执行（重试），支持主/子关系';
COMMENT ON COLUMN ai_task_execution.parent_execution_id IS '子任务指向主执行实例（NULL=主执行）';
COMMENT ON COLUMN ai_task_execution.subtask_key IS '子任务标识（如 backend/frontend）';
COMMENT ON COLUMN ai_task_execution.checkpoint_id IS '最新检查点 ID';

CREATE TABLE ai_task_checkpoint (
    id                BIGSERIAL       PRIMARY KEY,
    execution_id      BIGINT          NOT NULL REFERENCES ai_task_execution(id),
    scope             VARCHAR(20)     NOT NULL,
    step_index        INTEGER         NOT NULL DEFAULT 0,
    state_json        JSONB           NOT NULL,
    create_time       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_task_checkpoint_exec ON ai_task_checkpoint(execution_id, step_index DESC);

COMMENT ON TABLE ai_task_checkpoint IS '任务检查点快照——支持从最近检查点恢复';
COMMENT ON COLUMN ai_task_checkpoint.scope IS 'coordinator/subtask/agent_step';
COMMENT ON COLUMN ai_task_checkpoint.state_json IS '状态快照（taskBoard/workingMemory/completedSteps 等）';

CREATE TABLE ai_task_event (
    id                BIGSERIAL       PRIMARY KEY,
    task_id           BIGINT          NOT NULL,
    execution_id      BIGINT,
    subtask_key       VARCHAR(100),
    type              VARCHAR(50)     NOT NULL,
    payload_json      JSONB,
    create_time       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_task_event_task ON ai_task_event(task_id, create_time);
CREATE INDEX idx_task_event_exec ON ai_task_event(execution_id, create_time) WHERE execution_id IS NOT NULL;

COMMENT ON TABLE ai_task_event IS '任务事件日志（append-only）——完整审计轨迹';
COMMENT ON COLUMN ai_task_event.type IS '事件类型：task_started/step_completed/tool_called/checkpoint_saved/error 等';


-- ============================================================
-- AI 产出记录（异步审查 + 可回退）
-- ============================================================

CREATE TABLE ai_output (
    id                BIGSERIAL       PRIMARY KEY,
    version           INTEGER         NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    session_id        BIGINT,
    task_id           BIGINT,
    execution_id      BIGINT,
    creator_id        BIGINT          NOT NULL,
    source_type       VARCHAR(30)     NOT NULL,
    category          VARCHAR(30)     NOT NULL,
    risk_level        VARCHAR(10)     NOT NULL DEFAULT 'low',
    title             VARCHAR(500)    NOT NULL,
    description       TEXT,
    content_snapshot  JSONB,
    revert_info       JSONB,
    status            VARCHAR(20)     NOT NULL DEFAULT 'effective',
    adjust_note       TEXT,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP,
    deleted           BOOLEAN         NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

CREATE INDEX idx_ai_output_creator ON ai_output(creator_id, create_time DESC) WHERE deleted = false;
CREATE INDEX idx_ai_output_risk ON ai_output(creator_id, risk_level, status) WHERE deleted = false;

COMMENT ON TABLE ai_output IS 'AI 产出记录——所有助理工作成果的统一归档';
COMMENT ON COLUMN ai_output.source_type IS '来源：autodev/task/chat/tool';
COMMENT ON COLUMN ai_output.category IS '类别：code/document/entity_change/config/file';
COMMENT ON COLUMN ai_output.risk_level IS '风险：high/medium/low（仅影响通知优先级）';
COMMENT ON COLUMN ai_output.status IS 'effective（生效中）/adjusted（已调整）/reverted（已回退）';
COMMENT ON COLUMN ai_output.revert_info IS '回退信息（变更前状态快照，用于撤销）';



-- ============================================================
-- 工具调用审计
-- ============================================================

CREATE TABLE tool_call_audit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    session_id      VARCHAR(64),
    agent_id        VARCHAR(64),
    function_name   VARCHAR(128) NOT NULL,
    arguments       TEXT,
    success         BOOLEAN      NOT NULL,
    output          TEXT,
    error_message   TEXT,
    duration_ms     BIGINT,
    risk_level      VARCHAR(16),
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE tool_call_audit IS '工具调用审计记录';
CREATE INDEX idx_tool_call_audit_user ON tool_call_audit (user_id, created_at DESC);
CREATE INDEX idx_tool_call_audit_func ON tool_call_audit (function_name, created_at DESC);

-- AI 工作流定义表
CREATE TABLE ai_flow_definition (
    id              BIGSERIAL     PRIMARY KEY,
    version         INTEGER       NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP,
    owner_id        BIGINT,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN       NOT NULL DEFAULT FALSE,
    remark          VARCHAR(512),

    name            VARCHAR(128)  NOT NULL,
    description     VARCHAR(512),
    mode            VARCHAR(32)   NOT NULL DEFAULT 'CHAT',
    definition      JSONB         NOT NULL DEFAULT '{}',
    status          VARCHAR(16)   NOT NULL DEFAULT 'DRAFT',
    deployment_id   VARCHAR(64),
    published_at    TIMESTAMP,
    agent_callable  BOOLEAN       NOT NULL DEFAULT FALSE,
    require_confirm BOOLEAN       NOT NULL DEFAULT TRUE
);

COMMENT ON TABLE  ai_flow_definition                  IS 'AI 工作流定义';
COMMENT ON COLUMN ai_flow_definition.mode             IS '流程模式：CHAT / COMPLETION / AGENT';
COMMENT ON COLUMN ai_flow_definition.definition       IS '编辑态 JSON（ReactFlow 节点+连线）';
COMMENT ON COLUMN ai_flow_definition.status           IS '发布状态：DRAFT / PUBLISHED / DISABLED';
COMMENT ON COLUMN ai_flow_definition.deployment_id    IS 'Flowable deployment ID，发布后有值';
COMMENT ON COLUMN ai_flow_definition.agent_callable   IS '是否允许智能体自动调用';
COMMENT ON COLUMN ai_flow_definition.require_confirm  IS '智能体调用前是否需要用户确认';

-- ============================================================
-- AI 生成工具（Generated Tool）
-- ============================================================

CREATE TABLE ai_generated_tool (
    id              BIGSERIAL       PRIMARY KEY,
    version         INTEGER         NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(64)     NOT NULL UNIQUE,
    description     VARCHAR(256),
    parameters_json TEXT,
    code            TEXT            NOT NULL,
    creator_user_id BIGINT          NOT NULL,
    visibility      VARCHAR(16)     NOT NULL DEFAULT 'PRIVATE',
    status          VARCHAR(16)     NOT NULL DEFAULT 'active',
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN         NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

CREATE UNIQUE INDEX idx_ai_generated_tool_name ON ai_generated_tool (name);
CREATE INDEX idx_ai_generated_tool_creator ON ai_generated_tool (creator_user_id);
CREATE INDEX idx_ai_generated_tool_visibility ON ai_generated_tool (visibility);

COMMENT ON TABLE ai_generated_tool IS 'AI 动态生成工具';
