-- doc_document 补充 front_matter 字段
ALTER TABLE doc_document ADD COLUMN IF NOT EXISTS front_matter JSONB;

COMMENT ON COLUMN doc_document.front_matter IS 'Front Matter 元数据（YAML 解析后的 JSON）';

-- 全文检索索引
CREATE INDEX IF NOT EXISTS idx_doc_document_fts
    ON doc_document USING GIN (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content, '')));

-- doc_link 表（文档引用关系镜像）
CREATE TABLE IF NOT EXISTS doc_link (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id   BIGINT NOT NULL REFERENCES doc_document(id) ON DELETE CASCADE,
    target_id   BIGINT NOT NULL REFERENCES doc_document(id) ON DELETE CASCADE,
    link_type   VARCHAR(20) NOT NULL DEFAULT 'mdlink',
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_id, target_id, link_type)
);

COMMENT ON TABLE doc_link IS '文档引用关系（双链/Markdown链接）';
CREATE INDEX IF NOT EXISTS idx_doc_link_source ON doc_link(source_id);
CREATE INDEX IF NOT EXISTS idx_doc_link_target ON doc_link(target_id);
