-- ============================================================
-- document 子域（业务文档，基础 CRUD）
-- ============================================================

CREATE TABLE doc_document (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    title        VARCHAR(200) NOT NULL,
    file_path    VARCHAR(500),
    content      TEXT,
    doc_type     VARCHAR(50)  NOT NULL DEFAULT 'spec',
    front_matter JSONB,
    status       VARCHAR(20)  NOT NULL DEFAULT 'active',
    archived_at  TIMESTAMP(6),
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE doc_document IS '业务文档';
COMMENT ON COLUMN doc_document.front_matter IS 'Front Matter 元数据（YAML 解析后的 JSON）';

CREATE INDEX idx_doc_document_fts
    ON doc_document USING GIN (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content, '')));
