-- ============================================================
-- document 子域（业务文档，基础 CRUD）
-- ============================================================

CREATE TABLE doc_document (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      INTEGER      NOT NULL DEFAULT 0,
    org_id       BIGINT,
    workspace_id BIGINT,
    title        VARCHAR(200) NOT NULL,
    file_path    VARCHAR(500),
    content      TEXT,
    doc_type     VARCHAR(50)  NOT NULL DEFAULT 'spec',
    front_matter JSONB,
    status       VARCHAR(20)  NOT NULL DEFAULT 'active',
    publish      VARCHAR(20)  NOT NULL DEFAULT 'draft',
    archived_at  TIMESTAMP(6),
    owner_id     BIGINT,
    create_by    BIGINT,
    create_by_type VARCHAR(16),
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_by_type VARCHAR(16),
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE doc_document IS '业务文档';
COMMENT ON COLUMN doc_document.front_matter IS 'Front Matter 元数据（YAML 解析后的 JSON）';
COMMENT ON COLUMN doc_document.publish IS '发布状态：draft=草稿，published=已发布';

CREATE INDEX idx_doc_document_fts
    ON doc_document USING GIN (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content, '')));

CREATE INDEX idx_doc_document_publish ON doc_document (publish) WHERE deleted = FALSE;


CREATE TABLE doc_link (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    source_id       BIGINT       NOT NULL,
    target_id       BIGINT       NOT NULL,
    link_type       VARCHAR(32),
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6),
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6),
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE doc_link IS '文档关联关系';
CREATE INDEX idx_doc_link_source ON doc_link (source_id);
CREATE INDEX idx_doc_link_target ON doc_link (target_id);


CREATE TABLE ai_knowledge_problem (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id BIGINT        NOT NULL,
    content           VARCHAR(1000) NOT NULL,
    is_active         BOOLEAN       NOT NULL DEFAULT TRUE
);

COMMENT ON TABLE ai_knowledge_problem IS 'QA 问题——手动维护的问答对，检索时优先匹配';
CREATE INDEX idx_ai_knowledge_problem_base ON ai_knowledge_problem (knowledge_base_id);

CREATE TABLE ai_knowledge_problem_paragraph (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL,
    segment_id BIGINT NOT NULL
);

COMMENT ON TABLE ai_knowledge_problem_paragraph IS '问题-段落关联';
CREATE INDEX idx_kpp_problem ON ai_knowledge_problem_paragraph (problem_id);
CREATE INDEX idx_kpp_segment ON ai_knowledge_problem_paragraph (segment_id);
