-- AAF-032 #1 RBAC 权限：角色、权限、角色-权限关联、用户-角色关联

-- ==================== 角色表 ====================

CREATE TABLE sys_role (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    code         VARCHAR(50)  NOT NULL UNIQUE,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(500),
    status       INTEGER      NOT NULL DEFAULT 0,
    version      INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_role IS '系统角色';
COMMENT ON COLUMN sys_role.code IS '角色编码，唯一标识';
COMMENT ON COLUMN sys_role.status IS '0 正常 / 1 禁用';

-- ==================== 权限表 ====================

CREATE TABLE sys_permission (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    action       VARCHAR(20)  NOT NULL,
    field_access JSONB,
    version      INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_permission IS '实体权限';
COMMENT ON COLUMN sys_permission.entity_slug IS '实体标识';
COMMENT ON COLUMN sys_permission.action IS '操作类型：read/create/update/delete';
COMMENT ON COLUMN sys_permission.field_access IS '字段级权限，JSONB 格式：{"fieldName": {"visible": true, "editable": false}}';

-- ==================== 角色-权限关联表 ====================

CREATE TABLE sys_role_permission (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id        BIGINT,
    workspace_id  BIGINT,
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    version       INTEGER      NOT NULL DEFAULT 0,
    create_by     BIGINT,
    create_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by     BIGINT,
    update_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    remark        VARCHAR(255),
    UNIQUE (role_id, permission_id)
);

COMMENT ON TABLE sys_role_permission IS '角色-权限关联';

-- ==================== 用户-角色关联表 ====================

CREATE TABLE sys_user_role (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    user_id      BIGINT NOT NULL,
    role_id      BIGINT NOT NULL,
    version      INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255),
    UNIQUE (user_id, role_id)
);

COMMENT ON TABLE sys_user_role IS '用户-角色关联';

-- ==================== 初始数据 ====================

-- admin 角色（全权限）
INSERT INTO sys_role (code, name, description) VALUES ('admin', '管理员', '系统管理员，拥有全部权限');
-- user 角色（只读）
INSERT INTO sys_role (code, name, description) VALUES ('user', '普通用户', '普通用户，仅有只读权限');

-- 为 admin 用户分配 admin 角色（admin 用户 id=1）
INSERT INTO sys_user_role (user_id, role_id) VALUES (1, 1);
-- 为 user1, user2 分配 user 角色
INSERT INTO sys_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO sys_user_role (user_id, role_id) VALUES (3, 2);
