-- AAF-032 #3 行级数据权限规则表

CREATE TABLE sys_data_access_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    roles        JSONB        NOT NULL DEFAULT '[]',
    condition    JSONB        NOT NULL DEFAULT '{}',
    effect       VARCHAR(10)  NOT NULL DEFAULT 'allow',
    version      INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_data_access_rule IS '行级数据权限规则';
COMMENT ON COLUMN sys_data_access_rule.entity_slug IS '实体标识';
COMMENT ON COLUMN sys_data_access_rule.roles IS '适用角色编码数组，JSONB 格式：["user","editor"]';
COMMENT ON COLUMN sys_data_access_rule.condition IS '条件表达式，JSONB 格式：{"field":"created_by","operator":"eq","value":"$user.id"}';
COMMENT ON COLUMN sys_data_access_rule.effect IS '效果：allow 允许 / deny 拒绝';

CREATE INDEX idx_data_access_rule_entity ON sys_data_access_rule (entity_slug) WHERE deleted = false;
