-- ============================================================
-- 支付、积分与结算 Schema
-- ============================================================

-- ==================== 积分账户 ====================

CREATE TABLE credit_account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    user_id         BIGINT       NOT NULL,
    balance         BIGINT       NOT NULL DEFAULT 0,
    frozen          BIGINT       NOT NULL DEFAULT 0,
    total_earned    BIGINT       NOT NULL DEFAULT 0,
    total_spent     BIGINT       NOT NULL DEFAULT 0,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE credit_account IS '积分账户';
COMMENT ON COLUMN credit_account.balance IS '可用余额（分）';
COMMENT ON COLUMN credit_account.frozen IS '冻结金额（分）';

CREATE UNIQUE INDEX uk_credit_account_user ON credit_account(user_id) WHERE deleted = FALSE;

-- ==================== 积分流水 ====================

CREATE TABLE credit_transaction (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    account_id      BIGINT       NOT NULL,
    type            VARCHAR(20)  NOT NULL,
    amount          BIGINT       NOT NULL,
    balance_after   BIGINT       NOT NULL,
    source          VARCHAR(100),
    biz_id          VARCHAR(64),
    batch_type      VARCHAR(16),
    expire_at       TIMESTAMP(6),
    remain          BIGINT,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE credit_transaction IS '积分流水记录';
COMMENT ON COLUMN credit_transaction.type IS 'EARN/SPEND/FREEZE/UNFREEZE/EXPIRE';
COMMENT ON COLUMN credit_transaction.batch_type IS '批次来源：SUBSCRIPTION/TOPUP/REWARD/WEEKLY/MANUAL';
COMMENT ON COLUMN credit_transaction.expire_at  IS '过期时间，NULL=永不过期（充值积分）';
COMMENT ON COLUMN credit_transaction.remain     IS '本批次剩余可用量（EARN 时=amount，消费后递减）';

CREATE INDEX idx_credit_transaction_account ON credit_transaction(account_id) WHERE deleted = FALSE;
CREATE INDEX idx_credit_transaction_biz ON credit_transaction(biz_id) WHERE deleted = FALSE;

-- ==================== 积分转Token规则 ====================

CREATE TABLE credit_token_rule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(100) NOT NULL,
    credit_amount   BIGINT       NOT NULL,
    token_amount    BIGINT       NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ENABLED',
    priority        INTEGER      NOT NULL DEFAULT 0,
    effective_from  TIMESTAMP(6),
    effective_to    TIMESTAMP(6),
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE credit_token_rule IS '积分转Token规则';
COMMENT ON COLUMN credit_token_rule.status IS 'ENABLED/DISABLED';
COMMENT ON COLUMN credit_token_rule.priority IS '数值越小优先级越高';

-- ==================== 支付订单 ====================

CREATE TABLE pay_order (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER      NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    merchant_order_no   VARCHAR(64)  NOT NULL,
    subject             VARCHAR(200) NOT NULL,
    body                VARCHAR(500),
    amount              BIGINT       NOT NULL,
    status              INTEGER      NOT NULL DEFAULT 0,
    channel_code        VARCHAR(32)  NOT NULL,
    channel_order_no    VARCHAR(128),
    user_id             BIGINT       NOT NULL,
    expire_time         TIMESTAMP(6),
    success_time        TIMESTAMP(6),
    refund_amount       BIGINT       NOT NULL DEFAULT 0,
    owner_id            BIGINT,
    create_by           BIGINT,
    create_by_type      VARCHAR(16),
    create_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    remark              VARCHAR(255)
);

COMMENT ON TABLE pay_order IS '支付订单';
COMMENT ON COLUMN pay_order.amount IS '支付金额（分）';
COMMENT ON COLUMN pay_order.status IS '0=等待支付 10=支付成功 30=已关闭';

CREATE UNIQUE INDEX uk_pay_order_merchant_no ON pay_order(merchant_order_no) WHERE deleted = FALSE;
CREATE INDEX idx_pay_order_user ON pay_order(user_id) WHERE deleted = FALSE;

-- ==================== 业务订单 ====================

CREATE TABLE biz_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    order_no        VARCHAR(64)  NOT NULL,
    user_id         BIGINT       NOT NULL,
    order_type      VARCHAR(32)  NOT NULL,
    subject         VARCHAR(200) NOT NULL,
    total_amount    BIGINT       NOT NULL,
    pay_order_id    BIGINT,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE biz_order IS '业务订单';
COMMENT ON COLUMN biz_order.order_type IS 'RECHARGE/PURCHASE/SUBSCRIPTION';
COMMENT ON COLUMN biz_order.status IS 'PENDING/PAID/CANCELLED/REFUNDED';
COMMENT ON COLUMN biz_order.total_amount IS '订单总金额（分）';

CREATE UNIQUE INDEX uk_biz_order_no ON biz_order(order_no) WHERE deleted = FALSE;
CREATE INDEX idx_biz_order_user ON biz_order(user_id) WHERE deleted = FALSE;
CREATE INDEX idx_biz_order_pay ON biz_order(pay_order_id) WHERE deleted = FALSE;


-- ==================== 订单明细行 ====================

CREATE TABLE biz_order_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    order_id        BIGINT       NOT NULL,
    product_type    VARCHAR(32)  NOT NULL,
    product_id      VARCHAR(64),
    product_name    VARCHAR(200) NOT NULL,
    quantity        INTEGER      NOT NULL DEFAULT 1,
    unit_price      BIGINT       NOT NULL,
    total_price     BIGINT       NOT NULL,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE biz_order_item IS '订单明细行';
COMMENT ON COLUMN biz_order_item.product_type IS 'CREDIT_PACK/TOKEN_PACK/SUBSCRIPTION/AGENT/TOOL/KNOWLEDGE';
COMMENT ON COLUMN biz_order_item.product_id IS '关联产品 ID（套餐ID/Agent ID 等）';
COMMENT ON COLUMN biz_order_item.unit_price IS '单价（分）';
COMMENT ON COLUMN biz_order_item.total_price IS '小计（分）= unit_price * quantity';

CREATE INDEX idx_biz_order_item_order ON biz_order_item(order_id) WHERE deleted = FALSE;



-- ==================== 退款单 ====================

CREATE TABLE pay_refund_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    refund_no       VARCHAR(64)  NOT NULL,
    pay_order_id    BIGINT       NOT NULL,
    merchant_order_no VARCHAR(64) NOT NULL,
    channel_code    VARCHAR(32)  NOT NULL,
    refund_amount   BIGINT       NOT NULL,
    status          INTEGER      NOT NULL DEFAULT 0,
    reason          VARCHAR(500),
    channel_refund_no VARCHAR(128),
    success_time    TIMESTAMP(6),
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE pay_refund_order IS '退款单';
COMMENT ON COLUMN pay_refund_order.refund_amount IS '退款金额（分）';
COMMENT ON COLUMN pay_refund_order.status IS '0=等待退款 10=退款成功 20=退款失败';

CREATE UNIQUE INDEX uk_refund_order_no ON pay_refund_order(refund_no) WHERE deleted = FALSE;
CREATE INDEX idx_refund_order_pay ON pay_refund_order(pay_order_id) WHERE deleted = FALSE;

-- ==================== 对账记录 ====================

CREATE TABLE pay_reconcile_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    reconcile_date  DATE         NOT NULL,
    channel_code    VARCHAR(32)  NOT NULL,
    total_count     INTEGER      NOT NULL DEFAULT 0,
    matched_count   INTEGER      NOT NULL DEFAULT 0,
    mismatch_count  INTEGER      NOT NULL DEFAULT 0,
    status          INTEGER      NOT NULL DEFAULT 0,
    diff_details    TEXT,
    total_income    BIGINT       NOT NULL DEFAULT 0,
    total_refund    BIGINT       NOT NULL DEFAULT 0,
    total_fee       BIGINT       NOT NULL DEFAULT 0,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE pay_reconcile_record IS '对账记录';
COMMENT ON COLUMN pay_reconcile_record.status IS '0=待对账 10=已对平 20=存在差异';
COMMENT ON COLUMN pay_reconcile_record.diff_details IS '差异明细（JSON）';
COMMENT ON COLUMN pay_reconcile_record.total_income IS '总收入（分）';
COMMENT ON COLUMN pay_reconcile_record.total_refund IS '总退款（分）';
COMMENT ON COLUMN pay_reconcile_record.total_fee IS '总手续费（分）';

CREATE INDEX idx_reconcile_record_date ON pay_reconcile_record(reconcile_date, channel_code) WHERE deleted = FALSE;



-- ============================================================
-- 会员与权益 Schema（AAF-074）
-- ============================================================

-- ==================== 成长等级 ====================

CREATE TABLE billing_level (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    code            VARCHAR(16)  NOT NULL,
    name            VARCHAR(64)  NOT NULL,
    exp_min         INTEGER      NOT NULL,
    exp_max         INTEGER      NOT NULL,
    perks           JSONB,
    sort            INTEGER      NOT NULL DEFAULT 0,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE billing_level IS '成长等级（免费线）';
COMMENT ON COLUMN billing_level.perks IS '成长小权益（JSONB）';

CREATE UNIQUE INDEX uk_level_code ON billing_level(code) WHERE deleted = FALSE;

-- ==================== 订阅套餐 ====================

CREATE TABLE billing_subscription_plan (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    code            VARCHAR(32)  NOT NULL,
    name            VARCHAR(64)  NOT NULL,
    duration_days   INTEGER      NOT NULL,
    price           BIGINT       NOT NULL,
    market_price    BIGINT       NOT NULL,
    monthly_credits BIGINT       NOT NULL DEFAULT 0,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    sort            INTEGER      NOT NULL DEFAULT 0,
    ext             JSONB,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE billing_subscription_plan IS '订阅套餐定义';
COMMENT ON COLUMN billing_subscription_plan.duration_days IS '有效天数（0=永久）';
COMMENT ON COLUMN billing_subscription_plan.price IS '售价（分）';
COMMENT ON COLUMN billing_subscription_plan.monthly_credits IS '每月发放积分数，0=不发放';
COMMENT ON COLUMN billing_subscription_plan.ext IS '扩展配置（JSONB），如高亮、徽标、特性列表等';

CREATE UNIQUE INDEX uk_subscription_plan_code ON billing_subscription_plan(code) WHERE deleted = FALSE;

-- ==================== 权益定义 ====================

CREATE TABLE billing_entitlement_def (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    code            VARCHAR(64)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    type            VARCHAR(16)  NOT NULL,
    unit            VARCHAR(32),
    description     VARCHAR(500),
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE billing_entitlement_def IS '权益定义字典';
COMMENT ON COLUMN billing_entitlement_def.type IS 'BOOLEAN（开关型）/ COUNTABLE（计量型）';

CREATE UNIQUE INDEX uk_entitlement_def_code ON billing_entitlement_def(code) WHERE deleted = FALSE;

-- ==================== 套餐×权益规则 ====================

CREATE TABLE billing_plan_entitlement (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    plan_id         BIGINT       NOT NULL,
    ent_id          BIGINT       NOT NULL,
    quota           BIGINT       NOT NULL,
    reset_cycle     VARCHAR(16)  NOT NULL DEFAULT 'NONE',
    refill_price    BIGINT       NOT NULL DEFAULT 0,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE billing_plan_entitlement IS '套餐×权益规则（多对多）';
COMMENT ON COLUMN billing_plan_entitlement.quota IS '授予额度（-1=无限）';
COMMENT ON COLUMN billing_plan_entitlement.reset_cycle IS 'NONE/DAILY/MONTHLY/YEARLY';
COMMENT ON COLUMN billing_plan_entitlement.refill_price IS '额度用尽后单次充值价（积分），0=不可充值';

CREATE UNIQUE INDEX uk_plan_ent ON billing_plan_entitlement(plan_id, ent_id) WHERE deleted = FALSE;

-- ==================== 用户订阅实例 ====================

CREATE TABLE billing_subscription (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    user_id         BIGINT       NOT NULL,
    plan_id         BIGINT       NOT NULL,
    start_at        TIMESTAMP(6) NOT NULL,
    end_at          TIMESTAMP(6),
    status          VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    source_id       BIGINT,
    last_credit_issued_at TIMESTAMP(6),
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE billing_subscription IS '用户订阅实例';
COMMENT ON COLUMN billing_subscription.status IS 'ACTIVE/EXPIRED/CANCELLED';
COMMENT ON COLUMN billing_subscription.last_credit_issued_at IS '上次月度积分发放时间';

CREATE INDEX idx_subscription_user ON billing_subscription(user_id, status) WHERE deleted = FALSE;

-- ==================== 订阅购买流水 ====================

CREATE TABLE subscription_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    user_id         BIGINT       NOT NULL,
    plan_id         BIGINT       NOT NULL,
    operation       VARCHAR(16)  NOT NULL,
    pay_order_id    BIGINT,
    pay_price       BIGINT       NOT NULL,
    pay_status      VARCHAR(16)  NOT NULL DEFAULT 'UNPAID',
    pay_time        TIMESTAMP(6),
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE subscription_record IS '订阅购买流水';
COMMENT ON COLUMN subscription_record.operation IS 'NEW/RENEW';
COMMENT ON COLUMN subscription_record.pay_status IS 'UNPAID/PAID';

CREATE INDEX idx_subscription_record_user ON subscription_record(user_id) WHERE deleted = FALSE;

-- ==================== 用户权益额度实例 ====================

CREATE TABLE billing_entitlement_quota (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    user_id         BIGINT       NOT NULL,
    ent_id          BIGINT       NOT NULL,
    total           BIGINT       NOT NULL,
    used            BIGINT       NOT NULL DEFAULT 0,
    remain          BIGINT       NOT NULL,
    last_reset_at   TIMESTAMP(6),
    next_reset_at   TIMESTAMP(6),
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE billing_entitlement_quota IS '用户权益额度实例';
COMMENT ON COLUMN billing_entitlement_quota.total IS '本周期总额度';
COMMENT ON COLUMN billing_entitlement_quota.remain IS '剩余额度';

CREATE UNIQUE INDEX uk_quota_user_ent ON billing_entitlement_quota(user_id, ent_id) WHERE deleted = FALSE;
CREATE INDEX idx_quota_next_reset ON billing_entitlement_quota(next_reset_at) WHERE deleted = FALSE AND next_reset_at IS NOT NULL;

-- ==================== 权益额度变更流水 ====================

CREATE TABLE billing_entitlement_ledger (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quota_id        BIGINT       NOT NULL,
    delta           BIGINT       NOT NULL,
    operation       VARCHAR(16)  NOT NULL,
    biz_type        VARCHAR(24),
    biz_id          BIGINT,
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE billing_entitlement_ledger IS '权益额度变更流水（账本）';
COMMENT ON COLUMN billing_entitlement_ledger.delta IS '变化量（负数=消费，正数=充值/重置）';
COMMENT ON COLUMN billing_entitlement_ledger.operation IS 'USE/REFILL/RESET/ADJUST';

CREATE INDEX idx_ledger_quota ON billing_entitlement_ledger(quota_id);
CREATE INDEX idx_ledger_created ON billing_entitlement_ledger(created_at);

-- ==================== 补 credit_account 的 exp/level_id 列（wallet 复用） ====================

ALTER TABLE credit_account ADD COLUMN IF NOT EXISTS exp INTEGER NOT NULL DEFAULT 0;
ALTER TABLE credit_account ADD COLUMN IF NOT EXISTS level_id BIGINT;

COMMENT ON COLUMN credit_account.exp IS '成长经验值';
COMMENT ON COLUMN credit_account.level_id IS '当前等级 ID，引用 billing_level.id';

-- ==================== credit_grant_rule 批次查询索引 ====================

CREATE INDEX IF NOT EXISTS idx_credit_tx_batch
    ON credit_transaction(account_id, remain, expire_at)
    WHERE deleted = FALSE AND remain > 0;

-- ==================== 积分发放规则 ====================

CREATE TABLE credit_grant_rule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    code            VARCHAR(32)  NOT NULL,
    name            VARCHAR(64)  NOT NULL,
    amount          BIGINT       NOT NULL,
    expire_days     INTEGER      NOT NULL DEFAULT 0,
    trigger         VARCHAR(16)  NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    effective_from  TIMESTAMP(6),
    effective_to    TIMESTAMP(6),
    ext             JSONB,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE  credit_grant_rule             IS '积分发放规则（运营后台配置）';
COMMENT ON COLUMN credit_grant_rule.code        IS '规则编码：WEEKLY/INVITE/EXPLORE/REGISTER/EVENT_xxx';
COMMENT ON COLUMN credit_grant_rule.amount      IS '发放积分数';
COMMENT ON COLUMN credit_grant_rule.expire_days IS '有效天数，0=永久';
COMMENT ON COLUMN credit_grant_rule.trigger     IS '触发方式：SCHEDULE（定时）/ EVENT（事件）/ MANUAL（手动）';
COMMENT ON COLUMN credit_grant_rule.ext         IS '扩展配置（JSONB），如每用户上限、描述等';

CREATE UNIQUE INDEX uk_credit_grant_rule_code ON credit_grant_rule(code) WHERE deleted = FALSE;

-- ============================================================
-- 字典 Seed 数据
-- ============================================================

-- 成长等级
INSERT INTO billing_level (code, name, exp_min, exp_max, perks, sort) VALUES
    ('L0', '普通会员', 0, 99, '{"sign_bonus": 1.0}', 0),
    ('L1', '银牌会员', 100, 499, '{"sign_bonus": 1.5}', 1),
    ('L2', '金牌会员', 500, 2147483647, '{"sign_bonus": 2.0}', 2);

-- 订阅套餐
INSERT INTO billing_subscription_plan (code, name, duration_days, price, market_price, status, sort) VALUES
    ('FREE', '免费版', 0, 0, 0, 'ENABLED', 0),
    ('PRO', '专业版', 30, 9900, 12900, 'ENABLED', 1),
    ('TEAM', '团队版', 30, 29900, 39900, 'ENABLED', 2),
    ('ENTERPRISE', '企业版', 365, 299900, 399900, 'ENABLED', 3);

-- 权益定义
INSERT INTO billing_entitlement_def (code, name, type, unit, description) VALUES
    ('ai_token', 'AI Token 额度', 'COUNTABLE', 'token', 'AI 对话消耗的 Token 额度'),
    ('model_gpt4', 'GPT-4 模型访问', 'BOOLEAN', NULL, '是否可使用 GPT-4 模型'),
    ('kb_storage', '知识库存储', 'COUNTABLE', 'MB', '知识库文件存储空间'),
    ('workflow_run', '工作流执行次数', 'COUNTABLE', '次', '每月可执行工作流次数');

-- 套餐×权益规则（FREE）
INSERT INTO billing_plan_entitlement (plan_id, ent_id, quota, reset_cycle, refill_price)
SELECT sp.id, ed.id, 10000, 'MONTHLY', 100
FROM billing_subscription_plan sp, billing_entitlement_def ed
WHERE sp.code = 'FREE' AND ed.code = 'ai_token';

INSERT INTO billing_plan_entitlement (plan_id, ent_id, quota, reset_cycle, refill_price)
SELECT sp.id, ed.id, 1024, 'NONE', 0
FROM billing_subscription_plan sp, billing_entitlement_def ed
WHERE sp.code = 'FREE' AND ed.code = 'kb_storage';

INSERT INTO billing_plan_entitlement (plan_id, ent_id, quota, reset_cycle, refill_price)
SELECT sp.id, ed.id, 10, 'MONTHLY', 50
FROM billing_subscription_plan sp, billing_entitlement_def ed
WHERE sp.code = 'FREE' AND ed.code = 'workflow_run';

-- 套餐×权益规则（PRO）
INSERT INTO billing_plan_entitlement (plan_id, ent_id, quota, reset_cycle, refill_price)
SELECT sp.id, ed.id, 1000000, 'MONTHLY', 10
FROM billing_subscription_plan sp, billing_entitlement_def ed
WHERE sp.code = 'PRO' AND ed.code = 'ai_token';

INSERT INTO billing_plan_entitlement (plan_id, ent_id, quota, reset_cycle, refill_price)
SELECT sp.id, ed.id, 1, 'NONE', 0
FROM billing_subscription_plan sp, billing_entitlement_def ed
WHERE sp.code = 'PRO' AND ed.code = 'model_gpt4';

INSERT INTO billing_plan_entitlement (plan_id, ent_id, quota, reset_cycle, refill_price)
SELECT sp.id, ed.id, 10240, 'NONE', 0
FROM billing_subscription_plan sp, billing_entitlement_def ed
WHERE sp.code = 'PRO' AND ed.code = 'kb_storage';

INSERT INTO billing_plan_entitlement (plan_id, ent_id, quota, reset_cycle, refill_price)
SELECT sp.id, ed.id, 100, 'MONTHLY', 20
FROM billing_subscription_plan sp, billing_entitlement_def ed
WHERE sp.code = 'PRO' AND ed.code = 'workflow_run';

-- 订阅套餐月度积分
UPDATE billing_subscription_plan SET monthly_credits = 8400   WHERE code = 'PRO';
UPDATE billing_subscription_plan SET monthly_credits = 30000  WHERE code = 'TEAM';
UPDATE billing_subscription_plan SET monthly_credits = 100000 WHERE code = 'ENTERPRISE';

-- 积分发放规则
INSERT INTO credit_grant_rule (code, name, amount, expire_days, trigger, status) VALUES
    ('WEEKLY',   '每周积分',     200,  7, 'SCHEDULE', 'ENABLED'),
    ('REGISTER', '注册奖励',     100, 30, 'EVENT',    'ENABLED'),
    ('INVITE',   '邀请奖励',     500, 30, 'EVENT',    'ENABLED'),
    ('EXPLORE',  '探索使用奖励', 200, 30, 'EVENT',    'ENABLED');


-- 会员与积分 FAQ（前端定价页展示）
INSERT INTO sys_config (category, config_key, value, default_value, value_type, name, description, visible, editable)
VALUES (
    'member',
    'member.faq',
    '[
  {
    "q": "什么是积分（credits），我如何获得？",
    "a": "积分是平台的标准计量单位，用于 AI 对话、图片生成、视频生成等功能。你可以通过以下方式获取积分：\n订阅会员后每月自动到账（有效期 30 天）；\n每周一自动发放每周积分（有效期 7 天）；\n成功邀请用户注册后获取邀请奖励（有效期 30 天）；\n使用平台功能可获得探索使用奖励（有效期 30 天）；\n也可直接充值购买积分（永久有效）。"
  },
  {
    "q": "积分在使用过程中如何扣除？",
    "a": "积分的具体消耗以功能价格表为准。系统将优先扣除更快到期的积分，以最大程度保障你的积分使用权益。"
  },
  {
    "q": "订阅是如何运作的？",
    "a": "订阅后立即生效，每月自动发放对应积分（有效期 30 天）。到期后需重新购买，暂不支持自动续费。升级套餐时，旧套餐剩余权益将在当前周期内继续有效。"
  },
  {
    "q": "订阅会自动续费吗？",
    "a": "目前暂不支持自动续费。订阅到期后需手动重新购买，到期前系统会发送提醒通知。"
  },
  {
    "q": "充值积分有有效期吗？",
    "a": "充值购买的积分有效期为 2 年，到期自动清零。订阅赠送的月度积分有效期为 30 天，每周积分有效期为 7 天，奖励积分有效期为 30 天。系统优先消耗更快到期的积分，保障你的权益。"
  },
  {
    "q": "如何修改或取消订阅？",
    "a": "你可以随时在「设置 → 订阅」页面管理订阅。取消后，当前订阅周期内权益仍然有效，周期结束后不再续期。"
  },
  {
    "q": "如何申请退款？",
    "a": "如果你在最近一次付款后未有任何使用行为，可在购买后 7 天内联系客服申请全额退款。因系统问题导致的失败操作将自动退还对应积分。"
  }
]',
    NULL,
    'json',
    '会员与积分常见问题',
    '定价页展示的 FAQ 列表，JSON 数组，每项包含 q（问题）和 a（答案）',
    TRUE,
    TRUE
);


-- ==================== 积分充值套餐 ====================

CREATE TABLE credit_package (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    org_id           BIGINT,
    workspace_id     BIGINT,
    name             VARCHAR(64)  NOT NULL,
    credits          BIGINT       NOT NULL,
    bonus_credits    BIGINT       NOT NULL DEFAULT 0,
    price            BIGINT       NOT NULL,
    group_label      VARCHAR(32),
    recommended      BOOLEAN      NOT NULL DEFAULT FALSE,
    status           VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    sort             INT          NOT NULL DEFAULT 0,
    create_by        BIGINT,
    create_by_type   VARCHAR(16),
    create_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by        BIGINT,
    update_by_type   VARCHAR(16),
    update_time      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time      TIMESTAMP(6),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    owner_id         BIGINT,
    remark           VARCHAR(255)
);

COMMENT ON TABLE  credit_package               IS '积分充值套餐';
COMMENT ON COLUMN credit_package.credits       IS '积分数';
COMMENT ON COLUMN credit_package.bonus_credits IS '赠送积分';
COMMENT ON COLUMN credit_package.price         IS '售价（分）';
COMMENT ON COLUMN credit_package.group_label   IS '套餐分组标签';

-- ==================== 支付通知任务 ====================

CREATE TABLE pay_notify_task (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    pay_order_id      BIGINT       NOT NULL,
    biz_order_type    VARCHAR(32)  NOT NULL,
    status            VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    notify_times      INTEGER      NOT NULL DEFAULT 0,
    max_notify_times  INTEGER      NOT NULL DEFAULT 8,
    last_execute_time TIMESTAMP(6),
    next_notify_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    response          VARCHAR(512),
    create_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE pay_notify_task IS '支付通知任务（可靠通知，失败重试）';
COMMENT ON COLUMN pay_notify_task.status IS 'PENDING=待通知, SUCCESS=成功, FAILURE=失败放弃';
COMMENT ON COLUMN pay_notify_task.next_notify_time IS '下次执行时间（指数退避计算）';

CREATE INDEX idx_pay_notify_task_pending ON pay_notify_task(next_notify_time)
    WHERE status = 'PENDING';


-- ==================== 积分兑换码 ====================
CREATE TABLE credit_redeem_code
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash             VARCHAR(64)              NOT NULL UNIQUE,
    code_prefix           VARCHAR(20)              NOT NULL,
    credit_amount         BIGINT                   NOT NULL,
    batch_type            VARCHAR(20)              NOT NULL DEFAULT 'REWARD',
    status                VARCHAR(20)              NOT NULL DEFAULT 'UNUSED',
    expires_at            TIMESTAMP,
    redeemed_by_user_id   BIGINT,
    redeemed_at           TIMESTAMP,
    remark                VARCHAR(255),
    org_id                BIGINT,
    workspace_id          BIGINT,
    owner_id              BIGINT,
    create_by             BIGINT,
    create_by_type        VARCHAR(16),
    update_by             BIGINT,
    update_by_type        VARCHAR(16),
    deleted               BOOLEAN                  NOT NULL DEFAULT FALSE,
    delete_time           TIMESTAMP,
    create_time           TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time           TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version               INTEGER                  NOT NULL DEFAULT 0
);

CREATE INDEX idx_credit_redeem_code_status ON credit_redeem_code (status) WHERE deleted = FALSE;

COMMENT ON TABLE credit_redeem_code IS '积分兑换码';
COMMENT ON COLUMN credit_redeem_code.code_hash IS '兑换码 SHA-256 哈希，不存明文';
COMMENT ON COLUMN credit_redeem_code.code_prefix IS '兑换码前缀展示（如 CRED-XXXXX...），用于管理界面识别';
COMMENT ON COLUMN credit_redeem_code.credit_amount IS '可兑换积分数量';
COMMENT ON COLUMN credit_redeem_code.batch_type IS '积分批次类型：SUBSCRIPTION/TOPUP/REWARD/WEEKLY/MANUAL';
COMMENT ON COLUMN credit_redeem_code.status IS '状态：UNUSED=未使用, REDEEMED=已兑换, EXPIRED=已过期';
COMMENT ON COLUMN credit_redeem_code.expires_at IS '过期时间，NULL 表示永不过期';
COMMENT ON COLUMN credit_redeem_code.redeemed_by_user_id IS '兑换者用户 ID';
COMMENT ON COLUMN credit_redeem_code.redeemed_at IS '兑换时间';
