-- ============================================================
-- 智能体执行追踪 Schema
-- 包含：执行运行记录、执行步骤
-- ============================================================

CREATE TABLE execution_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id    VARCHAR(128) NOT NULL UNIQUE,
    parent_run_id   BIGINT REFERENCES execution_run(id),
    agent_id        VARCHAR(64)  NOT NULL,
    agent_name      VARCHAR(128),
    user_id         BIGINT,
    conversation_id VARCHAR(64),
    input           TEXT,
    output          TEXT,
    status          VARCHAR(16)  NOT NULL,
    error_message   TEXT,
    token_input     INTEGER      NOT NULL DEFAULT 0,
    token_output    INTEGER      NOT NULL DEFAULT 0,
    started_at      TIMESTAMPTZ  NOT NULL,
    finished_at     TIMESTAMPTZ,
    duration_ms     BIGINT,
    retry_count     INTEGER      NOT NULL DEFAULT 0,
    metadata        JSONB
);

COMMENT ON TABLE execution_run IS '智能体执行运行记录';
CREATE INDEX idx_execution_run_user   ON execution_run(user_id, started_at DESC);
CREATE INDEX idx_execution_run_agent  ON execution_run(agent_id, started_at DESC);
CREATE INDEX idx_execution_run_status ON execution_run(status) WHERE status != 'SUCCESS';
CREATE INDEX idx_execution_run_parent ON execution_run(parent_run_id) WHERE parent_run_id IS NOT NULL;

CREATE TABLE execution_step (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT       NOT NULL REFERENCES execution_run(id),
    parent_step_id  BIGINT REFERENCES execution_step(id),
    step_index      INTEGER      NOT NULL,
    step_type       VARCHAR(32)  NOT NULL,
    agent_id        VARCHAR(64),
    tool_name       VARCHAR(128),
    input           TEXT,
    output          TEXT,
    status          VARCHAR(16)  NOT NULL,
    error_message   TEXT,
    started_at      TIMESTAMPTZ  NOT NULL,
    finished_at     TIMESTAMPTZ,
    duration_ms     BIGINT
);

COMMENT ON TABLE execution_step IS '智能体执行步骤';
CREATE INDEX idx_execution_step_run ON execution_step(run_id, step_index);
