-- ============================================================
-- 支付、积分与结算 Schema
-- ============================================================

-- ==================== 积分账户 ====================

CREATE TABLE credit_account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    user_id         BIGINT       NOT NULL,
    balance         BIGINT       NOT NULL DEFAULT 0,
    frozen          BIGINT       NOT NULL DEFAULT 0,
    total_earned    BIGINT       NOT NULL DEFAULT 0,
    total_spent     BIGINT       NOT NULL DEFAULT 0,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE credit_account IS '积分账户';
COMMENT ON COLUMN credit_account.balance IS '可用余额（分）';
COMMENT ON COLUMN credit_account.frozen IS '冻结金额（分）';

CREATE UNIQUE INDEX uk_credit_account_user ON credit_account(user_id) WHERE deleted = FALSE;

-- ==================== 积分流水 ====================

CREATE TABLE credit_transaction (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    account_id      BIGINT       NOT NULL,
    type            VARCHAR(20)  NOT NULL,
    amount          BIGINT       NOT NULL,
    balance_after   BIGINT       NOT NULL,
    source          VARCHAR(100),
    biz_id          VARCHAR(64),
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE credit_transaction IS '积分流水记录';
COMMENT ON COLUMN credit_transaction.type IS 'EARN/SPEND/FREEZE/UNFREEZE';

CREATE INDEX idx_credit_transaction_account ON credit_transaction(account_id) WHERE deleted = FALSE;
CREATE INDEX idx_credit_transaction_biz ON credit_transaction(biz_id) WHERE deleted = FALSE;

-- ==================== 积分转Token规则 ====================

CREATE TABLE credit_token_rule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(100) NOT NULL,
    credit_amount   BIGINT       NOT NULL,
    token_amount    BIGINT       NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ENABLED',
    priority        INTEGER      NOT NULL DEFAULT 0,
    effective_from  TIMESTAMP(6),
    effective_to    TIMESTAMP(6),
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE credit_token_rule IS '积分转Token规则';
COMMENT ON COLUMN credit_token_rule.status IS 'ENABLED/DISABLED';
COMMENT ON COLUMN credit_token_rule.priority IS '数值越小优先级越高';

-- ==================== 支付订单 ====================

CREATE TABLE pay_order (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER      NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    merchant_order_no   VARCHAR(64)  NOT NULL,
    subject             VARCHAR(200) NOT NULL,
    body                VARCHAR(500),
    amount              BIGINT       NOT NULL,
    status              INTEGER      NOT NULL DEFAULT 0,
    channel_code        VARCHAR(32)  NOT NULL,
    channel_order_no    VARCHAR(128),
    user_id             BIGINT       NOT NULL,
    expire_time         TIMESTAMP(6),
    success_time        TIMESTAMP(6),
    refund_amount       BIGINT       NOT NULL DEFAULT 0,
    owner_id            BIGINT,
    create_by           BIGINT,
    create_by_type      VARCHAR(16),
    create_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    remark              VARCHAR(255)
);

COMMENT ON TABLE pay_order IS '支付订单';
COMMENT ON COLUMN pay_order.amount IS '支付金额（分）';
COMMENT ON COLUMN pay_order.status IS '0=等待支付 10=支付成功 30=已关闭';

CREATE UNIQUE INDEX uk_pay_order_merchant_no ON pay_order(merchant_order_no) WHERE deleted = FALSE;
CREATE INDEX idx_pay_order_user ON pay_order(user_id) WHERE deleted = FALSE;

-- ==================== 业务订单 ====================

CREATE TABLE biz_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    order_no        VARCHAR(64)  NOT NULL,
    user_id         BIGINT       NOT NULL,
    order_type      VARCHAR(32)  NOT NULL,
    subject         VARCHAR(200) NOT NULL,
    total_amount    BIGINT       NOT NULL,
    pay_order_id    BIGINT,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE biz_order IS '业务订单';
COMMENT ON COLUMN biz_order.order_type IS 'RECHARGE/PURCHASE/SUBSCRIPTION';
COMMENT ON COLUMN biz_order.status IS 'PENDING/PAID/CANCELLED/REFUNDED';
COMMENT ON COLUMN biz_order.total_amount IS '订单总金额（分）';

CREATE UNIQUE INDEX uk_biz_order_no ON biz_order(order_no) WHERE deleted = FALSE;
CREATE INDEX idx_biz_order_user ON biz_order(user_id) WHERE deleted = FALSE;
CREATE INDEX idx_biz_order_pay ON biz_order(pay_order_id) WHERE deleted = FALSE;
