-- AAF-032 #7 数据归档

-- ==================== 归档规则配置表 ====================

CREATE TABLE sys_archive_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_slug  VARCHAR(100) NOT NULL,
    condition    JSONB        NOT NULL DEFAULT '{}',
    after_days   INTEGER      NOT NULL DEFAULT 90,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    version      INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_archive_rule IS '数据归档规则';
COMMENT ON COLUMN sys_archive_rule.entity_slug IS '实体标识';
COMMENT ON COLUMN sys_archive_rule.condition IS '归档条件，JSONB 格式：{"field":"status","operator":"eq","value":"done"}';
COMMENT ON COLUMN sys_archive_rule.after_days IS '满足条件后等待天数';
COMMENT ON COLUMN sys_archive_rule.enabled IS '是否启用';

CREATE INDEX idx_archive_rule_entity ON sys_archive_rule (entity_slug) WHERE deleted = false;

-- ==================== 已有业务表加 archived_at 列 ====================

ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE sys_todo ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE sys_notification ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE sys_notification_preference ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE sys_record_version ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE sys_activity_log ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE sys_comment ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE sys_subscription ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE sys_role ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE sys_permission ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE sys_role_permission ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE sys_user_role ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE sys_data_access_rule ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE doc_document ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE autodev_request ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE autodev_generated_code ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
ALTER TABLE autodev_execution_log ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP(6);
