-- ============================================================
-- 动态数据表元数据 Schema
-- 存储用户自定义表的定义（表名、列定义），实际数据表通过 DDL 动态创建
-- ============================================================

CREATE TABLE data_table_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(64)  NOT NULL UNIQUE,
    display_name    VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    table_name      VARCHAR(80)  NOT NULL UNIQUE,  -- 实际 PG 表名（data_{slug}）
    org_id          BIGINT,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ
);

COMMENT ON TABLE data_table_definition IS '动态数据表定义';

CREATE TABLE data_column_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id        BIGINT       NOT NULL REFERENCES data_table_definition(id) ON DELETE CASCADE,
    name            VARCHAR(64)  NOT NULL,
    display_name    VARCHAR(128),
    column_type     VARCHAR(32)  NOT NULL,  -- string/text/integer/decimal/boolean/timestamp/json
    nullable        BOOLEAN      NOT NULL DEFAULT TRUE,
    unique_col      BOOLEAN      NOT NULL DEFAULT FALSE,
    default_value   VARCHAR(256),
    sort_order      INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE data_column_definition IS '动态数据表列定义';
CREATE INDEX idx_data_column_table ON data_column_definition(table_id, sort_order);


-- ============================================================
-- 数据摄入 API Key
-- ============================================================

CREATE TABLE data_api_key (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_hash        VARCHAR(64)  NOT NULL UNIQUE,
    key_prefix      VARCHAR(16)  NOT NULL,
    name            VARCHAR(128) NOT NULL,
    user_id         BIGINT       NOT NULL,
    allowed_tables  VARCHAR(1024),
    permissions     VARCHAR(64)  NOT NULL DEFAULT 'ingest',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at      TIMESTAMPTZ,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    last_used_at    TIMESTAMPTZ
);

COMMENT ON TABLE data_api_key IS '数据摄入 API Key';
CREATE INDEX idx_data_api_key_user ON data_api_key(user_id);
