-- ============================================================
-- AIGC 统一基线 Schema
-- 历史迁移重写已获批准；所有环境必须清空后按 Flyway 顺序重建。
-- 约束：唯一 aigc_project；内部持久文件只通过 file_id/media_version_id 标识。
-- ============================================================

-- ============================================================
-- 项目定义与版本化配置
-- ============================================================

CREATE TABLE aigc_project_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    icon VARCHAR(64),
    description VARCHAR(500),
    brief_placeholder VARCHAR(500),
    definition_version VARCHAR(32) NOT NULL DEFAULT '1.0.0',
    default_channels JSONB,
    default_production_mode VARCHAR(32),
    quick_entry BOOLEAN NOT NULL DEFAULT FALSE,
    builtin BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_project_type IS 'AIGC 项目业务目标类型';
COMMENT ON COLUMN aigc_project_type.definition_version IS '项目类型定义语义版本';
CREATE UNIQUE INDEX uk_aigc_project_type_code_active ON aigc_project_type (code) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_project_type_status_sort ON aigc_project_type (status, sort_order) WHERE deleted = FALSE;

CREATE TABLE aigc_project_blueprint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    project_type_code VARCHAR(64) NOT NULL,
    blueprint_version VARCHAR(32) NOT NULL,
    production_mode VARCHAR(32) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(32) NOT NULL,
    object_spec JSONB,
    relation_spec JSONB,
    deliverable_spec JSONB,
    action_keys JSONB,
    confirmation_gates JSONB,
    brief_fields JSONB,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_project_blueprint IS 'AIGC 版本化项目骨架';
COMMENT ON COLUMN aigc_project_blueprint.object_spec IS '项目对象规格 JSON';
COMMENT ON COLUMN aigc_project_blueprint.relation_spec IS '项目关系规格 JSON';
CREATE UNIQUE INDEX uk_aigc_blueprint_code_version_active
    ON aigc_project_blueprint (code, blueprint_version) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_blueprint_compatible
    ON aigc_project_blueprint (project_type_code, production_mode, status) WHERE deleted = FALSE;

CREATE TABLE aigc_domain_extension (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    extension_version VARCHAR(32) NOT NULL,
    industry VARCHAR(64),
    region VARCHAR(32),
    language VARCHAR(32),
    status VARCHAR(32) NOT NULL,
    profile_schema_ext JSONB,
    object_definitions JSONB,
    knowledge_requirements JSONB,
    rule_sets JSONB,
    validators JSONB,
    role_recommendations JSONB,
    action_constraints JSONB,
    channel_overrides JSONB,
    migration_declaration JSONB,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_domain_extension IS 'AIGC 版本化领域扩展';
CREATE UNIQUE INDEX uk_aigc_domain_extension_version_active
    ON aigc_domain_extension (code, extension_version) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_domain_extension_status ON aigc_domain_extension (status) WHERE deleted = FALSE;

CREATE TABLE aigc_channel_spec (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    spec_version VARCHAR(32) NOT NULL,
    aspect_ratio VARCHAR(32),
    width INTEGER,
    height INTEGER,
    max_duration_seconds INTEGER,
    copy_structure JSONB,
    required_disclaimers VARCHAR(1000),
    export_format VARCHAR(64),
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_channel_spec IS 'AIGC 版本化渠道规格';
CREATE UNIQUE INDEX uk_aigc_channel_spec_version_active
    ON aigc_channel_spec (code, spec_version) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_channel_spec_status_sort
    ON aigc_channel_spec (status, sort_order) WHERE deleted = FALSE;

CREATE TABLE aigc_execution_binding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    action_key VARCHAR(100) NOT NULL,
    project_type_code VARCHAR(64),
    domain_extension_code VARCHAR(64),
    production_mode VARCHAR(32),
    channel_code VARCHAR(64),
    target_type VARCHAR(32) NOT NULL,
    target_ref VARCHAR(200) NOT NULL,
    binding_version VARCHAR(32) NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    confirmation_required BOOLEAN NOT NULL DEFAULT TRUE,
    estimated_credits NUMERIC(12,2),
    status VARCHAR(32) NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_execution_binding IS 'AIGC 动作到 Agent/Tool/Workflow 的版本化绑定';
COMMENT ON COLUMN aigc_execution_binding.target_ref IS '执行目标稳定引用，不保存运行时实例';
CREATE INDEX idx_aigc_execution_binding_action_status
    ON aigc_execution_binding (action_key, status) WHERE deleted = FALSE;

CREATE TABLE aigc_project_type_package (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    package_version VARCHAR(32) NOT NULL,
    project_type_id BIGINT NOT NULL REFERENCES aigc_project_type(id) ON DELETE RESTRICT,
    blueprint_id BIGINT NOT NULL REFERENCES aigc_project_blueprint(id) ON DELETE RESTRICT,
    domain_extension_id BIGINT REFERENCES aigc_domain_extension(id) ON DELETE RESTRICT,
    channel_spec_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    execution_binding_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    production_mode VARCHAR(32) NOT NULL,
    compatibility_result JSONB,
    status VARCHAR(32) NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_project_type_package IS '项目类型、蓝图、领域、渠道和执行绑定的兼容版本组合';
CREATE UNIQUE INDEX uk_aigc_project_type_package_active
    ON aigc_project_type_package (project_type_id, package_version) WHERE deleted = FALSE;

-- ============================================================
-- 品牌/IP 与唯一项目聚合
-- ============================================================

CREATE TABLE aigc_brand_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    name VARCHAR(200) NOT NULL,
    kind VARCHAR(32) NOT NULL,
    industry VARCHAR(64),
    current_version_id BIGINT,
    status VARCHAR(32) NOT NULL,
    user_id BIGINT,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_brand_profile IS '品牌/IP 稳定身份';
CREATE INDEX idx_aigc_brand_profile_owner ON aigc_brand_profile (owner_id) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_brand_profile_kind ON aigc_brand_profile (kind) WHERE deleted = FALSE;

CREATE TABLE aigc_brand_profile_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    brand_profile_id BIGINT NOT NULL REFERENCES aigc_brand_profile(id) ON DELETE RESTRICT,
    version_no INTEGER NOT NULL,
    positioning VARCHAR(1000),
    audience VARCHAR(1000),
    tone_of_voice VARCHAR(1000),
    visual_style VARCHAR(1000),
    disclaimer VARCHAR(1000),
    forbidden_items VARCHAR(1000),
    rules JSONB,
    status VARCHAR(32) NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_brand_profile_version IS '不可变品牌/IP 资料版本';
CREATE UNIQUE INDEX uk_aigc_brand_profile_version_active
    ON aigc_brand_profile_version (brand_profile_id, version_no) WHERE deleted = FALSE;
ALTER TABLE aigc_brand_profile
    ADD CONSTRAINT fk_aigc_brand_profile_current_version
    FOREIGN KEY (current_version_id) REFERENCES aigc_brand_profile_version(id) ON DELETE RESTRICT;

CREATE TABLE aigc_project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    project_type_code VARCHAR(64) NOT NULL,
    blueprint_code VARCHAR(64),
    blueprint_version VARCHAR(32),
    domain_extension_code VARCHAR(64),
    domain_extension_version VARCHAR(32),
    production_mode VARCHAR(32) NOT NULL,
    generation_mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    brief TEXT,
    prompt TEXT,
    cover_media_version_id BIGINT,
    config_snapshot_id BIGINT,
    graph_revision INTEGER NOT NULL DEFAULT 1,
    primary_brand_profile_id BIGINT REFERENCES aigc_brand_profile(id) ON DELETE RESTRICT,
    assistant_id BIGINT,
    budget_limit NUMERIC(12,2),
    cost_used NUMERIC(12,2) NOT NULL DEFAULT 0,
    last_active_time TIMESTAMP(6),
    user_id BIGINT NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_project IS 'AIGC 唯一项目聚合根';
COMMENT ON COLUMN aigc_project.cover_media_version_id IS '项目封面媒体版本，不持久化内部文件 URL';
COMMENT ON COLUMN aigc_project.graph_revision IS '项目对象图谱当前逻辑修订号';
CREATE INDEX idx_aigc_project_owner ON aigc_project (owner_id) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_project_user ON aigc_project (user_id) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_project_status ON aigc_project (status) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_project_type_mode
    ON aigc_project (project_type_code, production_mode) WHERE deleted = FALSE;

CREATE TABLE aigc_project_config_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    revision_no INTEGER NOT NULL,
    project_type_version VARCHAR(32),
    blueprint_version VARCHAR(32),
    domain_extension_version VARCHAR(32),
    channel_versions JSONB,
    execution_binding_versions JSONB,
    compatibility_result JSONB,
    snapshot JSONB NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_project_config_snapshot IS '项目创建或升级时采用的不可变配置快照';
CREATE UNIQUE INDEX uk_aigc_project_config_snapshot_active
    ON aigc_project_config_snapshot (project_id, revision_no) WHERE deleted = FALSE;
ALTER TABLE aigc_project
    ADD CONSTRAINT fk_aigc_project_config_snapshot
    FOREIGN KEY (config_snapshot_id) REFERENCES aigc_project_config_snapshot(id) ON DELETE RESTRICT;

CREATE TABLE aigc_project_profile_ref (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    brand_profile_version_id BIGINT NOT NULL REFERENCES aigc_brand_profile_version(id) ON DELETE RESTRICT,
    ref_scope VARCHAR(32) NOT NULL,
    scope_note VARCHAR(500),
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_project_profile_ref IS '项目对品牌/IP 资料精确版本的引用';
CREATE UNIQUE INDEX uk_aigc_project_profile_ref_active
    ON aigc_project_profile_ref (project_id, brand_profile_version_id, ref_scope) WHERE deleted = FALSE;

CREATE TABLE aigc_project_channel_ref (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    channel_spec_id BIGINT NOT NULL REFERENCES aigc_channel_spec(id) ON DELETE RESTRICT,
    primary_channel BOOLEAN NOT NULL DEFAULT FALSE,
    override_config JSONB,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_project_channel_ref IS '项目引用的渠道规格版本和项目级覆盖配置';
CREATE UNIQUE INDEX uk_aigc_project_channel_ref_active
    ON aigc_project_channel_ref (project_id, channel_spec_id) WHERE deleted = FALSE;

CREATE TABLE aigc_resolved_domain_context (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    revision_no INTEGER NOT NULL,
    input_facts JSONB,
    resolved_rules JSONB,
    resolution_result JSONB NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_resolved_domain_context IS '解析后的项目领域上下文修订';
CREATE UNIQUE INDEX uk_aigc_resolved_domain_context_active
    ON aigc_resolved_domain_context (project_id, revision_no) WHERE deleted = FALSE;

CREATE TABLE aigc_project_object (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    object_type VARCHAR(48) NOT NULL,
    object_key VARCHAR(100) NOT NULL,
    blueprint_node_key VARCHAR(100),
    parent_id BIGINT REFERENCES aigc_project_object(id) ON DELETE RESTRICT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    title VARCHAR(300),
    status VARCHAR(32) NOT NULL,
    source VARCHAR(32) NOT NULL,
    schema_version VARCHAR(32),
    entity_resource VARCHAR(100),
    entity_id BIGINT,
    adopted_version_id BIGINT,
    summary VARCHAR(500),
    payload JSONB,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_project_object IS '项目内类型化对象；Brief/Deliverable/Episode/Scene/Shot 等均由 object_type 表达';
COMMENT ON COLUMN aigc_project_object.object_key IS '项目内稳定对象键';
CREATE UNIQUE INDEX uk_aigc_project_object_key_active
    ON aigc_project_object (project_id, object_key) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_project_object_parent
    ON aigc_project_object (project_id, parent_id) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_project_object_type
    ON aigc_project_object (project_id, object_type) WHERE deleted = FALSE;

CREATE TABLE aigc_project_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    relation_type VARCHAR(32) NOT NULL,
    layer VARCHAR(32) NOT NULL,
    source_object_id BIGINT NOT NULL REFERENCES aigc_project_object(id) ON DELETE RESTRICT,
    target_object_id BIGINT NOT NULL REFERENCES aigc_project_object(id) ON DELETE RESTRICT,
    relation_meta JSONB,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_project_relation IS '项目对象图谱的语义关系';
CREATE UNIQUE INDEX uk_aigc_project_relation_active
    ON aigc_project_relation (project_id, relation_type, layer, source_object_id, target_object_id)
    WHERE deleted = FALSE;
CREATE INDEX idx_aigc_project_relation_source ON aigc_project_relation (source_object_id) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_project_relation_target ON aigc_project_relation (target_object_id) WHERE deleted = FALSE;

CREATE TABLE aigc_project_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    revision_no INTEGER NOT NULL,
    changed_object_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    changed_relation_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    actor_type VARCHAR(16) NOT NULL,
    actor_id BIGINT,
    source_execution_run_id BIGINT,
    summary VARCHAR(500),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE aigc_project_revision IS '项目对象图谱逻辑修订记录';
CREATE UNIQUE INDEX uk_aigc_project_revision ON aigc_project_revision (project_id, revision_no);

CREATE TABLE aigc_project_document_ref (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    object_id BIGINT REFERENCES aigc_project_object(id) ON DELETE RESTRICT,
    document_version_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_project_document_ref IS '项目对外部文档精确版本的稳定引用';
CREATE UNIQUE INDEX uk_aigc_project_document_ref_active
    ON aigc_project_document_ref (project_id, document_version_id, role) WHERE deleted = FALSE;

CREATE TABLE aigc_project_resource_ref (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    resource_type VARCHAR(32) NOT NULL,
    resource_id VARCHAR(128) NOT NULL,
    resource_version VARCHAR(64),
    role VARCHAR(32),
    sort_order INTEGER NOT NULL DEFAULT 0,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_project_resource_ref IS '项目对 Assistant/KnowledgeBase/Workflow/Skill/ModelPolicy 的稳定引用';
CREATE UNIQUE INDEX uk_aigc_project_resource_ref_active
    ON aigc_project_resource_ref (project_id, resource_type, resource_id) WHERE deleted = FALSE;

-- ============================================================
-- 统一执行与媒体生成子任务
-- ============================================================

CREATE TABLE aigc_execution_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    object_id BIGINT REFERENCES aigc_project_object(id) ON DELETE RESTRICT,
    parent_run_id BIGINT REFERENCES aigc_execution_run(id) ON DELETE RESTRICT,
    action_key VARCHAR(100) NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_ref VARCHAR(200),
    status VARCHAR(32) NOT NULL,
    generation_mode VARCHAR(32),
    role_profile_code VARCHAR(64),
    model_policy_version VARCHAR(64),
    selected_model_version VARCHAR(100),
    skill_definition_version_id VARCHAR(64),
    prompt_text TEXT,
    snippet_refs JSONB,
    attachment_refs JSONB,
    tool_calls JSONB,
    context_snapshot JSONB,
    input_payload JSONB,
    output_payload JSONB,
    cost_credits NUMERIC(12,2),
    retry_of_run_id BIGINT REFERENCES aigc_execution_run(id) ON DELETE RESTRICT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    error_message VARCHAR(1000),
    start_time TIMESTAMP(6),
    end_time TIMESTAMP(6),
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_execution_run IS '所有 Agent/Tool/Workflow 动作的统一业务执行记录';
CREATE INDEX idx_aigc_execution_run_project ON aigc_execution_run (project_id, create_time DESC) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_execution_run_object ON aigc_execution_run (object_id) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_execution_run_status ON aigc_execution_run (status) WHERE deleted = FALSE;

ALTER TABLE aigc_project_revision
    ADD CONSTRAINT fk_aigc_project_revision_execution
    FOREIGN KEY (source_execution_run_id) REFERENCES aigc_execution_run(id) ON DELETE RESTRICT;

CREATE TABLE aigc_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    user_id BIGINT NOT NULL,
    project_id BIGINT REFERENCES aigc_project(id) ON DELETE RESTRICT,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    provider VARCHAR(50),
    model VARCHAR(100),
    model_name VARCHAR(100),
    prompt TEXT,
    params JSONB,
    provider_task_id TEXT,
    provider_result JSONB,
    output_media_version_id BIGINT,
    error_msg TEXT,
    credit_tx_id BIGINT,
    system_prompt TEXT,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_task IS '图片、视频、音频、音乐、3D、处理、转码和合成媒体子任务';
COMMENT ON COLUMN aigc_task.provider_result IS '供应商原始响应快照，不作为内部文件身份';
COMMENT ON COLUMN aigc_task.output_media_version_id IS '平台保留结果对应的媒体版本';
CREATE INDEX idx_aigc_task_user ON aigc_task (user_id, create_time DESC) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_task_project ON aigc_task (project_id) WHERE project_id IS NOT NULL AND deleted = FALSE;
CREATE INDEX idx_aigc_task_status ON aigc_task (status) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_task_credit_tx ON aigc_task (credit_tx_id) WHERE credit_tx_id IS NOT NULL;

CREATE TABLE aigc_execution_task_ref (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_run_id BIGINT NOT NULL REFERENCES aigc_execution_run(id) ON DELETE RESTRICT,
    task_id BIGINT NOT NULL REFERENCES aigc_task(id) ON DELETE RESTRICT,
    role VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    delete_time TIMESTAMP(6)
);
COMMENT ON TABLE aigc_execution_task_ref IS '统一执行记录与一个或多个媒体生成子任务的关系';
CREATE UNIQUE INDEX uk_aigc_execution_task_ref_active
    ON aigc_execution_task_ref (execution_run_id, task_id, role) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_execution_task_ref_task ON aigc_execution_task_ref (task_id) WHERE deleted = FALSE;

CREATE TABLE aigc_object_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    object_id BIGINT NOT NULL REFERENCES aigc_project_object(id) ON DELETE RESTRICT,
    version_no INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    content_payload JSONB,
    document_version_id BIGINT,
    execution_run_id BIGINT REFERENCES aigc_execution_run(id) ON DELETE RESTRICT,
    summary VARCHAR(500),
    adopted_time TIMESTAMP(6),
    adopted_by BIGINT,
    superseded_by_version_id BIGINT REFERENCES aigc_object_version(id) ON DELETE RESTRICT,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_object_version IS '项目对象不可变候选与采用版本';
CREATE UNIQUE INDEX uk_aigc_object_version_no_active
    ON aigc_object_version (object_id, version_no) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_object_version_project ON aigc_object_version (project_id) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_object_version_status ON aigc_object_version (object_id, status) WHERE deleted = FALSE;
ALTER TABLE aigc_project_object
    ADD CONSTRAINT fk_aigc_project_object_adopted_version
    FOREIGN KEY (adopted_version_id) REFERENCES aigc_object_version(id) ON DELETE RESTRICT;

-- ============================================================
-- Media / MediaVersion：内部持久文件唯一身份链
-- ============================================================

CREATE TABLE aigc_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    name VARCHAR(200) NOT NULL,
    media_type VARCHAR(20) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_execution_run_id BIGINT REFERENCES aigc_execution_run(id) ON DELETE RESTRICT,
    source_task_id BIGINT REFERENCES aigc_task(id) ON DELETE RESTRICT,
    current_version_id BIGINT,
    original_project_id BIGINT REFERENCES aigc_project(id) ON DELETE RESTRICT,
    user_id BIGINT NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_media IS '全部上传或生成素材的稳定逻辑身份';
COMMENT ON COLUMN aigc_media.source_type IS 'UPLOAD/GENERATION/IMPORT/DERIVED/EXPORT';
CREATE INDEX idx_aigc_media_user_type ON aigc_media (user_id, media_type) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_media_project ON aigc_media (original_project_id) WHERE original_project_id IS NOT NULL AND deleted = FALSE;
CREATE INDEX idx_aigc_media_source_run ON aigc_media (source_execution_run_id) WHERE source_execution_run_id IS NOT NULL;

CREATE TABLE aigc_media_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    media_id BIGINT NOT NULL REFERENCES aigc_media(id) ON DELETE RESTRICT,
    version_no INTEGER NOT NULL,
    file_id BIGINT NOT NULL REFERENCES sys_file(id) ON DELETE RESTRICT,
    thumbnail_file_id BIGINT REFERENCES sys_file(id) ON DELETE RESTRICT,
    mime_type VARCHAR(200),
    size BIGINT,
    width INTEGER,
    height INTEGER,
    duration NUMERIC(12,3),
    frame_rate NUMERIC(8,3),
    generation_info JSONB,
    checksum VARCHAR(64),
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_media_version IS '不可变媒体文件版本，物理文件由 sys_file 持有';
COMMENT ON COLUMN aigc_media_version.file_id IS '主文件 sys_file.id；禁止以 URL 替代';
CREATE UNIQUE INDEX uk_aigc_media_version_no_active
    ON aigc_media_version (media_id, version_no) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_media_version_file ON aigc_media_version (file_id) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_media_version_thumbnail ON aigc_media_version (thumbnail_file_id)
    WHERE thumbnail_file_id IS NOT NULL AND deleted = FALSE;
ALTER TABLE aigc_media
    ADD CONSTRAINT fk_aigc_media_current_version
    FOREIGN KEY (current_version_id) REFERENCES aigc_media_version(id) ON DELETE RESTRICT;
ALTER TABLE aigc_task
    ADD CONSTRAINT fk_aigc_task_output_media_version
    FOREIGN KEY (output_media_version_id) REFERENCES aigc_media_version(id) ON DELETE RESTRICT;
ALTER TABLE aigc_project
    ADD CONSTRAINT fk_aigc_project_cover_media_version
    FOREIGN KEY (cover_media_version_id) REFERENCES aigc_media_version(id) ON DELETE RESTRICT;

CREATE TABLE aigc_brand_profile_media_ref (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_profile_version_id BIGINT NOT NULL REFERENCES aigc_brand_profile_version(id) ON DELETE RESTRICT,
    media_version_id BIGINT NOT NULL REFERENCES aigc_media_version(id) ON DELETE RESTRICT,
    role VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    delete_time TIMESTAMP(6)
);
COMMENT ON TABLE aigc_brand_profile_media_ref IS '品牌资料版本对媒体版本的引用';
CREATE UNIQUE INDEX uk_aigc_brand_profile_media_ref_active
    ON aigc_brand_profile_media_ref (brand_profile_version_id, media_version_id, role) WHERE deleted = FALSE;

CREATE TABLE aigc_brand_profile_document_ref (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_profile_version_id BIGINT NOT NULL REFERENCES aigc_brand_profile_version(id) ON DELETE RESTRICT,
    document_version_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    delete_time TIMESTAMP(6)
);
COMMENT ON TABLE aigc_brand_profile_document_ref IS '品牌资料版本对文档版本的稳定引用';
CREATE UNIQUE INDEX uk_aigc_brand_profile_document_ref_active
    ON aigc_brand_profile_document_ref (brand_profile_version_id, document_version_id, role) WHERE deleted = FALSE;

CREATE TABLE aigc_project_media_ref (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    object_id BIGINT REFERENCES aigc_project_object(id) ON DELETE RESTRICT,
    object_version_id BIGINT REFERENCES aigc_object_version(id) ON DELETE RESTRICT,
    media_version_id BIGINT NOT NULL REFERENCES aigc_media_version(id) ON DELETE RESTRICT,
    role VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    adoption_status VARCHAR(32) NOT NULL DEFAULT 'candidate',
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_project_media_ref IS '项目或项目对象对媒体版本的用途引用';
CREATE UNIQUE INDEX uk_aigc_project_media_ref_active
    ON aigc_project_media_ref (project_id, media_version_id, role, object_id) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_project_media_ref_object ON aigc_project_media_ref (object_id) WHERE object_id IS NOT NULL AND deleted = FALSE;

-- ============================================================
-- Asset：跨项目可复用登记，不复制 MediaVersion
-- ============================================================

CREATE TABLE aigc_asset_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    name VARCHAR(100) NOT NULL,
    parent_id BIGINT REFERENCES aigc_asset_category(id) ON DELETE RESTRICT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_asset_category IS '工作区资产分类树';
CREATE INDEX idx_aigc_asset_category_parent ON aigc_asset_category (workspace_id, parent_id) WHERE deleted = FALSE;

CREATE TABLE aigc_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    media_id BIGINT NOT NULL REFERENCES aigc_media(id) ON DELETE RESTRICT,
    category_id BIGINT REFERENCES aigc_asset_category(id) ON DELETE RESTRICT,
    scope VARCHAR(32) NOT NULL DEFAULT 'WORKSPACE',
    copyright_info JSONB,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    usage_count INTEGER NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_asset IS '允许跨项目复用的 Media 登记；不复制媒体文件';
CREATE UNIQUE INDEX uk_aigc_asset_media_active ON aigc_asset (media_id) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_asset_workspace_category ON aigc_asset (workspace_id, category_id) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_asset_user ON aigc_asset (user_id) WHERE deleted = FALSE;

CREATE TABLE aigc_asset_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    name VARCHAR(50) NOT NULL,
    color VARCHAR(20),
    usage_count INTEGER NOT NULL DEFAULT 0,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_asset_tag IS '工作区资产标签';
CREATE UNIQUE INDEX uk_aigc_asset_tag_name_active
    ON aigc_asset_tag (workspace_id, name) WHERE deleted = FALSE;

CREATE TABLE aigc_asset_tag_ref (
    asset_id BIGINT NOT NULL REFERENCES aigc_asset(id) ON DELETE RESTRICT,
    tag_id BIGINT NOT NULL REFERENCES aigc_asset_tag(id) ON DELETE RESTRICT,
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    delete_time TIMESTAMP(6),
    PRIMARY KEY (asset_id, tag_id)
);
COMMENT ON TABLE aigc_asset_tag_ref IS '资产与标签关系';
CREATE INDEX idx_aigc_asset_tag_ref_tag ON aigc_asset_tag_ref (tag_id) WHERE deleted = FALSE;

CREATE TABLE aigc_asset_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    source_media_id BIGINT NOT NULL REFERENCES aigc_media(id) ON DELETE RESTRICT,
    target_media_id BIGINT NOT NULL REFERENCES aigc_media(id) ON DELETE RESTRICT,
    relation_type VARCHAR(32) NOT NULL,
    process_params JSONB,
    execution_run_id BIGINT REFERENCES aigc_execution_run(id) ON DELETE RESTRICT,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_asset_relation IS '媒体变体、裁剪、转码、提取和放大等派生关系';
CREATE UNIQUE INDEX uk_aigc_asset_relation_active
    ON aigc_asset_relation (source_media_id, target_media_id, relation_type) WHERE deleted = FALSE;

CREATE TABLE aigc_asset_collection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    name VARCHAR(200) NOT NULL,
    collection_type VARCHAR(32),
    description VARCHAR(500),
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_asset_collection IS '品牌、角色、场景、产品或风格资产集合';
CREATE INDEX idx_aigc_asset_collection_workspace ON aigc_asset_collection (workspace_id) WHERE deleted = FALSE;

CREATE TABLE aigc_asset_collection_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id BIGINT NOT NULL REFERENCES aigc_asset_collection(id) ON DELETE RESTRICT,
    asset_id BIGINT NOT NULL REFERENCES aigc_asset(id) ON DELETE RESTRICT,
    role VARCHAR(32),
    sort_order INTEGER NOT NULL DEFAULT 0,
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    delete_time TIMESTAMP(6)
);
COMMENT ON TABLE aigc_asset_collection_item IS '资产集合成员';
CREATE UNIQUE INDEX uk_aigc_asset_collection_item_active
    ON aigc_asset_collection_item (collection_id, asset_id) WHERE deleted = FALSE;

-- ============================================================
-- Work 与发布：引用已采用对象版本，不复制文件
-- ============================================================

CREATE TABLE aigc_work (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    deliverable_object_id BIGINT NOT NULL REFERENCES aigc_project_object(id) ON DELETE RESTRICT,
    adopted_object_version_id BIGINT NOT NULL REFERENCES aigc_object_version(id) ON DELETE RESTRICT,
    title VARCHAR(300) NOT NULL,
    cover_media_version_id BIGINT REFERENCES aigc_media_version(id) ON DELETE RESTRICT,
    status VARCHAR(32) NOT NULL,
    visibility VARCHAR(32) NOT NULL DEFAULT 'PRIVATE',
    user_id BIGINT NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_work IS '作品库对已采用、发布或归档交付物的登记';
CREATE UNIQUE INDEX uk_aigc_work_deliverable_version_active
    ON aigc_work (deliverable_object_id, adopted_object_version_id) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_work_user_status ON aigc_work (user_id, status) WHERE deleted = FALSE;

CREATE TABLE aigc_work_publication (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    work_id BIGINT NOT NULL REFERENCES aigc_work(id) ON DELETE RESTRICT,
    channel_spec_version_id BIGINT NOT NULL REFERENCES aigc_channel_spec(id) ON DELETE RESTRICT,
    channel_code VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    external_id VARCHAR(200),
    external_url VARCHAR(1000),
    status VARCHAR(32) NOT NULL,
    scheduled_time TIMESTAMP(6),
    published_time TIMESTAMP(6),
    response_payload JSONB,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_work_publication IS '作品多渠道发布记录；external_url 仅表示外部平台地址';
CREATE INDEX idx_aigc_work_publication_work ON aigc_work_publication (work_id) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_work_publication_status ON aigc_work_publication (status, scheduled_time) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_work_publication_channel_spec
    ON aigc_work_publication (channel_spec_version_id) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_aigc_work_publication_idempotency_active
    ON aigc_work_publication (work_id, idempotency_key) WHERE deleted = FALSE;

-- ============================================================
-- 轻量视频时间线与 Storyboard 导出投影
-- ============================================================

CREATE TABLE aigc_timeline_composition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    deliverable_object_id BIGINT REFERENCES aigc_project_object(id) ON DELETE RESTRICT,
    title VARCHAR(200) NOT NULL,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    fps NUMERIC(8,3) NOT NULL DEFAULT 30,
    width INTEGER NOT NULL DEFAULT 1920,
    height INTEGER NOT NULL DEFAULT 1080,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    adopted_revision_no INTEGER,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_timeline_composition IS '视频交付物的轻量时间线组合';
CREATE INDEX idx_aigc_timeline_composition_project
    ON aigc_timeline_composition (project_id) WHERE deleted = FALSE;

CREATE TABLE aigc_timeline_track (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    composition_id BIGINT NOT NULL REFERENCES aigc_timeline_composition(id) ON DELETE RESTRICT,
    track_type VARCHAR(20) NOT NULL,
    name VARCHAR(100),
    sort_order INTEGER NOT NULL DEFAULT 0,
    muted BOOLEAN NOT NULL DEFAULT FALSE,
    locked BOOLEAN NOT NULL DEFAULT FALSE,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_timeline_track IS '视频、语音、音乐、字幕或叠加层轨道';
CREATE INDEX idx_aigc_timeline_track_composition
    ON aigc_timeline_track (composition_id, sort_order) WHERE deleted = FALSE;

CREATE TABLE aigc_timeline_clip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    track_id BIGINT NOT NULL REFERENCES aigc_timeline_track(id) ON DELETE RESTRICT,
    media_version_id BIGINT REFERENCES aigc_media_version(id) ON DELETE RESTRICT,
    source_object_id BIGINT REFERENCES aigc_project_object(id) ON DELETE RESTRICT,
    source_object_version_id BIGINT REFERENCES aigc_object_version(id) ON DELETE RESTRICT,
    position_ms BIGINT NOT NULL DEFAULT 0,
    in_ms BIGINT NOT NULL DEFAULT 0,
    out_ms BIGINT NOT NULL DEFAULT 0,
    properties JSONB,
    transition JSONB,
    volume NUMERIC(8,4),
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_timeline_clip IS '时间线片段；媒体片段引用不可变 MediaVersion';
CREATE INDEX idx_aigc_timeline_clip_track ON aigc_timeline_clip (track_id, position_ms) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_timeline_clip_media ON aigc_timeline_clip (media_version_id)
    WHERE media_version_id IS NOT NULL AND deleted = FALSE;

CREATE TABLE aigc_storyboard_export (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    project_id BIGINT NOT NULL REFERENCES aigc_project(id) ON DELETE RESTRICT,
    source_revision_no INTEGER NOT NULL,
    deliverable_object_id BIGINT REFERENCES aigc_project_object(id) ON DELETE RESTRICT,
    export_media_version_id BIGINT NOT NULL REFERENCES aigc_media_version(id) ON DELETE RESTRICT,
    export_format VARCHAR(32) NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_storyboard_export IS '由 Shot/ShotKeyframe 投影生成的只读故事板导出快照';
CREATE UNIQUE INDEX uk_aigc_storyboard_export_active
    ON aigc_storyboard_export (project_id, source_revision_no, export_format) WHERE deleted = FALSE;

-- ============================================================
-- 创作片段与原 AIGC 专业能力（保留但统一文件身份）
-- ============================================================

CREATE TABLE aigc_snippet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(64),
    content TEXT,
    reference_media_version_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    variable_slots JSONB,
    project_type_code VARCHAR(64),
    brand_profile_id BIGINT REFERENCES aigc_brand_profile(id) ON DELETE RESTRICT,
    use_count INTEGER NOT NULL DEFAULT 0,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE aigc_snippet IS '可复用轻量创作片段，参考文件使用媒体版本 ID';
CREATE INDEX idx_aigc_snippet_owner ON aigc_snippet (owner_id) WHERE deleted = FALSE;
CREATE INDEX idx_aigc_snippet_category_type ON aigc_snippet (category, project_type_code) WHERE deleted = FALSE;

CREATE TABLE batch_generation_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    user_id BIGINT NOT NULL,
    project_id BIGINT REFERENCES aigc_project(id) ON DELETE RESTRICT,
    execution_run_id BIGINT REFERENCES aigc_execution_run(id) ON DELETE RESTRICT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    total_count INTEGER NOT NULL DEFAULT 0,
    completed_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    params JSONB,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE batch_generation_task IS 'AIGC 批量生成任务协调记录';
CREATE INDEX idx_batch_generation_task_user ON batch_generation_task (user_id) WHERE deleted = FALSE;
CREATE INDEX idx_batch_generation_task_status ON batch_generation_task (status) WHERE deleted = FALSE;

CREATE TABLE generation_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(30) NOT NULL DEFAULT 'IMAGE_GEN',
    category VARCHAR(50),
    prompt TEXT NOT NULL,
    negative_prompt TEXT,
    model VARCHAR(100),
    width INTEGER,
    height INTEGER,
    steps INTEGER,
    seed BIGINT,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    usage_count INTEGER NOT NULL DEFAULT 0,
    scope VARCHAR(20) NOT NULL DEFAULT 'GENERATION',
    user_id BIGINT NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE generation_template IS 'AIGC 图像、视频与文案生成参数模板';
CREATE INDEX idx_generation_template_user ON generation_template (user_id) WHERE deleted = FALSE;
CREATE INDEX idx_generation_template_category ON generation_template (category) WHERE deleted = FALSE;
CREATE INDEX idx_generation_template_public ON generation_template (is_public) WHERE deleted = FALSE;
CREATE INDEX idx_generation_template_scope ON generation_template (scope) WHERE deleted = FALSE;

CREATE TABLE video_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(30) NOT NULL,
    params JSONB,
    preview_media_version_id BIGINT REFERENCES aigc_media_version(id) ON DELETE RESTRICT,
    thumbnail_media_version_id BIGINT REFERENCES aigc_media_version(id) ON DELETE RESTRICT,
    user_id BIGINT,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE video_template IS 'AIGC 视频模板；预览与缩略图引用媒体版本';
CREATE INDEX idx_video_template_type ON video_template (type) WHERE deleted = FALSE;

CREATE TABLE generation_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    user_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    prompt TEXT,
    model VARCHAR(100),
    params JSONB,
    execution_run_id BIGINT REFERENCES aigc_execution_run(id) ON DELETE RESTRICT,
    task_id BIGINT REFERENCES aigc_task(id) ON DELETE RESTRICT,
    media_version_id BIGINT REFERENCES aigc_media_version(id) ON DELETE RESTRICT,
    session_id BIGINT,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE generation_history IS 'AIGC 生成历史查询投影，不保存内部文件 URL';
CREATE INDEX idx_generation_history_user ON generation_history (user_id, create_time DESC) WHERE deleted = FALSE;
CREATE INDEX idx_generation_history_session ON generation_history (session_id) WHERE session_id IS NOT NULL;

CREATE TABLE ai_cloned_voice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    voice VARCHAR(200) NOT NULL,
    preferred_name VARCHAR(64) NOT NULL,
    target_model VARCHAR(100) NOT NULL,
    source_media_version_id BIGINT REFERENCES aigc_media_version(id) ON DELETE RESTRICT,
    sample_audio_media_version_id BIGINT REFERENCES aigc_media_version(id) ON DELETE RESTRICT,
    user_id BIGINT NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE ai_cloned_voice IS '用户克隆音色元数据，原始与样例音频引用媒体版本';
CREATE INDEX idx_ai_cloned_voice_user ON ai_cloned_voice (user_id) WHERE deleted = FALSE;
CREATE INDEX idx_ai_cloned_voice_voice ON ai_cloned_voice (voice) WHERE deleted = FALSE;

CREATE TABLE ai_digital_avatar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    name VARCHAR(100) NOT NULL,
    image_media_version_id BIGINT NOT NULL REFERENCES aigc_media_version(id) ON DELETE RESTRICT,
    source_media_version_id BIGINT REFERENCES aigc_media_version(id) ON DELETE RESTRICT,
    detect_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    detect_reason VARCHAR(500),
    default_voice VARCHAR(200),
    user_id BIGINT NOT NULL,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark VARCHAR(255)
);
COMMENT ON TABLE ai_digital_avatar IS '数字人形象与检测状态，形象文件引用媒体版本';
CREATE INDEX idx_ai_digital_avatar_user ON ai_digital_avatar (user_id) WHERE deleted = FALSE;
CREATE INDEX idx_ai_digital_avatar_detect_status ON ai_digital_avatar (detect_status) WHERE deleted = FALSE;

-- ============================================================
-- 保留的 User Studio 通用能力（不再含项目模板/项目资源双模型）
-- ============================================================

CREATE TABLE user_favorite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    user_id BIGINT NOT NULL,
    target_type VARCHAR(20) NOT NULL,
    target_id BIGINT NOT NULL,
    note VARCHAR(500),
    sort_order INTEGER NOT NULL DEFAULT 0,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark TEXT,
    CONSTRAINT uq_user_favorite_target UNIQUE (user_id, target_type, target_id)
);
COMMENT ON TABLE user_favorite IS '用户跨资源收藏夹';
CREATE INDEX idx_user_favorite_user_type ON user_favorite (user_id, target_type) WHERE deleted = FALSE;

CREATE TABLE user_workflow_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    cover_media_version_id BIGINT REFERENCES aigc_media_version(id) ON DELETE RESTRICT,
    category VARCHAR(50) NOT NULL,
    template_config JSONB,
    is_official BOOLEAN NOT NULL DEFAULT FALSE,
    usage_count INTEGER NOT NULL DEFAULT 0,
    user_id BIGINT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark TEXT
);
COMMENT ON TABLE user_workflow_template IS '用户工作流模板；封面引用媒体版本';
CREATE UNIQUE INDEX uk_user_workflow_template_code_active
    ON user_workflow_template (code) WHERE deleted = FALSE;
CREATE INDEX idx_user_workflow_template_category ON user_workflow_template (category) WHERE deleted = FALSE;

CREATE TABLE user_growth_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    icon VARCHAR(50),
    category VARCHAR(30) NOT NULL DEFAULT 'ONBOARDING',
    trigger_event VARCHAR(100),
    target_count INTEGER NOT NULL DEFAULT 1,
    reward_credits BIGINT NOT NULL DEFAULT 0,
    reward_outfit VARCHAR(100),
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark TEXT
);
COMMENT ON TABLE user_growth_task IS '用户成长任务定义';
CREATE UNIQUE INDEX uk_user_growth_task_code_active ON user_growth_task (code) WHERE deleted = FALSE;
CREATE INDEX idx_user_growth_task_category ON user_growth_task (category) WHERE deleted = FALSE;

CREATE TABLE user_growth_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    org_id BIGINT,
    workspace_id BIGINT,
    user_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL REFERENCES user_growth_task(id) ON DELETE RESTRICT,
    progress INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    completed_time TIMESTAMP(6),
    claimed_time TIMESTAMP(6),
    owner_id BIGINT,
    create_by BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    remark TEXT,
    CONSTRAINT uq_user_growth_progress UNIQUE (user_id, task_id)
);
COMMENT ON TABLE user_growth_progress IS '用户成长任务进度';
CREATE INDEX idx_user_growth_progress_user ON user_growth_progress (user_id) WHERE deleted = FALSE;
