-- ============================================================
-- AIGC 完整 Schema
-- 素材库 + 素材元素 + 创作项目 + 内容产出 + 剪辑时间轴
-- ============================================================

-- ============================================================
-- 素材库
-- ============================================================

CREATE TABLE media_asset (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(200)   NOT NULL,
    type              VARCHAR(20)    NOT NULL,
    url               VARCHAR(1000)  NOT NULL,
    thumbnail_url     VARCHAR(1000),
    size              BIGINT,
    width             INTEGER,
    height            INTEGER,
    duration          NUMERIC(10,2),
    generation_params JSONB,
    tags              VARCHAR(500),
    category_id       BIGINT,
    element_id        BIGINT,
    project_id        BIGINT,
    source_type       VARCHAR(30),
    source_id         BIGINT,
    ai_generated      BOOLEAN        NOT NULL DEFAULT FALSE,
    model_name        VARCHAR(100),
    provider_code     VARCHAR(64),
    user_id           BIGINT         NOT NULL,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE media_asset IS 'AIGC 素材库';
COMMENT ON COLUMN media_asset.name IS '素材名称';
COMMENT ON COLUMN media_asset.type IS '素材类型：IMAGE/VIDEO/AUDIO/MODEL_3D/TEXT';
COMMENT ON COLUMN media_asset.url IS '素材访问 URL';
COMMENT ON COLUMN media_asset.thumbnail_url IS '缩略图 URL';
COMMENT ON COLUMN media_asset.size IS '文件大小（字节）';
COMMENT ON COLUMN media_asset.width IS '宽度（像素），图片/视频适用';
COMMENT ON COLUMN media_asset.height IS '高度（像素），图片/视频适用';
COMMENT ON COLUMN media_asset.duration IS '时长（秒），音视频适用';
COMMENT ON COLUMN media_asset.generation_params IS 'AI 生成参数（prompt、模型等）';
COMMENT ON COLUMN media_asset.tags IS '标签，逗号分隔（冗余字段，详细关系见 media_asset_tag）';
COMMENT ON COLUMN media_asset.category_id IS '所属分类 ID';
COMMENT ON COLUMN media_asset.element_id IS '所属元素 ID，NULL 表示未分组';
COMMENT ON COLUMN media_asset.project_id IS '归属创作项目';
COMMENT ON COLUMN media_asset.source_type IS '来源类型：TIMELINE/SHOT/UPLOAD/GENERATION';
COMMENT ON COLUMN media_asset.source_id IS '来源 ID（对应 source_type 的主键）';
COMMENT ON COLUMN media_asset.user_id IS '上传/生成该素材的用户 ID';

CREATE INDEX idx_media_asset_user_id  ON media_asset (user_id);
CREATE INDEX idx_media_asset_type     ON media_asset (user_id, type);
CREATE INDEX idx_media_asset_category ON media_asset (category_id);
CREATE INDEX idx_media_asset_element  ON media_asset (element_id);
CREATE INDEX idx_media_asset_project  ON media_asset (project_id);

-- 素材分类（多级树形）
CREATE TABLE media_category (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(100)   NOT NULL,
    parent_id         BIGINT,
    sort_order        INTEGER        NOT NULL DEFAULT 0,
    user_id           BIGINT,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE media_category IS '素材分类（多级树形）';
COMMENT ON COLUMN media_category.name IS '分类名称';
COMMENT ON COLUMN media_category.parent_id IS '父分类 ID，NULL 表示根分类';
COMMENT ON COLUMN media_category.sort_order IS '同级排序权重，值越小越靠前';
COMMENT ON COLUMN media_category.user_id IS '所属用户，NULL 表示全局公共分类';
CREATE INDEX idx_media_category_parent ON media_category (parent_id);

-- 素材标签
CREATE TABLE media_tag (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(50)    NOT NULL,
    color             VARCHAR(20),
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE media_tag IS '素材标签';
COMMENT ON COLUMN media_tag.name IS '标签名称';
COMMENT ON COLUMN media_tag.color IS '标签颜色，十六进制色值，如 #FF5733';

CREATE TABLE media_asset_tag (
    asset_id          BIGINT         NOT NULL,
    tag_id            BIGINT         NOT NULL,
    PRIMARY KEY (asset_id, tag_id)
);

COMMENT ON TABLE media_asset_tag IS '素材-标签关联';
COMMENT ON COLUMN media_asset_tag.asset_id IS '素材 ID';
COMMENT ON COLUMN media_asset_tag.tag_id IS '标签 ID';
CREATE INDEX idx_media_asset_tag_asset ON media_asset_tag (asset_id);
CREATE INDEX idx_media_asset_tag_tag   ON media_asset_tag (tag_id);

-- 素材变体
CREATE TABLE media_asset_variant (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    original_asset_id BIGINT         NOT NULL,
    variant_asset_id  BIGINT         NOT NULL,
    params_diff       JSONB,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE media_asset_variant IS '素材变体关联';
COMMENT ON COLUMN media_asset_variant.original_asset_id IS '原始素材 ID';
COMMENT ON COLUMN media_asset_variant.variant_asset_id IS '变体素材 ID';
COMMENT ON COLUMN media_asset_variant.params_diff IS '与原始素材的生成参数差异（JSONB）';
CREATE INDEX idx_media_variant_original ON media_asset_variant (original_asset_id);
CREATE INDEX idx_media_variant_variant  ON media_asset_variant (variant_asset_id);

-- 批量生成任务
CREATE TABLE batch_generation_task (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    user_id           BIGINT         NOT NULL,
    status            VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    total_count       INTEGER        NOT NULL DEFAULT 0,
    completed_count   INTEGER        NOT NULL DEFAULT 0,
    failed_count      INTEGER        NOT NULL DEFAULT 0,
    params            JSONB,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE batch_generation_task IS 'AIGC 批量生成任务';
COMMENT ON COLUMN batch_generation_task.user_id IS '发起批量任务的用户 ID';
COMMENT ON COLUMN batch_generation_task.status IS '任务状态：PENDING/PROCESSING/SUCCESS/PARTIAL_FAILED/FAILED';
COMMENT ON COLUMN batch_generation_task.total_count IS '总子任务数量';
COMMENT ON COLUMN batch_generation_task.completed_count IS '已完成子任务数量';
COMMENT ON COLUMN batch_generation_task.failed_count IS '失败子任务数量';
COMMENT ON COLUMN batch_generation_task.params IS '批量生成参数（prompt、模型、尺寸等，JSONB）';
CREATE INDEX idx_batch_task_user   ON batch_generation_task (user_id);
CREATE INDEX idx_batch_task_status ON batch_generation_task (status);

-- 生成参数模板
CREATE TABLE generation_template (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(100)   NOT NULL,
    type              VARCHAR(30)    NOT NULL DEFAULT 'IMAGE',
    category          VARCHAR(50),
    prompt            TEXT           NOT NULL,
    negative_prompt   TEXT,
    model             VARCHAR(100),
    width             INTEGER,
    height            INTEGER,
    steps             INTEGER,
    seed              BIGINT,
    is_public         BOOLEAN        NOT NULL DEFAULT FALSE,
    usage_count       INTEGER        NOT NULL DEFAULT 0,
    scope             VARCHAR(20)    NOT NULL DEFAULT 'GENERATION',
    user_id           BIGINT         NOT NULL,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE generation_template IS 'AIGC 生成参数模板';
COMMENT ON COLUMN generation_template.name IS '模板名称';
COMMENT ON COLUMN generation_template.category IS '模板分类，如 portrait/landscape/anime';
COMMENT ON COLUMN generation_template.prompt IS '正向提示词';
COMMENT ON COLUMN generation_template.negative_prompt IS '负向提示词';
COMMENT ON COLUMN generation_template.model IS '默认使用的模型名称';
COMMENT ON COLUMN generation_template.width IS '默认生成宽度（像素）';
COMMENT ON COLUMN generation_template.height IS '默认生成高度（像素）';
COMMENT ON COLUMN generation_template.steps IS '默认推理步数';
COMMENT ON COLUMN generation_template.seed IS '随机种子，-1 表示随机';
COMMENT ON COLUMN generation_template.is_public IS '是否公开，true 表示全用户可见';
COMMENT ON COLUMN generation_template.usage_count IS '被使用次数';
COMMENT ON COLUMN generation_template.user_id IS '创建者用户 ID';
COMMENT ON COLUMN generation_template.scope IS '使用场景：GENERATION=单次生成面板，PROJECT=项目级提示词';
CREATE INDEX idx_gen_template_user     ON generation_template (user_id);
CREATE INDEX idx_gen_template_category ON generation_template (category);
CREATE INDEX idx_gen_template_public   ON generation_template (is_public);
CREATE INDEX idx_gen_template_scope    ON generation_template (scope);

-- 视频模板
CREATE TABLE video_template (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(100)   NOT NULL,
    type              VARCHAR(30)    NOT NULL,
    params            TEXT,
    preview_url       VARCHAR(500),
    thumbnail_url     VARCHAR(500),
    user_id           BIGINT,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE video_template IS 'AIGC 视频模板';
COMMENT ON COLUMN video_template.name IS '模板名称';
COMMENT ON COLUMN video_template.type IS '模板类型，如 INTRO/OUTRO/TRANSITION/FULL';
COMMENT ON COLUMN video_template.params IS '模板参数配置（JSON/DSL 字符串）';
COMMENT ON COLUMN video_template.preview_url IS '预览视频 URL';
COMMENT ON COLUMN video_template.thumbnail_url IS '封面缩略图 URL';
COMMENT ON COLUMN video_template.user_id IS '创建者用户 ID，NULL 表示系统内置模板';
CREATE INDEX idx_video_template_type ON video_template (type);

-- 生成历史
CREATE TABLE generation_history (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    user_id           BIGINT         NOT NULL,
    type              VARCHAR(20)    NOT NULL,
    prompt            TEXT,
    model             VARCHAR(100),
    params            TEXT,
    result_url        VARCHAR(500),
    asset_id          BIGINT,
    session_id        BIGINT,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE generation_history IS 'AIGC 生成历史记录';
COMMENT ON COLUMN generation_history.user_id IS '发起生成的用户 ID';
COMMENT ON COLUMN generation_history.type IS '生成类型：IMAGE/VIDEO/MODEL_3D';
COMMENT ON COLUMN generation_history.prompt IS '生成提示词';
COMMENT ON COLUMN generation_history.model IS '使用的模型名称';
COMMENT ON COLUMN generation_history.params IS '完整生成参数快照（JSON 字符串）';
COMMENT ON COLUMN generation_history.result_url IS '生成结果 URL';
COMMENT ON COLUMN generation_history.asset_id IS '保存后关联的 media_asset ID，未保存则为 NULL';
COMMENT ON COLUMN generation_history.session_id IS '所属对话会话 ID，NULL 表示非对话触发';
CREATE INDEX idx_gen_history_user    ON generation_history (user_id);
CREATE INDEX idx_gen_history_type    ON generation_history (user_id, type);
CREATE INDEX idx_gen_history_session ON generation_history (session_id);

-- AIGC 统一任务表
CREATE TABLE aigc_task (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    user_id           BIGINT         NOT NULL,
    type              VARCHAR(20)    NOT NULL,
    status            VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    provider          VARCHAR(50),
    model             VARCHAR(100),
    model_name        VARCHAR(100),
    prompt            TEXT,
    params            JSONB,
    task_id           TEXT,
    result_url        TEXT,
    oss_url           TEXT,
    error_msg         TEXT,
    asset_id          BIGINT,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE aigc_task IS 'AIGC 统一异步任务（IMAGE/VIDEO/MODEL_3D）';
COMMENT ON COLUMN aigc_task.user_id IS '发起任务的用户 ID';
COMMENT ON COLUMN aigc_task.type IS '任务类型：IMAGE/VIDEO/MODEL_3D';
COMMENT ON COLUMN aigc_task.status IS '任务状态：PENDING/PROCESSING/SUCCESS/FAILED';
COMMENT ON COLUMN aigc_task.provider IS '第三方服务商标识，如 ALIYUN/STABILITY/OPENAI';
COMMENT ON COLUMN aigc_task.model IS '调用的模型名称，如 wanx-v1/stable-diffusion-xl';
COMMENT ON COLUMN aigc_task.prompt IS '生成提示词';
COMMENT ON COLUMN aigc_task.params IS '扩展生成参数（负向提示词、尺寸、步数、seed 等）';
COMMENT ON COLUMN aigc_task.task_id IS '第三方服务商返回的异步任务 ID，用于轮询查询生成结果';
COMMENT ON COLUMN aigc_task.result_url IS '第三方服务商返回的原始结果 URL';
COMMENT ON COLUMN aigc_task.oss_url IS '转存至自有 OSS 后的访问 URL';
COMMENT ON COLUMN aigc_task.error_msg IS '失败时的错误信息';
COMMENT ON COLUMN aigc_task.asset_id IS '生成完成后关联的 media_asset ID';
CREATE INDEX idx_aigc_task_user_id ON aigc_task (user_id);
CREATE INDEX idx_aigc_task_status  ON aigc_task (status);

-- ============================================================
-- 素材元素分组（角色/场景/道具等主题）
-- ============================================================

CREATE TABLE media_element (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(200)   NOT NULL,
    description       VARCHAR(500),
    cover_url         VARCHAR(1000),
    project_id        BIGINT,
    user_id           BIGINT         NOT NULL,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE media_element IS '素材元素分组（角色/场景/道具等主题）';
COMMENT ON COLUMN media_element.name IS '元素名称，如"林贝"、"咖啡厅场景"';
COMMENT ON COLUMN media_element.description IS '元素描述';
COMMENT ON COLUMN media_element.cover_url IS '封面图 URL';
COMMENT ON COLUMN media_element.user_id IS '所属用户 ID';
COMMENT ON COLUMN media_element.project_id IS '归属创作项目';
CREATE INDEX idx_media_element_user_id ON media_element (user_id);
CREATE INDEX idx_media_element_project ON media_element (project_id);

-- ============================================================
-- 创作项目
-- ============================================================

CREATE TABLE aigc_project (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    name              VARCHAR(200)   NOT NULL,
    cover_url         VARCHAR(1000),
    description       VARCHAR(500),
    type              VARCHAR(30)    NOT NULL DEFAULT 'MIXED',
    status            VARCHAR(20)    NOT NULL DEFAULT 'DRAFT',
    user_id           BIGINT         NOT NULL,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE aigc_project IS 'AIGC 创作项目';
COMMENT ON COLUMN aigc_project.name IS '项目名称';
COMMENT ON COLUMN aigc_project.cover_url IS '项目封面图 URL';
COMMENT ON COLUMN aigc_project.description IS '项目描述';
COMMENT ON COLUMN aigc_project.type IS '项目类型：VIDEO_DRAMA/IMAGE_POST/SHORT_VIDEO/MIXED';
COMMENT ON COLUMN aigc_project.status IS '项目状态：DRAFT/IN_PROGRESS/COMPLETED/ARCHIVED';
COMMENT ON COLUMN aigc_project.user_id IS '项目所有者用户 ID';
CREATE INDEX idx_aigc_project_user ON aigc_project (user_id);

-- ============================================================
-- 分镜规划（project 1:1，视频创作前期规划）
-- ============================================================

CREATE TABLE aigc_storyboard (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    project_id        BIGINT         NOT NULL,
    title             VARCHAR(200),
    status            VARCHAR(20)    NOT NULL DEFAULT 'DRAFT',
    doc_id            BIGINT,
    user_id           BIGINT         NOT NULL,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE aigc_storyboard IS '分镜规划（project 1:N，支持多版本）';
COMMENT ON COLUMN aigc_storyboard.project_id IS '归属创作项目 ID';
COMMENT ON COLUMN aigc_storyboard.title IS '分镜规划标题';
COMMENT ON COLUMN aigc_storyboard.status IS '状态：DRAFT/REVIEWING/APPROVED';
COMMENT ON COLUMN aigc_storyboard.doc_id IS '关联脚本文档（doc_document type=aigc_script）';
COMMENT ON COLUMN aigc_storyboard.user_id IS '创建者用户 ID';
CREATE INDEX idx_aigc_storyboard_project ON aigc_storyboard (project_id);

-- ============================================================
-- 内容产出（project 1:N，最终发布内容）
-- ============================================================

CREATE TABLE aigc_content (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    project_id        BIGINT         NOT NULL,
    type              VARCHAR(30)    NOT NULL,
    title             VARCHAR(200),
    doc_id            BIGINT,
    asset_ids         JSONB,
    platform          VARCHAR(50),
    publish_status    VARCHAR(20)    NOT NULL DEFAULT 'DRAFT',
    publish_time      TIMESTAMP(6),
    user_id           BIGINT         NOT NULL,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE aigc_content IS 'AIGC 内容产出（project 1:N）';
COMMENT ON COLUMN aigc_content.project_id IS '归属创作项目 ID';
COMMENT ON COLUMN aigc_content.type IS '内容类型：SHORT_VIDEO/IMAGE_POST/RICH_TEXT';
COMMENT ON COLUMN aigc_content.title IS '内容标题';
COMMENT ON COLUMN aigc_content.doc_id IS '委托 doc_document 存储正文（M2O）';
COMMENT ON COLUMN aigc_content.asset_ids IS '关联素材 ID 列表（冗余，详细关系见 aigc_content_asset）';
COMMENT ON COLUMN aigc_content.platform IS '发布目标平台：WECHAT/DOUYIN/XIAOHONGSHU/BILIBILI';
COMMENT ON COLUMN aigc_content.publish_status IS '发布状态：DRAFT/REVIEWING/PUBLISHED/FAILED';
COMMENT ON COLUMN aigc_content.publish_time IS '实际发布时间';
COMMENT ON COLUMN aigc_content.user_id IS '创建者用户 ID';
CREATE INDEX idx_aigc_content_project ON aigc_content (project_id);
CREATE INDEX idx_aigc_content_doc     ON aigc_content (doc_id);

-- 内容-素材关联（M2M，区分封面/正片/BGM 等角色）
CREATE TABLE aigc_content_asset (
    content_id BIGINT      NOT NULL,
    asset_id   BIGINT      NOT NULL,
    role       VARCHAR(20) NOT NULL DEFAULT 'MAIN',
    PRIMARY KEY (content_id, asset_id)
);

COMMENT ON TABLE aigc_content_asset IS '内容-素材关联';
COMMENT ON COLUMN aigc_content_asset.role IS '素材角色：MAIN/COVER/BGM/SUBTITLE';
CREATE INDEX idx_aigc_content_asset_content ON aigc_content_asset (content_id);
CREATE INDEX idx_aigc_content_asset_asset   ON aigc_content_asset (asset_id);

-- ============================================================
-- 视频剪辑时间轴
-- ============================================================

CREATE TABLE aigc_timeline (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    project_id        BIGINT         NOT NULL,
    storyboard_id     BIGINT,
    title             VARCHAR(200),
    status            VARCHAR(20)    NOT NULL DEFAULT 'DRAFT',
    duration_ms       BIGINT         NOT NULL DEFAULT 0,
    fps               SMALLINT       NOT NULL DEFAULT 30,
    resolution        VARCHAR(20)    NOT NULL DEFAULT '1920x1080',
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE aigc_timeline IS '视频剪辑时间轴（project 1:N，支持多版本：正片/预告/花絮）';
COMMENT ON COLUMN aigc_timeline.project_id IS '归属创作项目 ID';
COMMENT ON COLUMN aigc_timeline.storyboard_id IS '来源分镜规划 ID，NULL 表示手动创建';
COMMENT ON COLUMN aigc_timeline.title IS '时间轴标题，如"正片"、"预告片"';
COMMENT ON COLUMN aigc_timeline.status IS '状态：DRAFT/EXPORTING/EXPORTED';
COMMENT ON COLUMN aigc_timeline.duration_ms IS '总时长（毫秒）';
COMMENT ON COLUMN aigc_timeline.fps IS '帧率，默认 30';
COMMENT ON COLUMN aigc_timeline.resolution IS '分辨率，格式 WxH，如 1920x1080';
CREATE INDEX idx_aigc_timeline_project ON aigc_timeline (project_id);

CREATE TABLE aigc_track (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    timeline_id       BIGINT         NOT NULL,
    type              VARCHAR(20)    NOT NULL,
    sort_order        INTEGER        NOT NULL DEFAULT 0,
    muted             BOOLEAN        NOT NULL DEFAULT FALSE,
    locked            BOOLEAN        NOT NULL DEFAULT FALSE,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE aigc_track IS '时间轴轨道';
COMMENT ON COLUMN aigc_track.timeline_id IS '所属时间轴 ID';
COMMENT ON COLUMN aigc_track.type IS '轨道类型：VIDEO/AUDIO/SUBTITLE/STICKER';
COMMENT ON COLUMN aigc_track.sort_order IS '轨道排列顺序，值越小越靠前（上层）';
COMMENT ON COLUMN aigc_track.muted IS '是否静音，仅音频轨道有效';
COMMENT ON COLUMN aigc_track.locked IS '是否锁定，锁定后不可编辑';
CREATE INDEX idx_aigc_track_timeline ON aigc_track (timeline_id);

CREATE TABLE aigc_clip (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    track_id          BIGINT         NOT NULL,
    asset_id          BIGINT,
    shot_id           BIGINT,
    position_ms       BIGINT         NOT NULL DEFAULT 0,
    in_ms             BIGINT         NOT NULL DEFAULT 0,
    out_ms            BIGINT         NOT NULL DEFAULT 0,
    properties        JSONB,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE aigc_clip IS '时间轴片段';
COMMENT ON COLUMN aigc_clip.track_id IS '所属轨道 ID';
COMMENT ON COLUMN aigc_clip.asset_id IS '引用的素材 ID，NULL 表示纯文字/贴纸片段';
COMMENT ON COLUMN aigc_clip.shot_id IS '来源分镜 ID，NULL 表示手动添加的片段';
COMMENT ON COLUMN aigc_clip.position_ms IS '在轨道上的起始位置（毫秒）';
COMMENT ON COLUMN aigc_clip.in_ms IS '素材入点（毫秒）';
COMMENT ON COLUMN aigc_clip.out_ms IS '素材出点（毫秒）';
COMMENT ON COLUMN aigc_clip.properties IS '扩展属性：speed/volume/filter/text 等';
CREATE INDEX idx_aigc_clip_track ON aigc_clip (track_id);
CREATE INDEX idx_aigc_clip_asset ON aigc_clip (asset_id);
CREATE INDEX idx_aigc_clip_shot  ON aigc_clip (shot_id) WHERE shot_id IS NOT NULL;


-- ============================================================
-- 分镜（挂在 aigc_content type=STORYBOARD 下，创作前期规划）
-- ============================================================

CREATE TABLE aigc_shot (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    storyboard_id     BIGINT         NOT NULL,
    shot_no           INTEGER        NOT NULL,
    name              VARCHAR(200),
    description       TEXT,
    dialogue          TEXT,
    properties        JSONB,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE aigc_shot IS '分镜（归属 aigc_storyboard）';
COMMENT ON COLUMN aigc_shot.storyboard_id IS '归属分镜规划 ID';
COMMENT ON COLUMN aigc_shot.shot_no IS '镜号（排序）';
COMMENT ON COLUMN aigc_shot.name IS '镜头名称，如 Shot_LinBei_Entrance';
COMMENT ON COLUMN aigc_shot.description IS '镜头描述，支持实体引用标记 @[名称](类型:ID)，类型：e=元素/s=镜头/a=素材，示例：@[江澄](e:5) 坐在靠窗位';
COMMENT ON COLUMN aigc_shot.dialogue IS '台词/旁白';
COMMENT ON COLUMN aigc_shot.properties IS '扩展属性：景别/运镜/情绪/滤镜等';
CREATE INDEX idx_aigc_shot_content ON aigc_shot (storyboard_id, shot_no);

-- 分镜-素材关联（M2M，一个分镜对应多个素材：最终视频/音频/参考图）
CREATE TABLE aigc_shot_asset (
    shot_id    BIGINT      NOT NULL,
    asset_id   BIGINT      NOT NULL,
    role       VARCHAR(20) NOT NULL DEFAULT 'FINAL_VIDEO',
    PRIMARY KEY (shot_id, asset_id)
);

COMMENT ON TABLE aigc_shot_asset IS '分镜-素材关联';
COMMENT ON COLUMN aigc_shot_asset.role IS '素材角色：FINAL_VIDEO/FINAL_AUDIO/REFERENCE';
CREATE INDEX idx_aigc_shot_asset_shot  ON aigc_shot_asset (shot_id);
CREATE INDEX idx_aigc_shot_asset_asset ON aigc_shot_asset (asset_id);


-- ============================================================
-- ai_model 图像生成能力配置（image_config）
-- ============================================================
-- wan2.7-image（支持文生图和图像编辑，size 用档位 1K/2K，最多9张输入图）
UPDATE ai_model SET image_config = '{
  "mode": "fixed",
  "sizes": [],
  "generate": {
    "maxImages": 4,
    "sizePresets": ["1K","2K"],
    "seed": true
  },
  "edit": {
    "maxInputImages": 9,
    "maxImages": 4,
    "sizePresets": ["1K","2K"],
    "seed": true
  }
}' WHERE model_id = 'qwen:wan2.7-image';

-- qwen-image-2.0（fixed 模式，生成和编辑参数相同，编辑支持最多3张参考图）
UPDATE ai_model SET image_config = '{
  "mode": "fixed",
  "sizes": [[2688,1536],[2368,1728],[2048,2048],[1728,2368],[1536,2688]],
  "generate": {"maxImages": 6, "seed": true, "promptExtend": true, "negativePrompt": true},
  "edit":     {"maxInputImages": 3, "maxImages": 6, "seed": true, "promptExtend": true, "negativePrompt": true}
}' WHERE model_id = 'qwen:qwen-image-2';

-- gpt-image-2（文生图/编辑都支持 quality/format/background/moderation，编辑多了 maxInputImages=16）
UPDATE ai_model SET image_config = '{
  "mode": "fixed",
  "sizes": [[1024,1024],[1536,1024],[1024,1536],[2048,2048],[2048,1152],[3840,2160],[2160,3840]],
  "generate": {
    "maxImages": 10,
    "quality": ["auto","low","medium","high"],
    "format": ["png","jpeg","webp"],
    "background": ["auto","transparent","opaque"],
    "contentModeration": ["auto","low"]
  },
  "edit": {
    "maxInputImages": 16,
    "maxImages": 10,
    "quality": ["auto","low","medium","high"],
    "format": ["png","jpeg","webp"],
    "background": ["auto","transparent","opaque"],
    "contentModeration": ["auto","low"]
  }
}' WHERE model_id = 'n1n:gpt-image-2';

-- gemini-3.1-flash-image-preview（支持 14 张参考图，比例完整，档位 512/1K/2K/4K）
UPDATE ai_model SET image_config = '{
  "mode": "ratio",
  "sizes": {
    "1:1": [], "1:4": [], "1:8": [], "2:3": [], "3:2": [],
    "3:4": [], "4:1": [], "4:3": [], "4:5": [], "5:4": [],
    "8:1": [], "9:16": [], "16:9": [], "21:9": []
  },
  "generate": {
    "maxImages": 1,
    "sizePresets": ["512","1K","2K","4K"]
  },
  "edit": {
    "maxInputImages": 14,
    "maxImages": 1,
    "sizePresets": ["512","1K","2K","4K"]
  }
}' WHERE model_id = 'n1n:gemini-3.1-flash-image-preview';

-- gemini-3-pro-image-preview（支持 14 张参考图，比例不含极端比，档位 1K/2K/4K）
UPDATE ai_model SET image_config = '{
  "mode": "ratio",
  "sizes": {
    "1:1": [], "2:3": [], "3:2": [], "3:4": [],
    "4:3": [], "4:5": [], "5:4": [], "9:16": [], "16:9": [], "21:9": []
  },
  "generate": {
    "maxImages": 1,
    "sizePresets": ["1K","2K","4K"]
  },
  "edit": {
    "maxInputImages": 14,
    "maxImages": 1,
    "sizePresets": ["1K","2K","4K"]
  }
}' WHERE model_id = 'n1n:gemini-3-pro-image-preview';

-- ============================================================
-- 素材组（每次生成任务自动建组，组内含一张或多张素材）
-- ============================================================

CREATE TABLE media_asset_group (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER        NOT NULL DEFAULT 0,
    name              VARCHAR(200)   NOT NULL,
    cover_url         VARCHAR(1000),
    asset_count       INTEGER        NOT NULL DEFAULT 0,
    user_id           BIGINT         NOT NULL,
    create_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           BOOLEAN        NOT NULL DEFAULT FALSE
);

COMMENT ON TABLE  media_asset_group            IS '素材组——每次生成任务对应一个组';
COMMENT ON COLUMN media_asset_group.name       IS '组名，默认由 prompt 截取或文件名生成';
COMMENT ON COLUMN media_asset_group.cover_url  IS '封面图，取组内第一张素材 URL';
COMMENT ON COLUMN media_asset_group.asset_count IS '组内素材数量（冗余，便于列表展示）';
COMMENT ON COLUMN media_asset_group.user_id    IS '所属用户';
CREATE INDEX idx_media_asset_group_user ON media_asset_group (user_id);

-- media_asset 加 group_id 列
ALTER TABLE media_asset ADD COLUMN IF NOT EXISTS group_id BIGINT;
COMMENT ON COLUMN media_asset.group_id IS '所属素材组 ID，NULL 表示未分组';
CREATE INDEX idx_media_asset_group_id ON media_asset (group_id);

-- doubao-seedream-5-0（支持 2K/4K 档位或固定尺寸，n=1-4，output_format）
UPDATE ai_model SET image_config = '{
  "mode": "fixed",
  "sizes": [[1024,1024],[1536,1024],[1024,1536],[2048,2048],[2048,1152],[1152,2048]],
  "generate": {
    "maxImages": 4,
    "format": ["jpeg","png"]
  }
}' WHERE model_id = 'n1n:doubao-seedream-5-0';


-- ============================================================
-- PDF 导入链路 + AIGC 项目文档关联（原 v11）
-- ============================================================

-- doc_document 加 source_file_id 关联原始文件（PDF 导入时指向 sys_file.id）
ALTER TABLE doc_document
    ADD COLUMN IF NOT EXISTS source_file_id BIGINT;

COMMENT ON COLUMN doc_document.source_file_id IS '来源文件 ID（sys_file.id），PDF 导入时非空';

-- aigc_project 加 prompt 字段（项目级提示词，生成时直接使用，文档为可选增强）
ALTER TABLE aigc_project
    ADD COLUMN IF NOT EXISTS prompt TEXT;

COMMENT ON COLUMN aigc_project.prompt IS '项目级提示词，生成时直接使用，文档关联为可选增强';

-- AIGC 项目-文档 M2M 关联表
CREATE TABLE IF NOT EXISTS aigc_project_doc (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT       NOT NULL,
    doc_id       BIGINT       NOT NULL,
    role         VARCHAR(20)  NOT NULL DEFAULT 'ref',
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_aigc_project_doc UNIQUE (project_id, doc_id),
    CONSTRAINT fk_apd_project FOREIGN KEY (project_id) REFERENCES aigc_project (id) ON DELETE CASCADE,
    CONSTRAINT fk_apd_doc     FOREIGN KEY (doc_id)     REFERENCES doc_document (id) ON DELETE CASCADE
);

COMMENT ON TABLE aigc_project_doc IS 'AIGC 项目-文档关联';
COMMENT ON COLUMN aigc_project_doc.role IS '文档角色：spec=创作规范 / ref=参考资料 / output=产出文档';

CREATE INDEX IF NOT EXISTS idx_apd_project ON aigc_project_doc (project_id);
CREATE INDEX IF NOT EXISTS idx_apd_doc     ON aigc_project_doc (doc_id);
