-- 工具调用审计记录
CREATE TABLE IF NOT EXISTS tool_call_audit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    session_id      VARCHAR(64),
    agent_id        VARCHAR(64),
    function_name   VARCHAR(128) NOT NULL,
    arguments       TEXT,
    success         BOOLEAN      NOT NULL,
    output          TEXT,
    error_message   TEXT,
    duration_ms     BIGINT,
    risk_level      VARCHAR(16),
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE tool_call_audit IS '工具调用审计记录';
CREATE INDEX idx_tool_call_audit_user ON tool_call_audit (user_id, created_at DESC);
CREATE INDEX idx_tool_call_audit_func ON tool_call_audit (function_name, created_at DESC);
