-- ============================================================
-- 统一会话主表
-- 支持三类会话：AI（用户与助理）/ LIVECHAT（客服）/ IM（用户间/代理间）
-- ============================================================

CREATE TABLE conversation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER      NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    -- 会话类型：AI=用户与助理私聊 / LIVECHAT=客服渠道接入 / IM=任意参与方对话
    type                VARCHAR(16)  NOT NULL DEFAULT 'AI',
    title               VARCHAR(200),
    -- 状态：AI→ACTIVE/ARCHIVED；LIVECHAT→BOT/WAITING/ACTIVE/CLOSED；IM→ACTIVE/CLOSED
    status              VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    creator_id          BIGINT       NOT NULL,
    -- AI 对话快捷字段（type=AI 时填充，避免每次 JOIN participant）
    assistant_id        BIGINT       REFERENCES ai_assistant(id),
    thread_id           VARCHAR(64),
    model_id            VARCHAR(100),
    total_tokens        BIGINT       DEFAULT 0,
    agent_role          VARCHAR(64),
    -- 绑定的知识库 ID（AI 对话直连知识库时使用）
    knowledge_base_id   BIGINT,
    -- 客服相关（type=LIVECHAT 时填充）
    staff_id            BIGINT,
    priority            INTEGER      DEFAULT 3,
    -- 渠道扩展（LIVECHAT 渠道信息，含 channel_type/external_user_id/skill_group/tags 等）
    channel_extension   JSONB,
    -- 会话创建时的用户感知上下文
    context_snapshot    JSONB,
    closed_at           TIMESTAMP(6),
    owner_id            BIGINT,
    create_by           BIGINT,
    create_by_type      VARCHAR(16),
    create_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    remark              VARCHAR(255)
);

COMMENT ON TABLE conversation IS '统一会话表：AI对话 / 客服会话 / IM（含代理间）';
COMMENT ON COLUMN conversation.type IS 'AI=用户与助理 / LIVECHAT=客服渠道 / IM=任意参与方';
COMMENT ON COLUMN conversation.status IS 'ACTIVE/ARCHIVED（AI）; BOT/WAITING/ACTIVE/CLOSED（LIVECHAT）; ACTIVE/CLOSED（IM）';
COMMENT ON COLUMN conversation.assistant_id IS 'AI对话快捷字段，BIGINT，外键引用 ai_assistant.id';
COMMENT ON COLUMN conversation.thread_id IS 'AG-UI threadId，用于 /agui/runs 链路关联';
COMMENT ON COLUMN conversation.agent_role IS 'AgentScope 路由角色，用于 /agui/runs/{agentRole}';
COMMENT ON COLUMN conversation.knowledge_base_id IS 'AI对话直连知识库 ID';
COMMENT ON COLUMN conversation.channel_extension IS '渠道扩展：{channel_type, external_user_id, skill_group, tags}';

CREATE INDEX idx_conversation_creator ON conversation(creator_id) WHERE deleted = FALSE;
CREATE INDEX idx_conversation_type_status ON conversation(type, status) WHERE deleted = FALSE;
CREATE INDEX idx_conversation_assistant ON conversation(assistant_id) WHERE deleted = FALSE AND assistant_id IS NOT NULL;
CREATE UNIQUE INDEX idx_conversation_thread ON conversation(thread_id) WHERE deleted = FALSE AND thread_id IS NOT NULL;

-- ============================================================
-- 参与方表
-- 支持任意类型参与方动态进出（转人工、A2A、群组等）
-- ============================================================

CREATE TABLE conversation_participant (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id     BIGINT       NOT NULL REFERENCES conversation(id) ON DELETE CASCADE,
    -- 参与方 ID（HUMAN/STAFF=sys_user.id；ASSISTANT/BOT=ai_assistant.id；AGENT=ai_agent_definition.id）
    participant_id      BIGINT       NOT NULL,
    -- 参与方类型：HUMAN=用户 / ASSISTANT=AI助理 / AGENT=自主Agent / STAFF=人工坐席 / BOT=机器人
    participant_type    VARCHAR(16)  NOT NULL,
    -- 角色：OWNER=发起方 / MEMBER=参与方 / OBSERVER=旁观（如督导）
    role                VARCHAR(16)  NOT NULL DEFAULT 'MEMBER',
    joined_at           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 离开时间（NULL=仍在会话中）
    left_at             TIMESTAMP(6),
    -- 离开原因：TRANSFER/CLOSED/LEFT
    left_reason         VARCHAR(32),
    -- 扩展元数据（如转接备注、代理任务上下文）
    metadata            JSONB,
    create_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE conversation_participant IS '会话参与方：支持 HUMAN/ASSISTANT/AGENT/STAFF/BOT 动态进出';
COMMENT ON COLUMN conversation_participant.participant_id IS 'HUMAN/STAFF=sys_user.id；ASSISTANT/BOT=ai_assistant.id；AGENT=ai_agent_definition.id';
COMMENT ON COLUMN conversation_participant.left_at IS 'NULL表示仍在会话中；转人工时Bot left_at填入';

CREATE INDEX idx_conv_participant_conv ON conversation_participant(conversation_id);
CREATE INDEX idx_conv_participant_pid ON conversation_participant(participant_id, participant_type);
-- 同一参与方在同一会话中最多一个活跃记录（left_at IS NULL 表示当前在会话中）
CREATE UNIQUE INDEX idx_conv_participant_active
    ON conversation_participant(conversation_id, participant_id)
    WHERE left_at IS NULL;

-- ============================================================
-- 消息表
-- 统一 AI/LIVECHAT/IM 三类消息，sender 支持任意参与方类型
-- ============================================================

CREATE TABLE conversation_message (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER      NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    conversation_id     BIGINT       NOT NULL REFERENCES conversation(id),
    -- 发送方 ID（HUMAN/STAFF=sys_user.id；ASSISTANT/BOT=ai_assistant.id；AGENT=ai_agent_definition.id）
    sender_id           VARCHAR(64)  NOT NULL,
    -- 发送方类型：HUMAN / ASSISTANT / AGENT / STAFF / BOT / SYSTEM
    sender_type         VARCHAR(16)  NOT NULL DEFAULT 'HUMAN',
    -- LLM role：user / assistant / system / tool
    role                VARCHAR(20)  NOT NULL DEFAULT 'user',
    content             TEXT,
    -- 内容类型：TEXT / IMAGE / FILE / TOOL_CALL / TOOL_RESULT / TASK / SYSTEM_EVENT
    content_type        VARCHAR(20)  NOT NULL DEFAULT 'TEXT',
    -- 结构化内容（tool_call参数、task描述、A2A任务结果等）
    payload             JSONB,
    -- 引用回复的消息 ID
    reply_to_id         BIGINT,
    -- IM 已读状态：{user_id: "timestamp"} 或 null
    read_by             JSONB,
    -- 是否内部消息（客服内部备注，不推送给用户）
    is_internal         BOOLEAN      NOT NULL DEFAULT FALSE,
    -- 用户感知上下文（pageId/operation/entityType/entityId 等）
    awareness_context   JSONB,
    token_count         INTEGER,
    metadata            JSONB,
    create_by           BIGINT,
    create_by_type      VARCHAR(16),
    create_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id            BIGINT,
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    remark              VARCHAR(255)
);

COMMENT ON TABLE conversation_message IS '统一会话消息：AI/LIVECHAT/IM 共用';
COMMENT ON COLUMN conversation_message.sender_id IS 'HUMAN/STAFF=sys_user.id；ASSISTANT/BOT=ai_assistant.id；AGENT=ai_agent_definition.id';
COMMENT ON COLUMN conversation_message.content_type IS 'TEXT/IMAGE/FILE/TOOL_CALL/TOOL_RESULT/TASK/SYSTEM_EVENT';
COMMENT ON COLUMN conversation_message.payload IS '结构化内容：tool参数、A2A任务、系统事件等';
COMMENT ON COLUMN conversation_message.read_by IS 'IM已读状态：{userId: isoTimestamp}';
COMMENT ON COLUMN conversation_message.is_internal IS '客服内部备注，不推送给用户';

CREATE INDEX idx_conv_message_conv ON conversation_message(conversation_id, create_time) WHERE deleted = FALSE;
CREATE INDEX idx_conv_message_type ON conversation_message(conversation_id, content_type) WHERE deleted = FALSE;

-- ============================================================
-- livechat_seat / livechat_session_rating / livechat_ticket 已在 v1 直接修改，无需 ALTER
-- ============================================================

-- ============================================================
-- 客服坐席（支持人工 + AI 坐席）
-- ============================================================

CREATE TABLE livechat_seat (
    id              BIGSERIAL PRIMARY KEY,
    -- seat_type=HUMAN 时填 user_id；seat_type=AI 时填 assistant_id
    seat_type       VARCHAR(16)  NOT NULL DEFAULT 'HUMAN',
    user_id         BIGINT,
    assistant_id    BIGINT,
    nickname        VARCHAR(64),
    skill_group     VARCHAR(128),
    status          VARCHAR(16)  NOT NULL DEFAULT 'offline',
    current_sessions INTEGER     NOT NULL DEFAULT 0,
    max_sessions    INTEGER      NOT NULL DEFAULT 5,
    org_id          BIGINT,
    workspace_id    BIGINT,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255),
    version         INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE livechat_seat IS '客服坐席';
COMMENT ON COLUMN livechat_seat.seat_type IS 'HUMAN=人工坐席 / AI=AI助理坐席';
COMMENT ON COLUMN livechat_seat.user_id IS 'seat_type=HUMAN 时填充';
COMMENT ON COLUMN livechat_seat.assistant_id IS 'seat_type=AI 时填充，BIGINT，引用 ai_assistant.id';
CREATE UNIQUE INDEX idx_livechat_seat_user ON livechat_seat(user_id)
    WHERE seat_type = 'HUMAN' AND user_id IS NOT NULL AND deleted = FALSE;
CREATE UNIQUE INDEX idx_livechat_seat_assistant ON livechat_seat(assistant_id)
    WHERE seat_type = 'AI' AND assistant_id IS NOT NULL AND deleted = FALSE;

-- ============================================================
-- 会话满意度评价
-- ============================================================

CREATE TABLE livechat_session_rating (
    id              BIGSERIAL PRIMARY KEY,
    conversation_id BIGINT       NOT NULL,
    user_id         BIGINT,
    staff_id        BIGINT,
    score           INTEGER      NOT NULL,
    comment         VARCHAR(512),
    org_id          BIGINT,
    workspace_id    BIGINT,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255),
    version         INTEGER      NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX idx_session_rating_conv ON livechat_session_rating(conversation_id) WHERE deleted = FALSE;
COMMENT ON TABLE livechat_session_rating IS '会话满意度评价';

-- ============================================================
-- 客服工单
-- ============================================================

CREATE TABLE livechat_ticket (
    id              BIGSERIAL PRIMARY KEY,
    ticket_no       VARCHAR(32)  NOT NULL UNIQUE,
    title           VARCHAR(128) NOT NULL,
    description     TEXT,
    user_id         BIGINT,
    conversation_id BIGINT,
    type            VARCHAR(32)  NOT NULL,
    priority        VARCHAR(16)  NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    assignee_id     BIGINT,
    sla_due_time    TIMESTAMP,
    closed_time     TIMESTAMP,
    org_id          BIGINT,
    workspace_id    BIGINT,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255),
    version         INTEGER      NOT NULL DEFAULT 0
);

CREATE INDEX idx_ticket_status ON livechat_ticket(status);
COMMENT ON TABLE livechat_ticket IS '客服工单';

CREATE TABLE livechat_ticket_record (
    id              BIGSERIAL PRIMARY KEY,
    ticket_id       BIGINT       NOT NULL,
    operation       VARCHAR(16)  NOT NULL,
    operator_id     BIGINT,
    from_status     VARCHAR(16),
    to_status       VARCHAR(16),
    record_remark   VARCHAR(512),
    org_id          BIGINT,
    workspace_id    BIGINT,
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP,
    delete_time     TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255),
    version         INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE livechat_ticket_record IS '工单流转记录';


-- ai_token_usage.conversation_id FK（v2 建表时 conversation 表未创建，在此追加）
ALTER TABLE ai_token_usage
    ADD CONSTRAINT fk_token_usage_conversation FOREIGN KEY (conversation_id) REFERENCES conversation(id) ON DELETE SET NULL;


-- ============================================================
-- 消息反馈（单条消息点赞/踩/纠错）
-- 注：依赖 conversation_message，故定义在此（原 v2 因建表顺序无法引用）
-- ============================================================

CREATE TABLE conversation_message_feedback (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id      BIGINT       NOT NULL REFERENCES conversation_message(id),
    conversation_id BIGINT       NOT NULL,
    user_id         BIGINT       NOT NULL,
    -- 反馈类型：LIKE=点赞 / DISLIKE=踩 / CORRECTION=纠错
    feedback_type   VARCHAR(16)  NOT NULL,
    correction      TEXT,                           -- feedback_type=CORRECTION 时填写正确答案
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (message_id, user_id)
);

COMMENT ON TABLE  conversation_message_feedback              IS '单条消息用户反馈：点赞/踩/纠错（append-only）';
COMMENT ON COLUMN conversation_message_feedback.feedback_type IS 'LIKE/DISLIKE/CORRECTION';
COMMENT ON COLUMN conversation_message_feedback.correction    IS '用户提供的正确答案，用于模型微调数据集收集';

CREATE INDEX idx_conv_msg_feedback_conv ON conversation_message_feedback(conversation_id);
CREATE INDEX idx_conv_msg_feedback_type ON conversation_message_feedback(feedback_type, create_time);
