-- AAF-032 #11 自动化规则

CREATE TABLE sys_automation_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    name         VARCHAR(100) NOT NULL,
    entity_slug  VARCHAR(100) NOT NULL,
    trigger_type VARCHAR(50)  NOT NULL,
    conditions   JSONB,
    actions      JSONB        NOT NULL,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    version      INTEGER      NOT NULL DEFAULT 0,
    create_by    BIGINT,
    create_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by    BIGINT,
    update_time  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time  TIMESTAMP(6),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    remark       VARCHAR(255)
);

COMMENT ON TABLE sys_automation_rule IS '自动化规则';
COMMENT ON COLUMN sys_automation_rule.entity_slug IS '关联实体标识';
COMMENT ON COLUMN sys_automation_rule.trigger_type IS '触发器类型：on_create/on_update/field_change/schedule/delay';
COMMENT ON COLUMN sys_automation_rule.conditions IS '触发条件（JSON）';
COMMENT ON COLUMN sys_automation_rule.actions IS '执行动作列表（JSON）';
COMMENT ON COLUMN sys_automation_rule.enabled IS '是否启用';

CREATE INDEX idx_automation_rule_entity ON sys_automation_rule (entity_slug, trigger_type) WHERE deleted = false AND enabled = true;

CREATE TABLE sys_automation_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id        BIGINT,
    workspace_id  BIGINT,
    rule_id       BIGINT       NOT NULL,
    trigger_type  VARCHAR(50)  NOT NULL,
    entity_type   VARCHAR(100),
    entity_id     BIGINT,
    status        VARCHAR(20)  NOT NULL,
    error_message TEXT,
    executed_at   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version       INTEGER      NOT NULL DEFAULT 0,
    create_by     BIGINT,
    create_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by     BIGINT,
    update_time   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time   TIMESTAMP(6),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    remark        VARCHAR(255)
);

COMMENT ON TABLE sys_automation_log IS '自动化执行日志';
COMMENT ON COLUMN sys_automation_log.rule_id IS '规则 ID';
COMMENT ON COLUMN sys_automation_log.trigger_type IS '触发器类型';
COMMENT ON COLUMN sys_automation_log.status IS '执行状态：success/failed/skipped';
COMMENT ON COLUMN sys_automation_log.error_message IS '错误信息';
COMMENT ON COLUMN sys_automation_log.executed_at IS '执行时间';

CREATE INDEX idx_automation_log_rule ON sys_automation_log (rule_id) WHERE deleted = false;
