-- 审计日志表（不可变，禁止 UPDATE/DELETE）
CREATE TABLE sys_audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT,
    workspace_id BIGINT,
    entity_type  VARCHAR(50)   NOT NULL,
    entity_id    BIGINT        NOT NULL,
    action       VARCHAR(50)   NOT NULL,
    user_id      BIGINT,
    changes      JSONB,
    ip           VARCHAR(45),
    created_at   TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 禁止更新
CREATE RULE audit_log_no_update AS ON UPDATE TO sys_audit_log DO INSTEAD NOTHING;

-- 禁止删除
CREATE RULE audit_log_no_delete AS ON DELETE TO sys_audit_log DO INSTEAD NOTHING;

-- 常用查询索引
CREATE INDEX idx_audit_log_entity ON sys_audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_log_user   ON sys_audit_log (user_id);
CREATE INDEX idx_audit_log_time   ON sys_audit_log (created_at);
