-- ============================================================
-- 分销模块 Schema
-- ============================================================

-- ==================== 分销员 ====================

CREATE TABLE brokerage_user (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             INTEGER      NOT NULL DEFAULT 0,
    org_id              BIGINT,
    workspace_id        BIGINT,
    contact_id          BIGINT       NOT NULL,
    referrer_contact_id BIGINT,
    referrer_bind_time  TIMESTAMP(6),
    brokerage_enabled   BOOLEAN      NOT NULL DEFAULT FALSE,
    brokerage_time      TIMESTAMP(6),
    balance             BIGINT       NOT NULL DEFAULT 0,
    frozen              BIGINT       NOT NULL DEFAULT 0,
    owner_id            BIGINT,
    create_by           BIGINT,
    create_by_type      VARCHAR(16),
    create_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by           BIGINT,
    update_by_type      VARCHAR(16),
    update_time         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time         TIMESTAMP(6),
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    remark              VARCHAR(255)
);

COMMENT ON TABLE brokerage_user IS '分销员';
COMMENT ON COLUMN brokerage_user.contact_id IS '关联 sys_contact.id';
COMMENT ON COLUMN brokerage_user.referrer_contact_id IS '推荐人 contact_id（上级分销员）';
COMMENT ON COLUMN brokerage_user.brokerage_enabled IS '是否有分销资格';
COMMENT ON COLUMN brokerage_user.balance IS '可用佣金（分）';
COMMENT ON COLUMN brokerage_user.frozen IS '冻结佣金（分）';

CREATE UNIQUE INDEX uk_brokerage_user_contact ON brokerage_user(contact_id) WHERE deleted = FALSE;
CREATE INDEX idx_brokerage_user_referrer ON brokerage_user(referrer_contact_id) WHERE deleted = FALSE;

-- ==================== 佣金规则 ====================

CREATE TABLE brokerage_rule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    name            VARCHAR(64)  NOT NULL,
    biz_type        VARCHAR(32)  NOT NULL,
    biz_target_type VARCHAR(32),
    biz_target_id   VARCHAR(64),
    level1_rate     NUMERIC(5,4) NOT NULL DEFAULT 0,
    level2_rate     NUMERIC(5,4) NOT NULL DEFAULT 0,
    calc_base       VARCHAR(16)  NOT NULL DEFAULT 'AMOUNT',
    fixed_amount    BIGINT,
    frozen_days     INTEGER      NOT NULL DEFAULT 7,
    priority        INTEGER      NOT NULL DEFAULT 0,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE brokerage_rule IS '佣金规则';
COMMENT ON COLUMN brokerage_rule.biz_type IS '业务类型：ORDER/SUBSCRIBE/RECHARGE/INVITE';
COMMENT ON COLUMN brokerage_rule.biz_target_type IS '目标类型：PRODUCT/PLAN/PACKAGE，null=全部';
COMMENT ON COLUMN brokerage_rule.biz_target_id IS '具体目标ID，null=全部';
COMMENT ON COLUMN brokerage_rule.level1_rate IS '一级佣金比例（0.1000=10%）';
COMMENT ON COLUMN brokerage_rule.level2_rate IS '二级佣金比例';
COMMENT ON COLUMN brokerage_rule.calc_base IS '计算基准：AMOUNT=按金额比例 / FIXED=固定金额';
COMMENT ON COLUMN brokerage_rule.fixed_amount IS '固定佣金金额（分），calc_base=FIXED 时有效';
COMMENT ON COLUMN brokerage_rule.frozen_days IS '佣金冻结天数';
COMMENT ON COLUMN brokerage_rule.priority IS '优先级，数字越小越优先';
COMMENT ON COLUMN brokerage_rule.status IS 'ENABLED/DISABLED';

CREATE INDEX idx_brokerage_rule_biz ON brokerage_rule(biz_type, priority) WHERE deleted = FALSE AND status = 'ENABLED';

-- ==================== 会员等级佣金加成 ====================

CREATE TABLE brokerage_level_bonus (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     INTEGER      NOT NULL DEFAULT 0,
    org_id      BIGINT,
    workspace_id BIGINT,
    rule_id     BIGINT       NOT NULL,
    plan_id     BIGINT       NOT NULL,
    level1_rate NUMERIC(5,4) NOT NULL,
    level2_rate NUMERIC(5,4) NOT NULL,
    owner_id    BIGINT,
    create_by   BIGINT,
    create_by_type VARCHAR(16),
    create_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by   BIGINT,
    update_by_type VARCHAR(16),
    update_time TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time TIMESTAMP(6),
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    remark      VARCHAR(255)
);

COMMENT ON TABLE brokerage_level_bonus IS '会员等级佣金加成（分销员自身套餐决定佣金比例）';
COMMENT ON COLUMN brokerage_level_bonus.rule_id IS '关联 brokerage_rule.id';
COMMENT ON COLUMN brokerage_level_bonus.plan_id IS '关联 billing_subscription_plan.id（分销员自己的套餐）';
COMMENT ON COLUMN brokerage_level_bonus.level1_rate IS '覆盖 rule 的一级比例';
COMMENT ON COLUMN brokerage_level_bonus.level2_rate IS '覆盖 rule 的二级比例';

CREATE UNIQUE INDEX uk_brokerage_level_bonus ON brokerage_level_bonus(rule_id, plan_id) WHERE deleted = FALSE;

-- ==================== 佣金流水 ====================

CREATE TABLE brokerage_record (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           INTEGER      NOT NULL DEFAULT 0,
    org_id            BIGINT,
    workspace_id      BIGINT,
    contact_id        BIGINT       NOT NULL,
    source_contact_id BIGINT,
    source_level      SMALLINT     NOT NULL DEFAULT 1,
    biz_type          VARCHAR(32)  NOT NULL,
    biz_id            VARCHAR(64),
    title             VARCHAR(200),
    amount            BIGINT       NOT NULL,
    status            VARCHAR(16)  NOT NULL DEFAULT 'FROZEN',
    frozen_days       INTEGER      NOT NULL DEFAULT 0,
    unfreeze_time     TIMESTAMP(6),
    rule_id           BIGINT,
    applied_rate      NUMERIC(5,4),
    calc_base_amount  BIGINT,
    owner_id          BIGINT,
    create_by         BIGINT,
    create_by_type    VARCHAR(16),
    create_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_by_type    VARCHAR(16),
    update_time       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time       TIMESTAMP(6),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    remark            VARCHAR(255)
);

COMMENT ON TABLE brokerage_record IS '佣金流水';
COMMENT ON COLUMN brokerage_record.contact_id IS '获佣分销员 contact_id';
COMMENT ON COLUMN brokerage_record.source_contact_id IS '触发来源联系人（消费者）contact_id';
COMMENT ON COLUMN brokerage_record.source_level IS '推广层级：1=直接推广 2=间接推广';
COMMENT ON COLUMN brokerage_record.biz_type IS 'ORDER/SUBSCRIBE/RECHARGE/INVITE/ORDER_REFUND';
COMMENT ON COLUMN brokerage_record.biz_id IS '关联业务 ID';
COMMENT ON COLUMN brokerage_record.amount IS '佣金金额（分），负数=退款冲回';
COMMENT ON COLUMN brokerage_record.status IS 'FROZEN=冻结中 / VALID=可用 / CANCELLED=已取消';
COMMENT ON COLUMN brokerage_record.unfreeze_time IS '解冻时间';
COMMENT ON COLUMN brokerage_record.rule_id IS '命中的规则 ID（快照）';
COMMENT ON COLUMN brokerage_record.applied_rate IS '实际使用的佣金比例（快照）';
COMMENT ON COLUMN brokerage_record.calc_base_amount IS '计算基数（快照，如实付金额）';

CREATE INDEX idx_brokerage_record_contact ON brokerage_record(contact_id) WHERE deleted = FALSE;
CREATE INDEX idx_brokerage_record_unfreeze ON brokerage_record(unfreeze_time) WHERE deleted = FALSE AND status = 'FROZEN';
CREATE INDEX idx_brokerage_record_biz ON brokerage_record(biz_type, biz_id) WHERE deleted = FALSE;

-- ==================== 佣金提现 ====================

CREATE TABLE brokerage_withdraw (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         INTEGER      NOT NULL DEFAULT 0,
    org_id          BIGINT,
    workspace_id    BIGINT,
    contact_id      BIGINT       NOT NULL,
    amount          BIGINT       NOT NULL,
    fee             BIGINT       NOT NULL DEFAULT 0,
    type            VARCHAR(16)  NOT NULL,
    account_name    VARCHAR(100),
    account_no      VARCHAR(200),
    qr_code_url     VARCHAR(500),
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    audit_reason    VARCHAR(500),
    audit_time      TIMESTAMP(6),
    pay_transfer_id BIGINT,
    transfer_time   TIMESTAMP(6),
    transfer_error  VARCHAR(500),
    owner_id        BIGINT,
    create_by       BIGINT,
    create_by_type  VARCHAR(16),
    create_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_by_type  VARCHAR(16),
    update_time     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time     TIMESTAMP(6),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    remark          VARCHAR(255)
);

COMMENT ON TABLE brokerage_withdraw IS '佣金提现申请';
COMMENT ON COLUMN brokerage_withdraw.contact_id IS '申请人 contact_id';
COMMENT ON COLUMN brokerage_withdraw.amount IS '申请提现金额（分）';
COMMENT ON COLUMN brokerage_withdraw.fee IS '手续费（分）';
COMMENT ON COLUMN brokerage_withdraw.type IS 'WECHAT/ALIPAY/BANK';
COMMENT ON COLUMN brokerage_withdraw.account_name IS '收款人姓名';
COMMENT ON COLUMN brokerage_withdraw.account_no IS '收款账号';
COMMENT ON COLUMN brokerage_withdraw.status IS 'PENDING=待审核 / APPROVED=已审核 / REJECTED=已拒绝 / TRANSFERRED=已转账';
COMMENT ON COLUMN brokerage_withdraw.pay_transfer_id IS '关联转账单 ID';

CREATE INDEX idx_brokerage_withdraw_contact ON brokerage_withdraw(contact_id) WHERE deleted = FALSE;
CREATE INDEX idx_brokerage_withdraw_status ON brokerage_withdraw(status) WHERE deleted = FALSE;


-- ==================== 分销邀请码 ====================

CREATE TABLE brokerage_invite_code (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        INTEGER      NOT NULL DEFAULT 0,
    org_id         BIGINT,
    workspace_id   BIGINT,
    contact_id     BIGINT       NOT NULL,
    code           VARCHAR(20)  NOT NULL,
    channel        VARCHAR(32),
    used_count     INTEGER      NOT NULL DEFAULT 0,
    owner_id       BIGINT,
    create_by      BIGINT,
    create_by_type VARCHAR(16),
    create_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by      BIGINT,
    update_by_type VARCHAR(16),
    update_time    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time    TIMESTAMP(6),
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    remark         VARCHAR(255)
);

COMMENT ON TABLE brokerage_invite_code IS '分销邀请码（一人一码，可区分推广来源渠道）';
COMMENT ON COLUMN brokerage_invite_code.contact_id IS '归属联系人 contact_id';
COMMENT ON COLUMN brokerage_invite_code.code IS '短码，如 AAF-X8K2';
COMMENT ON COLUMN brokerage_invite_code.channel IS '推广来源渠道，如 wechat / poster / card，null=默认';
COMMENT ON COLUMN brokerage_invite_code.used_count IS '被使用（绑定）次数';

CREATE UNIQUE INDEX uk_brokerage_invite_code_contact_channel
    ON brokerage_invite_code(contact_id, COALESCE(channel, ''));
CREATE UNIQUE INDEX uk_brokerage_invite_code_code ON brokerage_invite_code(code);


-- =====================================================
-- 分销统计视图
-- =====================================================

-- 佣金每日发放趋势（按业务类型）
CREATE VIEW v_brokerage_record_daily AS
SELECT
    DATE_TRUNC('day', r.create_time)      AS stat_date,
    r.biz_type,
    r.status,
    COUNT(*)                              AS record_count,
    SUM(r.amount)                         AS total_amount,
    AVG(r.amount)                         AS avg_amount
FROM brokerage_record r
WHERE r.deleted = FALSE
GROUP BY DATE_TRUNC('day', r.create_time), r.biz_type, r.status;

COMMENT ON VIEW v_brokerage_record_daily IS '佣金流水每日统计（按业务类型+状态）';

-- 分销员成长趋势（每日新增）
CREATE VIEW v_brokerage_user_daily AS
SELECT
    DATE_TRUNC('day', u.brokerage_time)   AS stat_date,
    COUNT(*)                              AS new_brokers
FROM brokerage_user u
WHERE u.deleted = FALSE AND u.brokerage_enabled = TRUE AND u.brokerage_time IS NOT NULL
GROUP BY DATE_TRUNC('day', u.brokerage_time);

COMMENT ON VIEW v_brokerage_user_daily IS '分销员每日新增趋势';

-- 分销核心 KPI 汇总（单行，供仪表盘数字卡片使用）
CREATE VIEW v_brokerage_summary AS
SELECT
    COUNT(DISTINCT u.id)                                                        AS total_brokers,
    COUNT(DISTINCT CASE WHEN u.brokerage_enabled THEN u.id END)                AS active_brokers,
    COALESCE(SUM(CASE WHEN r.create_time >= DATE_TRUNC('month', NOW())
                       AND r.deleted = FALSE THEN r.amount END), 0)            AS month_amount,
    COUNT(DISTINCT CASE WHEN w.status = 'PENDING' AND w.deleted = FALSE
                         THEN w.id END)                                        AS pending_withdraws,
    COALESCE(SUM(ic.used_count), 0)                                            AS total_invite_binds
FROM brokerage_user u
LEFT JOIN brokerage_record r   ON r.contact_id = u.contact_id
LEFT JOIN brokerage_withdraw w ON w.contact_id = u.contact_id
LEFT JOIN brokerage_invite_code ic ON ic.contact_id = u.contact_id AND ic.deleted = FALSE
WHERE u.deleted = FALSE;

COMMENT ON VIEW v_brokerage_summary IS '分销核心 KPI 汇总（数字卡片用）';

CREATE INDEX IF NOT EXISTS idx_brokerage_record_daily
    ON brokerage_record(create_time, biz_type, status) WHERE deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_brokerage_user_time
    ON brokerage_user(brokerage_time, brokerage_enabled) WHERE deleted = FALSE;
