[program:aaf-service]
directory=/opt/aaf/service
command=java %(ENV_JAVA_OPS)s -jar /opt/aaf/service/aaf-service.jar %(ENV_APP_ARGS)s
user=aaf
autostart=true
autorestart=true
startsecs=20
startretries=3
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=60
redirect_stderr=true
stdout_logfile=/opt/aaf/service/logs/console.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=10
environment=SPRING_PROFILES_ACTIVE="prod",JAVA_OPS="-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:InitialRAMPercentage=25 -XX:MaxRAMPercentage=75 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/aaf/service/heap-dumps -XX:+ExitOnOutOfMemoryError -Xlog:gc*:/opt/aaf/service/logs/gc.log:time,tags:filecount=5,filesize=50m -Dfile.encoding=UTF-8 -Duser.timezone=Asia/Shanghai --enable-preview",APP_ARGS="--server.port=8080 --spring.profiles.active=prod"
