package com.xuejiai.aaf.framework.intelligent.shared.event;

/** AAF 执行轨迹中可跨层观察的事实类型。 */
public enum ExecutionEventType {
    EXECUTION_STARTED,
    EXECUTION_COMPLETED,
    EXECUTION_FAILED,
    EXECUTION_CANCELED,
    EXECUTION_PAUSED,
    EXECUTION_RESUMED,
    COMMAND_REJECTED,

    RUN_STARTED,
    RUN_COMPLETED,
    RUN_FAILED,

    MESSAGE_STARTED,
    MESSAGE_DELTA,
    MESSAGE_COMPLETED,

    MODEL_CALL_STARTED,
    MODEL_CALL_COMPLETED,
    MODEL_CALL_FAILED,

    TOOL_CALL_STARTED,
    TOOL_CALL_COMPLETED,
    TOOL_CALL_FAILED,

    AUTHORIZATION_REQUESTED,
    AUTHORIZATION_GRANTED,
    AUTHORIZATION_DENIED,
    AUTHORIZATION_REVOKED,

    APPROVAL_REQUESTED,
    APPROVAL_RESOLVED,

    CLARIFICATION_REQUESTED,
    CLARIFICATION_UPDATED,
    CLARIFICATION_RESOLVED,
    CLARIFICATION_CANCELED,
    CLARIFICATION_EXPIRED,

    ITERATION_EVALUATED,
    ITERATION_STOPPED,

    SUBTASK_CREATED,
    SUBTASK_STARTED,
    SUBTASK_COMPLETED,
    SUBTASK_FAILED,
    SUBTASK_CANCELED,

    VALIDATION_STARTED,
    VALIDATION_COMPLETED,
    VALIDATION_FAILED,

    RECOVERY_STARTED,
    RECOVERY_COMPLETED,
    OWNERSHIP_TRANSFERRED,

    TASK_STATUS_CHANGED,
    CONTROL_MODE_CHANGED,

    INPUT_CANCELED,
    INPUT_MODIFIED,
    INPUT_SUPPLEMENTED,
    INPUT_UNRELATED
}
