/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatChatBubble: typeof import('./components/chat/ChatBubble.vue')['default']
    ChatChatWidget: typeof import('./components/chat/ChatWidget.vue')['default']
    ChatImagePicker: typeof import('./components/chat/ImagePicker.vue')['default']
    ChatMessageInput: typeof import('./components/chat/MessageInput.vue')['default']
    ChatStreamText: typeof import('./components/chat/StreamText.vue')['default']
    DemoBlock: typeof import('./components/DemoBlock.vue')['default']
    GlobalDialog: typeof import('./components/GlobalDialog.vue')['default']
    GlobalLoading: typeof import('./components/GlobalLoading.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    PosterPosterEditor: typeof import('./components/poster/PosterEditor.vue')['default']
    PosterPosterModal: typeof import('./components/poster/PosterModal.vue')['default']
    PosterPosterPreview: typeof import('./components/poster/PosterPreview.vue')['default']
    PrivacyPopup: typeof import('./components/PrivacyPopup.vue')['default']
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['default']
    WdCell: typeof import('@wot-ui/ui/components/wd-cell/wd-cell.vue')['default']
    WdCellGroup: typeof import('@wot-ui/ui/components/wd-cell-group/wd-cell-group.vue')['default']
    WdCheckbox: typeof import('@wot-ui/ui/components/wd-checkbox/wd-checkbox.vue')['default']
    WdConfigProvider: typeof import('@wot-ui/ui/components/wd-config-provider/wd-config-provider.vue')['default']
    WdDialog: typeof import('@wot-ui/ui/components/wd-dialog/wd-dialog.vue')['default']
    WdEmpty: typeof import('@wot-ui/ui/components/wd-empty/wd-empty.vue')['default']
    WdGap: typeof import('@wot-ui/ui/components/wd-gap/wd-gap.vue')['default']
    WdIcon: typeof import('@wot-ui/ui/components/wd-icon/wd-icon.vue')['default']
    WdInput: typeof import('@wot-ui/ui/components/wd-input/wd-input.vue')['default']
    WdLoading: typeof import('@wot-ui/ui/components/wd-loading/wd-loading.vue')['default']
    WdNoticeBar: typeof import('@wot-ui/ui/components/wd-notice-bar/wd-notice-bar.vue')['default']
    WdNotify: typeof import('@wot-ui/ui/components/wd-notify/wd-notify.vue')['default']
    WdSwiper: typeof import('@wot-ui/ui/components/wd-swiper/wd-swiper.vue')['default']
    WdTabbar: typeof import('@wot-ui/ui/components/wd-tabbar/wd-tabbar.vue')['default']
    WdTabbarItem: typeof import('@wot-ui/ui/components/wd-tabbar-item/wd-tabbar-item.vue')['default']
    WdToast: typeof import('@wot-ui/ui/components/wd-toast/wd-toast.vue')['default']
  }
}
