/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/startup/index" |
  "/pages/chat/detail" |
  "/pages/chat/index" |
  "/pages/index/index" |
  "/pages/login/index" |
  "/pages/profile/index" |
  "/subPages/message/detail" |
  "/subPages/message/list" |
  "/subPages/profile/edit" |
  "/subPages/settings/index" |
  "/subPages/admin/audit/index" |
  "/subPages/admin/dashboard/index" |
  "/subPages/admin/notice/edit" |
  "/subPages/admin/notice/index" |
  "/subPages/admin/roles/index" |
  "/subPages/admin/settings/index" |
  "/subPages/admin/users/index" |
  "/subPages/settings/about/index" |
  "/subEcharts/echarts/index" |
  "/subAsyncEcharts/asyncEcharts/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/chat/index" | "/pages/profile/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
